<?php

// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';
require_once dirname(__FILE__) . '/../orm/conf/config.php';

use ChurchCRM\EventAttendQuery;


class EventService
{

  function getEventsByPerson($id)
  {
    //$events = EventAttendQuery::create()->filterByPersonId($id)
    //  ->innerJoinWith(Event)
    //  ->orderByEventId()
    //  ->find();

    $sSQL = "SELECT event.event_title, event.event_desc, event.event_start, event.event_end
            FROM events_event AS event, event_attend
              WHERE event.event_id = event_attend.event_id
              AND event_attend.person_id =" . $id . "
            ORDER BY event_start DESC LIMIT 10";
    $result = RunQuery($sSQL);

    $return = array();
    while ($row = mysql_fetch_array($result)) {
      $values['title'] = $row['event_title'];
      $values['desc'] = $row['event_desc'];
      $values['date'] = $row['event_start'];
      array_push($return, $values);
    }

    return $return;
  }

}
