<?php

// This file is generated by Composer
// require_once dirname(__FILE__) . '/../vendor/autoload.php';


class EventService
{
  function getEventsByPerson($id)
  {
 $sSQL = "SELECT t1.event_title, t1.event_desc, t1.event_start, t1.event_end
            FROM events_event AS t1, event_attend AS t2
              WHERE t1.event_id = t2.event_id
              AND t2.person_id =" . $id . "
            ORDER BY event_start DESC LIMIT 10";

    $result = RunQuery($sSQL);

    $return = array();
    while ($row = mysql_fetch_array($result)) {
      $values['title'] = $row['event_title'];
      $values['desc'] = $row['event_desc'];
      $values['date'] = $row['event_start'];
      array_push($return, $values);
    }

    return $return;
  }

}
