# AI Agent Preferences - ChurchCRM Development
# Last Updated: 2025-11-02

enforcement:
  every_commit:
    - validate_commit_message_format
    - check_no_raw_sql
    - verify_propel_orm_used
    - ensure_systemurls_for_assets
    - validate_php82_compatibility
    - explicit_nullable_syntax
    - validate_http_headers
    - check_mime_type_detection
  every_pr:
    - review_communication_style
    - verify_service_classes_used
    - check_bootstrap_css_applied
    - validate_test_impact_documented
    - confirm_php82_standards
    - verify_cache_middleware_placement

communication:
  approach: direct_action_first
  response_format: action_then_context
  max_preamble_lines: 1
  output_display:
    - display_directly_in_chat
    - no_terminal_for_summaries
    - use_markdown_formatting

commits:
  message_format: imperative
  first_line_max: 72
  style: concise
  output_format: markdown

pull_requests:
  summary_max_lines: 10
  focus: what_changed_and_why
  output_format: markdown
  format_requirements:
    - use_markdown_headers
    - use_code_blocks
    - use_bullet_lists
    - use_checkboxes
    - ready_to_copy_paste

code_style:
  php:
    minimum_version: "8.2.0"
    framework: "Propel ORM (mandatory)"
    database: "never_raw_sql"
    patterns:
      - use Service classes for business logic
      - use Query classes for data access
      - avoid inline database logic
    validation:
      - run_php_lint before_committing
      - check syntax on_modified_files
    php82_requirements:
      - explicit_nullable_parameters
      - allow_dynamic_properties_attribute
      - intl_date_formatter
      - explicit_global_namespace
      - correct_version_checks
  javascript:
    bundler: webpack
    css_location: bundled_via_webpack

database:
  mandatory_orm: Propel ORM
  rules:
    - ALWAYS use ORM Query classes
    - NEVER use RunQuery() with string SQL
    - NEVER concatenate SQL strings
    - Cast dynamic identifiers to (int)
    - Use PDO::PARAM_* for bindings
  service_classes:
    - GroupService
    - FinancialService
    - SystemService
    - TaskService

slim_framework:
  middleware_order: critical
  correct_order:
    - $app->addBodyParsingMiddleware()
    - $app->addRoutingMiddleware()
    - $app->add(VersionMiddleware::class)
    - $app->add(AuthMiddleware::class)
    - $app->add(new CorsMiddleware())

http_response:
  header_validation: RFC 7230 compliant
  rules:
    - Header values must be valid strings without metadata
    - Use trim() on header values to remove whitespace
    - Always validate header type before setting
  mime_type_detection:
    correct: "new \\finfo(FILEINFO_MIME_TYPE)"
    wrong: "new \\finfo(FILEINFO_MIME)"
  cache_middleware:
    placement: route_level_not_app_level
  cache_duration:
    source: class constants (not config)
    pattern: "public const CACHE_DURATION_SECONDS = 7200;"

testing:
  api_location: cypress/e2e/api/private/[feature]/[endpoint].spec.js
  ui_location: cypress/e2e/ui/[feature]/
  categories:
    - Successful operations
    - Validation tests
    - Type safety
    - Error handling
    - Edge cases
  helpers:
    - cy.makePrivateAdminAPICall
    - cy.makePrivateUserAPICall
    - cy.apiRequest

i18n:
  javascript: i18next.t()
  php: gettext()
  mandatory_for:
    - error messages shown to users
    - success notifications
    - button labels
    - form labels
    - headings
    - confirmation dialogs
    - any text visible in UI
  forbidden_in:
    - console.log debug messages
    - error_log
    - database queries
    - API endpoint paths
    - variable and function names

notifications:
  mandatory: Notyf (via window.CRM.notify)
  forbidden: alert()
  types:
    success: "Green, for successful operations"
    danger: "Red, for errors"
    warning: "Yellow, for warnings"
    info: "Blue, for informational messages"

file_locations:
  services: src/ChurchCRM/Service/
  orm_generated: src/ChurchCRM/model/ChurchCRM/
  api: src/api/
  utilities: src/Include/
  i18n: src/locale/
  compiled_assets: src/skin/v2/
  react: react/
  webpack: webpack/
  api_tests: cypress/e2e/api/
  ui_tests: cypress/e2e/ui/
  docker: docker/

development:
  setup:
    - npm ci
    - npm run deploy
    - npm run docker:dev:start
  build:
    - npm run build:frontend
    - npm run build:php
  testing:
    - npm run test
    - npm run test:ui
  log_management:
    clear_before_test: rm -f src/logs/$(date +%Y-%m-%d)-*.log
    review_after_failure: cat src/logs/$(date +%Y-%m-%d)-php.log
