<?php

namespace ChurchCRM\Reports;

use ChurchCRM\data\Countries;
use ChurchCRM\dto\SystemConfig;
use ChurchCRM\model\ChurchCRM\FamilyQuery;
use FPDF;

// This class definition contains a bunch of configuration stuff and utilities
// that are useful to all the reports generated by ChurchInfo

// Load the FPDF library

#[\AllowDynamicProperties]
class ChurchInfoReport extends FPDF
{
    // Paper size for all PDF report documents
    // Sizes: A3, A4, A5, Letter, Legal, or a 2-element array for custom size
    // Sorry -- This should really be set in database, but it is needed before all the report settings
    // are read from the database.

    public string $paperFormat = 'Letter';

    /**
     * When true, every page the report draws is one half of a landscape sheet
     * and the pages are imposed two-up in booklet order when the PDF is
     * written. See enableBookletImposition().
     */
    protected bool $bookletImposition = false;

    /**
     * Lay the report out as a folded booklet.
     *
     * Each page the report draws becomes one half of the sheet turned
     * landscape (a letter sheet gives 5.5 x 8.5 in pages, A4 gives A5). When
     * the document is closed the pages are padded to a multiple of four and
     * placed two per sheet in booklet order, so the sheets can be printed
     * double sided (flip on the short edge) and folded down the middle.
     *
     * Must be called before the first AddPage().
     */
    public function enableBookletImposition(): void
    {
        if ($this->page > 0) {
            $this->Error('Booklet imposition must be enabled before the first page is added');
        }
        $this->bookletImposition = true;

        // FPDF stores the default size as [short edge, long edge] whatever the orientation.
        [$sheetShort, $sheetLong] = $this->DefPageSize;
        $this->DefOrientation = 'P';
        $this->CurOrientation = 'P';
        $this->DefPageSize = [$sheetLong / 2, $sheetShort];
        $this->CurPageSize = $this->DefPageSize;
        $this->w = $this->DefPageSize[0];
        $this->h = $this->DefPageSize[1];
        $this->wPt = $this->w * $this->k;
        $this->hPt = $this->h * $this->k;
        $this->PageBreakTrigger = $this->h - $this->bMargin;
    }

    public function isBookletImposition(): bool
    {
        return $this->bookletImposition;
    }

    protected function _putpages(): void
    {
        if ($this->bookletImposition) {
            $this->imposeBookletPages();
        }
        parent::_putpages();
    }

    /**
     * Rewrite the FPDF page buffers so each output page is a landscape sheet
     * carrying two of the pages drawn so far, in booklet order.
     *
     * For N pages (padded to a multiple of 4) sheet i carries pages N-i and
     * i+1, with the outer page on the left for even i and on the right for
     * odd i. That is the order which lines the backs up when the stack is
     * printed double sided with a short-edge flip and folded in half.
     *
     * FPDF keeps fonts and images in one document-wide resource dictionary
     * and every page stream starts by setting its own font and colours, so
     * two streams can be concatenated. Each is wrapped in q/Q so graphics
     * state does not leak from the left page into the right one, and the
     * right page is translated by one page width.
     */
    private function imposeBookletPages(): void
    {
        $pageCount = $this->page;
        if ($pageCount === 0) {
            return;
        }

        [$pageW, $pageH] = $this->DefPageSize;
        $pageWPt = $pageW * $this->k;
        $paddedCount = (int) ceil($pageCount / 4) * 4;

        $pages = $this->pages;
        $links = $this->PageLinks;
        for ($i = 1; $i <= $paddedCount; $i++) {
            if (!isset($pages[$i])) {
                $pages[$i] = '';
                $links[$i] = [];
            } elseif (!empty($this->AliasNbPages)) {
                $pages[$i] = str_replace($this->AliasNbPages, (string) $pageCount, $pages[$i]);
            }
        }

        $sheets = [];
        $sheetLinks = [];
        $shift = sprintf("q 1 0 0 1 %.2F 0 cm\n", $pageWPt);
        for ($i = 0; $i < $paddedCount / 2; $i++) {
            $outer = $paddedCount - $i;
            $inner = $i + 1;
            [$left, $right] = $i % 2 === 0 ? [$outer, $inner] : [$inner, $outer];

            $sheet = $i + 1;
            $sheets[$sheet] = "q\n" . $pages[$left] . "\nQ\n" . $shift . $pages[$right] . "\nQ";

            $sheetLinks[$sheet] = $links[$left];
            foreach ($links[$right] as $link) {
                $link[0] += $pageWPt;
                $sheetLinks[$sheet][] = $link;
            }
        }

        $this->pages = $sheets;
        $this->PageLinks = $sheetLinks;
        $this->PageInfo = [];
        $this->page = count($sheets);
        $this->AliasNbPages = '';
        // Sheets are landscape: two page widths across, one page high.
        $this->DefOrientation = 'P';
        $this->DefPageSize = [$pageW * 2, $pageH];
    }

    /**
     * Converts a UTF-8 string to ISO-8859-1 for FPDF compatibility.
     * Uses iconv() if available, falls back to mb_convert_encoding().
     */
    public static function convertToLatin1(string $str): string
    {
        if (function_exists('iconv')) {
            $result = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $str);
            if ($result !== false) {
                return $result;
            }
        }
        $result = mb_convert_encoding($str, 'ISO-8859-1', 'UTF-8');
        return is_string($result) ? $result : $str;
    }

    public function printRightJustified($x, $y, $str): void
    {
        $strconv = self::convertToLatin1($str);
        $iLen = strlen($strconv);
        $nMoveBy = 10 - 2 * $iLen;
        $this->SetXY($x + $nMoveBy, $y);
        $this->Write(SystemConfig::getValue('incrementY'), $strconv);
    }

    public function printRightJustifiedCell($x, $y, $wid, $str): void
    {
        $strconv = self::convertToLatin1($str);
        $this->SetXY($x, $y);
        $this->Cell($wid, SystemConfig::getValue('incrementY'), $strconv, 1, 0, 'R');
    }

    public function printCenteredCell($x, $y, $wid, $str): void
    {
        $strconv = self::convertToLatin1($str);
        $this->SetXY($x, $y);
        $this->Cell($wid, SystemConfig::getValue('incrementY'), $strconv, 1, 0, 'C');
    }

    public function writeAt($x, $y, $str): void
    {
        $strconv = self::convertToLatin1($str);
        $this->SetXY($x, $y);
        $this->Write(SystemConfig::getValue('incrementY'), $strconv);
    }

    public function writeAtCell($x, $y, $wid, $str): void
    {
        $strconv = self::convertToLatin1($str);
        $this->SetXY($x, $y);
        $this->MultiCell($wid, 4, $strconv, 1);
    }

    public function startLetterPage($fam_ID, $fam_Name, $fam_Address1, $fam_Address2, string $fam_City, string $fam_State, string $fam_Zip, $fam_Country, $letterhead = ''): float
    {
        $this->addPage();

        if ($letterhead == 'graphic' && is_readable(SystemConfig::getValue('bDirLetterHead'))) {
            $this->Image(SystemConfig::getValue('bDirLetterHead'), 12, 15, 185);
            $curY = 20 + (SystemConfig::getValue('incrementY') * 3) + 25;
            $this->writeAt(170, $curY, date(SystemConfig::getValue('sDateFormatLong')));
        } elseif ($letterhead == 'none') {
            $curY = 20 + (SystemConfig::getValue('incrementY') * 3) + 25;
            $this->writeAt(170, $curY, date(SystemConfig::getValue('sDateFormatLong')));
        } else {
            $dateX = 170;
            $dateY = 25;
            $this->writeAt($dateX, $dateY, date(SystemConfig::getValue('sDateFormatLong')));
            $curY = 20;
            $this->writeAt(SystemConfig::getValue('leftX'), $curY, (string) SystemConfig::getValue('sChurchName'));
            $curY += SystemConfig::getValue('incrementY');
            $this->writeAt(SystemConfig::getValue('leftX'), $curY, (string) SystemConfig::getValue('sChurchAddress'));
            $curY += SystemConfig::getValue('incrementY');
            $this->writeAt(SystemConfig::getValue('leftX'), $curY, (string) SystemConfig::getValue('sChurchCity') . ', ' . (string) SystemConfig::getValue('sChurchState') . '  ' . (string) SystemConfig::getValue('sChurchZip'));
            $curY += SystemConfig::getValue('incrementY');
            $curY += SystemConfig::getValue('incrementY'); // Skip another line before the phone/email
            $this->writeAt(SystemConfig::getValue('leftX'), $curY, (string) SystemConfig::getValue('sChurchPhone') . '  ' . (string) SystemConfig::getValue('sChurchEmail'));
            $curY += 25; // mm to move to the second window
        }
        $this->writeAt(SystemConfig::getValue('leftX'), $curY, $this->makeSalutation($fam_ID));
        $curY += SystemConfig::getValue('incrementY');
        if ($fam_Address1 !== null && $fam_Address1 !== '') {
            $this->writeAt(SystemConfig::getValue('leftX'), $curY, (string) $fam_Address1);
            $curY += SystemConfig::getValue('incrementY');
        }
        if ($fam_Address2 !== null && $fam_Address2 !== '') {
            $this->writeAt(SystemConfig::getValue('leftX'), $curY, (string) $fam_Address2);
            $curY += SystemConfig::getValue('incrementY');
        }
        $this->writeAt(SystemConfig::getValue('leftX'), $curY, $fam_City . ', ' . $fam_State . '  ' . $fam_Zip);
        $curY += SystemConfig::getValue('incrementY');
        if (Countries::isForeign($fam_Country)) {
            $this->writeAt(SystemConfig::getValue('leftX'), $curY, (string) $fam_Country);
            $curY += SystemConfig::getValue('incrementY');
        } // mm to get away from the second window

        return $curY + 5.0;
    }

    public function makeSalutation($famID): string
    {
        $family = FamilyQuery::create()->findPk($famID);

        if ($family === null) {
            return gettext('Dear Friend');  // Default salutation for unassigned/orphaned payments
        }

        return $family->getSalutation();
    }
}
