---
kind: pipeline
name: PHP:7.1

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: devilbox/php-fpm:7.1-work
  commands:
  - export DB=mysql
  - php --version
  - node --version
  - composer --version
  - composer global require hirak/prestissimo
  - apt-get update
  - apt-get install -y ruby-full
  - gem install sass -v 3.4.25
  - "chmod +x ./travis-ci/*.sh"
  - "chmod +x ./scripts/*.sh"
  - cp BuildConfig.json.example BuildConfig.json
  - chown -R devilbox:devilbox /drone/src/src
  - npm install --unsafe-perm
  - npm run composer-install
  - npm run orm-gen
  - npm run build-react
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug

- name: Test-7.1
  image: devilbox/php-fpm:7.1-work
  commands:
  - cp ./drone-ci/tests-run.sh ./scripts/tests-run.sh
  - cp ./drone-ci/bootstrap.php ./tests/bootstrap.php
  - npm run tests-install
  - "mysql --user=root --password=churchcrm --host=mysql -e 'drop database IF EXISTS churchcrm_test;'"
  - "mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'"
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - cp ./drone-ci/Config.php ./src/Include/Config.php
  - cp ./drone-ci/behat.yml ./tests/behat/behat.yml
  - npm run test
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug

services:
- name: mysql
  image: cytopia/mariadb-10.3
  environment:
    MYSQL_ROOT_PASSWORD: churchcrm

- name: php
  image: devilbox/php-fpm:7.1-work
  commands:
  - mkdir /var/www/default
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug
  working_dir: /var/www/default

- name: crm
  image: devilbox/apache-2.4
  commands:
  - rm -rf /var/www/default/htdocs
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php
    PHP_FPM_SERVER_PORT: 9000
  working_dir: /var/www/default

- name: selenium
  image: selenium/standalone-chrome
  volumes:
  - name: shm
    path: /dev/shm:/dev/shm

---
kind: pipeline
name: PHP:7.2

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: devilbox/php-fpm:7.2-work
  commands:
  - export DB=mysql
  - php --version
  - node --version
  - composer --version
  - composer global require hirak/prestissimo
  - apt-get update
  - apt-get install -y ruby-full
  - gem install sass -v 3.4.25
  - "chmod +x ./travis-ci/*.sh"
  - "chmod +x ./scripts/*.sh"
  - cp BuildConfig.json.example BuildConfig.json
  - chown -R devilbox:devilbox /drone/src/src
  - npm install --unsafe-perm
  - npm run composer-install
  - npm run orm-gen
  - npm run build-react
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug

- name: Test-7.2
  image: devilbox/php-fpm:7.2-work
  commands:
  - cp ./drone-ci/tests-run.sh ./scripts/tests-run.sh
  - cp ./drone-ci/bootstrap.php ./tests/bootstrap.php
  - npm run tests-install
  - "mysql --user=root --password=churchcrm --host=mysql -e 'drop database IF EXISTS churchcrm_test;'"
  - "mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'"
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - cp ./drone-ci/Config.php ./src/Include/Config.php
  - cp ./drone-ci/behat.yml ./tests/behat/behat.yml
  - npm run test
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug

services:
- name: mysql
  image: cytopia/mariadb-10.3
  environment:
    MYSQL_ROOT_PASSWORD: churchcrm

- name: php
  image: devilbox/php-fpm:7.2-work
  commands:
  - mkdir /var/www/default
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug
  working_dir: /var/www/default

- name: crm
  image: devilbox/apache-2.4
  commands:
  - rm -rf /var/www/default/htdocs
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php
    PHP_FPM_SERVER_PORT: 9000
  working_dir: /var/www/default

- name: selenium
  image: selenium/standalone-chrome
  volumes:
  - name: shm
    path: /dev/shm:/dev/shm

---
kind: pipeline
name: PHP:7.3

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: devilbox/php-fpm:7.3-work
  commands:
  - export DB=mysql
  - php --version
  - node --version
  - composer --version
  - composer global require hirak/prestissimo
  - apt-get update
  - apt-get install -y ruby-full
  - gem install sass -v 3.4.25
  - "chmod +x ./travis-ci/*.sh"
  - "chmod +x ./scripts/*.sh"
  - cp BuildConfig.json.example BuildConfig.json
  - chown -R devilbox:devilbox /drone/src/src
  - npm install --unsafe-perm
  - npm run composer-install
  - npm run orm-gen
  - npm run build-react
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug

- name: Test-7.3
  image: devilbox/php-fpm:7.3-work
  commands:
  - cp ./drone-ci/tests-run.sh ./scripts/tests-run.sh
  - cp ./drone-ci/bootstrap.php ./tests/bootstrap.php
  - npm run tests-install
  - "mysql --user=root --password=churchcrm --host=mysql -e 'drop database IF EXISTS churchcrm_test;'"
  - "mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'"
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - cp ./drone-ci/Config.php ./src/Include/Config.php
  - cp ./drone-ci/behat.yml ./tests/behat/behat.yml
  - npm run test
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug

- name: Pipeline Wait
  image: chrishsieh/drone_pipeline_wait
  settings:
    token:
      from_secret: drone_api
    wait_pipelines:
    - PHP:7.1
    - PHP:7.2
  when:
    branch:
    - master
    - develop

- name: Package
  image: devilbox/php-fpm:7.3-work
  commands:
  - chown -R www-data:www-data /drone/src/src
  - npm run package
  - npm run demosite
  environment:
    demoKey:
      from_secret: demokey
  when:
    branch:
    - master
    - develop

- name: Changelog
  image: devilbox/php-fpm:7.3-work
  commands:
  - "sed -i 's/ --token=<%= buildConfig.GitHub.token %>//g' ./Gruntfile.js"
  - npm run changelog-gen
  environment:
    GREN_GITHUB_TOKEN:
      from_secret: github_api
  when:
    branch:
    - master
    event:
    - release
    - tag

- name: Publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_api
    checksum:
    - sha1
    files:
    - "churchcrm/*"
    - "target/ChurchCRM*"
    note: CHANGELOG.md
  when:
    branch:
    - master
    event:
    - release
    - tag

services:
- name: mysql
  image: cytopia/mariadb-10.3
  environment:
    MYSQL_ROOT_PASSWORD: churchcrm

- name: php
  image: devilbox/php-fpm:7.3-work
  commands:
  - mkdir /var/www/default
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm:80"
    PHP_MODULES_DISABLE: xdebug
  working_dir: /var/www/default

- name: crm
  image: devilbox/apache-2.4
  commands:
  - rm -rf /var/www/default/htdocs
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php
    PHP_FPM_SERVER_PORT: 9000
  working_dir: /var/www/default

- name: selenium
  image: selenium/standalone-chrome
  volumes:
  - name: shm
    path: /dev/shm:/dev/shm

---
kind: pipeline
name: Notify

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify
  image: chrishsieh/drone_webhook
  settings:
    content_type: application/x-www-form-urlencoded
    on_failure: always
    on_success: change
    pipeline_name: Notify
    template: "{{#success build.status}}icon=smile{{else}}icon=frown{{/success}}&message=Drone [{{repo.owner}}/{{repo.name}}](https://github.com/{{repo.owner}}/{{repo.name}}/commit/{{build.commit}}) ({{build.branch}}) [**{{build.status}}**]({{build.link}})({{build.number}})\\n{{#each job.status}}{{#success this.status}}![Status](https://img.shields.io/badge/{{this.name}}-O-success.svg){{else}}![Status](https://img.shields.io/badge/{{this.name}}-X-critical.svg){{/success}}{{/each}} by {{build.author}}\n"
    token:
      from_secret: drone_api
    urls:
      from_secret: gitter_webhok

trigger:
  status:
  - success
  - failure

depends_on:
- PHP:7.1
- PHP:7.2
- PHP:7.3

...
