---
kind: pipeline
name: "Build&Test"

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: devilbox/php-fpm:7.2-work
  commands:
  - export DB=mysql
  - php --version
  - node --version
  - composer --version
  - apt-get update
  - apt-get install -y ruby-full
  - gem install sass -v 3.4.25
  - "chmod +x ./travis-ci/*.sh"
  - "chmod +x ./scripts/*.sh"
  - cp BuildConfig.json.example BuildConfig.json
  - chown -R devilbox:devilbox /drone/src/src
  - npm install --unsafe-perm
  - npm run composer-install
  - npm run orm-gen
  environment:
    FORWARD_PORTS_TO_LOCALHOST: 3306:mysql:3306
    PHP_MODULES_DISABLE: xdebug

- name: store-cache
  image: chrishsieh/drone-volume-cache
  environment:
    PLUGIN_MOUNT: drone-ci
    PLUGIN_REBUILD: true
  volumes:
  - name: cache
    path: /cache

- name: Test-7.0
  image: devilbox/php-fpm:7.0-work
  commands:
  - cp ./drone-ci/tests-run.sh ./scripts/tests-run.sh
  - cp ./drone-ci/bootstrap.php ./tests/bootstrap.php
  - npm run tests-install
  - "mysql --user=root --password=churchcrm --host=mysql -e 'drop database IF EXISTS churchcrm_test;'"
  - "mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'"
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - "sed -i 's/web_server/crm7.0/g' ./drone-ci/Config.php"
  - "sed -i 's/web_server/crm7.0/g' ./drone-ci/behat.yml"
  - cp ./drone-ci/Config.php ./src/Include/Config.php
  - cp ./drone-ci/behat.yml ./tests/behat/behat.yml
  - npm run test
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm7.0:80"
    PHP_MODULES_DISABLE: xdebug

- name: restore-cache-7.0
  image: chrishsieh/drone-volume-cache
  environment:
    PLUGIN_MOUNT: drone-ci
    PLUGIN_RESTORE: true
  volumes:
  - name: cache
    path: /cache

- name: Test-7.1
  image: devilbox/php-fpm:7.1-work
  commands:
  - cp ./drone-ci/tests-run.sh ./scripts/tests-run.sh
  - cp ./drone-ci/bootstrap.php ./tests/bootstrap.php
  - npm run tests-install
  - "mysql --user=root --password=churchcrm --host=mysql -e 'drop database IF EXISTS churchcrm_test;'"
  - "mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'"
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - "sed -i 's/web_server/crm7.1/g' ./drone-ci/Config.php"
  - "sed -i 's/web_server/crm7.1/g' ./drone-ci/behat.yml"
  - cp ./drone-ci/Config.php ./src/Include/Config.php
  - cp ./drone-ci/behat.yml ./tests/behat/behat.yml
  - npm run test
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm7.1:80"
    PHP_MODULES_DISABLE: xdebug

- name: restore-cache-7.1
  image: chrishsieh/drone-volume-cache
  environment:
    PLUGIN_MOUNT: drone-ci
    PLUGIN_RESTORE: true
  volumes:
  - name: cache
    path: /cache

- name: Test-7.2
  image: devilbox/php-fpm:7.2-work
  commands:
  - cp ./drone-ci/tests-run.sh ./scripts/tests-run.sh
  - cp ./drone-ci/bootstrap.php ./tests/bootstrap.php
  - npm run tests-install
  - "mysql --user=root --password=churchcrm --host=mysql -e 'drop database IF EXISTS churchcrm_test;'"
  - "mysql --user=root --password=churchcrm --host=mysql -e 'create database IF NOT EXISTS churchcrm_test;'"
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < src/mysql/install/Install.sql;
  - mysql --user=root --password=churchcrm --host=mysql churchcrm_test < demo/ChurchCRM-Database.sql;
  - "sed -i 's/web_server/crm7.2/g' ./drone-ci/Config.php"
  - "sed -i 's/web_server/crm7.2/g' ./drone-ci/behat.yml"
  - cp ./drone-ci/Config.php ./src/Include/Config.php
  - cp ./drone-ci/behat.yml ./tests/behat/behat.yml
  - npm run test
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm7.2:80"
    PHP_MODULES_DISABLE: xdebug

- name: restore-cache-7.2
  image: chrishsieh/drone-volume-cache
  environment:
    PLUGIN_MOUNT: drone-ci
    PLUGIN_RESTORE: true
  volumes:
  - name: cache
    path: /cache

services:
- name: mysql
  image: cytopia/mariadb-10.3
  environment:
    MYSQL_ROOT_PASSWORD: churchcrm

- name: selenium
  image: selenium/standalone-chrome
  volumes:
  - name: shm
    path: /dev/shm:/dev/shm

- name: php7.0
  image: devilbox/php-fpm:7.0-work
  commands:
  - mkdir /var/www/default
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm7.0:80"
    PHP_MODULES_DISABLE: xdebug
  working_dir: /var/www/default

- name: crm7.0
  image: devilbox/apache-2.4
  commands:
  - rm -rf /var/www/default/htdocs
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm7.0
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php7.0
    PHP_FPM_SERVER_PORT: 9000
  working_dir: /var/www/default

- name: php7.1
  image: devilbox/php-fpm:7.1-work
  commands:
  - mkdir /var/www/default
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm7.1:80"
    PHP_MODULES_DISABLE: xdebug
  working_dir: /var/www/default

- name: crm7.1
  image: devilbox/apache-2.4
  commands:
  - rm -rf /var/www/default/htdocs
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm7.1
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php7.1
    PHP_FPM_SERVER_PORT: 9000
  working_dir: /var/www/default

- name: php7.2
  image: devilbox/php-fpm:7.2-work
  commands:
  - mkdir /var/www/default
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    FORWARD_PORTS_TO_LOCALHOST: "3306:mysql:3306, 80:crm7.2:80"
    PHP_MODULES_DISABLE: xdebug
  working_dir: /var/www/default

- name: crm7.2
  image: devilbox/apache-2.4
  commands:
  - rm -rf /var/www/default/htdocs
  - ln -s /drone/src/src/ /var/www/default/htdocs
  - /docker-entrypoint.sh
  environment:
    MAIN_VHOST_ENABLE: 1
    MAIN_VHOST_SSL_CN: crm7.2
    PHP_FPM_ENABLE: 1
    PHP_FPM_SERVER_ADDR: php7.2
    PHP_FPM_SERVER_PORT: 9000
  working_dir: /var/www/default

volumes:
- name: cache
  temp: {}

...
