risky: false
version: 8.1
preset: psr12
monolithic: true

tab-width: 4
use-tabs: false

enabled:
- assign_null_coalescing_to_coalesce_equal
- backtick_to_shell_exec
- linebreak_after_opening_tag

disabled:

finder:
  path:
    - "src"
  exclude:
    - "src/vendor"
  name: "*.php"
