#!/usr/bin/env python3
"""Final push to reach 95%+ on AF and 25%+ on EL"""

import json

af_final = {
    "Go to Dashboard": "Gaan na Paneelbord",
    "Group Memberships": "Groep Lidmaatskappe",
    "Group management access": "Groepbestuur toegang",
    "Import failed": "Invoer Gefaal",
    "Import from CSV files": "Invoer Vanaf CSV-lêers",
    "Important Warning": "Belangrike Waarskuwing",
    "Includes database and all uploaded photos. Larger file size.": "Sluit databasis en alle oplaai foto's in. Groter lêergrootte.",
    "Install TLS/SSL certificate for better security": "Installeer TLS/SSL-sertifikaat vir beter sekuriteit",
    "Invalid CSRF token": "Ongeldig CSRF-teken",
    "Invalid fields or selections.": "Ongeldige velde of keuses.",
    "Invalid request data": "Ongeldige versoekgegewens",
    "Invalid status": "Ongeldige status",
    "Item deleted successfully": "Item suksesvol verwyder",
    "Local development:": "Plaaslike ontwikkeling:",
    "Locale Support": "Landinstelling Ondersteuning",
    "Location": "Ligging",
    "Location & Contact Information": "Ligging & Kontakbesluit",
    "Mar": "Mrt",
    "Membership Reports": "Lidmaatskap Verslae",
    "Menu options access": "Spyskaartopsies toegang",
    "Missing Files": "Ontbrekende Lêers",
    "Missing Secret Keys": "Ontbrekende Geheime Sleutels",
    "Modified Files": "Gewysigde Lêers",
    "Most reports can be exported as PDF for printing or CSV for spreadsheet analysis": "Meeste verslae kan as PDF vir druk of CSV vir sigbladanalise uitgevoer word",
    "Move down": "Beweeg Af",
    "Move up": "Beweeg Op",
    "Mr., Mrs., Dr.": "Mnr., Mev., Dr.",
    "Multiple Copies": "Veelvuldige Kopieë",
    "New to": "Nuut na",
    "No access required": "Geen toegang vereis",
    "No backup file found": "Geen rugsteunlêer gevind",
    "No category selected": "Geen kategorie gekies",
    "No churches available": "Geen kerke beskikbaar",
    "No data selected": "Geen gegewens gekies",
    "No events assigned to this group yet.": "Geen geleenthede aan hierdie groep toegeken nie.",
    "No file selected": "Geen lêer gekies",
    "No filters available": "Geen filters beskikbaar",
    "No funds available.": "Geen fondse beskikbaar.",
    "No person selected": "Geen persoon gekies",
    "No report": "Geen Verslag",
    "No results found": "Geen resultate gevind",
    "No upgrade available": "Geen opgradering beskikbaar",
    "Not Available": "Nie Beskikbaar",
    "Not Logged In": "Nie Aangeteken",
    "Not found": "Nie Gevind",
    "Not installed": "Nie Geïnstalleer",
    "Not set": "Nie Ingestel",
    "Not started": "Nie Begin",
    "Note - optional": "Notat - opsioneel",
    "Notification Email Sent": "Kennisgewingse-pos Gestuur",
    "Notifications": "Kennisgewings",
    "Now loading": "Nou Laai",
    "Number of Payments": "Aantal Betalings",
    "Number of Pledges": "Aantal Beloftes",
    "Number of records": "Aantal Rekorde",
    "Nov": "Nov",
    "Null": "Nul",
    "Null Option": "Nul-opsie",
    "Null Record": "Nul-rekord",
    "Null Value": "Nul-waarde",
    "Number": "Nommer",
    "Numbers": "Nommers",
    "Numeric": "Numeries",
    "Office": "Kantoor",
    "Offices": "Kantore",
    "Often": "Dikwels",
    "OK": "OK",
    "Old": "Oud",
    "Older": "Ouer",
    "Oldest": "Oudste",
    "On Hold": "Op Hou",
    "On Sale": "Op Verkoping",
    "On Time": "Op Tyd",
    "On request": "Op Versoek",
    "Once": "Eenmaal",
    "One": "Een",
    "One Page": "Een Bladsy",
    "One Time": "Een Tyd",
    "Only": "Slegs",
    "Only accounts": "Slegs Rekeninge",
    "Only from email": "Slegs Vanaf E-pos",
    "Open Financial Access": "Oopmaak Finansiële Toegang",
    "Or": "Of",
    "Organization": "Organisasie",
    "Organizations": "Organisasies",
    "Organized": "Georganiseerd",
    "Organize": "Organiseer",
    "Organizing": "Organisering",
    "Orientation": "Oriëntasie",
    "Origin": "Oorsprong",
    "Original": "Oorspronklik",
    "Other": "Ander",
    "Other Options": "Ander Opsies",
    "Other Payments": "Ander Betalings",
    "Other Type": "Ander Tipe",
    "Others": "Andersins",
    "Our": "Ons",
    "Out": "Uit",
    "Outcome": "Uitkoms",
    "Outcomes": "Uitkomste",
    "Outgoing": "Uitgaande",
    "Outing": "Uitgang",
    "Outings": "Uitgange",
    "Outline": "Skets",
    "Outlines": "Sketse",
    "Outlook": "Vooruitsig",
    "Outnumber": "Overtalle",
    "Outnumbered": "Overtalle",
    "Output": "Afvoer",
    "Outputs": "Afvoere",
    "Outside": "Buite",
}

el_final = {
    "Go to Dashboard": "Πηγαίνετε στο Ταμπλό",
    "Group Memberships": "Ομαδικά Μέλη",
    "Group management access": "Πρόσβαση διαχείρισης ομάδας",
    "Import failed": "Εισαγωγή Απέτυχε",
    "Import from CSV files": "Εισαγωγή από Αρχεία CSV",
    "Important Warning": "Σημαντική Προειδοποίηση",
    "Includes database and all uploaded photos. Larger file size.": "Περιλαμβάνει βάση δεδομένων και όλες τις φωτογραφίες που ανέβηκαν.",
    "Install TLS/SSL certificate for better security": "Εγκαταστήστε πιστοποιητικό TLS/SSL",
    "Invalid CSRF token": "Μη έγκυρο διακριτικό CSRF",
    "Invalid fields or selections.": "Μη έγκυρα πεδία ή επιλογές.",
    "Invalid request data": "Μη έγκυρα δεδομένα αιτήματος",
    "Invalid status": "Μη έγκυρη κατάσταση",
    "Item deleted successfully": "Το στοιχείο διαγράφηκε με επιτυχία",
    "Local development:": "Τοπική ανάπτυξη:",
    "Locale Support": "Υποστήριξη Τοπικών Ρυθμίσεων",
    "Location": "Τοποθεσία",
    "Location & Contact Information": "Τοποθεσία & Πληροφορίες Επαφής",
    "Mar": "Μαρ",
    "Membership Reports": "Αναφορές Ιδιοκτησίας",
    "Menu options access": "Πρόσβαση στις επιλογές μενού",
    "Missing Files": "Ελλιπή Αρχεία",
    "Missing Secret Keys": "Ελλιπή Μυστικά Κλειδιά",
    "Modified Files": "Τροποποιημένα Αρχεία",
    "Move down": "Μετακίνηση Κάτω",
    "Move up": "Μετακίνηση Πάνω",
    "Mr., Mrs., Dr.": "Κ., Δα., Δρ.",
    "Multiple Copies": "Πολλαπλά Αντίγραφα",
    "New to": "Νέα στο",
    "No access required": "Δεν απαιτείται πρόσβαση",
    "No backup file found": "Δεν βρέθηκε αρχείο αντιγράφου",
    "No category selected": "Δεν έχει επιλεγεί κατηγορία",
    "No data selected": "Δεν έχουν επιλεγεί δεδομένα",
    "No events assigned to this group yet.": "Δεν έχουν ανατεθεί εκδηλώσεις σε αυτήν την ομάδα.",
    "No file selected": "Δεν έχει επιλεγεί αρχείο",
    "No filters available": "Δεν υπάρχουν διαθέσιμα φίλτρα",
    "No funds available.": "Δεν υπάρχουν διαθέσιμα κεφάλαια.",
    "No person selected": "Δεν έχει επιλεγεί πρόσωπο",
    "No report": "Χωρίς Αναφορά",
    "No results found": "Δεν βρέθηκαν αποτελέσματα",
    "No upgrade available": "Δεν υπάρχει διαθέσιμη ενημέρωση",
    "Not Available": "Δεν Διατίθεται",
    "Not Logged In": "Δεν Έχει Συνδεθεί",
    "Not found": "Δεν Βρέθηκε",
    "Not installed": "Δεν Είναι Εγκατεστημένο",
    "Not set": "Δεν Έχει Οριστεί",
    "Not started": "Δεν Έχει Ξεκινήσει",
    "Note - optional": "Σημείωση - Προαιρετικό",
    "Notification Email Sent": "Ηλεκτρονικό Ταχυδρομείο Αποστάλθηκε",
    "Notifications": "Ειδοποιήσεις",
    "Now loading": "Φορτώνεται Τώρα",
    "Number of Payments": "Αριθμός Πληρωμών",
    "Number of Pledges": "Αριθμός Υποσχέσεων",
    "Number of records": "Αριθμός Αρχείων",
    "Nov": "Νοε",
    "Null": "Μηδέν",
    "Null Option": "Κανένα",
    "Null Record": "Κανένα",
    "Null Value": "Κανένα",
    "Number": "Αριθμός",
    "Numbers": "Αριθμοί",
    "Numeric": "Αριθμητικό",
    "Office": "Γραφείο",
    "Offices": "Γραφεία",
    "Often": "Συχνά",
    "OK": "ΟΚ",
    "Old": "Παλιό",
    "Older": "Παλιότερο",
    "Oldest": "Παλιότατο",
    "On Hold": "Σε Διακοπή",
    "On Sale": "Σε Πώληση",
    "On Time": "Έγκαιρα",
    "On request": "Κατ' αίτηση",
    "Once": "Μια φορά",
    "One": "Ένα",
    "One Page": "Μια Σελίδα",
    "One Time": "Μια Φορά",
    "Only": "Μόνο",
    "Only accounts": "Μόνο Λογαριασμοί",
    "Only from email": "Μόνο από Email",
    "Open Financial Access": "Ανοιχτή Οικονομική Πρόσβαση",
    "Or": "Ή",
    "Organization": "Οργάνωση",
    "Organizations": "Οργανώσεις",
    "Organized": "Οργανωμένο",
    "Organize": "Οργανώνω",
    "Organizing": "Οργάνωση",
    "Orientation": "Προσανατολισμός",
    "Origin": "Προέλευση",
    "Original": "Αρχικό",
    "Other": "Άλλα",
    "Other Options": "Άλλες Επιλογές",
    "Other Payments": "Άλλες Πληρωμές",
    "Other Type": "Άλλος Τύπος",
    "Others": "Άλλα",
    "Our": "Δικό μας",
    "Out": "Έξω",
    "Outcome": "Αποτέλεσμα",
    "Outcomes": "Αποτελέσματα",
    "Outgoing": "Εξερχόμενα",
    "Outing": "Εξόρμηση",
    "Outings": "Εξορμήσεις",
    "Outline": "Περίγραμμα",
    "Outlines": "Περιγράμματα",
    "Outlook": "Προοπτική",
    "Outnumber": "Υπερβαίνω σε Αριθμό",
    "Outnumbered": "Υπερβαίνει σε Αριθμό",
    "Output": "Αποτέλεσμα",
    "Outputs": "Αποτελέσματα",
}

# Apply
af_file = 'locale/missing-terms/af.json'
el_file = 'locale/missing-terms/el.json'

with open(af_file, 'r', encoding='utf-8') as f:
    af_data = json.load(f)

af_updated = 0
for key, translation in af_final.items():
    if key in af_data and af_data[key] == "":
        af_data[key] = translation
        af_updated += 1

with open(af_file, 'w', encoding='utf-8') as f:
    json.dump(af_data, f, ensure_ascii=False, indent=2)

with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

el_updated = 0
for key, translation in el_final.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = translation
        el_updated += 1

with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

# Stats
af_empty = len([v for v in af_data.values() if v == ""])
el_empty = len([v for v in el_data.values() if v == ""])
af_total = len(af_data)
el_total = len(el_data)
af_done = af_total - af_empty
el_done = el_total - el_empty

print(f"\n✓ Afrikaans: {af_updated} terms → {af_done}/{af_total} ({100*af_done/af_total:.1f}%)")
print(f"✓ Greek: {el_updated} terms → {el_done}/{el_total} ({100*el_done/el_total:.1f}%)")
print(f"\nRemaining: AF {af_empty}, EL {el_empty}")
