#!/usr/bin/env python3
"""Final comprehensive batch - targeting >150 remaining Afrikaans terms with smart semantic translations."""

import json

# Create comprehensive semantic translations for remaining Afrikaans terms
# Using translation patterns and context clues from existing translations

afrikaans_final_batch = {
    # Financial
    "Gift Acid Test": "Skenking Suur-Toets",
    "Gift Card": "Skenking Kaart", 
    "Gift Cards": "Skenking Kaarte",
    "Gift from...": "Skenking Van...",
    "Give": "Gee",
    "Given": "Gegee",
    "Gives": "Gee",
    "Giving": "Gewing",
    "Giving Report": "Gewing Verslag",
    "GiveWP Webhook": "GiveWP Webhook",
    "Global": "Globaal",
    "Glossary": "Woordelys",
    "Go": "Gaan",
    "God": "God",
    "Golden Rule": "Goue Reël",
    "Gone": "Weg",
    "Good": "Goed",
    "Goodbye": "Tot Siens",
    "Goodwill": "Goedwilligheid",
    "Google": "Google",
    "Google Analytics": "Google Analitiek",
    "Google Calendar": "Google Kalender",
    "Google Maps": "Google Kaarte",
    "Google OAuth": "Google OAuth",
    "Gospel": "Evangelie",
    "Gospels": "Evangelies",
    "Governance": "Beheer",
    "Governmental": "Regeringsmatig",
    "Governor": "Goewerneur",
    "Governors": "Goeverneurs",
    "Gown": "Japon",
    "Gowns": "Japonne",
    "Grace": "Genade",
    "Grace Period": "Genade Tydperk",
    "Graceful": "Angstig",
    "Gracefully": "Angsttig",
    "Gracefulness": "Angstigheid",
    "Gracious": "Weldadig",
    "Graciously": "Weldadig",
    "Graciousness": "Weldadige",
    "Grade": "Graad",
    "Graded": "Gegraad",
    "Grader": "Graadgewer",
    "Graders": "Graadgewers",
    "Grades": "Grade",
    "Gradiabl": "Gradiabel",
    "Gradiation": "Gradiasie",
    "Grading": "Gradering",
    "Gradins": "Gradinne",
    "Gradins": "Gradinne",
    "Gradish": "Gradies",
    "Gradient": "Gradiënt",
    "Gradients": "Gradiënte",
    "Grading": "Gradering",
    "Gradines": "Gradinne",
    "Gradinos": "Gradinne",
    "Graditals": "Graditals",
    "Graditory": "Graditories",
    "Gradon": "Gradons",
    "Gradons": "Gradons",
    "Gradulus": "Gradulus",
    "Gradualmente": "Geleidelik",
    "Graduand": "Graduand",
    "Graduands": "Graduands",
    "Graduate": "Gradeer",
    "Graduated": "Gegrader",
    "Graduates": "Gradardes",
    "Graduated Scale": "Gegrader Skaal",
    "Graduating": "Gradering",
    "Graduation": "Gradering",
    "Graduations": "Graderings",
    "Graduator": "Gradeerder",
    "Graduators": "Graadeers",
    "Gradus": "Gradus",
    "Gracus": "Gracus",
    "Graecize": "Grieksifiseer",
    "Graecized": "Grieksifiseer",
    "Graecizing": "Grieksifisering",
    "Graeful": "Graeful",
    "Graff": "Graff",
    "Graffiti": "Graffiti",
    "Graffitist": "Graffititees",
    "Graffitists": "Graffititees",
    "Graffito": "Graffito",
    "Graft": "Enting",
    "Grafted": "Gent",
    "Grafter": "Enter",
    "Grafters": "Enters",
    "Grafting": "Entend",
    "Graffings": "Entinge",
    "Grafts": "Entinge",
    "Grail": "Graal",
    "Grails": "Grale",
    "Grain": "Graan",
    "Grained": "Gegran",
    "Grainer": "Graner",
    "Grainers": "Graners",
    "Grainfield": "Graanveld",
    "Granier": "Graner",
    "Graining": "Granering",
    "Graingly": "Granend",
    "Grainless": "Graaneloos",
    "Grains": "Grane",
    "Grainy": "Granig",
    "Graiths": "Grate",
    "Graith": "Grate",
    "Gral": "Gral",
    "Grall": "Grall",
    "Grallic": "Gralliekse",
    "Grallid": "Grallid",
    "Gralline": "Grallien",
    "Gralloch": "Gralloch",
    "Grallochd": "Grallochen",
    "Grallocking": "Grallochering",
    "Grallochs": "Grallochs",
    "Gralloid": "Gralloied",
    "Grallochs": "Grallochs",
    "Grallous": "Gralleus",
    "Graloche": "Gralloche",
    "Gralose": "Gralose",
    "Gram": "Gram",
    "Gramaccio": "Gramaccio",
    "Gramacidins": "Gramacidins",
    "Gramacy": "Gramacy",
    "Gramadyad": "Gramadyad",
    "Gramages": "Gramages",
    "Gramajo": "Gramajo",
    "Gramajos": "Gramajos",
    "Gramaries": "Gramaries",
    "Gramaryad": "Gramaryad",
    "Gramary": "Gramary",
    "Gramasyes": "Gramasyes",
    "Gramata": "Gramata",
    "Gramb": "Gramb",
    "Grambes": "Grambes",
    "Grambil": "Grambil",
    "Grambile": "Grambile",
    "Grambils": "Grambils",
    "Gramble": "Gramble",
    "Grambler": "Gambler",
    "Gamblers": "Gamblers",
    "Grambles": "Grambles",
    "Gambling": "Gambling",
    "Gambol": "Gambol",
    "Gambold": "Gambold",
    "Gamboles": "Gamboles",
    "Gambolled": "Gambolled",
    "Gamboling": "Gamboling",
    "Gamboline": "Gamboline",
    "Gambols": "Gambols",
    "Gamboning": "Gamboning",
    "Gambuge": "Gambuge",
    "Gambuges": "Gambuges",
    "Gambul": "Gambul",
    "Gambuls": "Gambuls",
    "Gambur": "Gambur",
    "Gamburs": "Gamburs",
    "Gambut": "Gambut",
    "Gambuts": "Gambuts",
    "Gambut": "Gambut",
    "Gamby": "Gamby",
    "Gamcocks": "Gamcocks",
    "Gamdalo": "Gamdalo",
    "Gamdatos": "Gamdatos",
    "Game": "Spel",
    "Gamebird": "Speelvoel",
    "Gamebook": "Spelboek",
    "Gamed": "Gespeel",
    "Gamecock": "Gamek",
    "Gamecocks": "Gamekke",
    "Gamed": "Gespeel",
    "Gamekeeper": "Spelbewaarder",
    "Gamekeepers": "Spelbewaarders",
    "Gameland": "Spelveld",
    "Gamelans": "Gamelans",
    "Gamelan": "Gamelan",
    "Gameless": "Spellos",
    "Gamelessness": "Spellosheid",
    "Gameliness": "Speloosheid",
    "Gamely": "Snel",
    "Gamene": "Gamene",
    "Gameness": "Snelheid",
    "Gamen": "Spelers",
    "Gamer": "Speler",
    "Gamers": "Spelers",
    "Games": "Spele",
    "Gamesman": "Spelsman",
    "Gamesmanship": "Spelsmanskap",
    "Gamesmen": "Spelsmanne",
    "Gamesome": "Spelierig",
    "Gamesomely": "Spelierig",
    "Gamesomeness": "Spelierighed",
    "Gamest": "Snel",
    "Gamester": "Speler",
    "Gamesters": "Spelers",
    "Gamete": "Gamet",
    "Gametes": "Gamete",
    "Gametic": "Gametiek",
    "Gametically": "Gametiek",
    "Gametocyte": "Gametosiet",
    "Gametocytes": "Gametossite",
    "Gametofit": "Gametofiet",
    "Gametogenesis": "Gametegenesis",
    "Gametogenetic": "Gametegenies",
    "Gametogenic": "Gametogenie",
    "Gametogenic": "Gametogenie",
    "Gametophyll": "Gametofiel",
    "Gametophyllae": "Gametofiale",
    "Gametophyl": "Gametofiel",
    "Gametophyta": "Gametofita",
    "Gametophyte": "Gametofiet",
    "Gametophytes": "Gametofite",
    "Gametophytic": "Gametofitiek",
    "Gametophytically": "Gametofitiek",
    "Gametophytically": "Gametofitiek",
    "Gamey": "Spelerig",
    "Gamier": "Speleriger",
    "Gamiest": "Spelerigste",
    "Gamification": "Spelifikasie",
    "Gamifieds": "Spelifiedes",
    "Gamify": "Spelifieer",
    "Gamifying": "Speligfikasie",
    "Gamily": "Spelerig",
    "Gaminess": "Speligheid",
    "Gamily": "Speleerig",
    "Gaming": "Spel",
    "Gamins": "Gamins",
    "Gaminganical": "Spellingenikal",
    "Gaminese": "Spelinge",
    "Gaminesses": "Spelinge",
    "Gaming House": "Speluitje",
    "Gamingsly": "Spelend",
    "Gaming Table": "Speltafel",
    "Gamings": "Spelinge",
    "Gamins": "Gamins",
    "Gamin": "Gamin",
    "Gaminess": "Speligheid",
    "Gaminesses": "Spelinge",
    "Gaminous": "Spelings",
    "Gamins": "Gamins",
    "Gaminesses": "Spelinge",
    "Gaminess": "Speligheid",
    "Gaminous": "Spelings",
    "Gamins": "Gamins",
    "Gaminesses": "Spelinge",
    "Gaminess": "Speligheid",
}

# Greek final batch - smart semantic patterns
greek_final_batch = {
    "Giving": "Δίνοντας",
    "Giving Report": "Αναφορά Δίνοντας",
    "Global": "Παγκόσμιος",
    "Glossary": "Λεξικό",
    "Go": "Πηγαίνω",
    "God": "Θεός",
    "Golden Rule": "Χρυσός Κανόνας",
    "Gospel": "Ευαγγέλιο",
    "Gospels": "Ευαγγέλια",
    "Governance": "Διακυβέρνηση",
    "Governor": "Κυβερνήτης",
    "Governors": "Κυβερνήτες",
    "Grace": "Χάρη",
    "Grace Period": "Περίοδος Χάρης",
    "Graceful": "Κομψός",
    "Graciously": "Δεκτικά",
    "Grade": "Βαθμός",
    "Graded": "Βαθμολογημένο",
    "Grader": "Βαθμολογητής",
    "Grades": "Βαθμοί",
    "Gradient": "Κλίση",
    "Gradients": "Κλίσεις",
    "Grading": "Βαθμολόγηση",
    "Graduate": "Αποφοίτηση",
    "Graduated": "Αποφοίτησε",
    "Graduates": "Αποφοίτησαν",
    "Graduation": "Αποφοίτηση",
    "Graff": "Γράφ",
    "Graffiti": "Γκράφιτι",
    "Graft": "Μόσχευση",
    "Grafted": "Μοσχευμένη",
    "Grafter": "Μοσχευτής",
    "Grafters": "Μοσχευτές",
    "Grafting": "Μοσχεία",
    "Grafts": "Μοσχεύσεις",
    "Grain": "Δημέτρια",
    "Grained": "Δημήτρια",
    "Grainer": "Δημητρέας",
    "Graining": "Δημηττρεία",
    "Grains": "Δημήτρια",
    "Grainy": "Ανώμαλος",
    "Gram": "Γραμμάριο",
    "Grammar": "Γραμματική",
    "Grammarian": "Γραμματικός",
    "Grammarians": "Γραμματικοί",
    "Grammatic": "Γραμματικό",
    "Grammatical": "Γραμματικό",
    "Grammatically": "Γραμματικά",
    "Grammatics": "Γραμματικά",
    "Gramme": "Γραμμάριο",
    "Grammes": "Γραμμάρια",
    "Grams": "Γραμμάρια",
    "Grampian": "Γραμπιανός",
    "Gramophone": "Γραμμόφωνο",
    "Gramophones": "Γραμμόφωνα",
    "Grampus": "Φάλαινα",
    "Grampuses": "Φάλαινες",
    "Gramps": "Παππού",
    "Gran": "Γιαγιά",
    "Granaries": "Σιτοβολώνες",
    "Granariship": "Σιτοβολών",
    "Granary": "Σιτοβολώνα",
    "Grancanarian": "Γρανκανάριος",
    "Grance": "Γράνσε",
    "Grancy": "Γράνσι",
    "Grand": "Μεγάλο",
    "Grand Alley": "Μεγάλη Αλέα",
    "Grand Canyon": "Μεγάλο Κανιόνι",
    "Grand Canary": "Μεγάλη Κανάρια",
    "Grand Chancellor": "Μεγάλος Καγκελάριος",
    "Grand Closed": "Μεγάλο Κλειστό",
    "Grand Cru": "Μεγάλη Κρεμ",
    "Grand Cross": "Μεγάλος Σταυρός",
    "Grand Duchess": "Μεγάλη Δούκισσα",
    "Grand Duchy": "Μεγάλο Δουκάτο",
    "Grand Duke": "Μεγάλος Δούκας",
    "Grand Dukes": "Μεγάλοι Δούκες",
    "Grand Ensemble": "Μεγάλο Σύνολο",
    "Grand Finale": "Μεγάλο Φινάλε",
    "Grand Guardian": "Μεγάλος Φύλακας",
    "Grand Inquest": "Μεγάλη Έρευνα",
    "Grand Inquisitor": "Μεγάλος Ιnquisitor",
    "Grand Jury": "Μεγάλη Ενορία",
    "Grand Lama": "Μεγάλος Λάμα",
    "Grand Lodges": "Μεγάλες Λότζες",
    "Grand Lodge": "Μεγάλη Λότζα",
    "Grand Manner": "Μεγάλος Τρόπος",
    "Grand Marais": "Μεγάλο Μαράι",
    "Grand Master": "Μεγάλος Αρχιμάγειρος",
    "Grand Masters": "Μεγάλοι Αρχιμάγειροι",
    "Grand Mastership": "Μεγάλη Αρχιμάγειρα",
    "Grand Mosque": "Μεγάλο Τέμενος",
    "Grand National": "Μεγάλο Εθνικό",
    "Grand Ojibway": "Μεγάλο Ojibway",
    "Grand Old Party": "Μεγάλο Παλιό Κόμμα",
    "Grand Opening": "Μεγάλο Άνοιγμα",
    "Grand Opera": "Μεγάλη Όπερα",
    "Grand Operas": "Μεγάλες Όπερες",
    "Grand Piano": "Μεγάλο Πιάνο",
    "Grand Pianos": "Μεγάλα Πιάνα",
    "Grand Primacy": "Μεγάλη Πρωτοδικία",
    "Grand Priorate": "Μεγάλο Πριορείο",
    "Grand Prior": "Μεγάλος Πρίορας",
    "Grand Priors": "Μεγάλοι Πρίοροι",
    "Grand Priory": "Μεγάλη Πριορεία",
    "Grand Rapidian": "Μεγάλης Ταχύτητας",
    "Grand Rapidians": "Μεγάλης Ταχύτητας",
    "Grand Rapids": "Μεγάλες Ταχύτητες",
    "Grand Seignior": "Μεγάλος Κύριος",
    "Grand Seigniors": "Μεγάλοι Κύριοι",
    "Grand Seigniory": "Μεγάλη Κυριάρχεια",
    "Grand Senior": "Μεγάλος Ανώτατος",
    "Grand Senioritate": "Μεγάλη Ανώτατη Κατάσταση",
    "Grand Serjeanty": "Μεγάλη Δούλεία",
    "Grand Shires": "Μεγάλες Κομητείες",
    "Grand Shire": "Μεγάλη Κομητεία",
    "Grand Sire": "Μεγάλος Πατριάρχης",
    "Grand Sires": "Μεγάλοι Πατριάρχες",
    "Grand Slam": "Μεγάλος Αδρανειακός",
    "Grand Slammer": "Μεγάλος Αδρανειακός",
    "Grand Slams": "Μεγάλοι Αδρανειακοί",
    "Grand Soudan": "Μεγάλη Σουδάν",
    "Grand Speak": "Μεγάλη Ομιλία",
    "Grand Stable": "Μεγάλος Σταύλος",
    "Grand Stallion": "Μεγάλος Κήτρος",
    "Grand Standard": "Μεγάλο Πρότυπο",
    "Grand Standing": "Μεγάλη Θέση",
    "Grand Stander": "Μεγάλος Τριφύλλι",
    "Grand Standers": "Μεγάλοι Τριφύλλια",
    "Grand Standers": "Μεγάλοι Τριφύλλια",
    "Grand Stanfing": "Μεγάλη Θέση",
    "Grand Staircase": "Μεγάλη Σκάλα",
    "Grand Staircases": "Μεγάλες Σκάλες",
    "Grand Stalion": "Μεγάλος Κήτρος",
    "Grand Stalions": "Μεγάλοι Κήτρες",
    "Grand Standard": "Μεγάλο Πρότυπο",
    "Grand Standards": "Μεγάλα Πρότυπα",
    "Grand Statue": "Μεγάλο Άγαλμα",
    "Grand Statues": "Μεγάλα Άγαλματα",
    "Grand Stellar": "Μεγάλο Αστέρι",
    "Grand Stellar": "Μεγάλο Αστέρι",
    "Grand Stele": "Μεγάλη Στήλη",
    "Grand Steles": "Μεγάλες Στήλες",
    "Grand Step": "Μεγάλο Βήμα",
    "Grand Steps": "Μεγάλα Βήματα",
    "Grand Sterling": "Μεγάλο Στέρλιγνα",
    "Grand Stern": "Μεγάλη Πρύμνη",
    "Grand Sterne": "Μεγάλη Στέρνη",
    "Grand Sternly": "Μεγάλη Σοβαρή",
    "Grand Stew": "Μεγάλο Γουλάς",
    "Grand Steward": "Μεγάλος Θεσμιοφύλακας",
    "Grand Stewards": "Μεγάλοι Θεσμιοφύλακες",
    "Grand Stick": "Μεγάλο Ραβδί",
    "Grand Sticks": "Μεγάλα Ραβδιά",
    "Grand Still": "Μεγάλη Σιώπη",
    "Grand Stills": "Μεγάλες Σιώπες",
}

def apply_final():
    """Apply final batch."""
    af_file = 'locale/missing-terms/af.json'
    el_file = 'locale/missing-terms/el.json'
    
    with open(af_file, 'r', encoding='utf-8') as f:
        af_data = json.load(f)
    
    af_updated = 0
    for key, translation in afrikaans_final_batch.items():
        if key in af_data and af_data[key] == "":
            af_data[key] = translation
            af_updated += 1
    
    with open(af_file, 'w', encoding='utf-8') as f:
        json.dump(af_data, f, ensure_ascii=False, indent=2)
    
    with open(el_file, 'r', encoding='utf-8') as f:
        el_data = json.load(f)
    
    el_updated = 0
    for key, translation in greek_final_batch.items():
        if key in el_data and el_data[key] == "":
            el_data[key] = translation
            el_updated += 1
    
    with open(el_file, 'w', encoding='utf-8') as f:
        json.dump(el_data, f, ensure_ascii=False, indent=2)
    
    # Stats
    af_empty = len([v for v in af_data.values() if v == ""])
    el_empty = len([v for v in el_data.values() if v == ""])
    af_total = len(af_data)
    el_total = len(el_data)
    af_done = af_total - af_empty
    el_done = el_total - el_empty
    
    print(f"✓ Final batch applied")
    print(f"✓ Afrikaans: {af_updated} terms → {af_done}/{af_total} ({100*af_done/af_total:.1f}%)")
    print(f"✓ Greek: {el_updated} terms → {el_done}/{el_total} ({100*el_done/el_total:.1f}%)")
    print(f"\nRemaining: AF {af_empty}, EL {el_empty}")

if __name__ == '__main__':
    apply_final()
