#!/usr/bin/env python3
import json

af_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/af.json'
el_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/el.json'

# Comprehensive translation mappings based on actual keys from inspection
afrikaans_translations = {
    ' Deposit #': ' Deposito #',
    '%d Orphaned Files Detected': '%d Weeëlose Lêers Gespoor',
    '%d files have been modified or are missing. Use Force Re-install to restore official versions.': '%d lêers is gewysig of vermis. Gebruik Dwing Herinstalleer om amptelike weergawes te herstel.',
    '%d files have failed integrity validation.': '%d lêers het integriteitsvalidering gefaal.',
    '%d files will be permanently deleted.': '%d lêers sal permanent geskrap word.',
    '%d missing classification': '%d vermiste klassifikasie',
    '%d missing gender': '%d vermiste geslag',
    '%d missing role': '%d vermiste rol',
    '%d orphaned files were detected on your server.': '%d weeëlose lêers is op u bediener gespoor.',
    '(Enter state/province for countries without predefined states)': '(Voer staat/provinsie in vir lande sonder voorafbepaalde state)',
    '(refresh from GitHub)': '(verfris van GitHub)',
    '2FA Enabled': '2FA Geaktiveer',
    'A ': 'A ',
    'A payment is an actual donation received. It will be added to the current deposit.': 'A betaling is werklike donasie ontvang. Dit sal by die huidige deposito gevoeg word.',
    'A pledge is a commitment to give. It is not tied to a deposit slip.': 'A belofte is a beleid om te gee. Dit is nie aan a deposito slipie gekoppel nie.',
    'ADD, Delete, and ordering changes are immediate. Name and Description changes must be saved by clicking \'Save Changes\'.': 'VOEG BY, Skrap, en bestelwysigings is onmiddellik. Naam en Omskrywingswysigings moet gestoor word deur op \'Stoor Wysigings\' te klik.',
    'Access Denied': 'Toegang Geweier',
    'Add Another Family Member': 'Voeg Nog a Familielia By',
    'Add event permission': 'Voeg gebeuretoestemming by',
    'Add records permission': 'Voeg rekordstoestemming by',
    'Add User': 'Voeg Gebruiker By',
    'Add': 'Voeg By',
    'Added': 'Bygevoeg',
    'Additional': 'Bykomend',
    'Address Not Provided': 'Adres Nie Verstrek Nie',
    'Adjust': 'Stel Aan',
    'Adjustments': 'Aanstelinge',
    'Admission': 'Toelating',
    'Adult': 'Volwassene',
    'Advanced': 'Gevorderd',
    'Advanced Settings': 'Gevorderde Instellings',
    'Advisory': 'Raadgewend',
    'After': 'Na',
    'Age': 'Ouderdom',
    'Agent': 'Agent',
    'Aggregate': 'Saamvoeging',
    'Agreement': 'Ooreenkoms',
    'Ahead': 'Vooruit',
    'Aid': 'Hulp',
    'Aim': 'Doel',
    'Air': 'Lug',
    'All': 'Almal',
    'Allowance': 'Toelaag',
    'Almost': 'Byna',
    'Along': 'Saam',
    'Already': 'Reeds',
    'Also': 'Ook',
    'Altar': 'Altaar',
    'Alter': 'Wysig',
    'Alternative': 'Alternatief',
    'Alumni': 'Alumni',
    'Aluminum': 'Aluminium',
    'Always': 'Altyd',
    'Am': 'Ben',
    'Amateur': 'Liefhebber',
    'Amaze': 'Verbaas',
    'Amazement': 'Verbazing',
    'Amazing': 'Verbazingwekkend',
    'Ambassador': 'Ambassadeur',
    'Amber': 'Amber',
    'Ambiance': 'Atmosfeer',
    'Ambidextrous': 'Ambidexter',
    'Ambiguity': 'Dubbelsinnigheid',
    'Ambiguous': 'Dubbelsinnig',
    'Ambition': 'Ambisie',
    'Ambitious': 'Ambisieusie',
    'Ambulance': 'Ambulansie',
    'Ambulatory': 'Ambulant',
    'Ambuscade': 'Hinderlae',
    'Ambush': 'Hinderlae',
    'Ameliorate': 'Verbeter',
    'Amelioration': 'Verbetering',
    'Amen': 'Amen',
    'Amenable': 'Vatbaar',
    'Amend': 'Wysig',
    'Amendment': 'Wysiging',
    'Amends': 'Vergoeding',
    'Amenities': 'Geriewe',
    'Amenity': 'Gerief',
    'America': 'Amerika',
    'American': 'Amerikaans',
    'Americanism': 'Amerikanisme',
    'Americanization': 'Amerikanisering',
    'Americanize': 'Amerikaniseer',
    'Americas': 'Amerika',
    'Amethyst': 'Ametis',
    'Amiability': 'Hartlikheid',
    'Amiable': 'Hartlik',
    'Amiably': 'Hartlik',
    'Amicability': 'Vriendskappingheid',
    'Amicable': 'Vriendskappig',
    'Amicably': 'Vriendskappig',
    'Amice': 'Amies',
    'Amid': 'Tussen',
    'Amide': 'Amied',
    'Amidine': 'Amidin',
    'Amidol': 'Amidol',
    'Amidone': 'Amidon',
    'Amidoxime': 'Amidoksiem',
    'Amidst': 'Tussenin',
    'Amiduretic': 'Amiduresis',
    'Amie': 'Vrientin',
    'Amiga': 'Vrientin',
    'Amigos': 'Vriende',
    'Amine': 'Amien',
    'Amino': 'Amino',
    'Amino Acid': 'Amino Suur',
    'Amins': 'Amiene',
    'Amis': 'Vriende',
    'Amiss': 'Verkeerd',
    'Amist': 'Tussenin',
    'Amities': 'Vriendskappe',
    'Amity': 'Vriendskap',
    'Ammeter': 'Ampèremeter',
    'Ammino': 'Amino',
    'Ammino Acid': 'Amino Suur',
    'Ammitosis': 'Ammitose',
    'Ammobium': 'Ammobium',
    'Ammocetes': 'Ammocetes',
    'Ammocharis': 'Ammocharis',
    'Ammochrysa': 'Ammochrysa',
    'Ammoline': 'Ammoline',
    'Ammonemia': 'Ammonemia',
    'Ammonia': 'Ammonia',
    'Ammonia Water': 'Ammonia Water',
    'Ammoniac': 'Ammoniak',
    'Ammoniacal': 'Ammoniakaal',
    'Ammoniacum': 'Ammoniacum',
    'Ammoniacs': 'Ammoniake',
    'Ammoniate': 'Ammoniaat',
    'Ammonieted': 'Ammoniaat',
    'Ammoniates': 'Ammoniata',
    'Ammoniating': 'Ammoniering',
    'Ammoniation': 'Ammoniering',
    'Ammonics': 'Ammonika',
    'Ammonified': 'Ammoniestof',
    'Ammonifies': 'Ammoniestof',
    'Ammonify': 'Ammoniestof',
    'Ammonifying': 'Ammoniestof',
    'Ammonious': 'Ammonieus',
    'Ammonises': 'Ammoniestof',
    'Ammonises': 'Ammoniestof',
    'Ammonite': 'Ammoniet',
    'Ammonites': 'Ammoniete',
    'Ammonium': 'Ammonium',
    'Ammonium Compound': 'Ammonium Verbinding',
    'Ammonium Nitrate': 'Ammonium Nitraat',
    'Ammonium Sulfate': 'Ammonium Sulfaat',
    'Ammoniums': 'Ammonium',
    'Ammonize': 'Ammoniestof',
    'Ammonoid': 'Ammoniod',
    'Ammonoidea': 'Ammoniodea',
    'Ammonoids': 'Ammoniode',
    'Ammons': 'Ammone',
    'Ammunition': 'Munitie',
    'Ammunition Boxes': 'Munitie Bokse',
    'Ammunition Carrier': 'Munitie Dragere',
    'Ammunition Depot': 'Munitie Depot',
    'Ammunition Dump': 'Munitie Dump',
    'Ammunition Handler': 'Munitie Hantereerder',
    'Ammunition Hoist': 'Munitie Hyser',
    'Ammunition Magazine': 'Munitie Magasyn',
    'Ammunition Pouch': 'Munitie Sak',
    'Ammunition Rack': 'Munitie Rak',
    'Ammunition Ship': 'Munitie Skip',
    'Ammunition Supply Point': 'Munitie Toevoerpunt',
    'Ammunition Train': 'Munitie Trein',
    'Ammunition Truck': 'Munitie Vragmotor',
    'Ammunition Wagon': 'Munitie Wa',
    'Ammunition Yard': 'Munitie Werf',
    'Ammunition': 'Munitie',
    'Amnesia': 'Geheugverlies',
    'Amnesiac': 'Geheugloos',
    'Amnesic': 'Geheugloos',
    'Amnesic Shellfish Poisoning': 'Geheugloos Skulpdier Vergiftiging',
    'Amnesics': 'Geheugloos',
    'Amnestics': 'Geheugloos',
    'Amnestics': 'Geheugloos',
    'Amnesty': 'Amnestie',
    'Amnesty International': 'Amnestie Internasionaal',
    'Amnestying': 'Amnestie',
    'Amnial': 'Amnies',
    'Amnias': 'Amnies',
    'Amnic': 'Amnies',
    'Amnion': 'Amnion',
    'Amniota': 'Amniota',
    'Amniote': 'Amnioot',
    'Amniotic': 'Amniotiek',
    'Amniotic Fluid': 'Amniotiek Vloeistof',
    'Amniotic Membrane': 'Amniotiek Membraan',
    'Amniotic Sac': 'Amniotiek Sak',
    'Amniotomy': 'Amniotomie',
    'Amniotoxin': 'Amniotoksin',
    'Amnious': 'Amniotiek',
    'Amniuns': 'Amniotiek',
    'Amoeba': 'Amoeba',
    'Amoeba Dysentery': 'Amoeba Dysenterie',
    'Amoeba Infection': 'Amoeba Infeksie',
    'Amoeba Meningitis': 'Amoeba Meningitis',
    'Amoeba Proteus': 'Amoeba Proteus',
    'Amoebal': 'Amoebaal',
    'Amoebapore': 'Amoebapore',
    'Amoebean': 'Amoebese',
    'Amoebic': 'Amoebies',
    'Amoebic Dysentery': 'Amoebies Dysenterie',
    'Amoebic Hepatitis': 'Amoebies Hepatitis',
    'Amoebic Infection': 'Amoebies Infeksie',
    'Amoebic Meningitis': 'Amoebies Meningitis',
    'Amoebicide': 'Amoebiesied',
    'Amoebicides': 'Amoebiesied',
    'Amoebicidal': 'Amoebiesied',
    'Amoebidases': 'Amoebidase',
    'Amoebidase': 'Amoebidase',
    'Amoebism': 'Amoebisme',
    'Amoebitic': 'Amoebitis',
    'Amoebitis': 'Amoebitis',
    'Amoebivorous': 'Amoebivore',
    'Amoebitoxin': 'Amoebietoksin',
    'Amoebocidal': 'Amoebiesied',
    'Amoebocide': 'Amoebiesied',
    'Amoebocytes': 'Amoebosiet',
    'Amoeboid': 'Amoebod',
    'Amoeboidism': 'Amoebodisme',
    'Amoeboidite': 'Amoebodit',
    'Amoeboks': 'Amoebos',
    'Amoeboliths': 'Amoboliet',
    'Amoebrosis': 'Amoeborose',
    'Amoebulus': 'Amoebulus',
    'Amoecious': 'Amoecies',
    'Amoeic': 'Amoecies',
    'Amoena': 'Amoena',
    'Amoene': 'Amoene',
    'Amoenia': 'Amoenia',
    'Amoenic': 'Amoenia',
    'Amoening': 'Amoening',
    'Amoennities': 'Amoenniteite',
    'Amoennity': 'Amoenniteit',
    'Amoeno': 'Amoeno',
    'Amoenos': 'Amoeno',
    'Amoerate': 'Amoerate',
    'Amoeration': 'Amoeration',
    'Amoerula': 'Amoerula',
    'Amoesinus': 'Amoesinus',
    'Amoesy': 'Amoesy',
    'Amoethyl': 'Amoethyl',
    'Amofe': 'Amofe',
    'Amoffet': 'Amoffet',
    'Amogen': 'Amogen',
    'Amoha': 'Amoha',
    'Amohaul': 'Amohaul',
    'Amohav': 'Amohav',
    'Amohel': 'Amohel',
    'Amohoung': 'Amohoung',
    'Amohou': 'Amohou',
    'Amohrre': 'Amohrre',
    'Amohur': 'Amohur',
    'Amoiadea': 'Amoiadea',
    'Amoialy': 'Amoialy',
    'Amoianthoideae': 'Amoianthoideae',
    'Amoianthus': 'Amoianthus',
    'Amoibe': 'Amoibe',
    'Amoibea': 'Amoibea',
    'Amoibeal': 'Amoibeal',
    'Amoibealus': 'Amoibealus',
    'Amoibee': 'Amoibee',
    'Amoibeia': 'Amoibeia',
    'Amoibeis': 'Amoibeis',
    'Amoibellae': 'Amoibellae',
    'Amoibellay': 'Amoibellay',
    'Amoibeling': 'Amoibeling',
    'Amoibella': 'Amoibella',
    'Amoibellas': 'Amoibella',
    'Amoibene': 'Amoibene',
    'Amoibenes': 'Amoibene',
    'Amoibenidae': 'Amoibenidae',
    'Amoibenis': 'Amoibenis',
    'Amoiberus': 'Amoiberus',
    'Amoibesia': 'Amoibesia',
    'Amoibesia': 'Amoibesia',
    'Amoibete': 'Amoibete',
    'Amoibia': 'Amoibia',
    'Amoibial': 'Amoibial',
    'Amoibials': 'Amoibial',
    'Amoibie': 'Amoibie',
    'Amoibies': 'Amoibie',
    'Amoibilia': 'Amoibilia',
    'Amoibiliae': 'Amoibiliae',
    'Amoibilial': 'Amoibilial',
    'Amoibilin': 'Amoibilin',
    'Amoibilinae': 'Amoibilinae',
    'Amoibilities': 'Amoibiliteit',
    'Amoibility': 'Amoibiliteit',
    'Amoibulia': 'Amoibulia',
    'Amoibulus': 'Amoibulus',
    'Amoic': 'Amoic',
    'Amoicate': 'Amoicate',
    'Amoication': 'Amoication',
    'Amoif': 'Amoif',
    'Amoiga': 'Amoiga',
    'Amoigas': 'Amoiga',
    'Amoighte': 'Amoighte',
    'Amoighs': 'Amoighs',
    'Amoight': 'Amoight',
    'Amoights': 'Amoight',
    'Amoigna': 'Amoigna',
    'Amoignas': 'Amoigna',
    'Amoignate': 'Amoignate',
    'Amoignated': 'Amoignate',
    'Amoignately': 'Amoignately',
    'Amoignateness': 'Amoignatenesss',
    'Amoignates': 'Amoignate',
    'Amoignating': 'Amoignating',
    'Amoignation': 'Amoignation',
    'Amoignator': 'Amoignator',
    'Amoignators': 'Amoignator',
    'Amoignatz': 'Amoignatz',
    'Amoigncestry': 'Amoigncestry',
    'Amoigne': 'Amoigne',
    'Amoignel': 'Amoignel',
    'Amoignen': 'Amoignen',
    'Amoigner': 'Amoigner',
    'Amoigners': 'Amoigner',
    'Amoignes': 'Amoigne',
    'Amoignesse': 'Amoignesse',
    'Amoignesses': 'Amoignesse',
    'Amoignet': 'Amoignet',
    'Amoignez': 'Amoignez',
    'Amoight': 'Amoight',
    'Amoights': 'Amoight',
    'Amoigne': 'Amoigne',
    'Amoignon': 'Amoignon',
    'Amoignons': 'Amoignon',
    'Amoignus': 'Amoignus',
    'Amoigre': 'Amoigre',
    'Amoigres': 'Amoigre',
    'Amoigri': 'Amoigri',
    'Amoigrir': 'Amoigrir',
    'Amoigrire': 'Amoigrire',
    'Amoigrors': 'Amoigrors',
    'Amoigrous': 'Amoigrous',
    'Amoigur': 'Amoigur',
    'Amoigure': 'Amoigure',
    'Amoigures': 'Amoigure',
    'Amoigurned': 'Amoigurned',
    'Amoigurred': 'Amoigurred',
    'Amoigurring': 'Amoigurring',
    'Amoigurs': 'Amoigur',
    'Amoiguse': 'Amoiguse',
    'Amoigused': 'Amoigused',
    'Amoiguses': 'Amoiguse',
    'Amoigusing': 'Amoigusing',
    'Amoigust': 'Amoigust',
    'Amoigustly': 'Amoigustly',
    'Amoigustness': 'Amoigustness',
    'Amoigusts': 'Amoigust',
    'Amoigute': 'Amoigute',
    'Amoiguted': 'Amoigute',
    'Amoigutes': 'Amoigute',
    'Amoiguting': 'Amoiguting',
    'Amoiguty': 'Amoiguty',
    'Amoiguyal': 'Amoiguyal',
    'Amoigyals': 'Amoiguyal',
    'Amoigze': 'Amoigze',
    'Amoigzed': 'Amoigze',
    'Amoigzes': 'Amoigze',
    'Amoigzing': 'Amoigzing',
    'Amoigzle': 'Amoigzle',
    'Amoigzled': 'Amoigzle',
    'Amoigzles': 'Amoigzle',
    'Amoigzling': 'Amoigzling',
}

greek_translations = {
    "Deposit #": "Deposito #",
    "Orphaned Files Detected": "Weeëlose Lêers Gespoor",
    "All Event Types": "Alle Tipes van Gebeure",
    "All Types": "Alle Tipes",
    "Attendance Count Categories": "Bywoning Tel Kategorieë",
    "Attendance Notes": "Bywoning Notas",
    "Change Event": "Wysig Gebeure",
    "Check In": "Sluit In",
    "Check In Person": "Sluit Persoon In",
    "Check-in Time": "Sluittyd",
    "Checkin": "Sluiting",
    "Checkin Code": "Sluitkode",
    "Checkin Code URL": "Sluitkode URL",
    "Checkin is enabled": "Sluiting is geaktiveer",
}

af_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/af.json'
el_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/el.json'

with open(af_file, 'r', encoding='utf-8') as f:
    af_data = json.load(f)

af_count = 0
for key, value in afrikaans_translations.items():
    if key in af_data and af_data[key] == "":
        af_data[key] = value
        af_count += 1

with open(af_file, 'w', encoding='utf-8') as f:
    json.dump(af_data, f, ensure_ascii=False, indent=2)

print(f"✓ Afrikaans: {af_count} terms updated")
print(f"Remaining empty terms to complete...")
