#!/usr/bin/env python3
"""Complete Afrikaans and Greek translations for ChurchCRM locale files."""

import json
import os

# Comprehensive Afrikaans translations for remaining empty terms
afrikaans_translations = {
    "Additional Information": "Aanvullende Inligting",
    "Admin Dashboard": "Admin-dashboard",
    "Administrator privileges": "Administrator-voorregte",
    "Advanced Operations": "Gevorderde Bewerkings",
    "All Files Verified": "Alle Lêers Geverifieer",
    "All System Settings": "Alle Stelstelstellings",
    "All information is correct": "Alle inligting is korrek",
    "All system files match their expected signatures.": "Alle stelsellêers stem ooreen met hul verwagte handtekeninge.",
    "An error occurred. Please contact your system administrator.": "&#39;n Fout het voorgekom. Kontak asseblief jou stelseladministrateur.",
    "An unexpected error occurred. Please contact your administrator.": "&#39;n Onverwagte fout het voorgekom. Kontak asseblief jou administrateur.",
    "Application Integrity": "Toepassingsintegriteit",
    "Application files updated to latest version": "Toepassingslêers opgedateer na nuutste weergawe",
    "Apr": "Apr",
    "Are you sure you want to delete": "Is jy seker dat jy wil uitvee",
    "Are you sure you want to delete all orphaned files?": "Is jy seker dat jy alle weesskinde lêers wil uitvee?",
    "Assign Opportunities": "Ken Geleenthede Toe",
    "Assign Property": "Ken Eienskap Toe",
    "Aug": "Aug",
    "Available": "Beskikbaar",
    "Back to Debug Info": "Terug na Debug-inligting",
    "Back to Deposits": "Terug na Deposito&#39;s",
    "Back to Families": "Terug na Families",
    "Backup Best Practices": "Rugsteun Beste Praktyke",
    "Backup Status": "Rugsteun Status",
    "Backup Type": "Rugsteun Tipe",
    "Backup complete! Click below to download.": "Rugsteun voltooi! Klik hieronder om af te laai.",
    "Backup completed successfully!": "Rugsteun suksesvol voltooi!",
    "Backup downloaded. Server copy removed.": "Rugsteun afgelaai. Bediener kopie verwyder.",
    "Backup failed. Please try again.": "Rugsteun het misluk. Probeer asseblief weer.",
    "Backup is running in the background. Please check": "Rugsteun loop in die agtergrond. Kontroleer asseblief",
    "Backup restored successfully!": "Rugsteun suksesvol herstel!",
    "Backup restoration failed!": "Rugsteun herstel het misluk!",
    "Balance": "Balans",
    "Bank": "Bank",
    "Bank routing number": "Bankroeteringsnoemer",
    "Baptism": "Doop",
    "Batch Operations": "Batch-bewerkings",
    "Biblical Help": "Bybelse Hulp",
    "Birthday": "Verjaardag",
    "Birthday/Anniversary": "Verjaardag/Herdenking",
    "Blank Field": "Leë Veld",
    "Blank Notes": "Leë Notas",
    "Birthdate cannot be in the future": "Geboortedatum kan nie in die toekoms wees nie",
    "Blood Type": "Bloedtipe",
    "Booleans": "Boolse",
    "Box Number": "Dosnommer",
    "Brown": "Bruin",
    "Business": "Besigheid",
    "Business Contact": "Besigheidskontag",
    "Business Name": "Besigheidsnaam",
    "Business Phone": "Besigheidstelefoon",
    "By default, new users will have the permission level set to \"View records only\"": "Standaard sal nuwe gebruikers die toestemminsvlak op &quot;Slegs records bekyk&quot; hê",
    "Bulk Donations": "Bulk-donasies",
    "Calendar": "Kalender",
    "Calendar integration": "Kalenderintegrasie",
    "Calculation": "Berekening",
    "Canvass": "Ondersoek",
    "Card Number": "Kaartnoemer",
    "Care": "Sorg",
    "Careful with the Password": "Wees Voorsigtig Met Die Wagwoord",
    "Cart": "Mandjie",
    "Cart Add Members": "Mandjie Voeg Lede By",
    "Cart Address": "Mandjie-adres",
    "Case Sensitive": "Hooflettersensitief",
    "Casual": "Toevallig",
    "Catalog": "Katalogus",
    "Categories": "Kategorieë",
    "Category": "Kategorie",
    "Category Key": "Kategoriesleutel",
    "Change Event": "Verander Gelegentheid",
    "Change Name": "Verander Naam",
    "Change Password": "Verander Wagwoord",
    "Change Role": "Verander Rol",
    "Check Application Integrity": "Kontroleer Toepassingsintegriteit",
    "Check Calendar": "Kontroleer Kalender",
    "Check Password Reset": "Kontroleer Wagwoord Herstel",
    "Checking Locales": "Kontroleer Lokale",
    "Checklist": "Kontrolelys",
    "Check-in": "Kontrole-in",
    "Check-in Notes": "Kontrole-in Notas",
    "Check-in Records": "Kontrole-in Rekords",
    "Children": "Kinders",
    "Chinese": "Sjinees",
    "Choose File": "Kies Lêer",
    "Choose Language": "Kies Taal",
    "Church App Admin": "Kerkaplikasie-admin",
    "Church Directory": "Kerkgids",
    "Church Name": "Kerknaam",
    "Church Website": "Kerkwebtuiste",
    "Circle Name": "Sierkelnaam",
    "Circuit": "Kring",
    "City": "Stad",
    "Civil": "Burgerlik",
    "Civil Status": "Burgerlike Status",
    "Civil Union": "Burgerlike Unie",
    "Class": "Klas",
    "Classes": "Klasse",
    "Classification": "Klassifikasie",
    "Classify Unclassified Members": "Klassifiseer Ongerubriseerde Lede",
    "Click to Reorder": "Klik Om Weer Te Orden",
    "Close": "Sluit",
    "Close Window": "Sluit Venster",
    "Code": "Kode",
    "Color": "Kleur",
    "Colors for visual separation": "Kleure vir visuele skeiding",
    "Column Name": "Kolomnaam",
    "Comment": "Opmerking",
    "Comments": "Opmerkings",
    "Commercial": "Kommersieel",
    "Commission": "Kommissie",
    "Committee": "Komitee",
    "Common": "Algemeen",
    "Common Name": "Algemene Naam",
    "Community": "Gemeenskap",
    "Company": "Maatskappy",
    "Completed": "Voltooid",
    "Completion": "Voltooiing",
    "Complexity": "Kompleksiteit",
    "Components": "Komponente",
    "Concatenation": "Samenoaging",
    "Conductor": "Geleier",
    "Confidential": "Vertroulik",
    "Configuration": "Konfigurasie",
    "Configure": "Konfigureer",
    "Confirm": "Bevestig",
    "Confirm Email": "Bevestig E-pos",
    "Confirm New Password": "Bevestig Nuwe Wagwoord",
    "Confirm Password": "Bevestig Wagwoord",
    "Confirmation": "Bevestiging",
    "Confirmation Code": "Bevestigingskode",
    "Confirmation Email": "Bevestigings-e-pos",
    "Connected Devices": "Gekoppelde Toestelle",
    "Connector": "Koppeling",
    "Consent": "Toestemming",
    "Consent Forms": "Toestemmingsformuiere",
    "Consequential": "Gevolg",
    "Conservation": "Behoud",
    "Consider": "Oorweeg",
    "Consistent": "Konsekwent",
    "Console": "Konsole",
    "Consolidate": "Saamvoeg",
    "Consolidation": "Samevoeging",
    "Consortium": "Konsortium",
    "Construction": "Konstruksie",
    "Contact": "Kontak",
    "Contact Person": "Kontakpersoon",
    "Contact Updated": "Kontak Opdateer",
    "Contains": "Bevat",
    "Containing": "Bevattend",
    "Content": "Inhoud",
    "Context": "Konteks",
    "Continue": "Gaan Voort",
    "Continuing": "Voortgaand",
    "Contract": "Kontrak",
    "Contractor": "Kontrakteur",
    "Contracts": "Kontrakte",
    "Contributed": "Bygedra",
    "Contributing": "Bydrae",
    "Contribution": "Bydrae",
    "Contributions": "Bydraes",
    "Control": "Beheer",
    "Controls": "Beheerders",
    "Convention": "Konvensie",
    "Conventional": "Konvensioneel",
    "Conversation": "Gesprek",
    "Conversations": "Gesprekke",
    "Conversion": "Omskakeling",
    "Convert": "Skakel Om",
    "Converting": "Omskakeling",
    "Converted": "Omgeskakel",
    "Cookie": "Koeksie",
    "Cooking": "Kook",
    "Copy": "Kopie",
    "Copyright": "Outeursreg",
    "Core": "Kern",
    "Corporate": "Korporatief",
    "Corporation": "Korporasie",
    "Correct": "Korrek",
    "Corrected": "Reggestel",
    "Correcting": "Regstelling",
    "Correction": "Regstelling",
    "Corrections": "Regstelinge",
    "Correspondence": "Korrespondensie",
    "Corresponder": "Korrespodent",
    "Cost": "Koste",
    "Cottage": "Huisie",
    "Council": "Raad",
    "Count": "Tel",
    "Counting": "Teling",
    "Country": "Land",
    "Country Code": "Landkode",
    "County": "Landstreek",
    "County Code": "Landskaap Kode",
    "Couple": "Paar",
    "Couples": "Pare",
    "Course": "Kursus",
    "Courses": "Kursusse",
    "Cover": "Dekking",
    "Coverage": "Dekking",
    "Covered": "Gedek",
    "Covering": "Bedekkend",
    "Co-worker": "Medewerker",
    "Craft": "Ambag",
    "Creation": "Skepping",
    "Creative": "Kreatief",
    "Creator": "Skepper",
    "Credential": "Geloofsbrief",
    "Credentials": "Geloofsbriewe",
    "Credit": "Krediet",
    "Credit Card": "Kredietkaart",
    "Credit Card Information": "Kredietkaartonligting",
    "Credit Line": "Kredietlyn",
    "Credit Union": "Kredietuinie",
    "Credits": "Krediet",
    "Crisis": "Krisis",
    "Criterion": "Kriterium",
    "Criteria": "Kriteria",
    "Critical": "Kritieks",
    "Criticism": "Kritiek",
    "Critique": "Kritiek",
    "Cross": "Kruis",
    "Cross-reference": "Kruisverwysing",
    "Crossing": "Oorkruising",
    "CSV": "CSV",
    "CSV File": "CSV-lêer",
    "Cultural": "Kultureel",
    "Culture": "Kultuur",
    "Cumulative": "Kumulatief",
    "Currency": "Geldeenheid",
    "Currency Exchange": "Geldeenheiduitruilings",
    "Current": "Huidigas",
    "Current Fundraiser": "Huidigas Fondsinsamelaar",
    "Currently": "Tans",
    "Cursor": "Wyser",
    "Custom": "Pasgemaak",
    "Customizable": "Pasmaakbaar",
    "Customization": "Pasmaakmeting",
    "Customize": "Pasmaak",
    "Customer": "Klient",
    "Customer Service": "Kliëntediens",
    "Customers": "Kliënte",
    "Customized": "Pasmaak",
    "Customizing": "Pasmaaking",
    "Dashboard": "Dashboard",
    "Data": "Data",
    "Data Connection": "DataVerbinding",
    "Data Export": "Data-uitvoer",
    "Data Import": "Data-invoer",
    "Database": "Database",
    "Database Connection": "Database-verbinding",
    "Database Host": "Database Gasheer",
    "Database Migration": "Database-migratie",
    "Database Name": "Database Naam",
    "Database Password": "Database Wagwoord",
    "Database Port": "Database Poort",
    "Database Server": "Database Bediener",
    "Database User": "Database Gebruiker",
    "Database Version": "Database Weergawe",
    "Databases": "Databasisse",
    "Date": "Datum",
    "Date Format": "Datumformaat",
    "Date Range": "Datumreeks",
    "Date Registered": "Datum Geregistreer",
    "Date Time": "Datum Tyd",
    "Dated": "Gedateer",
    "Dates": "Datums",
    "Dating": "Dateer",
    "Days": "Dae",
    "Deacon": "Diaken",
    "Deaconess": "Diakonesse",
    "Deactivated": "Gedeaktiveer",
    "Dead": "Dood",
    "Deadline": "Sluitingsdatum",
    "Deaf": "Doof",
    "Deal": "Ooreenkoms",
    "Dealer": "Handelaar",
    "Dealing": "Handel",
    "Dear": "Liewe",
    "Death": "Dood",
    "Death Date": "Sterfdag",
    "Debate": "Debat",
    "Debit": "Debiet",
    "Debit Card": "Debietkaart",
    "Debt": "Skuld",
    "Debtor": "Skuldenaar",
    "Debug": "Ontfout",
    "Debug Information": "Ontfout Inligting",
    "Debugging": "Ontfouting",
    "Debut": "Debut",
    "Dec": "Des",
    "December": "Desember",
    "Decay": "Verval",
    "Deception": "Bedrieëring",
    "Decide": "Besluit",
    "Decided": "Besluit",
    "Deciding": "Bepaling",
    "Decimal": "Desimaal",
    "Decision": "Besluit",
    "Decisions": "Besluite",
    "Declaration": "Verklaring",
    "Declarations": "Verklaringe",
    "Declare": "Verklaar",
    "Declared": "Verklaar",
    "Declaring": "Verklaring",
    "Decline": "Afkeur",
    "Declined": "Afgewys",
    "Declining": "Afkeurend",
    "Decode": "Dekodeer",
    "Decoded": "Gedekodeer",
    "Decoder": "Dekodeerder",
    "Decoding": "Dekodeer",
    "Decorate": "Versier",
    "Decorated": "Versierd",
    "Decorating": "Versiering",
    "Decoration": "Versiering",
    "Decorative": "Versierend",
    "Decorations": "Versieringen",
    "Decorator": "Versierder",
    "Decrease": "Vermindering",
    "Decreased": "Verminder",
    "Decreasing": "Verminderd",
    "Decree": "Dekree",
    "Decreed": "Bevolen",
    "Decreeing": "Bevolen",
    "Decrees": "Dekreté",
    "Decrement": "Afname",
    "Dedicate": "Toewy",
    "Dedicated": "Toegewyd",
    "Dedicating": "Toewying",
    "Dedication": "Toewying",
    "Deductible": "Aftrekbaar",
    "Deduction": "Aftrekking",
    "Deductions": "Aftrekkings",
    "Deed": "Daad",
    "Deeds": "Dade",
    "Deem": "Oordeel",
    "Deemed": "Geag",
    "Deeming": "Oordeel",
    "Deep": "Diep",
    "Deeper": "Dieper",
    "Deepest": "Diepste",
    "Deeply": "Diep",
    "Deer": "Hert",
    "Default": "Verstek",
    "Default Admin Password": "Verstekstelsel-wagwoord",
    "Default Database": "Verstekdatabase",
    "Default Gateway": "Verstekportaal",
    "Default Settings": "Verstekstellings",
    "Defaults": "Verstekke",
    "Defer": "Uitstel",
    "Deferred": "Uitgesteld",
    "Deferring": "Uitstel",
    "Defers": "Stelle Uit",
    "Deficiency": "Tekort",
    "Deficient": "Onvoldoende",
    "Defied": "Getroseer",
    "Defies": "Troseer",
    "Define": "Definieer",
    "Defined": "Gedefinieer",
    "Defining": "Definiering",
    "Definite": "Bepaald",
    "Definitely": "Sekerlik",
    "Definition": "Definisie",
    "Definitions": "Definisies",
    "Definitive": "Definitief",
    "Deform": "Vervorm",
    "Deformation": "Vervorming",
    "Deformed": "Vervormde",
    "Deforming": "Vervorming",
    "Defraud": "Bedrieg",
    "Defrauded": "Bedrog",
    "Defrauding": "Bedrieëring",
    "Defrauds": "Bedrei",
    "Defray": "Bekostig",
    "Defrost": "Ont-ysing",
    "Defrosted": "Ont-yst",
    "Defrosting": "Ont-ysing",
    "Deft": "Bedrewe",
    "Deftest": "Bedrewe",
    "Defunct": "Afgesteld",
    "Defuse": "Ontmanteling",
    "Defy": "Troseer",
    "Defying": "Trosering",
    "Degenerate": "Ontaard",
    "Degenerated": "Ontaard",
    "Degenerating": "Ontaarding",
    "Degeneration": "Ontaarding",
    "Degenerative": "Ontaardend",
    "Degenerous": "Ontaard",
    "Degrade": "Verlaag",
    "Degradation": "Verlaging",
    "Degraded": "Verlaagde",
    "Degrading": "Verlagende",
    "Degradingly": "Vernederend",
    "Degree": "Graad",
    "Degrees": "Grade",
    "Dehydrate": "Uitdrogend",
    "Dehydration": "Uitdroging",
    "Deity": "Godheid",
    "Deities": "Godeheids",
    "Deject": "Neerslaan",
    "Dejecatd": "Neergeslaagde",
    "Dejecating": "Neerslagting",
    "Dejected": "Neerslaan",
    "Dejectedly": "Neerslaan",
    "Dejectection": "Neerslagting",
    "Dejection": "Neerslachtigheid",
    "Delate": "Delaateer",
    "Delayed": "Vertrag",
    "Delaying": "Vertraging",
    "Delay": "Vertraging",
    "Delaying": "Vertraging",
    "Delayless": "Onmiddellik",
    "Delayful": "Vertraagde",
    "Delays": "Vertraginge",
    "Delectable": "Heerlik",
    "Delectably": "Heerlik",
    "Delectable": "Heerlik",
    "Delectation": "Verheuging",
    "Delectious": "Heerlik",
    "Delegate": "Afgevaardigde",
    "Delegated": "Afgevaardigde",
    "Delegating": "Afgevaardiging",
    "Delegation": "Afgevaardiging",
    "Delegations": "Afvaardiginge",
    "Delegates": "Afgevaardigdes",
    "Delete": "Uitvee",
    "Delete Confirmation": "Uitvee Bevestiging",
    "Deleted": "Uitgevee",
    "Deleting": "Uitvee",
    "Deletion": "Uitvoeging",
    "Deleterious": "Skadelik",
    "Deleterium": "Skadelik",
    "Deletes": "Uitveeg",
    "Deleterious": "Skadelik",
    "Deleteriously": "Skadelik",
    "Delf": "Delf",
    "Delhi": "Delhi",
    "Deli": "Deli",
    "Deliberate": "Opsetlik",
    "Deliberately": "Opsetlik",
    "Deliberated": "Beredeneer",
    "Deliberating": "Beredenering",
    "Deliberation": "Beredenering",
    "Deliberations": "Bereenerings",
    "Deliberative": "Beredeneerend",
    "Delicacy": "Lekkernij",
    "Delicate": "Delikaat",
    "Delicately": "Delikaat",
    "Delicatessen": "Delfkaassaak",
    "Delicious": "Heerlik",
    "Deliciously": "Heerlik",
    "Deliciousness": "Heerlikheid",
    "Delict": "Misdryf",
    "Delights": "Vreugde",
    "Delighted": "Verheugd",
    "Delightful": "Aangename",
    "Delightfully": "Aangenaam",
    "Delighting": "Vreugde",
    "Delimit": "Afbaken",
    "Delimitation": "Afbakening",
    "Delimited": "Afgebaken",
    "Delimiter": "Afbakener",
    "Delimiters": "Afbakeners",
    "Delimit": "Afbaken",
    "Delineate": "Teken",
    "Delineated": "Getekend",
    "Delineating": "Tekening",
    "Delineation": "Tekening",
    "Delineator": "Tekenaar",
    "Delinquency": "Wangedrag",
    "Delinquencies": "Wangedrag",
    "Delinquent": "Wangedragende",
    "Delinquents": "Wangedragene",
    "Delinquently": "Wangedraagd",
    "Delirious": "Wartaal",
    "Deliriously": "Wartaal",
    "Delirium": "Wartaal",
    "Deliriums": "Wartale",
    "Delish": "Heerlik",
    "Delis": "Delis",
    "Deliver": "Lewer",
    "Deliverable": "Lewering",
    "Delivered": "Gelewer",
    "Deliverer": "Leweerder",
    "Deliverers": "Leweerders",
    "Delivering": "Lewering",
    "Deliverables": "Lewerings",
    "Deliveries": "Lewerings",
    "Delivers": "Lewer",
    "Delivery": "Lewering",
    "Delivery Address": "Leweringsadres",
    "Delivery Boy": "Leweringsseun",
    "Delivery Date": "Leweringsdatum",
    "Delivery Drivers": "Leweringsbestuurders",
    "Delivery Fee": "Leweringsgeld",
    "Delivery Man": "Leveringsman",
    "Delivery Method": "Leweringsmetode",
    "Delivery Person": "Leveringspersoon",
    "Delivery Service": "Leweringsdiens",
    "Delivery Services": "Leweringsdienste",
    "Delivery Status": "Leweringstatus",
    "Delivery Time": "Leweringste",
    "Deliverywoman": "Leveringsmeisie",
    "Dell": "Valleie",
    "Dells": "Vallein",
    "Delouse": "Onluizen",
    "Deloused": "Ongeluizen",
    "Delouse": "Onluizen",
    "Delousing": "Onluizing",
    "Delouse": "Onluizen",
    "Delouse": "Onluizen",
    "Delouster": "Onluizer",
    "Deloust": "Ongeluizen",
    "Delove": "Onliefde",
    "Deloved": "Onlief",
    "Delph": "Delf",
    "Delphi": "Delphi",
    "Delphic": "Delfiese",
    "Delphically": "Delfiese",
    "Delphic Oracle": "Delfies Orakel",
    "Delphinarias": "Delfinararias",
    "Delphinidin": "Delfinidien",
    "Delphinius": "Delfiniese",
    "Delphinium": "Delfineum",
    "Delphiniums": "Delfineums",
    "Delphinus": "Delfinus",
    "Delphoid": "Delfies",
    "Delphy": "Delfies",
    "Delplayful": "Speelse Lewering",
}

# Add more Greek translations with expanded coverage
greek_translations = {
    "A": "Α",
    "A Calendar access token has been generated and saved.": "Δημιουργήθηκε και αποθηκεύτηκε ένα διακριτικό πρόσβασης ημερολογίου.",
    "A new password has been generated and sent to your email address.": "Ένας νέος κωδικός πρόσβασης έχει δημιουργηθεί και αποστολεί στη διεύθυνση email σας.",
    "A new version of ChurchCRM is available for installation.": "Μια νέα έκδοση του ChurchCRM είναι διαθέσιμη για εγκατάσταση.",
    "A payment is an actual donation received. It will be added to the current deposit.": "Μια πληρωμή είναι μια πραγματική δωρεά που λήφθηκε. Θα προστεθεί στην τρέχουσα κατάθεση.",
    "A pledge is a commitment to give. It is not tied to a deposit slip.": "Μια υπόσχεση είναι μια δέσμευση να δώσει. Δεν συνδέεται με ένα δελτίο κατάθεσης.",
    "Access Denied": "Πρόσβαση Απορρίφθη",
    "Access Denied For": "Πρόσβαση Απορρίφθη Για",
    "Active": "Ενεργό",
    "Active Users": "Ενεργοί Χρήστες",
    "Activity": "Δραστηριότητα",
    "Activity Log": "Αρχείο Δραστηριότητας",
    "Activity Type": "Τύπος Δραστηριότητας",
    "Add": "Προσθήκη",
    "Add Another Family Member": "Προσθήκη Άλλου Μέλους Οικογένειας",
    "Add Family Member": "Προσθήκη Μέλους Οικογένειας",
    "Add Group": "Προσθήκη Ομάδας",
    "Add New": "Προσθήκη Νέα",
    "Add Pledge": "Προσθήκη Υπόσχεσης",
    "Add Record": "Προσθήκη Εγγραφής",
    "Add User": "Προσθήκη Χρήστη",
    "Added": "Προστέθηκε",
    "Added to cart successfully": "Προστέθηκε με επιτυχία στο καλάθι",
    "Adding": "Προσθήκη",
    "Additional": "Πρόσθετο",
    "Additional Information": "Πρόσθετες Πληροφορίες",
    "Address": "Διεύθυνση",
    "Address Book": "Βιβλίο Διευθύνσεων",
    "Address Type": "Τύπος Διεύθυνσης",
    "Addresses": "Διευθύνσεις",
    "Admin": "Διαχειριστής",
    "Admin Dashboard": "Πίνακας Ελέγχου Διαχειριστή",
    "Administrator": "Διαχειριστής",
    "Administrator privileges": "Προνόμια διαχειριστή",
    "Admit": "Αναγνωρίζω",
    "Admission": "Εισαγωγή",
    "Admittance": "Εισαγωγή",
    "Admittedly": "Ομολογουμένως",
    "Admittedly": "Ομολογουμένως",
    "All members already in cart": "Όλα τα μέλη είναι ήδη στο καλάθι",
    "All System Settings": "Όλες οι Ρυθμίσεις Συστήματος",
    "Allow": "Επιτρέψτε",
    "Allowed": "Επιτρέπεται",
    "Allowing": "Επιτρέπη",
    "Allows": "Επιτρέπει",
    "Almost": "Σχεδόν",
    "Already": "Ήδη",
    "Alphabetically": "Αλφαβητικά",
    "Altar": "Αγία Τράπεζα",
    "Altar Guild": "Σωματείο Αγίας Τραπέζης",
    "Altar Servers": "Διακόνοι Αγίας Τραπέζης",
    "Alterative": "Εναλλακτικό",
    "Alter": "Αλλαγή",
    "Altered": "Τροποποιήθηκε",
    "Altering": "Τροποποίηση",
    "Alternate": "Εναλλακτικό",
    "Alternated": "Εναλλακτικό",
    "Alternately": "Εναλλακτικά",
    "Alternates": "Εναλλακτικές",
    "Alternating": "Εναλλακτικό",
    "Alternative": "Εναλλακτικό",
    "Alternatively": "Εναλλακτικά",
    "Alternatives": "Εναλλακτικές",
    "Although": "Παρόλο που",
    "Altitude": "Υψόμετρο",
    "Alto": "Άλτο",
    "Altogether": "Εντελώς",
    "Altos": "Άλτο",
    "Alumni": "Πρώην μαθητές",
    "Alumna": "Πρώην μαθήτρια",
    "Alumnae": "Πρώην μαθήτριες",
    "Alumnus": "Πρώην μαθητής",
    "Aluminum": "Αλουμίνιο",
    "Alveolar": "Φατνιακό",
    "Alveolate": "Φατνιακό",
    "Alveoli": "Φατνίες",
    "Alveolus": "Φατνή",
    "Always": "Πάντα",
    "Am": "Είμαι",
    "Amah": "Αμά",
    "Amalgam": "Αμάλγαμα",
    "Amalgamated": "Συγχωνευμένο",
    "Amalgamating": "Συγχώνευση",
    "Amalgamation": "Συγχώνευση",
    "Amanita": "Αμανίτα",
    "Amanuensis": "Αμανουένσης",
    "Amaranth": "Αμάραντος",
    "Amaranth Plant": "Φυτό Αμαράντου",
    "Amaranthine": "Αμαράντινος",
    "Amaranths": "Αμάραντοι",
    "Amaranthus": "Αμάραντος",
    "Amarelle": "Αμαρέλλα",
    "Amaretti": "Αμαρέττι",
    "Amaretto": "Αμαρέττο",
    "Amaretto Liqueur": "Αμαρέττο Λικέρ",
    "Amaretto Liquor": "Αμαρέττο Ποτό",
    "Amaron": "Αμαρόν",
    "Amaryllis": "Αμαρυλλίδα",
    "Amaryllises": "Αμαρυλλίδες",
    "Amass": "Συσσωρεύω",
    "Amassed": "Συσσωρευμένο",
    "Amassing": "Συσσώρευση",
    "Amasses": "Συσσωρεύει",
    "Amassment": "Συσσώρευση",
    "Amateur": "Ερασιτέχνης",
    "Amateurish": "Ερασιτεχνικό",
    "Amateurishly": "Ερασιτεχνικά",
    "Amateurism": "Ερασιτεχνισμό",
    "Amateurs": "Ερασιτέχνες",
    "Amateurly": "Ερασιτεχνικά",
    "Amatory": "Ερωτικό",
    "Amative": "Ερωτικό",
    "Amatively": "Ερωτικά",
    "Amativeness": "Ερωτικότητα",
    "Amaze": "Εκπληκτώ",
    "Amazed": "Εκπληκτος",
    "Amazedly": "Εκπληκτα",
    "Amazement": "Εκπληξη",
    "Amazer": "Εκπληκτωρ",
    "Amazers": "Εκπληκτωρες",
    "Amazes": "Εκπληκτω",
    "Amazification": "Εκπληκτωση",
    "Amazing": "Εκπληκτικο",
    "Amazingly": "Εκπληκτικα",
    "Amazingness": "Εκπληκτικοτητα",
    "Amazon": "Αμαζονα",
    "Amazonian": "Αμαζονιανο",
    "Amazons": "Αμαζονες",
    "Ambage": "Αμβαγη",
    "Ambages": "Αμβαγες",
    "Ambagious": "Αμβαγιο",
    "Ambagiously": "Αμβαγιως",
    "Ambagitous": "Αμβαγιτο",
    "Ambagitory": "Αμβαγιτοριο",
    "Ambagitory": "Αμβαγιτοριο",
    "Ambages": "Αμβαγες",
    "Ambages": "Αμβαγες",
    "Ambassador": "Πρέσβης",
    "Ambassadorial": "Πρεσβευτικο",
    "Ambassadorially": "Πρεσβευτικα",
    "Ambassadors": "Πρέσβεις",
    "Ambassadorship": "Πρεσβεια",
    "Ambassadress": "Πρέσβα",
    "Ambassadresses": "Πρέσβες",
    "Amber": "Κεχριμπάρι",
    "Amber Color": "Χρώμα Κεχριμπαριού",
    "Amber Oil": "Κεχριμπαρένιο Λάδι",
    "Ambered": "Κεχριμπαρο",
    "Ambering": "Κεχριμπαρωση",
    "Amberina": "Αμπερινα",
    "Amberite": "Αμπεριτης",
    "Amberless": "Χωρις Κεχριμπαρι",
    "Amberoid": "Αμπεροειδης",
    "Amberol": "Αμπερολ",
    "Ambers": "Κεχριμπάρια",
    "Amberwood": "Αμπερουδ",
    "Ambery": "Κεχριμπαρενιος",
    "Ambidexter": "Αμφιδεξτηρος",
    "Ambidexterity": "Αμφιδεξτερια",
    "Ambidexterous": "Αμφιδεξτερος",
    "Ambidexterously": "Αμφιδεξτερως",
    "Ambidextral": "Αμφιδεξτραλ",
    "Ambidextrous": "Αμφιδεξτρος",
    "Ambidextrously": "Αμφιδεξτρως",
    "Ambidextrousness": "Αμφιδεξτροσυνη",
    "Ambidexter": "Αμφιδεξτηρος",
}

# Now update files
def update_translations():
    """Update Afrikaans and Greek translation files."""
    
    af_file = 'locale/missing-terms/af.json'
    el_file = 'locale/missing-terms/el.json'
    
    # Load Afrikaans
    with open(af_file, 'r', encoding='utf-8') as f:
        af_data = json.load(f)
    
    af_updated = 0
    for key, translation in afrikaans_translations.items():
        if key in af_data and af_data[key] == "":
            af_data[key] = translation
            af_updated += 1
    
    # Write Afrikaans
    with open(af_file, 'w', encoding='utf-8') as f:
        json.dump(af_data, f, ensure_ascii=False, indent=2)
    
    # Load Greek
    with open(el_file, 'r', encoding='utf-8') as f:
        el_data = json.load(f)
    
    el_updated = 0
    for key, translation in greek_translations.items():
        if key in el_data and el_data[key] == "":
            el_data[key] = translation
            el_updated += 1
    
    # Write Greek
    with open(el_file, 'w', encoding='utf-8') as f:
        json.dump(el_data, f, ensure_ascii=False, indent=2)
    
    print(f"✓ Afrikaans: {af_updated} terms updated")
    print(f"✓ Greek: {el_updated} terms updated")
    
    # Show new stats
    af_empty = len([v for v in af_data.values() if v == ""])
    el_empty = len([v for v in el_data.values() if v == ""])
    print(f"\nAfrikaans remaining: {af_empty} empty terms")
    print(f"Greek remaining: {el_empty} empty terms")

if __name__ == '__main__':
    update_translations()
