#!/usr/bin/env python3
"""Comprehensive terminology batch - all core categories."""

import json

# Comprehensive Afrikaans terminology
af_batch = {
    # Forms and Input
    "Form": "Vorm",
    "Forms": "Vorme",
    "Field": "Veld",
    "Fields": "Velde",
    "Input": "Invoer",
    "Inputs": "Invoere",
    "Submit": "Dien In",
    "Submitted": "Ingediend",
    "Submitting": "Indienings",
    "Submission": "Indiening",
    "Submissions": "Indienings",
    "Cancel": "Kanselleer",
    "Cancelled": "Gekanselleer",
    "Cancelling": "Kansellering",
    "Cancellation": "Kansellering",
    "Reset": "Stel Terug",
    "Reset Form": "Stel Vorm Terug",
    "Clear": "Verwyder",
    "Cleared": "Verwyderd",
    "Clearing": "Verwydring",
    "Save": "Stoor",
    "Saved": "Gestoor",
    "Saving": "Stoorwerk",
    "Saving Changes": "Veranderings Stoor",
    "Confirmation": "Bevestiging",
    "Confirmations": "Bevestigings",
    "Confirm": "Bevestig",
    "Confirmed": "Bevestig",
    "Confirming": "Bevestiging",
    "Confirmation Required": "Bevestiging Vereis",
    "Are you sure": "Is jy seker",
    "Are you sure?": "Is jy seker?",
    
    # Navigation
    "Back": "Terug",
    "Next": "Volgende",
    "Previous": "Vorige",
    "First": "Eerste",
    "Last": "Laaste",
    "Go": "Gaan",
    "Close": "Sluit",
    "Open": "Oopmaak",
    "Opened": "Oopgemaak",
    "Opening": "Oopmaking",
    "Menu": "Spyskaart",
    "Menus": "Spyskaarte",
    "Link": "Skakel",
    "Links": "Skakels",
    "Navigate": "Navigeer",
    "Navigation": "Navigasie",
    "Navigating": "Navigering",
    "Home": "Tuis",
    "Settings": "Instellings",
    "Options": "Opsies",
    "Configuration": "Opstellung",
    "Preferences": "Voorkeure",
    "Dashboard": "Paneelbord",
    "Dashboards": "Paneelborde",
    
    # Status and States
    "Active": "Aktief",
    "Inactive": "Onaktief",
    "Enabled": "Geaktiveer",
    "Disabled": "Gedeaktiveer",
    "Enable": "Aktiveer",
    "Disable": "Deaktiveer",
    "Status": "Status",
    "Statuses": "Statuse",
    "State": "Staat",
    "States": "State",
    "Success": "Sukses",
    "Successful": "Suksesvol",
    "Successfully": "Suksesvol",
    "Warning": "Waarskuwing",
    "Warnings": "Waarskuwings",
    "Alert": "Waarskuwing",
    "Alerts": "Waarskuwings",
    "Info": "Inligting",
    "Information": "Inligting",
    "Informations": "Inligtings",
    "Details": "Besonderhede",
    
    # Data Operations
    "Create": "Skep",
    "Created": "Geskep",
    "Creating": "Skepping",
    "Creation": "Skepping",
    "Update": "Opdateer",
    "Updated": "Opgedateer",
    "Updating": "Opdatering",
    "Update": "Opdatering",
    "Delete": "Wis",
    "Deleted": "Gewis",
    "Deleting": "Wisweg",
    "Deletion": "Wisking",
    "Remove": "Verwyder",
    "Removed": "Verwyderd",
    "Removing": "Verwydring",
    "Removal": "Verwydring",
    "Import": "Invoer",
    "Imported": "Ingevoerd",
    "Importing": "Invoering",
    "Importation": "Invoering",
    "Export": "Uitvoer",
    "Exported": "Uitgevoerd",
    "Exporting": "Uitvoering",
    "Exportation": "Uitvoering",
    "Copy": "Kopie",
    "Copied": "Gekopieer",
    "Copying": "Kopiering",
    "Paste": "Plak",
    "Pasted": "Geplak",
    "Pasting": "Plaking",
    "Cut": "Sny",
    "Cutting": "Snying",
    
    # Sorting and Filtering
    "Sort": "Sorteer",
    "Sorted": "Gesorteer",
    "Sorting": "Sortering",
    "Filter": "Filter",
    "Filtered": "Gefilterde",
    "Filtering": "Filtrering",
    "Filters": "Filters",
    "Search": "Soek",
    "Searched": "Gesoek",
    "Searching": "Soekwerk",
    "Searchable": "Soekbaar",
    "Results": "Resultate",
    "No Results": "Geen Resultate",
    "No Records": "Geen Rekords",
    "All": "Alles",
    "Any": "Enige",
    "None": "Niks",
    
    # Database
    "Database": "Databasis",
    "Databases": "Databases",
    "Record": "Rekord",
    "Records": "Rekordstel",
    "Table": "Tabel",
    "Tables": "Tabelle",
    "Column": "Kolom",
    "Columns": "Kolomeie",
    "Row": "Ry",
    "Rows": "Rye",
    "Data": "Gegewens",
    "Backup": "Rugsteun",
    "Backups": "Rugsteune",
    "Restore": "Herstel",
    "Restored": "Hersteld",
    "Restoring": "Herstelwerk",
    "Recovery": "Herstelwerk",
    
    # Page Elements
    "Page": "Bladsy",
    "Pages": "Bladsye",
    "Content": "Inhoud",
    "Contents": "Inhoud",
    "Header": "Kop",
    "Headers": "Koppe",
    "Footer": "Voetnotas",
    "Footers": "Voetnote",
    "Section": "Afdeling",
    "Sections": "Afdelings",
    "Panel": "Paneel",
    "Panels": "Panele",
    "Card": "Kaart",
    "Cards": "Kaarte",
    "Container": "Houer",
    "Containers": "Houers",
    "Box": "Doos",
    "Boxes": "Dosise",
    "Button": "Knoppie",
    "Buttons": "Knoppies",
    "Tab": "Oortjie",
    "Tabs": "Oortjies",
    "Modal": "Modal",
    "Modals": "Modale",
    "Dialog": "Dialoog",
    "Dialogs": "Dialoge",
    "Popup": "Popop",
    "Popups": "Popope",
    
    # Messages
    "Message": "Boodskap",
    "Messages": "Boodskappe",
    "Notification": "Kennisgeving",
    "Notifications": "Kennisgewings",
    "Notify": "Kennisgee",
    "Notified": "Kennisgegee",
    "Notifying": "Kennisgeewing",
    "Email": "E-pos",
    "Emails": "E-poste",
    "Send": "Stuur",
    "Sent": "Gestuur",
    "Sending": "Stuurwerk",
    "Reply": "Antwoord",
    "Replies": "Antwoorde",
    "Replied": "Beantwoord",
    "Replying": "Antwoordwerk",
    
    # Users and Permissions
    "User": "Gebruiker",
    "Users": "Gebruikers",
    "Username": "Gebruikernaam",
    "Password": "Wagwoord",
    "Passwords": "Wagwoorde",
    "Login": "Aanteken",
    "Logout": "Afmelding",
    "Account": "Rekening",
    "Accounts": "Rekeninge",
    "Profile": "Profiel",
    "Profiles": "Profiele",
    "Permission": "Toestemming",
    "Permissions": "Toestemmings",
    "Role": "Rol",
    "Roles": "Rolle",
    "Admin": "Admin",
    "Administrator": "Administrateur",
    "Administrators": "Administrateurs",
    "Access": "Toegang",
    "Access Denied": "Toegang Geweier",
    "Privilege": "Voorreg",
    "Privileges": "Voorregte",
}

# Comprehensive Greek terminology
el_batch = {
    # Forms and Input
    "Form": "Φόρμα",
    "Forms": "Φόρμες",
    "Field": "Πεδίο",
    "Fields": "Πεδία",
    "Input": "Είσοδος",
    "Inputs": "Εισόδους",
    "Submit": "Υποβολή",
    "Submitted": "Υποβλήθηκε",
    "Submitting": "Υποβολή",
    "Submission": "Υποβολή",
    "Submissions": "Υποβολές",
    "Cancel": "Ακύρωση",
    "Cancelled": "Ακυρώθηκε",
    "Cancelling": "Ακύρωση",
    "Cancellation": "Ακύρωση",
    "Reset": "Επαναφορά",
    "Reset Form": "Επαναφορά Φόρμας",
    "Clear": "Καθαρισμός",
    "Cleared": "Διαγράφηκε",
    "Clearing": "Καθαρισμός",
    "Save": "Αποθήκευση",
    "Saved": "Αποθηκευμένο",
    "Saving": "Αποθήκευση",
    "Saving Changes": "Αποθήκευση Αλλαγών",
    "Confirmation": "Επιβεβαίωση",
    "Confirmations": "Επιβεβαιώσεις",
    "Confirm": "Επιβεβαιώνω",
    "Confirmed": "Επιβεβαιωμένο",
    "Confirming": "Επιβεβαίωση",
    "Confirmation Required": "Απαιτείται Επιβεβαίωση",
    "Are you sure": "Είστε σίγουρος",
    "Are you sure?": "Είστε σίγουρος;",
    
    # Navigation
    "Back": "Πίσω",
    "Next": "Επόμενο",
    "Previous": "Προηγούμενο",
    "First": "Πρώτο",
    "Last": "Τελευταίο",
    "Go": "Πήγαινε",
    "Close": "Κλείνω",
    "Open": "Ανοίγω",
    "Opened": "Ανοικτό",
    "Opening": "Άνοιγμα",
    "Menu": "Μενού",
    "Menus": "Μενού",
    "Link": "Σύνδεσμος",
    "Links": "Σύνδεσμοι",
    "Navigate": "Πλοήγηση",
    "Navigation": "Πλοήγηση",
    "Navigating": "Πλοήγηση",
    "Home": "Αρχική",
    "Settings": "Ρυθμίσεις",
    "Options": "Επιλογές",
    "Configuration": "Διαμόρφωση",
    "Preferences": "Προτιμήσεις",
    "Dashboard": "Ταμπλό",
    "Dashboards": "Ταμπλό",
    
    # Status and States
    "Active": "Ενεργό",
    "Inactive": "Ανενεργό",
    "Enabled": "Ενεργοποιημένο",
    "Disabled": "Απενεργοποιημένο",
    "Enable": "Ενεργοποιώ",
    "Disable": "Απενεργοποιώ",
    "Status": "Κατάσταση",
    "Statuses": "Καταστάσεις",
    "State": "Κατάσταση",
    "States": "Καταστάσεις",
    "Success": "Επιτυχία",
    "Successful": "Επιτυχημένο",
    "Successfully": "Με επιτυχία",
    "Warning": "Προειδοποίηση",
    "Warnings": "Προειδοποιήσεις",
    "Alert": "Ειδοποίηση",
    "Alerts": "Ειδοποιήσεις",
    "Info": "Πληροφορία",
    "Information": "Πληροφορία",
    "Informations": "Πληροφορίες",
    "Details": "Λεπτομέρειες",
    
    # Data Operations
    "Create": "Δημιουργία",
    "Created": "Δημιουργήθηκε",
    "Creating": "Δημιουργία",
    "Creation": "Δημιουργία",
    "Update": "Ενημέρωση",
    "Updated": "Ενημερώθηκε",
    "Updating": "Ενημέρωση",
    "Delete": "Διαγραφή",
    "Deleted": "Διαγράφηκε",
    "Deleting": "Διαγραφή",
    "Deletion": "Διαγραφή",
    "Remove": "Αφαίρεση",
    "Removed": "Αφαιρέθηκε",
    "Removing": "Αφαίρεση",
    "Removal": "Αφαίρεση",
    "Import": "Εισαγωγή",
    "Imported": "Εισήχθη",
    "Importing": "Εισαγωγή",
    "Importation": "Εισαγωγή",
    "Export": "Εξαγωγή",
    "Exported": "Εξήχθη",
    "Exporting": "Εξαγωγή",
    "Exportation": "Εξαγωγή",
    "Copy": "Αντιγραφή",
    "Copied": "Αντιγράφηκε",
    "Copying": "Αντιγραφή",
    "Paste": "Επικόλληση",
    "Pasted": "Επικολλήθηκε",
    "Pasting": "Επικόλληση",
    "Cut": "Αποκοπή",
    "Cutting": "Αποκοπή",
    
    # Sorting and Filtering
    "Sort": "Ταξινόμηση",
    "Sorted": "Ταξινομημένο",
    "Sorting": "Ταξινόμηση",
    "Filter": "Φίλτρο",
    "Filtered": "Φιλτραρισμένο",
    "Filtering": "Φιλτράρισμα",
    "Filters": "Φίλτρα",
    "Search": "Αναζήτηση",
    "Searched": "Αναζητήθηκε",
    "Searching": "Αναζήτηση",
    "Searchable": "Αναζητήσιμος",
    "Results": "Αποτελέσματα",
    "No Results": "Κανένα αποτέλεσμα",
    "No Records": "Κανένα αρχείο",
    "All": "Όλα",
    "Any": "Κάποιος",
    "None": "Κανένα",
    
    # Database
    "Database": "Βάση δεδομένων",
    "Databases": "Βάσεις δεδομένων",
    "Record": "Αρχείο",
    "Records": "Αρχεία",
    "Table": "Πίνακας",
    "Tables": "Πίνακες",
    "Column": "Στήλη",
    "Columns": "Στήλες",
    "Row": "Σειρά",
    "Rows": "Σειρές",
    "Data": "Δεδομένα",
    "Backup": "Αντίγραφο ασφαλείας",
    "Backups": "Αντίγραφα ασφαλείας",
    "Restore": "Επαναφορά",
    "Restored": "Επαναφέρθηκε",
    "Restoring": "Επαναφορά",
    "Recovery": "Ανάκτηση",
    
    # Page Elements
    "Page": "Σελίδα",
    "Pages": "Σελίδες",
    "Content": "Περιεχόμενο",
    "Contents": "Περιεχόμενα",
    "Header": "Κεφαλίδα",
    "Headers": "Κεφαλίδες",
    "Footer": "Υποσέλιδο",
    "Footers": "Υποσέλιδα",
    "Section": "Ενότητα",
    "Sections": "Ενότητες",
    "Panel": "Πίνακας",
    "Panels": "Πίνακες",
    "Card": "Κάρτα",
    "Cards": "Κάρτες",
    "Container": "Κοντέινερ",
    "Containers": "Κοντέινερ",
    "Box": "Κουτί",
    "Boxes": "Κουτιά",
    "Button": "Κουμπί",
    "Buttons": "Κουμπιά",
    "Tab": "ΕTabulation",
    "Tabs": "ΕTabulation",
    "Modal": "Τροπικό",
    "Modals": "Τροπικά",
    "Dialog": "Διάλογος",
    "Dialogs": "Διάλογοι",
    "Popup": "Αναδυόμενο",
    "Popups": "Αναδυόμενα",
    
    # Messages
    "Message": "Μήνυμα",
    "Messages": "Μηνύματα",
    "Notification": "Ειδοποίηση",
    "Notifications": "Ειδοποιήσεις",
    "Notify": "Ειδοποίηση",
    "Notified": "Ειδοποιήθηκε",
    "Notifying": "Ειδοποίηση",
    "Email": "Ηλ. ταχυδρομείο",
    "Emails": "Ηλ. ταχυδρομεία",
    "Send": "Αποστολή",
    "Sent": "Αποστάλθηκε",
    "Sending": "Αποστολή",
    "Reply": "Απάντηση",
    "Replies": "Απαντήσεις",
    "Replied": "Απαντήθηκε",
    "Replying": "Απάντηση",
    
    # Users and Permissions
    "User": "Χρήστης",
    "Users": "Χρήστες",
    "Username": "Όνομα χρήστη",
    "Password": "Κωδικός πρόσβασης",
    "Passwords": "Κωδικοί πρόσβασης",
    "Login": "Σύνδεση",
    "Logout": "Αποσύνδεση",
    "Account": "Λογαριασμός",
    "Accounts": "Λογαριασμοί",
    "Profile": "Προφίλ",
    "Profiles": "Προφίλ",
    "Permission": "Άδεια",
    "Permissions": "Άδειες",
    "Role": "Ρόλος",
    "Roles": "Ρόλοι",
    "Admin": "Διαχειριστής",
    "Administrator": "Διαχειριστής",
    "Administrators": "Διαχειριστές",
    "Access": "Πρόσβαση",
    "Access Denied": "Άρνηση πρόσβασης",
    "Privilege": "Προνόμιο",
    "Privileges": "Προνόμια",
}

# Apply translations
af_file = 'locale/missing-terms/af.json'
el_file = 'locale/missing-terms/el.json'

with open(af_file, 'r', encoding='utf-8') as f:
    af_data = json.load(f)

af_updated = 0
for key, translation in af_batch.items():
    if key in af_data and af_data[key] == "":
        af_data[key] = translation
        af_updated += 1

with open(af_file, 'w', encoding='utf-8') as f:
    json.dump(af_data, f, ensure_ascii=False, indent=2)

with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

el_updated = 0
for key, translation in el_batch.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = translation
        el_updated += 1

with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

# Stats
af_empty = len([v for v in af_data.values() if v == ""])
el_empty = len([v for v in el_data.values() if v == ""])
af_total = len(af_data)
el_total = len(el_data)
af_done = af_total - af_empty
el_done = el_total - el_empty

print(f"\n✓ Afrikaans: {af_updated} terms → {af_done}/{af_total} ({100*af_done/af_total:.1f}%)")
print(f"✓ Greek: {el_updated} terms → {el_done}/{el_total} ({100*el_done/el_total:.1f}%)")
print(f"\nRemaining: AF {af_empty}, EL {el_empty}")
