import json

t = {
  "FY %s": "FY %s",
  "N/A": "",
  "- **Dashboard**: View all your MailChimp lists with subscriber statistics\n- **List Maintenance**: Identify people in MailChimp but not in CRM, and vice versa\n- **Contact Integration**: View MailChimp subscription status on Person and Family pages\n- **Automatic Sync**: Hooks into person/family updates to keep MailChimp in sync": "- **Přehled**: Zobrazte všechny své MailChimp seznamy se statistikami odběratelů\n- **Správa seznamů**: Identifikujte osoby v MailChimp, ale ne v CRM, a naopak\n- **Integrace kontaktů**: Zobrazte stav odběru MailChimp na stránkách Osoba a Rodina\n- **Automatická synchronizace**: Propojuje aktualizace osob/rodin pro udržování MailChimp v synchronizaci",
  "1. Create a Vonage account at https://dashboard.nexmo.com/sign-up (new accounts include free trial credit)\n2. Find your API Key and API Secret on the Vonage Dashboard homepage\n3. Go to Numbers > Buy Numbers and purchase a number with SMS capability\n4. Note the number in E.164 format (e.g., +14155551234)\n5. In ChurchCRM, enable the Vonage SMS plugin and enter your credentials": "1. Vytvořte si účet Vonage na https://dashboard.nexmo.com/sign-up (nové účty zahrnují bezplatný zkušební kredit)\n2. Na hlavní stránce Vonage Dashboard najděte svůj API klíč a tajný klíč API\n3. Přejděte na Čísla > Koupit čísla a zakupte číslo s funkcí SMS\n4. Poznamenejte si číslo ve formátu E.164 (např. +14155551234)\n5. V ChurchCRM povolte plugin Vonage SMS a zadejte své přihlašovací údaje",
  "1. Go to Google Analytics (analytics.google.com)\n2. Create a property or select an existing one\n3. Go to Admin → Data Streams → Web\n4. Copy the Measurement ID (starts with G-)": "1. Přejděte na Google Analytics (analytics.google.com)\n2. Vytvořte vlastnost nebo vyberte existující\n3. Přejděte na Správce → Datové toky → Web\n4. Zkopírujte ID měření (začíná G-)",
  "1. Install OpenLP 3.0 or later on your presentation computer\n2. Enable the Remote plugin in OpenLP (Settings → Configure OpenLP → Plugins)\n3. Enable the Alerts plugin in OpenLP for alert display support\n4. Note the IP address of the OpenLP computer\n5. Enter the server URL in the format: http://IP_ADDRESS:4316\n6. If you've configured authentication in OpenLP, enter the username and password": "1. Nainstalujte OpenLP 3.0 nebo novější na svůj prezentační počítač\n2. Povolte vzdálený plugin v OpenLP (Nastavení → Konfigurovat OpenLP → Pluginy)\n3. Povolte plugin Upozornění v OpenLP pro podporu zobrazení upozornění\n4. Poznamenejte si IP adresu počítače s OpenLP\n5. Zadejte URL serveru ve formátu: http://IP_ADRESA:4316\n6. Pokud jste nakonfigurovali autentizaci v OpenLP, zadejte uživatelské jméno a heslo",
  "Access the MailChimp Dashboard from the Email menu. The dashboard shows:\n\n- Member count for each list\n- Campaign statistics\n- Unsubscribe counts\n- List maintenance tools": "Přistupte k přehledu MailChimp z menu E-mail. Přehled zobrazuje:\n\n- Počet členů pro každý seznam\n- Statistiky kampaní\n- Počty odhlášení\n- Nástroje správy seznamů",
  "Adding Links": "Přidávání odkazů",
  "All configured links are shown in a table. You can:\n- View the link name and URL\n- Click the URL to test it opens correctly\n- Delete links you no longer need\n\nLinks appear in the order they were added in the navigation menu.": "Všechny nakonfigurované odkazy jsou zobrazeny v tabulce. Můžete:\n- Zobrazit název odkazu a URL\n- Kliknout na URL pro ověření, zda se správně otevírá\n- Smazat nepotřebné odkazy\n\nOdkazy se zobrazují v navigačním menu v pořadí, v jakém byly přidány.",
  "Allow Pre-release Upgrades": "Povolit předběžná vydání",
  "Allow recording of non-tax-deductible payments in the finance module": "Povolit zaznamenávání daňově neodečitatelných plateb ve finančním modulu",
  "Allow scanned check images to be attached to deposit records": "Povolit připojování naskenovaných obrázků šeků k záznamům vkladů",
  "Allow system upgrades to releases marked as 'pre release' on GitHub": "Povolit aktualizace systému na vydání označená jako ‚předběžné vydání' na GitHub",
  "Allow unauthenticated access to calendar events via public HTML, ICS, and JSON URLs. Required for sharing calendars with external apps.": "Umožnit neověřený přístup ke kalendářovým událostem prostřednictvím veřejných URL adres HTML, ICS a JSON. Nutné pro sdílení kalendářů s externími aplikacemi.",
  "Allow visitors to create their own family record via the self-registration page": "Umožnit návštěvníkům vytvořit svůj vlastní rodinný záznam prostřednictvím stránky pro vlastní registraci",
  "Allow visitors to self-register as new families.": "Umožnit návštěvníkům samostatně se registrovat jako nové rodiny.",
  "Any WebDAV-compatible service works with this plugin:\n\n- Nextcloud (recommended)\n- ownCloud\n- Synology NAS\n- QNAP NAS\n- Box.com (with WebDAV)\n- Apache mod_dav\n- nginx with WebDAV module\n\nNote: Some services require app-specific passwords for WebDAV access.": "S tímto pluginem funguje jakákoliv WebDAV-kompatibilní služba:\n\n- Nextcloud (doporučeno)\n- ownCloud\n- Synology NAS\n- QNAP NAS\n- Box.com (s WebDAV)\n- Apache mod_dav\n- nginx s modulem WebDAV\n\nPoznámka: Některé služby vyžadují pro přístup WebDAV specifická hesla aplikací.",
  "Authentication": "Autentizace",
  "Authentication is required for API v2 if you've enabled it in OpenLP's Remote plugin settings. The plugin uses HTTP Basic Authentication. Most local network setups don't require authentication, but it's recommended for security.": "Autentizace je vyžadována pro API v2, pokud jste ji povolili v nastavení vzdáleného pluginu OpenLP. Plugin používá HTTP Basic Authentication. Většina lokálních síťových nastavení nevyžaduje autentizaci, ale z bezpečnostních důvodů se doporučuje.",
  "Auto-Backup": "Automatická záloha",
  "BCC All Mail To": "Skrytá kopie veškeré pošty na",
  "Before relying on external backups, test your connection:\n1. Go to Plugins > External Backup\n2. Click 'Test WebDAV Connection'\n3. Verify you see a success message\n\nCommon issues:\n- 401/403 errors: Check username and password\n- Connection timeout: Verify the endpoint URL is correct\n- Certificate errors: Ensure the WebDAV server has a valid SSL certificate": "Před spoléháním se na externí zálohy otestujte připojení:\n1. Přejděte na Pluginy > Externí záloha\n2. Klikněte na ‚Testovat připojení WebDAV'\n3. Ověřte, že se zobrazí zpráva o úspěchu\n\nČasté problémy:\n- Chyby 401/403: Zkontrolujte uživatelské jméno a heslo\n- Vypršení časového limitu připojení: Ověřte správnost URL adresy koncového bodu\n- Chyby certifikátu: Ujistěte se, že WebDAV server má platný SSL certifikát",
  "Choose what appears when no Gravatar exists:\n• Mystery Person - Gray silhouette outline\n• Identicon - Geometric pattern based on email\n• MonsterID - Unique generated monster face\n• Wavatar - Abstract generated face\n• Retro - 8-bit arcade-style pixel art\n• RoboHash - Unique generated robot\n• Blank - Transparent (falls back to initials)": "Vyberte, co se zobrazí, když Gravatar neexistuje:\n• Mystery Person – šedý siluetový obrys\n• Identicon – geometrický vzor na základě e-mailu\n• MonsterID – jedinečná generovaná tvář monstra\n• Wavatar – abstraktní generovaná tvář\n• Retro – pixel art ve stylu 8-bitové arkády\n• RoboHash – jedinečný generovaný robot\n• Prázdný – průhledný (přejde na iniciály)",
  "Comma-separated query IDs that require finance permissions to view": "ID dotazů oddělených čárkami, které vyžadují finanční oprávnění k zobrazení",
  "Common uses for custom links:\n- Church website\n- Online giving portal\n- Volunteer signup forms\n- Denomination resources\n- Partner organization sites\n- Cloud storage folders\n- Event registration pages": "Běžné použití vlastních odkazů:\n- Webové stránky sboru\n- Online portál darování\n- Přihlašovací formuláře pro dobrovolníky\n- Zdroje denominace\n- Stránky partnerských organizací\n- Složky cloudového úložiště\n- Stránky registrace na akce",
  "Configuration": "Konfigurace",
  "Continent": "Kontinent",
  "Costs": "Náklady",
  "Credit Card People": "Osoby s kreditní kartou",
  "Current Usage": "Aktuální využití",
  "Default Image Styles": "Výchozí styly obrázků",
  "Default Map View": "Výchozí zobrazení mapy",
  "Deposit ticket type": "Typ vkladového lístku",
  "Do Not Email Property": "Vlastnost Neposílat e-mail",
  "Do Not SMS Property": "Vlastnost Neposílat SMS",
  "Download OpenLP": "Stáhnout OpenLP",
  "E.164 Phone Number Format": "Formát telefonního čísla E.164",
  "Enable Email": "Povolit e-mail",
  "Enable Events Menu": "Povolit menu Události",
  "Enable External Calendar API": "Povolit externí API kalendáře",
  "Enable email sending from ChurchCRM. Required for password reset, notifications, and email links.": "Umožnit odesílání e-mailů z ChurchCRM. Nutné pro obnovení hesla, oznámení a e-mailové odkazy.",
  "Enable if your SMTP server requires a username and password": "Povolte, pokud váš SMTP server vyžaduje uživatelské jméno a heslo",
  "Enable or disable the Sunday School module and sidebar menu.": "Povolit nebo zakázat modul Nedělní škola a boční menu.",
  "Enable the use of numbered donation envelopes for tracking contributions": "Umožnit použití číslovaných darových obálek pro sledování příspěvků",
  "Enable use of donation envelopes": "Umožnit použití darových obálek",
  "Enable use of scanned checks": "Umožnit použití naskenovaných šeků",
  "Family Pledge by Fiscal Year": "Finanční závazek rodiny podle fiskálního roku",
  "Features": "Funkce",
  "Finance permission query IDs": "ID dotazů pro finanční oprávnění",
  "Find Registered students": "Najít registrované žáky",
  "Find family": "Najít rodinu",
  "Finding Your Server URL": "Nalezení URL adresy serveru",
  "Fiscal Year.": "Fiskální rok.",
  "For security:\n- Only administrators can add or remove links\n- The 'Manage Links' option only appears for administrators\n- Links must use http:// or https:// protocols\n- HTML tags are not allowed in names or URLs\n- All input is validated and sanitized": "Z bezpečnostních důvodů:\n- Pouze správci mohou přidávat nebo odebírat odkazy\n- Možnost ‚Spravovat odkazy' se zobrazuje pouze správcům\n- Odkazy musí používat protokoly http:// nebo https://\n- HTML tagy nejsou povoleny v názvech ani URL\n- Veškerý vstup je validován a ošetřen",
  "GA4 Setup Guide": "Průvodce nastavením GA4",
  "Getting Started": "Začínáme",
  "Getting Your GA4 Measurement ID": "Získání ID měření GA4",
  "Google Analytics 4 (GA4) tracks how users interact with ChurchCRM, providing insights into page views, user engagement, and feature usage.": "Google Analytics 4 (GA4) sleduje, jak uživatelé interagují s ChurchCRM, a poskytuje přehledy o zobrazení stránek, zapojení uživatelů a využití funkcí.",
  "Google Analytics Help": "Nápověda Google Analytics",
  "Google Analytics collects anonymized usage data. No personal information from ChurchCRM records is sent to Google. Consider adding a privacy notice to your church's data policy.": "Google Analytics shromažďuje anonymizovaná data o používání. Žádné osobní informace ze záznamů ChurchCRM nejsou odesílány společnosti Google. Zvažte přidání oznámení o ochraně soukromí do zásad nakládání s daty vašeho sboru.",
  "Gravatar (Globally Recognized Avatar) displays profile photos from gravatar.com for members who don't have uploaded photos in ChurchCRM.": "Gravatar (Globally Recognized Avatar) zobrazuje profilové fotografie z gravatar.com pro členy, kteří nemají v ChurchCRM nahrané fotografie.",
  "Gravatar Image Options": "Možnosti obrázků Gravatar",
  "Gravatar Website": "Web Gravatar",
  "Gravatar works by converting email addresses into a hash (MD5). The actual email address is never sent to Gravatar's servers - only the hash is used to look up the image.": "Gravatar funguje tak, že převádí e-mailové adresy na hash (MD5). Skutečná e-mailová adresa není nikdy odeslána na servery Gravataru – k vyhledání obrázku se používá pouze hash.",
  "Group of registered students": "Skupina registrovaných žáků",
  "Hide Latitude/Longitude": "Skrýt zeměpisnou šířku/délku",
  "Hide Person Address": "Skrýt adresu osoby",
  "How it works": "Jak to funguje",
  "How many checks to print per deposit slip page": "Počet šeků k tisku na stránku vkladového lístku",
  "If SMS messages aren't being sent:\n1. Verify API Key and Secret are correct (no extra spaces)\n2. Check that the From Number is a valid Vonage number you own\n3. Ensure recipient phone numbers include country code\n4. Check your Vonage account balance\n5. Review the Vonage Dashboard > SMS > Logs for delivery status": "Pokud se SMS zprávy neodesílají:\n1. Ověřte, že API klíč a tajný klíč jsou správné (bez nadbytečných mezer)\n2. Zkontrolujte, že číslo odesílatele je platné číslo Vonage, které vlastníte\n3. Ujistěte se, že telefonní čísla příjemců obsahují kód země\n4. Zkontrolujte zůstatek svého účtu Vonage\n5. Zkontrolujte stav doručení v Vonage Dashboard > SMS > Protokoly",
  "If alerts aren't appearing:\n1. Verify OpenLP is running and the Remote plugin is active\n2. Ensure the Alerts plugin is enabled in OpenLP\n3. Check that the server URL is correct (try accessing it in a browser)\n4. Verify firewall settings allow connections on port 4316\n5. If using authentication, verify credentials are correct": "Pokud se upozornění nezobrazují:\n1. Ověřte, že OpenLP běží a vzdálený plugin je aktivní\n2. Ujistěte se, že plugin Upozornění je v OpenLP povolen\n3. Zkontrolujte, že URL serveru je správná (zkuste ji otevřít v prohlížeči)\n4. Ověřte, že nastavení firewallu povoluje připojení na portu 4316\n5. Pokud používáte autentizaci, ověřte správnost přihlašovacích údajů",
  "If messages are sent but not received:\n1. Check Vonage Dashboard > SMS > Logs for delivery status\n2. Verify the recipient number is correct and can receive SMS\n3. Some carriers may block messages from unknown numbers\n4. Check if the destination country has SMS restrictions": "Pokud jsou zprávy odeslány, ale nedoručeny:\n1. Zkontrolujte stav doručení v Vonage Dashboard > SMS > Protokoly\n2. Ověřte, že číslo příjemce je správné a může přijímat SMS\n3. Někteří operátoři mohou blokovat zprávy z neznámých čísel\n4. Zkontrolujte, zda cílová země nemá omezení pro SMS",
  "If you receive invalid sender ID errors:\n1. Use a phone number you've purchased from Vonage\n2. Format the number in E.164 format (+14155551234)\n3. Note: Alphanumeric sender IDs may be restricted in some countries": "Pokud dostanete chyby neplatného ID odesílatele:\n1. Použijte telefonní číslo zakoupené od Vonage\n2. Formátujte číslo ve formátu E.164 (+14155551234)\n3. Poznámka: Alfanumerická ID odesílatele mohou být v některých zemích omezena",
  "Important security notes:\n\n1. Always use HTTPS endpoints to encrypt backups in transit\n2. Use app-specific passwords when available (Nextcloud, ownCloud)\n3. Store backups in a folder with restricted access\n4. Periodically download and verify your backups are valid\n5. Consider encrypting sensitive backups with external tools before uploading": "Důležité bezpečnostní poznámky:\n\n1. Vždy používejte HTTPS koncové body pro šifrování záloh při přenosu\n2. Pokud jsou k dispozici, používejte hesla specifická pro aplikaci (Nextcloud, ownCloud)\n3. Ukládejte zálohy do složky s omezeným přístupem\n4. Pravidelně stahujte a ověřujte platnost záloh\n5. Zvažte šifrování citlivých záloh externími nástroji před nahráním",
  "Initial zoom level when opening the map": "Výchozí úroveň přiblížení při otevření mapy",
  "Learn more": "Zjistit více",
  "Log Settings": "Nastavení protokolu",
  "MailChimp Integration enables synchronization between ChurchCRM contacts and your MailChimp email marketing lists.": "Integrace MailChimp umožňuje synchronizaci mezi kontakty ChurchCRM a vašimi e-mailovými marketingovými seznamy MailChimp.",
  "Managing Links": "Správa odkazů",
  "Neighborhood": "Čtvrť",
  "OpenLP API v2 Source": "Zdroj OpenLP API v2",
  "OpenLP Documentation": "Dokumentace OpenLP",
  "OpenLP Website": "Web OpenLP",
  "OpenLP is free, open-source presentation software designed for churches. This plugin allows ChurchCRM to send notifications and alerts directly to your OpenLP display.": "OpenLP je bezplatný software s otevřeným zdrojovým kódem pro prezentace navržený pro sbory. Tento plugin umožňuje ChurchCRM odesílat oznámení a upozornění přímo na váš OpenLP displej.",
  "People who are configured to pay by credit card.": "Osoby nastavené k platbě kreditní kartou.",
  "Person/Family Integration": "Integrace osob/rodin",
  "Phone Number Format": "Formát telefonního čísla",
  "Phone numbers should be in E.164 format: country code + number. Examples:\n- US: +14155551234\n- UK: +447700900123\n- Australia: +61412345678\n\nRecipient phone numbers in ChurchCRM member profiles should include the country code for SMS to work correctly.": "Telefonní čísla by měla být ve formátu E.164: kód země + číslo. Příklady:\n- USA: +14155551234\n- UK: +447700900123\n- Austrálie: +61412345678\n\nTelefonní čísla příjemců v profilech členů ChurchCRM by měla obsahovat kód země, aby SMS fungovaly správně.",
  "Pledge summary by family name for each fund for the selected fiscal year": "Souhrn finančních závazků podle rodinného jména pro každý fond za vybraný fiskální rok",
  "Privacy & Compliance": "Soukromí a dodržování předpisů",
  "Privacy Considerations": "Aspekty ochrany soukromí",
  "Privacy Note": "Poznámka k soukromí",
  "Quick Settings": "Rychlá nastavení",
  "Registered students": "Registrovaní žáci",
  "SMTP Authentication": "SMTP autentizace",
  "SMTP Timeout": "Časový limit SMTP",
  "Security Considerations": "Bezpečnostní aspekty",
  "Show a breakdown of bill denominations on the deposit slip report": "Zobrazit rozpad nominálních hodnot bankovek na sestavě vkladového lístku",
  "Show or hide the Events menu in the main navigation.": "Zobrazit nebo skrýt menu Události v hlavní navigaci.",
  "Show or hide the Events section in the main navigation menu": "Zobrazit nebo skrýt sekci Události v hlavním navigačním menu",
  "Show or hide the Sunday School module in the sidebar navigation": "Zobrazit nebo skrýt modul Nedělní škola v boční navigaci",
  "Street": "Ulice",
  "Sunday School Module": "Modul Nedělní škola",
  "Supported Services": "Podporované služby",
  "Testing Connection": "Testování připojení",
  "The Custom Menu Links plugin allows administrators to add external links to the navigation menu. When enabled, a 'Links' menu appears in the sidebar containing all configured links.": "Plugin Vlastní položky menu umožňuje správcům přidávat externí odkazy do navigačního menu. Pokud je povolen, zobrazí se v postranním panelu menu ‚Odkazy' obsahující všechny nakonfigurované odkazy.",
  "The External Backup plugin allows you to automatically backup your ChurchCRM database to WebDAV-compatible cloud storage services. This includes popular services like Nextcloud, ownCloud, or any server supporting WebDAV protocol.": "Plugin Externí záloha vám umožňuje automaticky zálohovat databázi ChurchCRM do cloudových úložišť kompatibilních s WebDAV. To zahrnuje oblíbené služby jako Nextcloud, ownCloud nebo jakýkoli server podporující protokol WebDAV.",
  "The default OpenLP port is 4316. Your server URL will typically be: http://192.168.x.x:4316 where 192.168.x.x is the IP address of the computer running OpenLP. You can find this in OpenLP under Tools → Open Service Manager.": "Výchozí port OpenLP je 4316. URL vašeho serveru bude obvykle: http://192.168.x.x:4316, kde 192.168.x.x je IP adresa počítače s OpenLP. Tuto informaci najdete v OpenLP v Nástroje → Správce služby.",
  "The month that starts your organization's fiscal year": "Měsíc, který zahajuje fiskální rok vaší organizace",
  "This plugin is currently used for Kiosk Check-in Notifications. When a child is checked into a Sunday School class via the kiosk system, an SMS can be sent to notify parents or guardians.": "Tento plugin se aktuálně používá pro oznámení při přihlášení na kiosku. Když je dítě přihlášeno do skupiny Nedělní školy přes systém kiosku, může být rodičům nebo opatrovníkům odeslána SMS.",
  "This plugin is currently used for Kiosk Check-in Notifications. When a child is checked into a Sunday School class via the kiosk system, an alert can be sent to the OpenLP projector display to notify parents or volunteers.": "Tento plugin se aktuálně používá pro oznámení při přihlášení na kiosku. Když je dítě přihlášeno do skupiny Nedělní školy přes systém kiosku, může být na projektoru OpenLP zobrazeno upozornění pro rodiče nebo dobrovolníky.",
  "This plugin transmits email addresses to MailChimp servers. Ensure you have appropriate consent from your members before syncing their information to third-party services like MailChimp.": "Tento plugin odesílá e-mailové adresy na servery MailChimp. Před synchronizací informací členů se službami třetích stran, jako je MailChimp, se ujistěte, že máte odpovídající souhlas.",
  "To add a new link:\n1. Go to the Links menu in the sidebar and click 'Manage Links'\n2. Enter a display name (2-50 characters)\n3. Enter the full URL (must start with http:// or https://)\n4. Click 'Add Link'\n\nThe link will immediately appear in the Links menu.": "Přidání nového odkazu:\n1. Přejděte do menu Odkazy v postranním panelu a klikněte na ‚Spravovat odkazy'\n2. Zadejte zobrazovaný název (2–50 znaků)\n3. Zadejte celou URL adresu (musí začínat http:// nebo https://)\n4. Klikněte na ‚Přidat odkaz'\n\nOdkaz se okamžitě zobrazí v menu Odkazy.",
  "To configure external backups:\n1. Go to Admin > Plugins and find 'External Backup (WebDAV)'\n2. Click the settings icon to expand the configuration panel\n3. Enter your WebDAV endpoint URL (e.g., https://cloud.example.com/remote.php/dav/files/username/backups/)\n4. Enter your username and password\n5. Optionally set an auto-backup interval in hours\n6. Save your settings": "Konfigurace externích záloh:\n1. Přejděte na Správce > Pluginy a najděte ‚Externí záloha (WebDAV)'\n2. Klikněte na ikonu nastavení pro rozbalení konfiguračního panelu\n3. Zadejte URL adresu WebDAV koncového bodu (např. https://cloud.priklad.cz/remote.php/dav/files/uzivatel/zalohy/)\n4. Zadejte uživatelské jméno a heslo\n5. Volitelně nastavte interval automatické zálohy v hodinách\n6. Uložte nastavení",
  "To use MailChimp Integration, you need a MailChimp account and an API key.\n\n1. Log in to your MailChimp account\n2. Go to Account > Extras > API Keys\n3. Create a new API key or copy an existing one\n4. Enter the API key in the plugin settings": "Pro použití integrace MailChimp potřebujete účet MailChimp a API klíč.\n\n1. Přihlaste se do svého účtu MailChimp\n2. Přejděte na Účet > Doplňky > API klíče\n3. Vytvořte nový API klíč nebo zkopírujte existující\n4. Zadejte API klíč do nastavení pluginu",
  "Troubleshooting": "Řešení problémů",
  "Troubleshooting - Invalid Sender ID": "Řešení problémů – neplatné ID odesílatele",
  "Troubleshooting - Messages Not Delivered": "Řešení problémů – zprávy nedoručeny",
  "Troubleshooting - SMS Not Sending": "Řešení problémů – SMS se neodesílají",
  "Upgrade Settings": "Nastavení aktualizací",
  "Use Cases": "Případy použití",
  "User permission to export CSV files": "Uživatelské oprávnění k exportu souborů CSV",
  "Vonage Dashboard": "Vonage Dashboard",
  "Vonage Pricing": "Ceník Vonage",
  "Vonage SMS API Documentation": "Dokumentace Vonage SMS API",
  "Vonage SMS enables text message notifications for ChurchCRM using the Vonage API (formerly Nexmo). Send SMS alerts to parents when their child checks in via the kiosk system.": "Vonage SMS umožňuje textová oznámení pro ChurchCRM prostřednictvím Vonage API (dříve Nexmo). Zasílejte SMS upozornění rodičům, když se jejich dítě přihlásí přes systém kiosku.",
  "Vonage charges per SMS sent. Pricing varies by destination country. See the Vonage pricing page for current rates. New accounts receive free trial credit for testing.": "Vonage účtuje poplatek za každou odeslanou SMS. Ceny se liší podle cílové země. Aktuální sazby naleznete na stránce s cenami Vonage. Nové účty dostávají bezplatný zkušební kredit.",
  "What Gets Tracked": "Co se sleduje",
  "When MailChimp is configured, a 'MailChimp' tab appears on Person view pages showing:\n\n- Email subscription status across all lists\n- Which lists the person is subscribed to\n- Subscription statistics": "Když je MailChimp nakonfigurován, na stránkách zobrazení osoby se zobrazí záložka ‚MailChimp' s:\n\n- Stavem odběru e-mailu ve všech seznamech\n- Seznamy, ke kterým je osoba přihlášena\n- Statistikami odběru",
  "When a member doesn't have an uploaded photo, ChurchCRM checks if they have a Gravatar associated with their email address. If a Gravatar exists, it displays that image. If not, the configured default image style is used.": "Pokud člen nemá nahranou fotografii, ChurchCRM zkontroluje, zda má Gravatar přiřazený k jeho e-mailové adrese. Pokud Gravatar existuje, zobrazí se tento obrázek. Pokud ne, použije se nakonfigurovaný výchozí styl obrázku.",
  "When auto-backup is enabled (interval > 0 hours), ChurchCRM will automatically create and upload a full database backup at the specified interval. The backup runs as part of normal page loads, so the system must have regular user activity to trigger backups.\n\nRecommended intervals:\n- Daily backup: 24 hours\n- Twice daily: 12 hours\n- Weekly: 168 hours": "Když je automatická záloha povolena (interval > 0 hodin), ChurchCRM automaticky vytvoří a nahraje úplnou zálohu databáze v zadaném intervalu. Záloha probíhá jako součást normálního načítání stránek, takže systém musí mít pravidelnou aktivitu uživatelů pro spuštění záloh.\n\nDoporučené intervaly:\n- Denní záloha: 24 hodin\n- Dvakrát denně: 12 hodin\n- Týdenní: 168 hodin",
  "When enabled and configured, ChurchCRM sends alert messages to your OpenLP server using the API v2 endpoint (POST /api/v2/plugins/alerts). These alerts appear as overlay notifications on your projected display.": "Když je povoleno a nakonfigurováno, ChurchCRM odesílá upozornění na váš server OpenLP pomocí koncového bodu API v2 (POST /api/v2/plugins/alerts). Tato upozornění se zobrazují jako překryvná oznámení na vašem promítaném displeji.",
  "When enabled, hides the address field for people not assigned to a family": "Při povolení skryje pole adresy u osob, které nejsou přiřazeny k rodině",
  "When enabled, hides the latitude/longitude fields in the Family Editor. Geocoding still runs in the background.": "Při povolení skryje pole zeměpisné šířky/délky v editoru rodiny. Geokódování stále probíhá na pozadí.",
  "You can also trigger a manual backup at any time:\n1. Go to the External Backup settings page (Plugins > External Backup)\n2. Select backup type (Database Only or Full Backup)\n3. Click 'Backup to WebDAV Now'\n\nDatabase Only backups are smaller and faster. Full backups include uploaded photos.": "Ruční zálohu můžete spustit kdykoliv:\n1. Přejděte na stránku nastavení externí zálohy (Pluginy > Externí záloha)\n2. Vyberte typ zálohy (Pouze databáze nebo Úplná záloha)\n3. Klikněte na ‚Zálohovat na WebDAV nyní'\n\nZálohy Pouze databáze jsou menší a rychlejší. Úplné zálohy zahrnují nahrané fotografie.",
  "• Page views and navigation patterns\n• Session duration and engagement\n• User demographics (if enabled in GA4)\n• Device and browser information": "• Zobrazení stránek a navigační vzory\n• Délka relace a zapojení\n• Demografické údaje uživatelů (pokud je povoleno v GA4)\n• Informace o zařízení a prohlížeči"
}

with open('/home/runner/work/CRM/CRM/cs-1-trans.json', 'w', encoding='utf-8') as f:
    json.dump(t, f, ensure_ascii=False, indent=2)
print("cs done")
