import json

t = {
  "N/A": "",
  "Auto TLS": "Automaatne TLS",
  "Security": "Turvalisus",
  "Setup": "Seadistus",
  "- **Dashboard**: View all your MailChimp lists with subscriber statistics\n- **List Maintenance**: Identify people in MailChimp but not in CRM, and vice versa\n- **Contact Integration**: View MailChimp subscription status on Person and Family pages\n- **Automatic Sync**: Hooks into person/family updates to keep MailChimp in sync": "- **Armatuurlaud**: Vaadake kõiki oma MailChimp loendeid koos tellijate statistikaga\n- **Loendi hooldus**: Tuvastage inimesed, kes on MailChimps, kuid mitte CRMis, ja vastupidi\n- **Kontakti integreerimine**: Vaadake MailChimpi tellimuse olekut isiku ja pere lehtedel\n- **Automaatne sünkroonimine**: Ühendab isiku/pere uuendused, et hoida MailChimp sünkroonis",
  "1. Create a Vonage account at https://dashboard.nexmo.com/sign-up (new accounts include free trial credit)\n2. Find your API Key and API Secret on the Vonage Dashboard homepage\n3. Go to Numbers > Buy Numbers and purchase a number with SMS capability\n4. Note the number in E.164 format (e.g., +14155551234)\n5. In ChurchCRM, enable the Vonage SMS plugin and enter your credentials": "1. Looge Vonage konto aadressil https://dashboard.nexmo.com/sign-up (uued kontod sisaldavad tasuta proovikrediiti)\n2. Leidke oma API-võti ja API-saladus Vonage'i armatuurlaua avalehelt\n3. Minge Numbrid > Osta numbreid ja ostke SMS-võimalusega number\n4. Märkige number E.164 formaadis (nt +14155551234)\n5. Lubage ChurchCRMis Vonage SMS pistikprogramm ja sisestage oma mandaadid",
  "1. Go to Google Analytics (analytics.google.com)\n2. Create a property or select an existing one\n3. Go to Admin → Data Streams → Web\n4. Copy the Measurement ID (starts with G-)": "1. Minge Google Analyticsisse (analytics.google.com)\n2. Looge atribuut või valige olemasolev\n3. Minge Administraator → Andmevood → Veebi\n4. Kopeerige mõõtmise ID (algab G-ga)",
  "1. Install OpenLP 3.0 or later on your presentation computer\n2. Enable the Remote plugin in OpenLP (Settings → Configure OpenLP → Plugins)\n3. Enable the Alerts plugin in OpenLP for alert display support\n4. Note the IP address of the OpenLP computer\n5. Enter the server URL in the format: http://IP_ADDRESS:4316\n6. If you've configured authentication in OpenLP, enter the username and password": "1. Installige OpenLP 3.0 või uuem oma esitlusarvutisse\n2. Lubage OpenLPs kaugpistikprogramm (Seaded → Konfigureeri OpenLP → Pistikprogrammid)\n3. Lubage OpenLPs häiretus pistikprogramm häirete kuvamise toetuseks\n4. Märkige OpenLP arvuti IP-aadress\n5. Sisestage serveri URL formaadis: http://IP_AADRESS:4316\n6. Kui olete OpenLPs autentimise konfigureerinud, sisestage kasutajanimi ja parool",
  "Access the MailChimp Dashboard from the Email menu. The dashboard shows:\n\n- Member count for each list\n- Campaign statistics\n- Unsubscribe counts\n- List maintenance tools": "Avage MailChimpi armatuurlaud menüüst E-post. Armatuurlaud näitab:\n\n- Liikmete arv iga loendi kohta\n- Kampaania statistika\n- Loobumiste arv\n- Loendi haldustööriistad",
  "Adding Links": "Linkide lisamine",
  "All configured links are shown in a table. You can:\n- View the link name and URL\n- Click the URL to test it opens correctly\n- Delete links you no longer need\n\nLinks appear in the order they were added in the navigation menu.": "Kõik konfigureeritud lingid on kuvatud tabelis. Saate:\n- Vaadata lingi nime ja URL-i\n- Klõpsata URL-il, et kontrollida, kas see avaneb õigesti\n- Kustutada lingid, mida enam ei vaja\n\nLingid ilmuvad navigatsioonimenüüs lisamisjärjekorras.",
  "Allow Pre-release Upgrades": "Luba eelversiooni uuendusi",
  "Allow recording of non-tax-deductible payments in the finance module": "Luba maksuvabade maksete registreerimine finantsimoodulis",
  "Allow scanned check images to be attached to deposit records": "Luba skaneeritud tšeki piltide lisamine sissemaksete kirjetele",
  "Allow system upgrades to releases marked as 'pre release' on GitHub": "Luba süsteemi uuendamine versioonidele, mis on GitHubis märgitud kui ‚eelversioon'",
  "Allow unauthenticated access to calendar events via public HTML, ICS, and JSON URLs. Required for sharing calendars with external apps.": "Luba autentimata juurdepääs kalendrisündmustele avalike HTML-, ICS- ja JSON-URL-ide kaudu. Vajalik kalendrite jagamiseks väliste rakendustega.",
  "Allow visitors to create their own family record via the self-registration page": "Luba külastajatel luua oma perekonna kirje eneseregistreerimislehe kaudu",
  "Allow visitors to self-register as new families.": "Luba külastajatel registreeruda iseseisvalt uute peredena.",
  "Any WebDAV-compatible service works with this plugin:\n\n- Nextcloud (recommended)\n- ownCloud\n- Synology NAS\n- QNAP NAS\n- Box.com (with WebDAV)\n- Apache mod_dav\n- nginx with WebDAV module\n\nNote: Some services require app-specific passwords for WebDAV access.": "Selle pistikprogrammiga töötab iga WebDAV-ühilduv teenus:\n\n- Nextcloud (soovitatav)\n- ownCloud\n- Synology NAS\n- QNAP NAS\n- Box.com (WebDAViga)\n- Apache mod_dav\n- nginx WebDAV mooduliga\n\nMärkus: Mõned teenused nõuavad WebDAV-i juurdepääsuks rakendusepõhiseid paroole.",
  "Authentication": "Autentimine",
  "Authentication is required for API v2 if you've enabled it in OpenLP's Remote plugin settings. The plugin uses HTTP Basic Authentication. Most local network setups don't require authentication, but it's recommended for security.": "API v2 jaoks on autentimine nõutav, kui olete selle OpenLP kaugpistikprogrammi seadetes lubanud. Pistikprogramm kasutab HTTP põhiautentimist. Enamik kohalikke võrguseadistusi ei nõua autentimist, kuid turvalisuse huvides on see soovitatav.",
  "Auto-Backup": "Automaatne varundamine",
  "BCC All Mail To": "BCC kõik kirjad aadressile",
  "Before relying on external backups, test your connection:\n1. Go to Plugins > External Backup\n2. Click 'Test WebDAV Connection'\n3. Verify you see a success message\n\nCommon issues:\n- 401/403 errors: Check username and password\n- Connection timeout: Verify the endpoint URL is correct\n- Certificate errors: Ensure the WebDAV server has a valid SSL certificate": "Enne väliste varunduste kasutamist testige ühendust:\n1. Minge Pistikprogrammid > Väline varundamine\n2. Klõpsake ‚Testi WebDAV-ühendust'\n3. Veenduge, et näete edu teadet\n\nLevinud probleemid:\n- 401/403 vead: Kontrollige kasutajanime ja parooli\n- Ühenduse ajalõpp: Kontrollige lõpp-punkti URL-i\n- Sertifikaadi vead: Veenduge, et WebDAV-serveril on kehtiv SSL-sertifikaat",
  "Choose what appears when no Gravatar exists:\n• Mystery Person - Gray silhouette outline\n• Identicon - Geometric pattern based on email\n• MonsterID - Unique generated monster face\n• Wavatar - Abstract generated face\n• Retro - 8-bit arcade-style pixel art\n• RoboHash - Unique generated robot\n• Blank - Transparent (falls back to initials)": "Valige, mis kuvatakse, kui Gravatarit pole:\n• Mystery Person – hall siluett\n• Identicon – e-postil põhinev geomeetriline muster\n• MonsterID – unikaalne genereeritud koletise nägu\n• Wavatar – abstraktne genereeritud nägu\n• Retro – 8-bitine arkaadstiilis pikslikunst\n• RoboHash – unikaalne genereeritud robot\n• Tühi – läbipaistev (kasutab initsiaalide vaikeväärtust)",
  "Comma-separated query IDs that require finance permissions to view": "Komaga eraldatud päringute ID-d, mille vaatamiseks on vaja finantsõigusi",
  "Common uses for custom links:\n- Church website\n- Online giving portal\n- Volunteer signup forms\n- Denomination resources\n- Partner organization sites\n- Cloud storage folders\n- Event registration pages": "Kohandatud linkide tavapärased kasutusvõimalused:\n- Koguduse veebileht\n- Veebiandide portaal\n- Vabatahtlike registreerimisvormid\n- Konfessiooni ressursid\n- Partnerorganisatsioonide saidid\n- Pilvemälu kaustad\n- Ürituse registreerimislehed",
  "Configuration": "Konfiguratsioon",
  "Continent": "Manner",
  "Costs": "Kulud",
  "Credit Card People": "Krediitkaardiga isikud",
  "Current Usage": "Praegune kasutus",
  "Default Image Styles": "Vaikimisi pildistiilid",
  "Default Map View": "Kaardi vaikimisi vaade",
  "Deposit ticket type": "Sissemaksedokumendi tüüp",
  "Do Not Email Property": "Ära saada e-posti omadus",
  "Do Not SMS Property": "Ära saada SMS-i omadus",
  "Download OpenLP": "Laadi alla OpenLP",
  "E.164 Phone Number Format": "E.164 telefoninumbri vorming",
  "Enable Email": "Luba e-post",
  "Enable Events Menu": "Luba ürituste menüü",
  "Enable External Calendar API": "Luba väline kalender API",
  "Enable email sending from ChurchCRM. Required for password reset, notifications, and email links.": "Luba e-kirjade saatmine ChurchCRMist. Vajalik parooli lähtestamiseks, teadeteks ja e-posti linkideks.",
  "Enable if your SMTP server requires a username and password": "Luba, kui teie SMTP-server nõuab kasutajanime ja parooli",
  "Enable or disable the Sunday School module and sidebar menu.": "Lubage või keelake pühapäevakooli moodul ja külgmenüü.",
  "Enable the use of numbered donation envelopes for tracking contributions": "Luba nummerdatud annetusümbrikute kasutamine annetuste jälgimiseks",
  "Enable use of donation envelopes": "Luba annetusümbrikute kasutamine",
  "Enable use of scanned checks": "Luba skaneeritud tšekkide kasutamine",
  "Family Pledge by Fiscal Year": "Perekonna lubadus majandusaasta kaupa",
  "Features": "Funktsioonid",
  "Finance permission query IDs": "Finantsõiguste päringute ID-d",
  "Find Registered students": "Leia registreeritud õpilased",
  "Find family": "Leia perekond",
  "Finding Your Server URL": "Serveri URL-i leidmine",
  "Fiscal Year.": "Majandusaasta.",
  "For security:\n- Only administrators can add or remove links\n- The 'Manage Links' option only appears for administrators\n- Links must use http:// or https:// protocols\n- HTML tags are not allowed in names or URLs\n- All input is validated and sanitized": "Turvalisuse tagamiseks:\n- Ainult administraatorid saavad linke lisada või eemaldada\n- Valik ‚Halda linke' on nähtav ainult administraatoritele\n- Lingid peavad kasutama http:// või https:// protokolle\n- HTML-sildid pole nimedes ega URL-ides lubatud\n- Kõik sisendid valideeritakse ja puhastatakse",
  "GA4 Setup Guide": "GA4 seadistuse juhend",
  "Getting Started": "Alustamine",
  "Getting Your GA4 Measurement ID": "GA4 mõõtmise ID hankimine",
  "Google Analytics 4 (GA4) tracks how users interact with ChurchCRM, providing insights into page views, user engagement, and feature usage.": "Google Analytics 4 (GA4) jälgib, kuidas kasutajad ChurchCRMiga suhtlevad, pakkudes ülevaadet lehekülgede vaatamisest, kasutajate kaasatusest ja funktsioonide kasutamisest.",
  "Google Analytics Help": "Google Analyticsi abi",
  "Google Analytics collects anonymized usage data. No personal information from ChurchCRM records is sent to Google. Consider adding a privacy notice to your church's data policy.": "Google Analytics kogub anonüümitud kasutusandmeid. Ühtegi isiklikku teavet ChurchCRM kirjetest ei saadeta Google'ile. Kaaluge privaatsusteatise lisamist oma koguduse andmekaitsepoliitikasse.",
  "Gravatar (Globally Recognized Avatar) displays profile photos from gravatar.com for members who don't have uploaded photos in ChurchCRM.": "Gravatar (ülemaailmselt tunnustatud avatar) kuvab profiilifotosid gravatar.com-ist liikmetele, kellel pole ChurchCRMi laaditud fotosid.",
  "Gravatar Image Options": "Gravatari pildisuvandid",
  "Gravatar Website": "Gravatari veebisait",
  "Gravatar works by converting email addresses into a hash (MD5). The actual email address is never sent to Gravatar's servers - only the hash is used to look up the image.": "Gravatar töötab e-posti aadresside teisendamisel räsi (MD5) abil. Tegelikku e-posti aadressi ei saadeta kunagi Gravatari serveritesse – pildi otsimiseks kasutatakse ainult räsi.",
  "Group of registered students": "Registreeritud õpilaste rühm",
  "Hide Latitude/Longitude": "Peida laiuskraad/pikkuskraad",
  "Hide Person Address": "Peida isiku aadress",
  "How it works": "Kuidas see töötab",
  "How many checks to print per deposit slip page": "Mitu tšekki printida sissemaksedokumendi lehe kohta",
  "If SMS messages aren't being sent:\n1. Verify API Key and Secret are correct (no extra spaces)\n2. Check that the From Number is a valid Vonage number you own\n3. Ensure recipient phone numbers include country code\n4. Check your Vonage account balance\n5. Review the Vonage Dashboard > SMS > Logs for delivery status": "Kui SMS-sõnumeid ei saadeta:\n1. Veenduge, et API-võti ja saladus on õiged (ilma lisatühikuteta)\n2. Kontrollige, et saatja number on kehtiv Vonage'i number, mis teile kuulub\n3. Veenduge, et saaja telefoninumbrid sisaldavad riigikood\n4. Kontrollige oma Vonage'i konto saldo\n5. Vaadake edastuse olekut Vonage Dashboardis > SMS > Logid",
  "If alerts aren't appearing:\n1. Verify OpenLP is running and the Remote plugin is active\n2. Ensure the Alerts plugin is enabled in OpenLP\n3. Check that the server URL is correct (try accessing it in a browser)\n4. Verify firewall settings allow connections on port 4316\n5. If using authentication, verify credentials are correct": "Kui häired ei ilmu:\n1. Veenduge, et OpenLP töötab ja kaugpistikprogramm on aktiivne\n2. Veenduge, et häiretuse pistikprogramm on OpenLPs lubatud\n3. Kontrollige, kas serveri URL on õige (proovige brauseris avada)\n4. Veenduge, et tulemüüri sätted lubavad ühendusi pordil 4316\n5. Autentimise kasutamisel kontrollige mandaatide õigsust",
  "If messages are sent but not received:\n1. Check Vonage Dashboard > SMS > Logs for delivery status\n2. Verify the recipient number is correct and can receive SMS\n3. Some carriers may block messages from unknown numbers\n4. Check if the destination country has SMS restrictions": "Kui sõnumid on saadetud, kuid neid ei võeta vastu:\n1. Kontrollige edastuse olekut Vonage Dashboardis > SMS > Logid\n2. Veenduge, et saaja number on õige ja suudab SMS-e vastu võtta\n3. Mõned operaatorid võivad blokeerida sõnumeid tundmatutelt numbritelt\n4. Kontrollige, kas sihtriigil on SMS-piiranguid",
  "If you receive invalid sender ID errors:\n1. Use a phone number you've purchased from Vonage\n2. Format the number in E.164 format (+14155551234)\n3. Note: Alphanumeric sender IDs may be restricted in some countries": "Kui saate vigase saatja ID vigu:\n1. Kasutage Vonage'ilt ostetud telefoninumbrit\n2. Vormindage number E.164 formaadis (+14155551234)\n3. Märkus: Tähtnumbrilised saatja ID-d võivad mõnes riigis olla piiratud",
  "Important security notes:\n\n1. Always use HTTPS endpoints to encrypt backups in transit\n2. Use app-specific passwords when available (Nextcloud, ownCloud)\n3. Store backups in a folder with restricted access\n4. Periodically download and verify your backups are valid\n5. Consider encrypting sensitive backups with external tools before uploading": "Olulised turvamiärkused:\n\n1. Kasutage alati HTTPS lõpp-punkte varunduste krüptimiseks edastamisel\n2. Kasutage rakendusepõhiseid paroole, kui need on saadaval (Nextcloud, ownCloud)\n3. Salvestage varukoopiad piiratud juurdepääsuga kausta\n4. Laadige perioodiliselt alla ja kontrollige varukoopiate kehtivust\n5. Kaaluge tundlike varukoopiate krüptimist väliste tööriistadega enne üleslaadimist",
  "Initial zoom level when opening the map": "Kaardi esmane suumimistase avamisel",
  "Learn more": "Lisateave",
  "Log Settings": "Logimine seaded",
  "MailChimp Integration enables synchronization between ChurchCRM contacts and your MailChimp email marketing lists.": "MailChimpi integreerimine võimaldab sünkroonimist ChurchCRM kontaktide ja teie MailChimpi e-posti turundusloendite vahel.",
  "Managing Links": "Linkide haldamine",
  "Neighborhood": "Naabruskond",
  "OpenLP API v2 Source": "OpenLP API v2 allikas",
  "OpenLP Documentation": "OpenLP dokumentatsioon",
  "OpenLP Website": "OpenLP veebisait",
  "OpenLP is free, open-source presentation software designed for churches. This plugin allows ChurchCRM to send notifications and alerts directly to your OpenLP display.": "OpenLP on kirikutele loodud tasuta avatud lähtekoodiga esitlustarkvara. See pistikprogramm võimaldab ChurchCRMil saata teavitusi ja häireid otse teie OpenLP ekraanile.",
  "People who are configured to pay by credit card.": "Isikud, kes on seadistatud maksma krediitkaardiga.",
  "Person/Family Integration": "Isiku/perekonna integreerimine",
  "Phone Number Format": "Telefoninumbri vorming",
  "Phone numbers should be in E.164 format: country code + number. Examples:\n- US: +14155551234\n- UK: +447700900123\n- Australia: +61412345678\n\nRecipient phone numbers in ChurchCRM member profiles should include the country code for SMS to work correctly.": "Telefoninumbrid peaksid olema E.164 formaadis: riigikood + number. Näited:\n- USA: +14155551234\n- UK: +447700900123\n- Austraalia: +61412345678\n\nChurchCRM liikmete profiilide saaja telefoninumbrid peaksid sisaldama riigikoodi, et SMS-id toimiksid õigesti.",
  "Pledge summary by family name for each fund for the selected fiscal year": "Lubaduste kokkuvõte perekonna nime järgi iga fondi kohta valitud majandusaastal",
  "Privacy & Compliance": "Privaatsus ja nõuetele vastavus",
  "Privacy Considerations": "Privaatsuse kaalutlused",
  "Privacy Note": "Privaatsuse märkus",
  "Quick Settings": "Kiirseaded",
  "Registered students": "Registreeritud õpilased",
  "SMTP Authentication": "SMTP autentimine",
  "SMTP Timeout": "SMTP ajalõpp",
  "Security Considerations": "Turvalisuse kaalutlused",
  "Show a breakdown of bill denominations on the deposit slip report": "Näita rahatähtede nominaalide jaotust sissemaksedokumendi aruandes",
  "Show or hide the Events menu in the main navigation.": "Kuva või peida Ürituste menüü peanavigatsioonil.",
  "Show or hide the Events section in the main navigation menu": "Kuva või peida Ürituste jaotis peamises navigatsioonimenüüs",
  "Show or hide the Sunday School module in the sidebar navigation": "Kuva või peida pühapäevakooli moodul külgnavigatsioonis",
  "Street": "Tänav",
  "Sunday School Module": "Pühapäevakooli moodul",
  "Supported Services": "Toetatud teenused",
  "Testing Connection": "Ühenduse testimine",
  "The Custom Menu Links plugin allows administrators to add external links to the navigation menu. When enabled, a 'Links' menu appears in the sidebar containing all configured links.": "Kohandatud menüülinkide pistikprogramm võimaldab administraatoritel lisada väliseid linke navigatsioonimenüüsse. Lubamisel ilmub külgpaneelile menüü ‚Lingid', mis sisaldab kõiki konfigureeritud linke.",
  "The External Backup plugin allows you to automatically backup your ChurchCRM database to WebDAV-compatible cloud storage services. This includes popular services like Nextcloud, ownCloud, or any server supporting WebDAV protocol.": "Välise varundamise pistikprogramm võimaldab teil automaatselt varundada ChurchCRMi andmebaasi WebDAV-ühilduvatesse pilvemälundusteenus. See hõlmab populaarseid teenuseid nagu Nextcloud, ownCloud või mis tahes WebDAV-protokolli toetav server.",
  "The default OpenLP port is 4316. Your server URL will typically be: http://192.168.x.x:4316 where 192.168.x.x is the IP address of the computer running OpenLP. You can find this in OpenLP under Tools → Open Service Manager.": "Vaikimisi OpenLP port on 4316. Teie serveri URL on tavaliselt: http://192.168.x.x:4316, kus 192.168.x.x on OpenLPi käitava arvuti IP-aadress. Selle leiate OpenLPis Tööriistad → Ava teenusehaldur.",
  "The month that starts your organization's fiscal year": "Kuu, millest algab teie organisatsiooni majandusaasta",
  "This plugin is currently used for Kiosk Check-in Notifications. When a child is checked into a Sunday School class via the kiosk system, an SMS can be sent to notify parents or guardians.": "Seda pistikprogrammi kasutatakse praegu kioski sisseregistreerimise teavitusteks. Kui laps registreeritakse kioskisüsteemi kaudu pühapäevakooli tundi, võib vanematele või eestkostjatele saata SMS-i.",
  "This plugin is currently used for Kiosk Check-in Notifications. When a child is checked into a Sunday School class via the kiosk system, an alert can be sent to the OpenLP projector display to notify parents or volunteers.": "Seda pistikprogrammi kasutatakse praegu kioski sisseregistreerimise teavitusteks. Kui laps registreeritakse kioskisüsteemi kaudu pühapäevakooli tundi, võib OpenLP projekti ekraanile saata häire, et teavitada vanemaid või vabatahtlikke.",
  "This plugin transmits email addresses to MailChimp servers. Ensure you have appropriate consent from your members before syncing their information to third-party services like MailChimp.": "See pistikprogramm edastab e-posti aadresse MailChimpi serveritele. Enne liikmete teabe sünkroonimist kolmandate osapoolte teenustega nagu MailChimp veenduge, et teil on vastav nõusolek.",
  "To add a new link:\n1. Go to the Links menu in the sidebar and click 'Manage Links'\n2. Enter a display name (2-50 characters)\n3. Enter the full URL (must start with http:// or https://)\n4. Click 'Add Link'\n\nThe link will immediately appear in the Links menu.": "Uue lingi lisamiseks:\n1. Minge külgpaneeli menüüsse Lingid ja klõpsake ‚Halda linke'\n2. Sisestage kuvatav nimi (2–50 märki)\n3. Sisestage täielik URL (peab algama http:// või https://)\n4. Klõpsake ‚Lisa link'\n\nLink ilmub kohe menüüsse Lingid.",
  "To configure external backups:\n1. Go to Admin > Plugins and find 'External Backup (WebDAV)'\n2. Click the settings icon to expand the configuration panel\n3. Enter your WebDAV endpoint URL (e.g., https://cloud.example.com/remote.php/dav/files/username/backups/)\n4. Enter your username and password\n5. Optionally set an auto-backup interval in hours\n6. Save your settings": "Väliste varunduste seadistamiseks:\n1. Minge Administraator > Pistikprogrammid ja leidke ‚Väline varundamine (WebDAV)'\n2. Klõpsake seadete ikoonil konfiguratsioonipaneeli laiendamiseks\n3. Sisestage oma WebDAV lõpp-punkti URL (nt https://pilv.näide.ee/remote.php/dav/files/kasutaja/varukoopiad/)\n4. Sisestage kasutajanimi ja parool\n5. Soovi korral seadistage automaatse varundamise intervall tundides\n6. Salvestage seaded",
  "To use MailChimp Integration, you need a MailChimp account and an API key.\n\n1. Log in to your MailChimp account\n2. Go to Account > Extras > API Keys\n3. Create a new API key or copy an existing one\n4. Enter the API key in the plugin settings": "MailChimpi integratsiooni kasutamiseks vajate MailChimpi kontot ja API-võtit.\n\n1. Logige sisse oma MailChimpi kontole\n2. Minge Konto > Lisad > API-võtmed\n3. Looge uus API-võti või kopeerige olemasolev\n4. Sisestage API-võti pistikprogrammi seadetesse",
  "Troubleshooting": "Tõrkeotsing",
  "Troubleshooting - Invalid Sender ID": "Tõrkeotsing – kehtetu saatja ID",
  "Troubleshooting - Messages Not Delivered": "Tõrkeotsing – sõnumeid ei edastatud",
  "Troubleshooting - SMS Not Sending": "Tõrkeotsing – SMS-e ei saadeta",
  "Upgrade Settings": "Uuenduse seaded",
  "Use Cases": "Kasutusjuhud",
  "User permission to export CSV files": "Kasutajaõigus CSV-failide eksportimiseks",
  "Vonage Dashboard": "Vonage Dashboard",
  "Vonage Pricing": "Vonage'i hinnad",
  "Vonage SMS API Documentation": "Vonage SMS API dokumentatsioon",
  "Vonage SMS enables text message notifications for ChurchCRM using the Vonage API (formerly Nexmo). Send SMS alerts to parents when their child checks in via the kiosk system.": "Vonage SMS võimaldab ChurchCRMi jaoks tekstsõnumite teavitusi Vonage API (endine Nexmo) abil. Saatke SMS-häireid vanematele, kui nende laps registreerub kioskisüsteemi kaudu.",
  "Vonage charges per SMS sent. Pricing varies by destination country. See the Vonage pricing page for current rates. New accounts receive free trial credit for testing.": "Vonage võtab tasu iga saadetud SMS-i eest. Hinnad varieeruvad sihtriigiti. Praeguste hindade kohta vaadake Vonage'i hindade lehte. Uued kontod saavad tasuta proovikrediiti.",
  "What Gets Tracked": "Mida jälgitakse",
  "When MailChimp is configured, a 'MailChimp' tab appears on Person view pages showing:\n\n- Email subscription status across all lists\n- Which lists the person is subscribed to\n- Subscription statistics": "Kui MailChimp on konfigureeritud, ilmub isiku vaatelehekülgedele vahekaart ‚MailChimp', mis näitab:\n\n- E-posti tellimuse olekut kõigis loendites\n- Millisesse loendisse on isik tellinud\n- Tellimuse statistikat",
  "When a member doesn't have an uploaded photo, ChurchCRM checks if they have a Gravatar associated with their email address. If a Gravatar exists, it displays that image. If not, the configured default image style is used.": "Kui liikmel pole üleslaaditud fotot, kontrollib ChurchCRM, kas neil on e-posti aadressiga seotud Gravatar. Kui Gravatar on olemas, kuvatakse see pilt. Kui mitte, kasutatakse konfigureeritud vaikimisi pildistiili.",
  "When auto-backup is enabled (interval > 0 hours), ChurchCRM will automatically create and upload a full database backup at the specified interval. The backup runs as part of normal page loads, so the system must have regular user activity to trigger backups.\n\nRecommended intervals:\n- Daily backup: 24 hours\n- Twice daily: 12 hours\n- Weekly: 168 hours": "Kui automaatne varundamine on lubatud (intervall > 0 tundi), loob ja laadib ChurchCRM määratud intervalliga automaatselt täieliku andmebaasi varukoopia. Varundamine toimub normaalse lehekülgede laadimise osana, seega peab süsteemil olema varundamise käivitamiseks regulaarne kasutajategevus.\n\nSoovitatavad intervallid:\n- Igapäevane varundamine: 24 tundi\n- Kaks korda päevas: 12 tundi\n- Iganädalane: 168 tundi",
  "When enabled and configured, ChurchCRM sends alert messages to your OpenLP server using the API v2 endpoint (POST /api/v2/plugins/alerts). These alerts appear as overlay notifications on your projected display.": "Lubamisel ja konfigureerimisel saadab ChurchCRM häireteateid teie OpenLP serverile API v2 lõpp-punkti kaudu (POST /api/v2/plugins/alerts). Need häired ilmuvad ülekatte teavitustena teie projitseeritud ekraanil.",
  "When enabled, hides the address field for people not assigned to a family": "Lubamisel peidab aadressivälja inimeste eest, kes pole perele määratud",
  "When enabled, hides the latitude/longitude fields in the Family Editor. Geocoding still runs in the background.": "Lubamisel peidab laiuskraadi/pikkuskraadi väljad perekonna redaktoris. Geokoodeerimine töötab endiselt taustal.",
  "You can also trigger a manual backup at any time:\n1. Go to the External Backup settings page (Plugins > External Backup)\n2. Select backup type (Database Only or Full Backup)\n3. Click 'Backup to WebDAV Now'\n\nDatabase Only backups are smaller and faster. Full backups include uploaded photos.": "Saate igal ajal käivitada ka käsitsi varundamise:\n1. Minge välise varunduse seadete lehele (Pistikprogrammid > Väline varundamine)\n2. Valige varunduse tüüp (Ainult andmebaas või Täielik varundamine)\n3. Klõpsake ‚Varunda WebDAVi kohe'\n\nAinult andmebaasi varukoopiad on väiksemad ja kiiremad. Täielikud varukoopiad sisaldavad üleslaaditud fotosid.",
  "• Page views and navigation patterns\n• Session duration and engagement\n• User demographics (if enabled in GA4)\n• Device and browser information": "• Lehekülgede vaatamised ja navigatsioonimustrid\n• Seansi kestus ja kaasatus\n• Kasutajate demograafia (kui lubatud GA4-s)\n• Seadme ja brauseri teave"
}

with open('/home/runner/work/CRM/CRM/et-1-trans.json', 'w', encoding='utf-8') as f:
    json.dump(t, f, ensure_ascii=False, indent=2)
print("et done")
