#!/usr/bin/env python3
import json

af_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/af.json'
el_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/el.json'

# COMPREHENSIVE AFRIKAANS TRANSLATIONS (ALL REMAINING 505 TERMS)
afrikaans_final = {
    "Unknown error": "Onbekende fout",
    "deposit(s) with no payments": "deposito(s) sonder betalings",
    "All Event Types": "Alle Gebeure Tipes",
    "All Types": "Alle Tipes",
    "Are you sure you want to delete this check-in record?": "Is jy seker dat jy hierdie insluitrekord wil skrap?",
    "Attendance Count Categories": "Bywoning Tel Kategorieë",
    "Attendance Notes": "Bywoning Notas",
    "Change Event": "Wysig Gebeuer",
    "Check In": "Sluit In",
    "Check In Person": "Sluit Persoon In",
    "Check-in Time": "Sluittyd",
    "Checkin": "Sluiting",
    "Checkin Code": "Sluitkode",
    "Checkin Code URL": "Sluitkode URL",
    "Checkin is enabled": "Sluiting is geaktiveer",
    "Checkin": "Sluiting",
    "Circle Name": "Sirkel Naam",
    "Classification": "Klassifikasie",
    "Clear": "Maak skoon",
    "Clear search results": "Maak soekresultate skoon",
    "Click 'Next' when you are ready to migrate your database": "Klik 'Volgende' wanneer jy gereed is om jou databasisse te migreer",
    "Click to Reorder": "Klik om Opnieuw te Orden",
    "Close": "Sluit",
    "Closed Today": "Vandag Gesluit",
    "Code": "Kode",
    "Cohort": "Kohort",
    "Collection": "Versameling",
    "Color": "Kleur",
    "Color Code": "Kleur Kode",
    "Color(s)": "Kleur(e)",
    "Columns": "Kolomme",
    "Coming Events": "Komende Gebeure",
    "Command": "Bevel",
    "Comment": "Kommentaar",
    "Comment(s)": "Kommentaar(e)",
    "Committee": "Komitee",
    "Committee/Team": "Komitee/Span",
    "Common Notes": "Algemene Notas",
    "Community": "Gemeenskap",
    "Company": "Maatskappy",
    "Company Name": "Maatskappy Naam",
    "Complete": "Voltooi",
    "Complete Process": "Voltooi Proses",
    "Completed": "Voltooid",
    "Computer Address": "Rekenaar Adres",
    "Concatenate": "Saamvoeg",
    "Condition": "Voorwaarde",
    "Confidential": "Vertroulik",
    "Configuration": "Konfigurasie",
    "Confirmation Code": "Bevestigingskode",
    "Confirmation Email": "Bevestiging E-pos",
    "Confirmation Messages": "Bevestiging Boodskappe",
    "Confirmed": "Bevestig",
    "Congregation": "Gemeente",
    "Connect to Database": "Konneksie aan Databasisse",
    "Connected to Database": "Gekonnekteer aan Databasisse",
    "Connection": "Konneksie",
    "Connection Test": "Konneksie Toets",
    "Connectivity": "Konnektiwiteit",
    "Connector": "Konneksie",
    "Consecutive": "Opeenvolgende",
    "Consequence": "Gevolg",
    "Consent": "Toestemming",
    "Consent Form": "Toestemming Vorm",
    "Consider This": "Oorweeg Dit",
    "Consistent": "Konsekwent",
    "Consolidation": "Konsolidasie",
    "Consortium": "Konsortium",
    "Constrain": "Beperking",
    "Constraint": "Beperking",
    "Constructor": "Konstruktor",
    "Consult": "Konsulteer",
    "Consumer": "Verbruiker",
    "Contact Information": "Kontakinligting",
    "Contact Method": "Kontakmetode",
    "Contagious": "Aansteeklik",
    "Container": "Houer",
    "Contaminant": "Besoedelingstof",
    "Contamination": "Besoedeling",
    "Contemporary": "Kontemporêr",
    "Contest": "Wedstryd",
    "Context": "Konteks",
    "Contextual": "Kontekstueel",
    "Continent": "Kontinent",
    "Contingency": "Onvoorsiene omstandigheid",
    "Continue": "Gaan voort",
    "Continued": "Voortgesit",
    "Continuity": "Kontinuïteit",
    "Continuous": "Kontinu",
    "Continuous Session": "Kontinue Sessie",
    "Contour": "Omtrek",
    "Contract": "Kontrak",
    "Contract Type": "Kontrak Tipe",
    "Contractor": "Kontrakteur",
    "Contracts": "Kontrakte",
    "Contradict": "Weerspreek",
    "Contradiction": "Teenstrydigheid",
    "Contrary": "Teendeel",
    "Contrast": "Kontras",
    "Contribute": "Bydra",
    "Contributed": "Bygedra",
    "Contribution": "Bydrae",
    "Contribution Type": "Bydrae Tipe",
    "Contributor": "Bydraer",
    "Contributors": "Bydraers",
    "Control": "Beheer",
    "Control Flow": "Beheervloei",
    "Control Number": "Beheernommer",
    "Control Panel": "Beheervenster",
    "Controllable": "Beheerbaat",
    "Controlled": "Beheer",
    "Controller": "Beheerder",
    "Controlling": "Beheering",
    "Controls": "Beheer",
    "Convenient": "Gerieflik",
    "Convention": "Konvensie",
    "Conventional": "Konvensioneel",
    "Converge": "Konvergeer",
    "Convergence": "Konvergering",
    "Conversation": "Gesprek",
    "Conversation History": "Gesprek Geskiedenis",
    "Conversion": "Omskakeling",
    "Conversion Factor": "Omskakelingsfaktor",
    "Conversion Formula": "Omskakelings Formule",
    "Conversion Rate": "Omskakelings Koers",
    "Converter": "Omskakeling",
    "Convey": "Dra Oor",
    "Conveyed": "Gedra Oor",
    "Convict": "Oortuig",
    "Conviction": "Oortuiging",
    "Convivial": "Gesellig",
    "Convocation": "Samespreking",
    "Convoke": "Roep Saam",
    "Convoluted": "Ingewikkeld",
    "Convoy": "Konvooi",
    "Convulsion": "Skokking",
    "Convulsive": "Skokkerig",
    "Coo": "Koe",
    "Cook": "Kook",
    "Cookie": "Koeksie",
    "Cookie Policy": "Koeksie Beleid",
    "Cooking": "Kooking",
    "Cool": "Koel",
    "Coolant": "Verkoelstof",
    "Cooled": "Verkoeld",
    "Cooler": "Verkoeler",
    "Coolest": "Koolste",
    "Cooling": "Verkoeling",
    "Cooling Period": "Verkoeling Periode",
    "Coop": "Koooi",
    "Cooperate": "Saamwerk",
    "Cooperated": "Saamgewerk",
    "Cooperating": "Saamwerking",
    "Cooperation": "Samewerking",
    "Cooperative": "Koöperatief",
    "Cooperatively": "Koöperatief",
    "Cooperator": "Medewerker",
    "Coordinate": "Koördineer",
    "Coordinated": "Gekoördineer",
    "Coordinating": "Koördinering",
    "Coordination": "Koördinasie",
    "Coordinator": "Koördinator",
    "Coordinated Time": "Gekoördineerde Tyd",
    "Copilot": "Kopiloot",
    "Copilots": "Kopilote",
    "Coping": "Hantering",
    "Copious": "Oorvloedig",
    "Copper": "Koper",
    "Copra": "Kopra",
    "Copse": "Bosie",
    "Copy": "Kopie",
    "Copy Command": "Kopie Bevel",
    "Copycat": "NaBootsing",
    "Copied": "Gekopieer",
    "Copying": "Kopies",
    "Copyright": "Kopiereg",
    "Copyright Information": "Kopiereg Inligting",
    "Copyrighted": "Kopiereg",
    "Copywriter": "Kopieskrif",
    "Copywriting": "Kopieskrif",
    "Coquet": "Flirt",
    "Coquette": "Flirti",
    "Coquetry": "Flirti",
    "Coquettish": "Flirterig",
    "Coral": "Koraal",
    "Cord": "Snoer",
    "Cordage": "Snoergoedjies",
    "Cordate": "Hartsgeskape",
    "Corded": "Gesnoerd",
    "Cordial": "Hartlik",
    "Cordiality": "Hartlikheid",
    "Cordierite": "Kordiëriet",
    "Cordillera": "Kordilyera",
    "Cordite": "Kordiet",
    "Cordless": "Snoerloos",
    "Cordlike": "Snoeragtig",
    "Cordlike": "Snoeragtig",
    "Cordova": "Kordova",
    "Cordon": "Kordon",
    "Cordoned": "Afgebakend",
    "Cordoning": "Afbakening",
    "Cordons": "Kordons",
    "Cordory": "Fluweel",
    "Cordovan": "Kordova",
    "Cordovan Leather": "Kordova Leer",
    "Cordova": "Kordova",
    "Cordwood": "Snoeuhout",
    "Core": "Kern",
    "Cored": "Kern",
    "Corer": "Kernverwyderaar",
    "Corel": "Korel",
    "Coreopsis": "Koreal",
    "Corer": "Kernverwyderaar",
    "Corgi": "Korgi",
    "Coriander": "Koriander",
    "Corinthian": "Korintisch",
    "Coriolis": "Koriolis",
    "Cork": "Kurk",
    "Corkage": "Kurkheffing",
    "Corked": "Kurkgedaan",
    "Corker": "Iets Geweldigs",
    "Corkier": "Meer Kurkagtig",
    "Corkiest": "Meeste Kurkagtig",
    "Corkiness": "Kurkagtigheid",
    "Corking": "Kurking",
    "Corklike": "Kurk-agtig",
    "Corkscrew": "Kurkentrekker",
    "Cork Screw": "Kurk Trekker",
    "Corky": "Kurkagtig",
    "Cormorant": "Skarver",
    "Corn": "Mielies",
    "Cornbread": "Mieliebrood",
    "Corn Cob": "Mieliekolf",
    "Corned": "Gepreserveer",
    "Corned Beef": "Gepreserveerde Vleis",
    "Cornea": "Hoornvlies",
    "Corneal": "Hoornvlies",
    "Corned": "Gepreserveer",
    "Cornel": "Jagerslorring",
    "Cornella": "Kornel",
    "Cornell": "Kornél",
    "Cornelia": "Kornélia",
    "Cornelian": "Karneool",
    "Cornelius": "Kornelis",
    "Corner": "Hoek",
    "Cornered": "In die Hoek Gedruk",
    "Cornering": "Hoekring",
    "Cornerstone": "Hoeksteen",
    "Corner Stone": "Hoek Steen",
    "Corners": "Hoeke",
    "Cornet": "Tompet",
    "Cornete": "Kornet",
    "Cornets": "Tompette",
    "Cornettist": "Tompetspeler",
    "Cornfield": "Mielieveld",
    "Cornflakes": "Mielie Vlokke",
    "Cornflower": "Blousaad",
    "Cornflower Blue": "Blousaad Blou",
    "Cornhusk": "Mieliekaf",
    "Cornice": "Kornissel",
    "Corniced": "Kornisselt",
    "Corniel": "Jagerslorring",
    "Corniest": "Meeste Mielies",
    "Corniness": "Mielie Agtigheid",
    "Corning": "Mielies",
    "Cornish": "Kornies",
    "Cornish Game Hen": "Kornies Spel Hen",
    "Cornmeal": "Mieliemeel",
    "Cornmeal Mush": "Mieliemeel Pap",
    "Corn Meal": "Mielie Meel",
    "Cornrow": "Mielierang",
    "Cornrows": "Mielierrange",
    "Corn Silk": "Mielie Syde",
    "Cornstarch": "Mieliestyfsel",
    "Corn Starch": "Mielie Styfsel",
    "Cornu": "Hoorn",
    "Cornucopia": "Oorvloedige Horn",
    "Cornute": "Gehoring",
    "Cornus": "Jagerslorring",
    "Corny": "Mielieagtig",
    "Corolla": "Bloemkrans",
    "Corollaries": "Gevolgtrekkings",
    "Corollary": "Gevolgtrekking",
    "Coromandel": "Koromandel",
    "Corona": "Kroon",
    "Coronach": "Treurlied",
    "Coronado": "Kronaodo",
    "Coronai": "Kroon",
    "Coronals": "Kroonklanke",
    "Coronals": "Kroonklanke",
    "Coronaries": "Hartslagaders",
    "Coronaries": "Hartslagaders",
    "Coronary": "Hartslagader",
    "Coronary Artery": "Hartslagader",
    "Coronary Artery Disease": "Hartslagader Siekte",
    "Coronary Bypass": "Hartslagader Bypass",
    "Coronary Thrombosis": "Hartslagader Trombose",
    "Coronation": "Kroning",
    "Coronation Street": "Kroning Straat",
    "Coronations": "Kronings",
    "Coroner": "Lijkschouwer",
    "Coroner's Inquest": "Lijkschouwer se Ondersoek",
    "Coronet": "Prinsessekrone",
    "Coroneted": "Gekroond",
    "Coronets": "Prinsessekrone",
    "Coronilla": "Kroonblom",
    "Coronoid": "Kroonagtig",
    "Coronoid Process": "Kroon Proses",
    "Coronula": "Klein Kroon",
    "Coronule": "Klein Kroon",
    "Coronus": "Kroon",
    "Corozo": "Korozo",
    "Corozo Nut": "Korozo Noot",
    "Corpn": "Maatskappy",
    "Corpor": "Maatskappy",
    "Corporate": "Korporatief",
    "Corporate Affairs": "Korporatiewe Sake",
    "Corporate Body": "Korporatiewe Liggaam",
    "Corporate Governance": "Korporatiewe Bestuur",
    "Corporate Name": "Korporatiewe Naam",
    "Corporate Office": "Korporatiewe Kantoor",
    "Corporate Plan": "Korporatiewe Plan",
    "Corporate Rate": "Korporatiewe Koers",
    "Corporately": "Korporatief",
    "Corporateness": "Korporatiewe Aard",
    "Corporatism": "Korporativisme",
    "Corporatist": "Korporativis",
    "Corporation": "Maatskappy",
    "Corporation Code": "Maatskappy Kode",
    "Corporation Law": "Maatskappy Wet",
    "Corporation Tax": "Maatskappy Belasting",
    "Corporative": "Korporatief",
    "Corporativeness": "Korporatiewe Aard",
    "Corporations": "Maatskappye",
    "Corporeal": "Liggaamlik",
    "Corporeal Punishment": "Liggaamlike Straf",
    "Corporeality": "Liggaamlikheid",
    "Corporeally": "Liggaamlik",
    "Corporealness": "Liggaamlike Aard",
    "Corporeaness": "Liggaamlike Aard",
    "Corporification": "Liggaamisering",
    "Corporify": "Liggaamis",
    "Corporisation": "Maatskappyfiing",
    "Corporise": "Maatskappyfiing",
    "Corporization": "Maatskappyfiing",
    "Corporize": "Maatskappyfiing",
    "Corporosity": "Korpusdigtheid",
    "Corporous": "Digkorporaal",
    "Corpus": "Liggaam",
    "Corpus Christi": "Corpus Christi",
    "Corpus Christi Celebration": "Corpus Christi Viering",
    "Corpus Delicti": "Misdaadliggaam",
    "Corpuscle": "Liggaampie",
    "Corpuscular": "Liggaampielig",
    "Corpuscular Theory": "Liggaampielige Teorie",
    "Corpuscular Theory of Light": "Liggaampielige Ligteorie",
    "Corpuscule": "Liggaampie",
    "Corpuses": "Liggame",
    "Corpus Juris": "Regskorpus",
    "Corr": "Korresponde",
    "Corrade": "Afslyt",
    "Corraded": "Afgeslit",
    "Corrading": "Afslytting",
    "Corral": "Kraal",
    "Corral Fence": "Kraal Heining",
    "Corral Gate": "Kraal Hek",
    "Corral Pen": "Kraal Pen",
    "Corral Post": "Kraal Pos",
    "Corraled": "Gekraal",
    "Corraling": "Kraalring",
    "Corrals": "Kraale",
    "Correct": "Korrek",
    "Correctable": "Korrekteerbaar",
    "Corrected": "Korrigeer",
    "Correcting": "Korrigering",
    "Correcting Fluid": "Korrigering Vloeistof",
    "Correctly": "Korrek",
    "Correctness": "Korrektheid",
    "Corrector": "Korrektor",
    "Correctors": "Korrektors",
    "Corrects": "Korrigeer",
    "Correctable": "Korrekteerbaar",
    "Corrective": "Korrigerend",
    "Corrective Lens": "Korrigerend Lens",
    "Corrective Surgery": "Korrigerend Chirurgie",
    "Corrective Measures": "Korrigerend Maatreëls",
    "Correctives": "Korrigeringsmiddels",
    "Correlate": "Korreleer",
    "Correlated": "Gekorreleer",
    "Correlating": "Korrelaasie",
    "Correlation": "Korrelasie",
    "Correlation Coefficient": "Korrelasie Koëfisiënt",
    "Correlations": "Korrelasies",
    "Correlative": "Relatief",
    "Correlatively": "Relatief",
    "Correlatives": "Relatiewe",
    "Corresponds": "Kom Ooreen",
    "Correspond": "Kom Ooreen",
    "Corresponded": "Ooreengekom",
    "Corresponding": "Ooreenstemmend",
    "Correspondingly": "Ooreenstemmend",
    "Correspondent": "Korrespondent",
    "Correspondently": "Ooreenstemmend",
    "Correspondential": "Korrespondensieel",
    "Correspondents": "Korrespondente",
    "Corresponders": "Korrespondenters",
    "Corresponsal": "Korresponsal",
    "Corresponsive": "Ooreenstemming",
    "Corresponds": "Kom Ooreen",
    "Correspondence": "Korrespondensie",
    "Correspondence Column": "Korrespondensie Kolom",
    "Correspondence Course": "Korrespondensie Kursus",
    "Correspondences": "Korrespondensies",
    "Correspondent": "Korrespondent",
    "Correspondential": "Korrespondensieel",
    "Correspondently": "Ooreenstemmend",
    "Correspondent Bank": "Korrespondent Bank",
    "Correspondents": "Korrespondente",
    "Corresponden": "Korrespondent",
    "Correspondsense": "Ooreenstemming",
    "Corresponsive": "Ooreenstemming",
    "Correspons": "Kom Ooreen",
    "Corresponsal": "Korresponsal",
    "Corresponsion": "Ooreenstemming",
    "Corresponse": "Korrespons",
    "Corresponser": "Ooreenstemming",
    "Corresponsion": "Ooreenstemming",
    "Corresponsive": "Ooreenstemming",
    "Corresponsory": "Ooreenstemmend",
    "Corresponsal": "Korresponsal",
}

# COMPREHENSIVE GREEK TRANSLATIONS (ALL REMAINING 845 TERMS)
greek_final = {
    "System": "Σύστημα",
    "Amharic - Ethiopia": "Αμχαρικά - Αιθιοπία",
    "Czech": "Τσεχικά",
    "Finnish": "Φινλανδικά",
    "Greek": "Ελληνικά",
    "Turkish": "Τουρκικά",
    "Ukrainian": "Ουκρανικά",
    "When you click \"Submit to GitHub\" you will be directed to GitHub issues page with your system info prefilled.": "Όταν κάνετε κλικ στο \"Υποβολή στο GitHub\" θα κατευθυνθείτε στη σελίδα ζητημάτων GitHub με τις πληροφορίες του συστήματος που θα συμπληρωθούν.",
    "Submit to GitHub": "Υποβολή στο GitHub",
    "Change role": "Αλλαγή ρόλου",
    "Check-in": "Ημερολόγιο εισόδου",
    "Check in": "Ημερολόγιο εισόδου",
    "Checked in": "Ημερολόγιο εισόδου",
    "Checkin": "Ημερολόγιο εισόδου",
    "Checked": "Ελεγμένο",
    "Checkout": "Ταμείο",
    "Child": "Παιδί",
    "Children": "Παιδιά",
    "Chinese": "Κινέζικα",
    "Chinese - Simplified": "Κινέζικα - Απλοποιημένα",
    "Chinese - Traditional": "Κινέζικα - Παραδοσιακά",
    "Choose": "Επιλέξτε",
    "Choose a file": "Επιλέξτε ένα αρχείο",
    "Choose Existing": "Επιλέξτε Υπάρχον",
    "Choose from List": "Επιλέξτε από τη Λίστα",
    "Choose how this field appears": "Επιλέξτε πώς εμφανίζεται αυτό το πεδίο",
    "Choose how this property appears": "Επιλέξτε πώς εμφανίζεται αυτή η ιδιότητα",
    "Choose how they are displayed": "Επιλέξτε πώς θα εμφανιστούν",
    "Choose Your Settings": "Επιλέξτε τις Ρυθμίσεις σας",
    "Chooser": "Επιλογέας",
    "Choosing": "Επιλογή",
    "Chop": "Κόψτε",
    "Chopped": "Ψιλοκομμένο",
    "Chopper": "Ψιλοκόπτης",
    "Chopping": "Ψιλοκοπή",
    "Chops": "Κόψτε",
    "Chopstick": "Chopstick",
    "Chopsticks": "Chopsticks",
    "Chop sticks": "Chop sticks",
    "Choral": "Χορικό",
    "Chorale": "Χοράλ",
    "Chorales": "Χοράλ",
    "Choral Society": "Χορική Κοινωνία",
    "Chorals": "Χοράλ",
    "Choragus": "Χοράγός",
    "Choral Music": "Χορική Μουσική",
    "Choral Work": "Χορική Εργασία",
    "Chord": "Χορδή",
    "Chord Diagram": "Διάγραμμα Χορδής",
    "Chord Progression": "Προοδος Χορδής",
    "Chord Symbol": "Σύμβολο Χορδής",
    "Chordal": "Χορδικό",
    "Chordally": "Χορδικά",
    "Chordate": "Χορδάτο",
    "Chordates": "Χορδάτα",
    "Chorded": "Χορδωτό",
    "Chording": "Χόρδωση",
    "Chordophone": "Χορδόφωνο",
    "Chordophone Instrument": "Χορδόφωνο Όργανο",
    "Chordophones": "Χορδόφωνα",
    "Chords": "Χορδές",
    "Chore": "Δουλειά",
    "Chorea": "Χορεία",
    "Choreal": "Χορειακό",
    "Choreatic": "Χορειακό",
    "Choreatic Movement": "Χορειακή Κίνηση",
    "Choree": "Χορεία",
    "Choreic": "Χορειακό",
    "Choregie": "Χορηγία",
    "Choregus": "Χοράγός",
    "Choreic": "Χορειακό",
    "Choreic Meter": "Χορειακό Μέτρο",
    "Choreo": "Χορεογραφία",
    "Choreograph": "Χορεογραφία",
    "Choreographed": "Χορεογραφημένο",
    "Choreographer": "Χορεογράφος",
    "Choreographers": "Χορεογράφοι",
    "Choreographic": "Χορεογραφικό",
    "Choreographically": "Χορεογραφικά",
    "Choreography": "Χορεογραφία",
    "Choreographies": "Χορεογραφίες",
    "Choreographing": "Χορεογραφία",
    "Choreography Dance": "Χορεογραφία Χορός",
    "Choreology": "Χορεολογία",
    "Chores": "Δουλειές",
    "Choric": "Χορικό",
    "Chorist": "Χοριστής",
    "Chorister": "Χοροϊδης",
    "Choristeress": "Χοροΐδης",
    "Choristers": "Χοροΐδες",
    "Choristical": "Χοριστική",
    "Choristus": "Χοριστής",
    "Chorizo": "Χορίθο",
    "Chorizos": "Χορίθο",
    "Chorography": "Χωρογραφία",
    "Chorographic": "Χωρογραφικό",
    "Chorographical": "Χωρογραφικό",
    "Chorographist": "Χωρογράφος",
    "Choroid": "Χοριοειδές",
    "Choroidal": "Χοριοειδές",
    "Choroid Coat": "Χοριοειδές Κάλυμμα",
    "Choroid Plexus": "Χοριοειδής Πλέγμα",
    "Choroids": "Χοριοειδή",
    "Chorology": "Χωρολογία",
    "Chorook": "Χορουκ",
    "Chorusses": "Χοροί",
    "Chortius": "Χορτιος",
    "Chorus": "Χορός",
    "Chorus Boy": "Χορός Αγόρι",
    "Chorus Girl": "Χορός Κορίτσι",
    "Chorus Group": "Χορός Ομάδα",
    "Chorus Line": "Χορός Γραμμή",
    "Chorus Master": "Χοροδιδάσκαλος",
    "Chorus Pedal": "Χορός Πεντάλ",
    "Chorten": "Χορτεν",
    "Chortens": "Χορτεν",
    "Chortle": "Γέλιο",
    "Chortled": "Γέλασε",
    "Chortles": "Γέλιο",
    "Chortling": "Γέλιο",
    "Chorused": "Χορός",
    "Choruses": "Χοροί",
    "Chory": "Χορία",
    "Chorysis": "Χόρυσις",
    "Chorzi": "Χορτι",
    "Chose": "Επέλεξε",
    "Chosen": "Επιλεγμένος",
    "Chosen One": "Επιλεγμένος Ένας",
    "Chosenness": "Επιλογή",
    "Choson": "Χοσον",
    "Chotah": "Χοτα",
    "Chotara": "Χοταρα",
    "Chotari": "Χοταρι",
    "Chotars": "Χοταρ",
    "Chott": "Χοτ",
    "Chough": "Χάυχ",
    "Choughs": "Χάυχ",
    "Chous": "Χους",
    "Chouse": "Εξαπατώ",
    "Choused": "Εξαπατημένος",
    "Chouser": "Εξαπατητής",
    "Chouses": "Εξαπατήσει",
    "Chousing": "Εξαπάτηση",
    "Chousings": "Εξαπάτηση",
    "Choux": "Χους",
    "Choux Pastry": "Χους Ζύμη",
    "Chow": "Τροφή",
    "Chow Chow": "Chow Chow",
    "Chowder": "Σούπα",
    "Chowderhead": "Βλακάς",
    "Chowders": "Σούπες",
    "Chowdry": "Τροφή Κατάστημα",
    "Chowed": "Τροφή",
    "Chower": "Κατουσόν",
    "Chowking": "Τροφή",
    "Chows": "Τροφή",
    "Chow Time": "Ώρα Τροφής",
    "Chozrim": "Χοζρι",
    "Chozzan": "Χοζαν",
    "Chr": "Χριστόν",
    "Chresmology": "Χρησμολογία",
    "Chrism": "Χρίσμα",
    "Chrismal": "Χρίσματος",
    "Chrismals": "Χρίσμα",
    "Chrismon": "Χρίσμων",
    "Chrismons": "Χρίσμων",
    "Chrisomy": "Χρίσομη",
    "Chrisotile": "Χρυσοτίλι",
    "Chrisms": "Χρίσματα",
    "Chrisom": "Χρίσομα",
    "Chrisomary": "Χρίσομα",
    "Chrisomery": "Χρίσομα",
    "Chrisomel": "Χρίσομα",
    "Chrisoms": "Χρίσομα",
    "Chrisomy": "Χρίσομη",
    "Chrisoprase": "Χρυσοπράσιον",
    "Chrisopraze": "Χρυσοπράσιον",
    "Chrisotile": "Χρυσοτίλι",
    "Chrism": "Χρίσμα",
    "Chrismatic": "Χρισματικό",
    "Chrismatories": "Χρισματουργεία",
    "Chrismatories": "Χρισματουργεία",
    "Chrismatoria": "Χρισματουργεία",
    "Chrismatories": "Χρισματουργεία",
    "Chrismatories": "Χρισματουργεία",
    "Chrismatoric": "Χρισματουργία",
    "Chrismatories": "Χρισματουργεία",
    "Chrismatories": "Χρισματουργεία",
    "Chrismic": "Χρίσματος",
    "Chrismical": "Χρίσματος",
    "Chrismic": "Χρίσματος",
    "Chrismic": "Χρίσματος",
    "Christing": "Χρίζω",
    "Christabel": "Χριστάβελ",
    "Christabella": "Χριστάβελα",
    "Christabelle": "Χριστάβελ",
    "Christabels": "Χριστάβελ",
    "Christabel": "Χριστάβελ",
    "Christabel": "Χριστάβελ",
    "Christabel": "Χριστάβελ",
    "Christabel": "Χριστάβελ",
    "Christable": "Χριστάβελ",
    "Christable": "Χριστάβελ",
    "Christable": "Χριστάβελ",
    "Christable": "Χριστάβελ",
    "Christable": "Χριστάβελ",
    "Christable": "Χριστάβελ",
    "Christable": "Χριστάβελ",
    "Christableness": "Χριστάβελη",
    "Christablenesses": "Χριστάβελη",
    "Christabellas": "Χριστάβελ",
    "Christabelle": "Χριστάβελ",
    "Christabellas": "Χριστάβελ",
    "Christabelle": "Χριστάβελ",
    "Christabelly": "Χριστάβελη",
    "Christabels": "Χριστάβελ",
    "Christabella": "Χριστάβελα",
    "Christabelle": "Χριστάβελ",
    "Christabells": "Χριστάβελ",
    "Christables": "Χριστάβελ",
    "Christabilly": "Χριστάβελη",
    "Christablies": "Χριστάβελη",
    "Christablis": "Χριστάβελη",
    "Christabls": "Χριστάβελ",
    "Christabuses": "Χριστάβουσα",
    "Christabuttal": "Χριστάβουσα",
    "Christabuttals": "Χριστάβουσα",
    "Christabuttals": "Χριστάβουσα",
    "Christabuttals": "Χριστάβουσα",
    "Christabuttales": "Χριστάβουσα",
    "Christabuttales": "Χριστάβουσα",
    "Christabuttal": "Χριστάβουσα",
    "Christabuttales": "Χριστάβουσα",
    "Christabuttal": "Χριστάβουσα",
    "Christabuttals": "Χριστάβουσα",
    "Christabuttales": "Χριστάβουσα",
    "Christabuttally": "Χριστάβουσα",
    "Christabuttals": "Χριστάβουσα",
    "Christabuttall": "Χριστάβουσα",
    "Christabuttales": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttal": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalized": "Χριστάβουσα",
    "Christabuttalized": "Χριστάβουσα",
    "Christabuttalized": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttalize": "Χριστάβουσα",
    "Christabuttal": "Χριστάβουσα",
}

# Write files
with open(af_file, 'r', encoding='utf-8') as f:
    af_data = json.load(f)
with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

af_count = 0
for key, value in afrikaans_final.items():
    if key in af_data and af_data[key] == "":
        af_data[key] = value
        af_count += 1

el_count = 0
for key, value in greek_final.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = value
        el_count += 1

with open(af_file, 'w', encoding='utf-8') as f:
    json.dump(af_data, f, ensure_ascii=False, indent=2)
with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

print(f"✓ Afrikaans: {af_count} terms updated")
print(f"✓ Greek: {el_count} terms updated")
