#!/usr/bin/env python3
"""Final Greek push - Target 50%+ with actual key translations"""

import json

# High-value Greek translations matched to actual remaining keys
el_final_batch = {
    "Are you sure you want to delete": "Είστε σίγουρος ότι θέλετε να διαγράψετε",
    "Are you sure you want to delete all orphaned files?": "Είστε σίγουρος ότι θέλετε να διαγράψετε όλα τα ορφανά αρχεία;",
    "Are you sure you want to delete this check-in record?": "Είστε σίγουρος ότι θέλετε να διαγράψετε αυτό το αρχείο εισόδου;",
    "Assign Opportunities": "Εκχώρηση Ευκαιριών",
    "Assign Property": "Εκχώρηση Περιουσίας",
    "Attendance Count Categories": "Κατηγορίες Μέτρησης Παρουσίας",
    "Attendance Notes": "Σημειώσεις Παρουσίας",
    "Aug": "Αυγ",
    "Back to Debug Info": "Επιστροφή σε Πληροφορίες Αποσφαλμάτωσης",
    "Back to Deposits": "Επιστροφή σε Καταθέσεις",
    "Back to Families": "Επιστροφή σε Οικογένειες",
    "Back to Group List": "Επιστροφή σε Λίστα Ομάδων",
    "Back to Login": "Επιστροφή σε Σύνδεση",
    "Back to login": "Επιστροφή σε σύνδεση",
    "Backup Best Practices": "Βέλτιστες Πρακτικές Αντιγράφου",
    "Backup Skipped": "Αντίγραφο Παραλείφθηκε",
    "Backup Status": "Κατάσταση Αντιγράφου",
    "Backup Type": "Τύπος Αντιγράφου",
    "Backup complete! Click below to download.": "Αντίγραφο ολοκληρώθηκε! Κάντε κλικ παρακάτω για λήψη.",
    "Backup completed successfully!": "Το αντίγραφο ολοκληρώθηκε με επιτυχία!",
    "Backup downloaded. Server copy removed.": "Αντίγραφο λήφθηκε. Το αντίγραφο διακομιστή αφαιρέθηκε.",
    "Backup failed. Please try again.": "Το αντίγραφο απέτυχε. Παρακαλώ δοκιμάστε ξανά.",
    "Backup generated and copied to remote server": "Αντίγραφο δημιουργήθηκε και αντιγράφηκε σε απομακρυσμένο διακομιστή",
    "Backup in progress, please wait...": "Αντίγραφο σε εξέλιξη, παρακαλώ περιμένετε...",
    "Backup to External Storage": "Αντίγραφο σε Εξωτερική Αποθήκευση",
    "Base URL": "Βάση URL",
    "Base URL configuration is invalid. Please check your Config.php file.": "Η διαμόρφωση βάσης URL είναι μη έγκυρη. Παρακαλώ ελέγξτε το αρχείο Config.php σας.",
    "Base URL is not configured in Config.php": "Η βάση URL δεν έχει ρυθμιστεί στο Config.php",
    "Base URL is required": "Η βάση URL απαιτείται",
    "Birth & Family": "Γέννηση & Οικογένεια",
    "CSV export is restricted to administrators.": "Η εξαγωγή CSV περιορίζεται στους διαχειριστές.",
    "CSV export permission": "Άδεια εξαγωγής CSV",
    "Cart": "Καλάθι",
    "Cart emptied successfully": "Το καλάθι αδειάστηκε με επιτυχία",
    "Cart emptied to group successfully": "Το καλάθι αδειάστηκε σε ομάδα με επιτυχία",
    "Change this in System Settings.": "Αλλάξτε αυτό στις Ρυθμίσεις Συστήματος.",
    "Changes not saved! Please correct and try again!": "Οι αλλαγές δεν αποθηκεύτηκαν! Παρακαλώ διορθώστε και δοκιμάστε ξανά!",
    "Check GitHub for the latest release information": "Ελέγξτε το GitHub για τις τελευταίες πληροφορίες έκδοσης",
    "Check In": "Έλεγχος Εισόδου",
    "Check In Person": "Έλεγχος Προσώπου Εισόδου",
    "Checks": "Έλεγχοι",
    "Choose a property...": "Επιλέξτε μια περιουσία...",
    "Choose an event...": "Επιλέξτε ένα εκδήλωση...",
    "Choose opportunities...": "Επιλέξτε ευκαιρίες...",
    "Class": "Τάξη",
    "Classes": "Τάξεις",
    "Click to edit": "Κάντε κλικ για επεξεργασία",
    "Click to select": "Κάντε κλικ για επιλογή",
    "Close": "Κλείσιμο",
    "Closed": "Κλειστό",
    "Collection": "Συλλογή",
    "Collections": "Συλλογές",
    "Communication": "Επικοινωνία",
    "Communications": "Επικοινωνίες",
    "Company": "Εταιρεία",
    "Companies": "Εταιρείες",
    "Completed": "Ολοκληρώθηκε",
    "Confirmation": "Επιβεβαίωση",
    "Connect": "Σύνδεση",
    "Connected": "Συνδεδεμένο",
    "Connection": "Σύνδεση",
    "Connections": "Συνδέσεις",
    "Contact": "Επαφή",
    "Contact Information": "Πληροφορίες Επαφής",
    "Contact Method": "Μέθοδος Επαφής",
    "Contact Preference": "Προτίμηση Επαφής",
    "Contacts": "Επαφές",
    "Container": "Κοντέινερ",
    "Containers": "Κοντέινερ",
    "Content": "Περιεχόμενο",
    "Content Type": "Τύπος Περιεχομένου",
    "Context": "Περιεχόμενο",
    "Copy": "Αντιγραφή",
    "Copied": "Αντιγράφηκε",
    "Copying": "Αντιγραφή",
    "Core": "Ινδία",
    "Create": "Δημιουργία",
    "Create New": "Δημιουργία Νέας",
    "Create new Family": "Δημιουργία Νέας Οικογένειας",
    "Create new Group": "Δημιουργία Νέας Ομάδας",
    "Create new Person": "Δημιουργία Νέου Προσώπου",
    "Created": "Δημιουργήθηκε",
    "Created by": "Δημιουργήθηκε από",
    "Created date": "Ημερομηνία δημιουργίας",
    "Creating": "Δημιουργία",
    "Credit Card": "Πιστωτική Κάρτα",
    "Credit Card Information": "Πληροφορίες Πιστωτικής Κάρτας",
    "Credit Card Number": "Αριθμός Πιστωτικής Κάρτας",
    "Criteria": "Κριτήρια",
    "Critical": "Κρίσιμο",
    "CSS": "CSS",
    "CSV": "CSV",
    "CSV File": "Αρχείο CSV",
    "CSV Format": "Μορφή CSV",
    "CSV Import": "Εισαγωγή CSV",
    "Current": "Τρέχον",
    "Current Page": "Τρέχουσα Σελίδα",
    "Current Status": "Τρέχουσα Κατάσταση",
    "Current User": "Τρέχων Χρήστης",
    "Currently": "Προς το παρόν",
    "Custom": "Προσαρμοσμένο",
    "Custom Field": "Προσαρμοσμένο Πεδίο",
    "Custom Fields": "Προσαρμοσμένα Πεδία",
    "Custom Report": "Προσαρμοσμένη Αναφορά",
    "Customer": "Πελάτης",
    "Customer ID": "Αναγνωριστικό Πελάτη",
    "Customer Name": "Όνομα Πελάτη",
    "Customer Service": "Υπηρεσία Πελάτη",
    "Customers": "Πελάτες",
    "Customize": "Προσαρμογή",
    "Customized": "Προσαρμοσμένο",
    "Customizing": "Προσαρμογή",
    "Cut": "Αποκοπή",
    "Date": "Ημερομηνία",
    "Date Created": "Ημερομηνία Δημιουργίας",
    "Date Format": "Μορφή Ημερομηνίας",
    "Date Range": "Εύρος Ημερομηνίας",
    "Date Time": "Ημερομηνία Ώρα",
    "Dated": "Χρονολογημένο",
    "Dates": "Ημερομηνίες",
    "Day": "Ημέρα",
    "Days": "Ημέρες",
    "Deactivate": "Απενεργοποίηση",
    "Deactivated": "Απενεργοποιημένο",
    "Deactivating": "Απενεργοποίηση",
    "Dear": "Αγαπητέ",
    "Dec": "Δεκ",
    "Decimal": "Δεκαδικό",
    "Decimals": "Δεκαδικά",
    "Decision": "Απόφαση",
    "Decisions": "Αποφάσεις",
    "Default": "Προεπιλογή",
    "Default Contact Method": "Προεπιλογή Μέθοδος Επαφής",
    "Default Font": "Προεπιλογή Γραμματοσειράς",
    "Default Language": "Προεπιλογή Γλώσσα",
    "Default Page": "Προεπιλογή Σελίδα",
    "Default Timezone": "Προεπιλογή Ζώνη Ώρας",
    "Default Value": "Προεπιλογή Τιμή",
    "Defaults": "Προεπιλογές",
    "Defined": "Ορισμένο",
    "Definition": "Ορισμό",
    "Definitions": "Ορισμοί",
}

# Apply to Greek file
el_file = 'locale/missing-terms/el.json'

with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

el_updated = 0
for key, translation in el_final_batch.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = translation
        el_updated += 1

with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

# Stats
el_empty = len([v for v in el_data.values() if v == ""])
el_total = len(el_data)
el_done = el_total - el_empty

print(f"\n✓ Greek: {el_updated} terms → {el_done}/{el_total} ({100*el_done/el_total:.1f}%)")
print(f"Remaining: EL {el_empty}")
