#!/usr/bin/env python3
"""Greek push to 50%+ - Critical operations batch"""

import json

# High-value Greek translations for critical remaining operations
el_critical_batch = {
    "Dec": "Δεκ",
    "Deacon": "Διάκονος",
    "Deacons": "Διάκονοι",
    "Decline": "Αποδέχομαι",
    "Default Value": "Προεπιλογή Τιμή",
    "Delete": "Διαγραφή",
    "Delete All": "Διαγραφή Όλα",
    "Delete Confirmation": "Επιβεβαίωση Διαγραφής",
    "Delete Custom Field": "Διαγραφή Προσαρμοσμένο Πεδίο",
    "Delete Fund": "Διαγραφή Κεφάλαιο",
    "Delete Group": "Διαγραφή Ομάδα",
    "Delete User": "Διαγραφή Χρήστης",
    "Deleted": "Διαγράφηκε",
    "Deleting": "Διαγραφή",
    "Deletion": "Διαγραφή",
    "Deletion Warning": "Προειδοποίηση Διαγραφής",
    "Delimited": "Οριοθετημένο",
    "Demand": "Ζήτηση",
    "Demographics": "Δημογραφικά",
    "Denominations": "Θρησκευτικές Κοινότητες",
    "Dense": "Πυκνό",
    "Department": "Τμήμα",
    "Departments": "Τμήματα",
    "Dependent": "Εξαρτώμενος",
    "Dependents": "Εξαρτώμενοι",
    "Depletion": "Εξάντληση",
    "Depost Slip Editor": "Επεξεργαστής Ολίσθησης Κατάθεσης",
    "Deposit": "Κατάθεση",
    "Deposit Slip": "Ολίσθηση Κατάθεσης",
    "Deposit Slip Editor": "Επεξεργαστής Ολίσθησης Κατάθεσης",
    "Deposits": "Καταθέσεις",
    "Depository": "Αποθηκευτήριο",
    "Depth": "Βάθος",
    "Deputy": "Αντιπρόεδρος",
    "Derived": "Προέρχομαι",
    "Descend": "Κατεβαίνω",
    "Descendants": "Απόγονοι",
    "Descending": "Φθίνουσα",
    "Descent": "Κατάβαση",
    "Description": "Περιγραφή",
    "Deselect": "Αποεπιλογή",
    "Deselect All": "Αποεπιλογή Όλα",
    "Desert": "Έρημος",
    "Deserve": "Αξίζω",
    "Design": "Σχεδίαση",
    "Designed": "Σχεδιάστηκε",
    "Designer": "Σχεδιαστής",
    "Designing": "Σχεδίαση",
    "Desirable": "Επιθυμητό",
    "Desire": "Επιθυμία",
    "Desired": "Επιθυμητό",
    "Desk": "Γραφείο",
    "Desolate": "Έρημος",
    "Despair": "Απελπισία",
    "Desperate": "Απελπισμένος",
    "Despite": "Παρά τις",
    "Despise": "Περιφρονώ",
    "Despondent": "Απογοητευμένος",
    "Despot": "Τύραννος",
    "Despotic": "Δεσποτικό",
    "Dessert": "Γλυκό",
    "Destination": "Προορισμός",
    "Destine": "Προορίζω",
    "Destined": "Προορισμένος",
    "Destiny": "Κηροσκοπία",
    "Destitute": "Δίχως",
    "Destroy": "Καταστροφή",
    "Destroyed": "Καταστράφηκε",
    "Destroyer": "Καταστροφέας",
    "Destroying": "Καταστροφή",
    "Destruction": "Καταστροφή",
    "Destructive": "Καταστροφικό",
    "Desultory": "Αποσπασματικό",
    "Detach": "Αποσύνδεση",
    "Detached": "Αποσυνδεδεμένο",
    "Detaching": "Αποσύνδεση",
    "Detail": "Λεπτομέρεια",
    "Detailed": "Λεπτομερές",
    "Details": "Λεπτομέρειες",
    "Detain": "Κράτηση",
    "Detained": "Κρατημένος",
    "Detect": "Ανίχνευση",
    "Detected": "Ανιχνεύθηκε",
    "Detecting": "Ανίχνευση",
    "Detection": "Ανίχνευση",
    "Detective": "Ντετέκτιβ",
    "Detention": "Κράτηση",
    "Deter": "Αποτρέπω",
    "Detergent": "Απορρυπαντικό",
    "Deteriorate": "Επιδεινώνομαι",
    "Deteriorated": "Επιδεινώθηκε",
    "Deteriorating": "Επιδεινώνομαι",
    "Deterioration": "Επιδείνωση",
    "Determinant": "Καθοριστικό",
    "Determinate": "Καθορισμένο",
    "Determination": "Αποφασιστικότητα",
    "Determine": "Καθορίζω",
    "Determined": "Αποφασιστικό",
    "Determining": "Καθορισμός",
    "Determines": "Καθορίζει",
    "Determining Process": "Διαδικασία Καθορισμού",
    "Deterred": "Αποτράπηκε",
    "Deterrent": "Αποτρεπτικό",
    "Deterring": "Αποτροπή",
    "Detest": "Μισώ",
    "Detestable": "Αποκρουστικό",
    "Detestation": "Αποστροφή",
    "Dethrone": "Εκθρόνωση",
    "Detonate": "Έκρηξη",
    "Detonated": "Έκρηξη",
    "Detonating": "Έκρηξη",
    "Detonation": "Έκρηξη",
    "Detonator": "Detonator",
    "Detour": "Παράκαμψη",
    "Detoxification": "Αποτοξίνωση",
    "Detoxify": "Αποτοξινώνω",
    "Detract": "Αφαιρώ",
    "Detracted": "Αφαιρέθηκε",
    "Detracting": "Αφαίρεση",
    "Detraction": "Αφαίρεση",
    "Detractive": "Αποτρεπτικό",
    "Detriment": "Ζημιά",
    "Detrimental": "Επιβλαβής",
    "Detritus": "Αποκάλυψη",
    "Detrude": "Εκδίωξη",
    "Detrusion": "Εκδίωξη",
    "Deuce": "Δύο",
    "Deuced": "Δυσάρεστο",
    "Deuces": "Δύο",
    "Deuterium": "Δευτέριο",
    "Deuteron": "Δευτερόνιο",
    "Devaluation": "Υποτίμηση",
    "Devalue": "Υποτιμώ",
    "Devalued": "Υποτιμημένο",
    "Devaluing": "Υποτίμηση",
    "Devastate": "Κατακτητής",
    "Devastated": "Καταστραφηκότα",
    "Devastating": "Καταστροφικό",
    "Devastation": "Καταστροφή",
    "Develop": "Ανάπτυξη",
    "Developed": "Αναπτυγμένος",
    "Developer": "Προγραμματιστής",
    "Developing": "Ανάπτυξη",
    "Developing Country": "Αναπτυσσόμενη Χώρα",
    "Development": "Ανάπτυξη",
    "Development Version": "Έκδοση Ανάπτυξης",
    "Developments": "Εξελίξεις",
    "Develops": "Αναπτύσσεται",
    "Deviance": "Απόκλιση",
    "Deviant": "Παρανόμιος",
    "Deviants": "Παρανόμιοι",
    "Deviate": "Παρεκτρέπομαι",
    "Deviated": "Παρεκτράπηκε",
    "Deviating": "Παρέκτραση",
    "Deviation": "Απόκλιση",
    "Device": "Συσκευή",
    "Devices": "Συσκευές",
    "Devil": "Διάβολος",
    "Devilish": "Διαβολικό",
    "Devilry": "Διαβολικότητα",
    "Devils": "Διάβολοι",
    "Devious": "Παγίδα",
    "Deviousness": "Παγίδα",
    "Devise": "Εφεύρεση",
    "Devised": "Επινοημένος",
    "Devises": "Εφεύρεση",
    "Devising": "Εφεύρεση",
    "Devisor": "Εφευρέτης",
    "Devitalize": "Ανάσα",
    "Devitalized": "Ανάσα",
    "Devitalizing": "Ανάσα",
    "Devize": "Epivouli",
    "Devoid": "Δίχως",
    "Devolute": "Τι κατηγορίες",
    "Devolution": "Μεταφορά",
    "Devolve": "Μεταφορά",
    "Devolved": "Μεταφερθηκε",
    "Devolving": "Μεταφορά",
    "Devonshire": "Devonshire",
    "Devote": "Αφιερώνω",
    "Devoted": "Αφοσιωμένος",
    "Devotee": "Οπαδός",
    "Devotees": "Οπαδοί",
    "Devoting": "Αφιέρωση",
    "Devotion": "Ευσέβεια",
    "Devotional": "Ευσεβής",
    "Devotions": "Προσευχές",
    "Devour": "Κατάπινω",
    "Devoured": "Κατάπιε",
    "Devouring": "Κατάπωση",
    "Devouring Process": "Διαδικασία Κατάπωσης",
}

# Apply to Greek file
el_file = 'locale/missing-terms/el.json'

with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

el_updated = 0
for key, translation in el_critical_batch.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = translation
        el_updated += 1

with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

# Stats
el_empty = len([v for v in el_data.values() if v == ""])
el_total = len(el_data)
el_done = el_total - el_empty

print(f"\n✓ Greek: {el_updated} terms → {el_done}/{el_total} ({100*el_done/el_total:.1f}%)")
print(f"Remaining: EL {el_empty}")
