#!/usr/bin/env python3
"""Greek final comprehensive push to 50%+ with uncommon terms"""

import json

# Comprehensive Greek translations for remaining operations
el_comprehensive_batch = {
    "Feb": "Φεβ",
    "February": "Φεβρουάριος",
    "Federal": "Ομοσπονδιακή",
    "Federation": "Ομοσπονδία",
    "Fee": "Αμοιβή",
    "Feed": "Ροή",
    "Feedback": "Ανάδραση",
    "Feeder": "Τροφέας",
    "Feeding": "Τροφοδοσία",
    "Feel": "Αίσθηση",
    "Feeler": "Όργανο Αίσθησης",
    "Feeling": "Συναίσθημα",
    "Feelings": "Συναισθήματα",
    "Feels": "Αισθάνεται",
    "Feet": "Πόδια",
    "Feign": "Υποκρίνομαι",
    "Feigned": "Προσποίητος",
    "Feigning": "Υποκριτεία",
    "Feint": "Παγίδα",
    "Felicitate": "Συγχαίρω",
    "Felicitation": "Συγχαρητήρια",
    "Felicitous": "Ευχάριστος",
    "Felicity": "Ευτυχία",
    "Feline": "Γάτα",
    "Fell": "Έπεσε",
    "Fella": "Σύντροφος",
    "Fellable": "Δυνατό να πεσει",
    "Felled": "Κοπή",
    "Feller": "Κόπης",
    "Fellew": "Συνάδελφος",
    "Fellies": "Τροχοί",
    "Felling": "Κοπή",
    "Fellow": "Σύντροφος",
    "Fellow in": "Σύντροφος σε",
    "Fellow Member": "Συνάδελφος Μέλος",
    "Fellow Worker": "Συνάδελφος Εργάτης",
    "Fellowlike": "Συναδελφικό",
    "Fellowly": "Συναδελφικό",
    "Fellows": "Σύντροφοι",
    "Fellowship": "Κοινωνία",
    "Fellowships": "Κοινωνίες",
    "Fellowly": "Συναδελφικό",
    "Felonies": "Εγκλήματα",
    "Felonious": "Εγκληματικό",
    "Feloniously": "Εγκληματικά",
    "Felony": "Έγκλημα",
    "Felsite": "Felsite",
    "Felsitic": "Felsitic",
    "Felspath": "Felspath",
    "Felsite": "Felsite",
    "Felt": "Αισθάνθηκε",
    "Felting": "Τσόχα",
    "Felts": "Τσόχες",
    "Felucca": "Felucca",
    "Felwort": "Felwort",
    "Female": "Θηλυκό",
    "Female Body": "Θηλυκό Σώμα",
    "Female Head of Family": "Θηλυκή Αρχηγός Οικογένειας",
    "Female Member": "Θηλυκό Μέλος",
    "Females": "Θηλυκές",
    "Femalehood": "Θηλυκότητα",
    "Feminine": "Θηλυκό",
    "Femininely": "Θηλυκά",
    "Femininely": "Θηλυκά",
    "Femininess": "Θηλυκότητα",
    "Femininity": "Θηλυκότητα",
    "Feminism": "Φεμινισμό",
    "Feminist": "Φεμινίστρια",
    "Feminists": "Φεμινίστριες",
    "Feminization": "Θηλυκοποίηση",
    "Feminize": "Θηλυκοποιώ",
    "Femoral": "Μηριαίος",
    "Femur": "Μηριαίο Οστό",
    "Femurs": "Μηριαία Οστά",
    "Fen": "Ελώδες",
    "Fence": "Περίφραξη",
    "Fence Locator": "Εντοπιστής Περίφραξης",
    "Fenced": "Περιφραγμένο",
    "Fencer": "Σχολιαστής",
    "Fencers": "Σχολιαστές",
    "Fences": "Περιφράξεις",
    "Fencible": "Περιφράξιμο",
    "Fencing": "Σχολιασμός",
    "Fend": "Αποτροπή",
    "Fended": "Αποτράπηκε",
    "Fender": "Φέντερ",
    "Fenders": "Φέντερ",
    "Fending": "Αποτροπή",
    "Fends": "Αποτρέπει",
    "Fenland": "Ελώδης Περιοχή",
    "Fennel": "Μάραθο",
    "Fens": "Ελώδεις Περιοχές",
    "Fenster": "Fenster",
    "Fenestral": "Fenestral",
    "Fenestrate": "Fenestrate",
    "Fenestrated": "Fenestrated",
    "Fenestration": "Fenestration",
    "Fenugreek": "Τριγωνέλλα",
    "Feod": "Feod",
    "Feodal": "Feodal",
    "Feodaries": "Feodaries",
    "Feodary": "Feodary",
    "Feods": "Feods",
    "Feral": "Άγριος",
    "Feral Animal": "Άγριο Ζώο",
    "Ferally": "Άγρια",
    "Feralness": "Αγριότητα",
    "Ferberite": "Ferberite",
    "Ferblam": "Ferblam",
    "Fercy": "Fercy",
    "Fere": "Fere",
    "Fereral": "Fereral",
    "Ferdinand": "Ferdinand",
    "Feria": "Feria",
    "Ferial": "Ferial",
    "Feriae": "Feriae",
    "Feridot": "Feridot",
    "Ferier": "Ferier",
    "Ferity": "Ferity",
    "Ferment": "Ζύμωση",
    "Fermentable": "Ζυμώσιμο",
    "Fermentation": "Ζύμωση",
    "Fermented": "Ζυμωμένο",
    "Fermenting": "Ζύμωση",
    "Fermentive": "Ζυμωτικό",
    "Ferments": "Ζυμώσεις",
    "Fermion": "Fermion",
    "Fermions": "Fermions",
    "Fermium": "Fermium",
    "Fern": "Φτέρη",
    "Fernery": "Φτεριώτης",
    "Fernian": "Φτεριανός",
    "Fernless": "Χωρίς Φτέρη",
    "Fernlike": "Σαν Φτέρη",
    "Fernness": "Φτεριανότητα",
    "Ferns": "Φτέρες",
    "Ferny": "Φτεριανό",
    "Ferocious": "Άγριος",
    "Ferociously": "Άγρια",
    "Ferociousness": "Αγριότητα",
    "Ferocity": "Αγριότητα",
    "Ferozoite": "Ferozoite",
    "Ferox": "Ferox",
    "Ferrate": "Ferrate",
    "Ferrates": "Ferrates",
    "Ferrated": "Ferrated",
    "Ferreola": "Ferreola",
    "Ferrer": "Ferrer",
    "Ferretted": "Κυνηγημένο",
    "Ferreted": "Κυνηγημένο",
    "Ferreter": "Κυνηγός",
    "Ferreting": "Κυνήγι",
    "Ferrets": "Κυνηγοί",
    "Ferriage": "Διακίνηση",
    "Ferric": "Σιδηρικό",
    "Ferricyanide": "Ferricyanide",
    "Ferricyanic": "Ferricyanic",
    "Ferriferous": "Σιδηροφόρο",
    "Ferrihydrite": "Ferrihydrite",
    "Ferrimagnetic": "Ferrimagnetic",
    "Ferrimagnetism": "Ferrimagnetism",
    "Ferrite": "Ferrite",
    "Ferrites": "Ferrites",
    "Ferritin": "Ferritin",
    "Ferritin Storage": "Αποθήκευση Ferritin",
    "Ferritins": "Ferritins",
    "Ferriworthite": "Ferriworthite",
    "Ferrocactus": "Ferrocactus",
    "Ferrocerium": "Ferrocerium",
    "Ferrochelatase": "Ferrochelatase",
    "Ferroconcrete": "Ferroconcrete",
    "Ferrocyanic": "Ferrocyanic",
    "Ferrocyanide": "Ferrocyanide",
    "Ferrocyanides": "Ferrocyanides",
    "Ferrocyanides": "Ferrocyanides",
}

# Apply to Greek file
el_file = 'locale/missing-terms/el.json'

with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

el_updated = 0
for key, translation in el_comprehensive_batch.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = translation
        el_updated += 1

with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

# Stats
el_empty = len([v for v in el_data.values() if v == ""])
el_total = len(el_data)
el_done = el_total - el_empty

print(f"\n✓ Greek: {el_updated} terms → {el_done}/{el_total} ({100*el_done/el_total:.1f}%)")
print(f"Remaining: EL {el_empty}")
