import json

translations_10 = {
  "Latest People": "ഏറ്റവും പുതിയ ആളുകൾ",
  "Updated People": "അപ്‌ഡേറ്റ് ചെയ്ത ആളുകൾ",
  "User must have Manage Groups permission": "ഉപയോക്താവിന് ഗ്രൂപ്പ് മാനേജ് ചെയ്യൽ അനുമതി ഉണ്ടായിരിക്കണം",
  "Missing": "കാണുന്നില്ല",
  "User must have Edit Records permission": "ഉപയോക്താവിന് റെക്കോർഡ് എഡിറ്റ് ചെയ്യൽ അനുമതി ഉണ്ടായിരിക്കണം",
  "Can't delete yourself": "സ്വയം ഇല്ലാതാക്കാൻ കഴിയില്ല",
  "The role could not be found.": "പങ്ക് കണ്ടെത്തിയില്ല.",
  "is disabled": "പ്രവർത്തനരഹിതമാണ്",
  "Software Version": "സോഫ്‌റ്റ്‌വെയർ പതിപ്പ്",
  "Database Version": "ഡേറ്റാബേസ് പതിപ്പ്",
  "Application Prerequisites": "ആപ്ലിക്കേഷൻ ആവശ്യകതകൾ",
  "Invalid country name supplied": "അസാധുവായ രാജ്യ നാമം നൽകി",
  "LastName FirstName": "കുടുംബപ്പേര് പേര്",
  "Holidays": "അവധികൾ",
  "Person Name": "വ്യക്തിയുടെ പേര്",
  "Custom message for church greeter email 1, max 255 characters": "പള്ളി സ്വീകർത്താവ് ഇമെയിൽ 1-നുള്ള ഇഷ്‌ടാനുസൃത സന്ദേശം, പരമാവധി 255 അക്ഷരങ്ങൾ",
  "Custom message for church greeter email 2, max 255 characters": "പള്ളി സ്വീകർത്താവ് ഇമെയിൽ 2-നുള്ള ഇഷ്‌ടാനുസൃത സന്ദേശം, പരമാവധി 255 അക്ഷരങ്ങൾ",
  "Include contact and demographic data in new member email notification body": "പുതിയ അംഗ ഇമെയിൽ അറിയിപ്പ് ബോഡിയിൽ ബന്ധ, ജനസ്ഥിതി ഡേറ്റ ഉൾപ്പെടുത്തുക",
  "Include family custom properties in global search.": "ആഗോള തിരയലിൽ കുടുംബ ഇഷ്‌ടാനുസൃത സ്വഭാവങ്ങൾ ഉൾപ്പെടുത്തുക.",
  "Latvia (Latvija)": "ലാറ്റ്‌വിയ",
  "You are about to add a new deposit without a comment": "നിങ്ങൾ അഭിപ്രായം ഇല്ലാതെ ഒരു പുതിയ ഡിപ്പോസിറ്റ് ചേർക്കാൻ പോകുകയാണ്",
  "Record": "റെക്കോർഡ്",
  "Records": "റെക്കോർഡുകൾ",
  "Emptied into Event": "ഇവന്റിലേക്ക് ഒഴിച്ചു",
  "Passed": "പൂർത്തിയായി",
  "Focus": "ഫോക്കസ്",
  "Unfocus": "ഫോക്കസ് നീക്കുക",
  "Estonian": "Estonian",
  "Error decoding signature definition file": "സിഗ്നേച്ചർ ഡെഫിനിഷൻ ഫയൽ ഡീകോഡ് ചെയ്യുന്നതിൽ പിശക്",
  "Event not found": "ഇവന്റ് കണ്ടെത്തിയില്ല",
  "Session timeout length in seconds\nSet to zero to disable session timeouts.": "സെഷൻ ടൈംഔട്ട് ദൈർഘ്യം സെക്കൻഡിൽ\nസെഷൻ ടൈംഔട്ട് പ്രവർത്തനരഹിതമാക്കാൻ പൂജ്യം ക്രമീകരിക്കുക.",
  "Minimum amount that a new password must differ from the old one (# of characters changed)\nSet to zero to disable this feature": "പുതിയ പാസ്‌വേഡ് പഴയതിൽ നിന്ന് വ്യത്യസ്തമാകേണ്ട ഏറ്റവും കുറഞ്ഞ അളവ് (# അക്ഷരങ്ങൾ)\nഈ ഫീച്ചർ പ്രവർത്തനരഹിതമാക്കാൻ പൂജ്യം ക്രമീകരിക്കുക",
  "Maximum number of failed logins to allow before a user account is locked.\nOnce the maximum has been reached, an administrator must re-enable the account.\nThis feature helps to protect against automated password guessing attacks.\nSet to zero to disable this feature.": "അക്കൗണ്ട് ലോക്ക് ചെയ്യുന്നതിന് മുൻപ് അനുവദിക്കേണ്ട പരമാവധി ലോഗിൻ പരാജയങ്ങൾ.\nഒരതിരിൽ എത്തിയാൽ അഡ്‌മിൻ വീണ്ടും പ്രവർത്തനക്ഷമമാക്കണം.\nഈ ഫീച്ചർ ഓട്ടോ-പാസ്‌വേഡ് ആക്രമണങ്ങളിൽ നിന്ന് സംരക്ഷിക്കുന്നു.\nപ്രവർത്തനരഹിതമാക്കാൻ പൂജ്യം ക്രമീകരിക്കുക.",
  "PDF handling mode.\n1 = Save File dialog\n2 = Open in current browser window": "PDF കൈകാര്യ രീതി.\n1 = ഫയൽ ഡയലോഗ് സംരക്ഷിക്കുക\n2 = നിലവിലെ ബ്രൗസർ വിൻഡോയിൽ തുറക്കുക",
  "Verify People": "ആളുകൾ സ്ഥിരീകരിക്കുക",
  "People Verify Dashboard": "ആളുകൾ സ്ഥിരീകരണ ഡാഷ്‌ബോർഡ്",
  "Verification recorded": "സ്ഥിരീകരണം രേഖപ്പെടുത്തി",
  "Verification URL created": "സ്ഥിരീകരണ URL ഉണ്ടാക്കി",
  "URL": "URL",
  "PDF": "PDF",
  "Error sending email(s)": "ഇമെയിൽ(കൾ) അയക്കുന്നതിൽ പിശക്",
  "Please check logs for more information": "കൂടുതൽ വിവരത്തിന് ലോഗ് പരിശോധിക്കുക",
  "Verification URL": "സ്ഥിരീകരണ URL",
  "Unexpected Person Id": "അപ്രതീക്ഷിത വ്യക്തി ID",
  "Search Calendar Events": "കലണ്ടർ ഇവന്റുകൾ തിരയുക",
  "Maximum number of Calendar Events": "പരമാവധി കലണ്ടർ ഇവന്റുകളുടെ എണ്ണം",
  "%d month old": "%d മാസം പ്രായം",
  "%d year old": "%d വയസ്സ്",
  "Missing PHP ZipArchive": "PHP ZipArchive ഇല്ല",
  "Add Results to Cart": "ഫലങ്ങൾ കാർട്ടിൽ ചേർക്കുക",
  "Remove Results from Cart": "കാർട്ടിൽ നിന്ന് ഫലങ്ങൾ നീക്കം ചെയ്യുക",
  "Database Reset Functions": "ഡേറ്റാബേസ് റീസെറ്റ് പ്രവർത്തനങ്ങൾ",
  "Reset Database": "ഡേറ്റാബേസ് റീസെറ്റ് ചെയ്യുക",
  "This will reset the system data and will restart the system as a new install.": "ഇത് സിസ്റ്റം ഡേറ്റ റീസെറ്റ് ചെയ്ത് പുതിയ ഇൻസ്റ്റാളായി പുനരാരംഭിക്കും.",
  "Portuguese - Portugal": "Portuguese - Portugal",
  "Holiday": "അവധി",
  "Specify the application name to be displayed in authenticator app": "ഓതന്റിക്കേറ്റർ ആപ്പിൽ കാണിക്കേണ്ട ആപ്ലിക്കേഷൻ നാമം നൽകുക",
  "Review": "അവലോകനം",
  "User authenticated via API Key: ": "API Key വഴി ഉപയോക്താവ് ആധികാരികമാക്കി: ",
  "Unsuccessful API Key authentication attempt": "API Key ആധികാരികമാക്കൽ പ്രയത്‌നം പരാജയപ്പെട്ടു",
  "Unpinned Events": "പിൻ ചെയ്യാത്ത ഇവന്റുകൾ",
  "LastName, FirstName MiddleName": "കുടുംബപ്പേര്, പേര് മദ്ധ്യനാമം",
  "Please confirm disabling 2 Factor Auth for this user": "ഈ ഉപയോക്താവിന്റെ 2 ഘടക ആധികാരികത പ്രവർത്തനരഹിതമാക്കൽ സ്ഥിരീകരിക്കുക",
  "Send an email notifying users when their account has been deleted": "അക്കൗണ്ട് ഇല്ലാതാക്കിയപ്പോൾ ഉപയോക്താക്കളെ ഇമെയിൽ മുഖേന അറിയിക്കുക",
  "Incorrect password supplied for current user": "നിലവിലെ ഉപയോക്താവ് തെറ്റായ പാസ്‌വേഡ് നൽകി",
  "Your new password must not match your old one.": "നിങ്ങളുടെ പുതിയ പാസ്‌വേഡ് പഴയതിന് സമാനമാകരുത്.",
  "Your new password is too similar to your old one.": "നിങ്ങളുടെ പുതിയ പാസ്‌വേഡ് പഴയതിന് വളരെ സമാനമാണ്.",
  "Password reset not available.  Please contact your system administrator": "പാസ്‌വേഡ് റീസെറ്റ് ലഭ്യമല്ല. ദയവായി സിസ്റ്റം അഡ്‌മിനിസ്‌ട്രേറ്ററെ ബന്ധപ്പെടുക",
  "Enter new user password. Administratively set passwords are not subject to length or complexity requirements": "പുതിയ ഉപയോക്തൃ പാസ്‌വേഡ് നൽകുക. അഡ്‌മിൻ ക്രമീകരിക്കുന്ന പാസ്‌വേഡുകൾ നീളം അല്ലെങ്കിൽ സങ്കീർണ്ണത ആവശ്യകതകൾ പാലിക്കേണ്ടതില്ല",
  "No email passed in": "ഇമെയിൽ നൽകിയില്ല",
  "Mailchimp is not active": "Mailchimp സജീവമല്ല",
  "Mailchimp": "Mailchimp",
  "Lists": "ലിസ്‌റ്റുകൾ",
  "loading": "ലോഡ് ചെയ്യുന്നു",
  "List not found": "ലിസ്‌റ്റ് കണ്ടെത്തിയില്ല",
  "People not in": "ഇവരിൽ ഇല്ലാത്ത ആളുകൾ",
  "Invalid List id": "അസാധുവായ ലിസ്‌റ്റ് ID",
  "Audience not in the ChurchCRM": "ChurchCRM-ൽ ഇല്ലാത്ത ഓഡിയൻസ്",
  "Web Server": "വെബ് സർവ്വർ",
  "Hebrew": "Hebrew",
  "open rate": "ഓപ്പൺ നിരക്ക്",
  "Login Info": "ലോഗിൻ വിവരം",
  "Login Count": "ലോഗിൻ എണ്ണം",
  "Failed Login": "പരാജയപ്പെട്ട ലോഗിൻ",
  "Permissions": "അനുമതികൾ",
  "Manage Notes": "കുറിപ്പുകൾ മാനേജ് ചെയ്യുക",
  "Failed generate a new API Key": "പുതിയ API Key ഉണ്ടാക്കൽ പരാജയപ്പെട്ടു",
  "Pledge Summary By Family": "കുടുംബം അനുസരിച്ചുള്ള സംഭാവന പ്രതിജ്ഞ സംഗ്രഹം",
  "Pledge": "സംഭാവന പ്രതിജ്ഞ",
  "Paid": "അടച്ചത്",
  "Owe": "ബാക്കി",
  "Start Date": "ആരംഭ തീയതി",
  "End Date": "അവസാന തീയതി",
  "Pinned Calendars": "പിൻ ചെയ്ത കലണ്ടറുകൾ",
  "This field is required": "ഈ ഫീൽഡ് ആവശ്യമാണ്",
  "Text": "ടെക്സ്റ്റ്",
  "Event Description": "ഇവന്റ് വിവരണം",
  "Help translate this project": "ഈ പ്രോജക്ട് പരിഭാഷ ചെയ്യാൻ സഹായിക്കൂ",
  "Afrikaans": "Afrikaans",
  "Loading": "ലോഡ് ചെയ്യുന്നു",
  "Family Property Unassignment": "കുടുംബ സ്വഭാവം നീക്കം",
  "Do you want to remove": "നീക്കണോ",
  "Today's Birthdays": "ഇന്നത്തെ ജന്മദിനങ്ങൾ",
  "Today's Wedding Anniversaries": "ഇന്നത്തെ വിവാഹ വാർഷികങ്ങൾ",
  "Api Key": "API Key",
  "Regen API Key": "API Key പുനരുൽപ്പാദിപ്പിക്കുക",
  "View Family Page": "കുടുംബ പേജ് കാണുക",
  "View Person Page": "വ്യക്തി പേജ് കാണുക",
  "Verify": "സ്ഥിരീകരിക്കുക",
  "Family has no emails to use": "കുടുംബത്തിന് ഉപയോഗിക്കാൻ ഇമെയിൽ ഇല്ല",
  "Boxed Layout": "ബോക്‌സ്ഡ് ലേഔട്ട്",
  "Activate the boxed layout": "ബോക്‌സ്ഡ് ലേഔട്ട് സജീവമാക്കുക",
  "Toggle Sidebar": "സൈഡ്ബാർ ടോഗിൾ ചെയ്യുക",
  "Toggle the left sidebar's state (open or collapse)": "ഇടത് സൈഡ്ബാറിന്റെ സ്ഥിതി (തുറക്കുക അല്ലെങ്കിൽ ചുരുക്കുക) ടോഗിൾ ചെയ്യുക",
  "Tables Settings": "ടേബിൾ ക്രമീകരണങ്ങൾ",
  "Page length": "പേജ് ദൈർഘ്യം",
  "Change the initial page length (number of rows per page)": "ആദ്യ പേജ് ദൈർഘ്യം (പ്രതി പേജ് വരികളുടെ എണ്ണം) മാറ്റുക",
  "User Interface": "ഉപയോക്തൃ ഇൻ്റർഫേസ്",
  "Locale": "ലോക്കൽ",
  "Override system locale": "സിസ്റ്റം ലോക്കൽ ഓവർറൈഡ് ചെയ്യുക",
  "Deleted": "ഇല്ലാതാക്കി",
  "Invalid Birth Date: Missing birth month or day.": "അസാധുവായ ജനന തീയതി: ജനന മാസം അല്ലെങ്കിൽ ദിവസം ഇല്ല.",
  "Invalid Birth Date: Missing birth month and day.": "അസാധുവായ ജനന തീയതി: ജനന മാസവും ദിവസവും ഇല്ല.",
  "System": "സിസ്റ്റം",
  "Amharic - Ethiopia": "Amharic - Ethiopia",
  "Czech": "Czech",
  "Finnish": "Finnish",
  "Greek": "Greek",
  "Turkish": "Turkish",
  "Ukrainian": "Ukrainian",
  "Change role": "പങ്ക് മാറ്റുക",
  "Closed": "അടഞ്ഞത്",
  "Delete this person?": "ഈ വ്യക്തിയെ ഇല്ലാതാക്കണോ?",
  "Deposit ID": "ഡിപ്പോസിറ്റ് ID",
  "Deposit Total": "ഡിപ്പോസിറ്റ് ആകെ",
  "If that doesn't work, copy and paste the following link in your browser": "ഇത് പ്രവർത്തിക്കോ ഇല്ലെങ്കിൽ, ഈ ലിങ്ക് ബ്രൗസറിൽ കോപ്പി-പേസ്റ്റ് ചെയ്യുക",
  "You received this email because we received a request for activity on your account. If you didn't request this you can safely delete this email.": "നിങ്ങളുടെ അക്കൗണ്ടിൽ ഒരു പ്രവർത്തനം അഭ്യർത്ഥിക്കപ്പെട്ടതിനാൽ ഈ ഇമെയിൽ ലഭിച്ചു. ഇത് നിങ്ങൾ അഭ്യർത്ഥിക്കാതിരുന്നെങ്കിൽ ഈ ഇമെയിൽ ഇല്ലാതാക്കാം.",
  "To stop receiving these emails, you can email": "ഈ ഇമെയിലുകൾ ലഭിക്കുന്നത് നിർത്താൻ, ഇവിടേക്ക് ഇമെയിൽ ചെയ്യൂ",
  "invalid group request": "അസാധുവായ ഗ്രൂപ്പ് അഭ്യർത്ഥന",
  "Hindi - India": "Hindi - India",
  "Japanese": "Japanese",
  "Tamil - India": "Tamil - India",
  "Not Subscribed": "സബ്‌സ്‌ക്രൈബ് ചെയ്തിട്ടില്ല",
  "property": "സ്വഭാവം",
  "Default Zip": "ഡിഫോൾട്ട് പിൻകോഡ്",
  "The previous integrity check passed. All system file hashes match the expected values.": "മുൻ ഇൻ്റഗ്രിറ്റി ചെക്ക് പൂർത്തിയായി. എല്ലാ സിസ്റ്റം ഫയൽ ഹാഷുകളും പ്രതീക്ഷിക്കുന്ന മൂല്യങ്ങളുമായി ഒത്തുചേരുന്നു.",
  "Comma separated list of classifications that should appear as inactive": "നിഷ്‌ക്രിയമായി കാണേണ്ട വർഗ്ഗീകരണങ്ങളുടെ കോമ-വേർതിരിച്ച ലിസ്‌റ്റ്",
  "MailChimp is not configured": "MailChimp ക്രമീകരിച്ചിട്ടില്ല",
  "English - South Africa": "English - South Africa",
  "English - Jamaica": "English - Jamaica"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-10.json', 'w', encoding='utf-8') as f:
    json.dump(translations_10, f, ensure_ascii=False, indent=2)
print("ml-10.json written")
