import json

translations_13 = {
  "Backup Best Practices": "ബാക്കപ്പ് മികച്ച രീതികൾ",
  "Backup Status": "ബാക്കപ്പ് സ്ഥിതി",
  "Backup Type": "ബാക്കപ്പ് തരം",
  "Backup complete! Click below to download.": "ബാക്കപ്പ് പൂർത്തിയായി! ഡൗൺലോഡ് ചെയ്യാൻ താഴെ ക്ലിക്ക് ചെയ്യൂ.",
  "Backup completed successfully!": "ബാക്കപ്പ് വിജയകരമായി പൂർത്തിയായി!",
  "Backup downloaded. Server copy removed.": "ബാക്കപ്പ് ഡൗൺലോഡ് ചെയ്തു. സർവ്വർ കോപ്പി നീക്കി.",
  "Backup failed. Please try again.": "ബാക്കപ്പ് പരാജയപ്പെട്ടു. വീണ്ടും ശ്രമിക്കുക.",
  "Backup generated and copied to remote server": "ബാക്കപ്പ് ഉണ്ടാക്കി ദൂര സർവ്വറിലേക്ക് കോപ്പി ചെയ്തു",
  "Backup in progress, please wait...": "ബാക്കപ്പ് നടക്കുന്നു, ദയവായി കാത്തിരിക്കൂ...",
  "CAUTION: Restoring a backup will completely erase the existing database and replace it with the backup data.": "ശ്രദ്ധ: ഒരു ബാക്കപ്പ് പുനഃസ്ഥാപിക്കുന്നത് നിലവിലുള്ള ഡേറ്റാബേസ് പൂർണ്ണമായും മായ്ക്കും.",
  "Close & Refresh": "അടയ്ക്കുക & പുതുക്കുക",
  "Confirm Deletion": "ഇല്ലാതാക്കൽ സ്ഥിരീകരിക്കുക",
  "Create directory permission": "ഡയറക്ടറി ഉണ്ടാക്കൽ അനുമതി",
  "Database Only": "ഡേറ്റാബേസ് മാത്രം",
  "Database Restored Successfully!": "ഡേറ്റാബേസ് വിജയകരമായി പുനഃസ്ഥാപിച്ചു!",
  "Database schema upgraded automatically": "ഡേറ്റാബേസ് സ്കീമ സ്വയം അപ്‌ഗ്രേഡ് ചെയ്തു",
  "Delete All Files": "എല്ലാ ഫയലുകളും ഇല്ലാതാക്കുക",
  "Delete All Orphaned Files": "എല്ലാ അനാഥ ഫയലുകളും ഇല്ലാതാക്കുക",
  "Delete records permission": "റെക്കോർഡ് ഇല്ലാതാക്കൽ അനുമതി",
  "Deleted %d files, %d failed": "%d ഫയലുകൾ ഇല്ലാതാക്കി, %d പരാജയപ്പെട്ടു",
  "Deletion Results": "ഇല്ലാതാക്കൽ ഫലങ്ങൾ",
  "Drag and drop your backup file here": "ബാക്കപ്പ് ഫയൽ ഇവിടെ ഡ്രാഗ് & ഡ്രോപ്പ് ചെയ്യുക",
  "Edit records permission": "റെക്കോർഡ് എഡിറ്റ് ചെയ്യൽ അനുമതി",
  "Encryption": "എൻക്രിപ്ഷൻ",
  "Exports database structure and data. Smaller file size.": "ഡേറ്റാബേസ് ഘടനയും ഡേറ്റയും കയറ്റുമതി ചെയ്യുന്നു. ചെറിയ ഫയൽ വലുപ്പം.",
  "File Path": "ഫയൽ പാത്ത്",
  "File signatures match the official release.": "ഫയൽ സിഗ്നേച്ചറുകൾ ഒഫീഷ്യൽ റിലീസുമായി ഒത്തുചേരുന്നു.",
  "Files may be modified or missing. Consider re-deploying from an official release.": "ഫയലുകൾ മാറ്റിയിരിക്കാം അല്ലെങ്കിൽ ഇല്ലാതായിരിക്കാം. ഒഫീഷ്യൽ റിലീസ് വീണ്ടും വിന്യസിക്കാൻ ആലോചിക്കൂ.",
  "Finance access": "ധനകാര്യ ആക്സസ്",
  "Force Re-install": "ബലമായ പുനരാരംഭ ഇൻസ്റ്റാൾ",
  "Force re-install initiated. Please backup your database before applying.": "ബലമായ പുനരാരംഭ ഇൻസ്റ്റാൾ ആരംഭിച്ചു. പ്രയോഗിക്കുന്നതിന് മുൻപ് ഡേറ്റാബേസ് ബാക്കപ്പ് ചെയ്യുക.",
  "Full Backup": "പൂർണ്ണ ബാക്കപ്പ്",
  "Generate & Download Backup": "ബാക്കപ്പ് ഉണ്ടാക്കി ഡൗൺലോഡ് ചെയ്യുക",
  "Go to Dashboard": "ഡാഷ്‌ബോർഡിലേക്ക് പോകുക",
  "Group management access": "ഗ്രൂപ്പ് മാനേജ്‌മെന്റ് ആക്സസ്",
  "If you upload a backup from ChurchInfo or a previous version of ChurchCRM, it will be automatically upgraded to the current database schema.": "ChurchInfo അല്ലെങ്കിൽ ChurchCRM-ന്റെ മുൻ പതിപ്പിൽ നിന്ന് ബാക്കപ്പ് അപ്‌ലോഡ് ചെയ്താൽ, അത് നിലവിലെ ഡേറ്റാബേസ് സ്കീമയിലേക്ക് സ്വയം അപ്‌ഗ്രേഡ് ആകും.",
  "Important Warning": "പ്രധാന മുന്നറിയിപ്പ്",
  "Includes database and all uploaded photos. Larger file size.": "ഡേറ്റാബേസും എല്ലാ അപ്‌ലോഡ് ചിത്രങ്ങളും ഉൾക്കൊള്ളുന്നു. വലിയ ഫയൽ വലുപ്പം.",
  "Keep one copy in a fire-proof safe on-site and another off-site.": "ഒരു കോപ്പി ഒരിടത്ത് ഫയർ-പ്രൂഫ് സേഫിൽ, മറ്റൊന്ന് മറ്റൊരിടത്ത് സൂക്ഷിക്കൂ.",
  "Loading...": "ലോഡ് ചെയ്യുന്നു...",
  "Manage Orphaned Files": "അനാഥ ഫയലുകൾ മാനേജ് ചെയ്യുക",
  "Menu options access": "മെനു ഓപ്ഷൻ ആക്സസ്",
  "Multiple Copies": "ഒന്നിലധികം കോപ്പികൾ",
  "No Orphaned Files Found": "അനാഥ ഫയലുകൾ കണ്ടെത്തിയില്ല",
  "Notes access": "കുറിപ്പ് ആക്സസ്",
  "Orphaned Files": "അനാഥ ഫയലുകൾ",
  "Orphaned Files Management": "അനാഥ ഫയൽ മാനേജ്‌മെന്റ്",
  "Orphaned files are PHP or JavaScript files that exist on your server but are not part of the official ChurchCRM release. These files may be leftover from previous versions and could pose security risks if they contain outdated code with vulnerabilities.": "അനാഥ ഫയലുകൾ സർവ്വറിൽ ഉള്ള PHP അല്ലെങ്കിൽ JavaScript ഫയലുകളാണ്, ഇവ ഒഫീഷ്യൽ ChurchCRM റിലീസിന്റെ ഭാഗമല്ല.",
  "Orphaned files from previous versions cleaned up": "മുൻ പതിപ്പുകളിലെ അനാഥ ഫയലുകൾ ക്ലീൻ ചെയ്തു",
  "Permission Required": "അനുമതി ആവശ്യമാണ്",
  "Please check the backup file and try again.": "ബാക്കപ്പ് ഫയൽ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",
  "Please select a backup file to restore": "പുനഃസ്ഥാപിക്കേണ്ട ബാക്കപ്പ് ഫയൽ തിരഞ്ഞെടുക്കുക",
  "Redirecting in": "ഇടത്ത് റീഡൈരക്ട് ചെയ്യുന്നു",
  "Refresh List": "ലിസ്‌റ്റ് പുതുക്കുക",
  "Regular Backups": "പതിവ് ബാക്കപ്പുകൾ",
  "Required Permission": "ആവശ്യ അനുമതി",
  "Required permission": "ആവശ്യ അനുമതി",
  "Restore Status": "പുനഃസ്ഥാപനം സ്ഥിതി",
  "Restore failed.": "പുനഃസ്ഥാപനം പരാജയപ്പെട്ടു.",
  "Restore failed. Please check the backup file and try again.": "പുനഃസ്ഥാപനം പരാജയപ്പെട്ടു. ദയവായി ബാക്കപ്പ് ഫയൽ പരിശോധിക്കൂ.",
  "Restore in progress, please wait...": "പുനഃസ്ഥാപനം നടക്കുന്നു, ദയവായി കാത്തിരിക്കൂ...",
  "Review the files below and delete them to improve security.": "സുരക്ഷ മെച്ചപ്പെടുത്താൻ താഴെ ഫയലുകൾ അവലോകനം ചെയ്ത് ഇല്ലാതാക്കൂ.",
  "Security Recommendation": "സുരക്ഷ ശുപാർശ",
  "Select Backup File": "ബാക്കപ്പ് ഫയൽ തിരഞ്ഞെടുക്കുക",
  "Supported formats:": "പിന്തുണ ഫോർമാറ്റുകൾ:",
  "The page you tried to visit requires special permissions that your account does not currently have.": "നിങ്ങൾ കാണാൻ ശ്രമിച്ച പേജ് നിങ്ങളുടെ അക്കൗണ്ടിൽ ഇല്ലാത്ത പ്രത്യേക അനുമതികൾ ആവശ്യമാണ്.",
  "These files are not part of the official release and may pose security risks.": "ഈ ഫയലുകൾ ഒഫീഷ്യൽ റിലീസിന്റെ ഭാഗമല്ല, സുരക്ഷ അപകടം ഉണ്ടാക്കിയേക്കാം.",
  "These files were likely part of an older ChurchCRM version and were not cleaned up during a previous upgrade. Deleting them will improve your system security.": "ഈ ഫയലുകൾ ChurchCRM-ന്റെ പഴയ പതിപ്പിന്റെ ഭാഗമായിരിക്കും. ഇല്ലാതാക്കുന്നത് സിസ്റ്റം സുരക്ഷ മെച്ചപ്പെടുത്തും.",
  "This action cannot be undone. Make sure you have a backup of the current data if needed.": "ഈ പ്രവർത്തനം പഴയ നിലയിലേക്ക് മടക്കാനാകില്ല. ആവശ്യമെങ്കിൽ നിലവിലെ ഡേറ്റ ബാക്കപ്പ് ചെയ്യുക.",
  "This may take a few minutes for large databases.": "വലിയ ഡേറ്റാബേസുകൾക്ക് ഇത് കുറച്ച് മിനിറ്റ് എടുക്കും.",
  "This may take several minutes for large databases. Do not close this page.": "വലിയ ഡേറ്റാബേസുകൾക്ക് ഇത് കുറച്ച് മിനിറ്റ് എടുക്കും. ഈ പേജ് അടയ്ക്കരുത്.",
  "Use external tools (GPG, 7-Zip) to encrypt backups before storing off-site.": "ഓഫ്-സൈറ്റ് സ്റ്റോർ ചെയ്യുന്നതിന് മുൻപ് ബാക്കപ്പ് എൻക്രിപ്ട് ചെയ്യാൻ ബാഹ്യ ഉപകരണങ്ങൾ (GPG, 7-Zip) ഉപയോഗിക്കൂ.",
  "User authentication": "ഉപയോക്തൃ ആധികാരികത",
  "User must have Add Event permission": "ഉപയോക്താവിന് ഇവന്റ് ചേർക്കൽ അനുമതി ഉണ്ടായിരിക്കണം",
  "User must have Menu Options permission": "ഉപയോക്താവിന് മെനു ഓപ്ഷൻ അനുമതി ഉണ്ടായിരിക്കണം",
  "What are Orphaned Files?": "അനാഥ ഫയലുകൾ എന്തൊക്കെ?",
  "You will be logged out and redirected to the login page.": "നിങ്ങൾ ലോഗ് ഔട്ട് ആകും, ലോഗിൻ പേജിലേക്ക് കൊണ്ടുപോകും.",
  "Your ChurchCRM installation is clean. All files on the server match the official release.": "നിങ്ങളുടെ ChurchCRM ഇൻസ്റ്റാളേഷൻ ശുദ്ധമാണ്. സർവ്വറിലെ എല്ലാ ഫയലുകളും ഒഫീഷ്യൽ റിലീസുമായി ഒത്തുചേരുന്നു.",
  "or click to browse": "അല്ലെങ്കിൽ ബ്രൗസ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക",
  "seconds...": "സെക്കൻഡ്...",
  " Deposit #": " ഡിപ്പോസിറ്റ് #",
  "%d missing classification": "%d വർഗ്ഗീകരണം ഇല്ല",
  "%d missing gender": "%d ലിംഗം ഇല്ല",
  "%d missing role": "%d പങ്ക് ഇല്ല",
  "A payment is an actual donation received. It will be added to the current deposit.": "ഒരു പേമെന്റ് ലഭിച്ച ഒരു യഥാർത്ഥ സംഭാവനയാണ്. ഇത് നിലവിലെ ഡിപ്പോസിറ്റിൽ ചേർക്കും.",
  "A pledge is a commitment to give. It is not tied to a deposit slip.": "ഒരു സംഭാവന പ്രതിജ്ഞ ഒരു ദക്ഷിണ നൽകാനുള്ള പ്രതിബദ്ധതയാണ്. ഇത് ഡിപ്പോസിറ്റ് സ്ലിപ്പുമായി ബന്ധിക്കില്ല.",
  "Add Another Family Member": "മറ്റൊരു കുടുംബ അംഗം ചേർക്കുക",
  "Add Pledge": "സംഭാവന പ്രതിജ്ഞ ചേർക്കുക",
  "Admin Dashboard": "അഡ്‌മിൻ ഡാഷ്‌ബോർഡ്",
  "Advanced Operations": "വിപുലമായ പ്രവർത്തനങ്ങൾ",
  "All System Settings": "എല്ലാ സിസ്റ്റം ക്രമീകരണങ്ങളും",
  "An unexpected error occurred. Please contact your administrator.": "അപ്രതീക്ഷിത പിശക് ഉണ്ടായി. ദയവായി അഡ്‌മിനിസ്‌ട്രേറ്ററെ ബന്ധപ്പെടുക.",
  "Apr": "ഏപ്രി",
  "Aug": "ഓഗ",
  "Back to Deposits": "ഡിപ്പോസിറ്റുകളിലേക്ക് മടങ്ങുക",
  "Back to Families": "കുടുംബങ്ങളിലേക്ക് മടങ്ങുക",
  "Birth & Family": "ജനനം & കുടുംബം",
  "Cart": "കാർട്ട്",
  "Change this in System Settings.": "ഇത് സിസ്റ്റം ക്രമീകരണങ്ങളിൽ മാറ്റൂ.",
  "Church Membership": "പള്ളി അംഗത്വം",
  "Clean Up Files": "ഫയലുകൾ ക്ലീൻ ചെയ്യുക",
  "Clear all data and start fresh. Cannot be undone.": "എല്ലാ ഡേറ്റയും ക്ലിയർ ചെയ്ത് പുതുതായി ആരംഭിക്കൂ. ഇത് പഴയ നിലയിലേക്ക് മടക്കാനാകില്ല.",
  "Close All Deposits": "എല്ലാ ഡിപ്പോസിറ്റുകളും അടയ്ക്കുക",
  "Closed Deposits:": "അടഞ്ഞ ഡിപ്പോസിറ്റുകൾ:",
  "Closed vs Total": "അടഞ്ഞത് vs ആകെ",
  "Coming soon": "ഉടൻ വരുന്നു",
  "Complete these tasks to ensure accurate year-end tax reporting for your donors.": "ദാതാക്കൾക്ക് കൃത്യമായ വർഷ-അന്ത നികുതി റിപ്പോർട്ടിംഗ് ഉറപ്പ് വരുത്താൻ ഈ ജോലികൾ പൂർത്തിയാക്കൂ.",
  "Configuration:": "കോൺഫിഗറേഷൻ:",
  "Configure Email": "ഇമെയിൽ ക്രമീകരിക്കുക",
  "Contact Information": "ബന്ധ വിവരം",
  "Create Deposit": "ഡിപ്പോസിറ്റ് ഉണ്ടാക്കുക",
  "Create First Deposit": "ആദ്യ ഡിപ്പോസിറ്റ് ഉണ്ടാക്കുക",
  "Create or open a deposit first": "ആദ്യം ഒരു ഡിപ്പോസിറ്റ് ഉണ്ടാക്കൂ അല്ലെങ്കിൽ തുറക്കൂ",
  "Create or select a deposit to get started.": "ആരംഭിക്കാൻ ഒരു ഡിപ്പോസിറ്റ് ഉണ്ടാക്കൂ അല്ലെങ്കിൽ തിരഞ്ഞെടുക്കൂ.",
  "Current Deposit": "നിലവിലെ ഡിപ്പോസിറ്റ്",
  "Current fiscal year": "നിലവിലെ ധനകാര്യ വർഷം",
  "Customizable report with filtering by date, fund, family, and payment method.": "തീയതി, ഫണ്ട്, കുടുംബം, പേമെന്റ് രീതി അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യാൻ കഴിയുന്ന ഇഷ്‌ടാനുസൃത റിപ്പോർട്ട്.",
  "Customize the text that appears on tax statements (sTaxReport1, sTaxReport2, etc).": "നികുതി സ്റ്റേറ്റ്‌മെന്റുകളിൽ കാണിക്കുന്ന ടെക്സ്റ്റ് ഇഷ്‌ടാനുസൃതമാക്കൂ.",
  "Data Quality:": "ഡേറ്റ ഗുണനിലവാരം:",
  "Database:": "ഡേറ്റാബേസ്:",
  "Day": "ദിവസം",
  "Dec": "ഡിസ",
  "Deposit Navigation": "ഡിപ്പോസിറ്റ് നാവിഗേഷൻ",
  "Deposit Statistics": "ഡിപ്പോസിറ്റ് സ്ഥിതിവിവരം",
  "Detailed breakdown of a single deposit slip.": "ഒരൊറ്റ ഡിപ്പോസിറ്റ് സ്ലിപ്പിന്റെ വിശദ വിഭജനം.",
  "Detailed breakdown of pledges and payments by family.": "കുടുംബം അനുസരിച്ചുള്ള സംഭാവന പ്രതിജ്ഞകളുടെ വിശദ വിഭജനം.",
  "Documentation": "ഡോക്യുമെന്റേഷൻ",
  "Donor Families": "ദാതൃ കുടുംബങ്ങൾ",
  "Edit Deposit": "ഡിപ്പോസിറ്റ് എഡിറ്റ് ചെയ്യുക",
  "Edit Family": "കുടുംബം എഡിറ്റ് ചെയ്യുക",
  "Edit Payment": "പേമെന്റ് എഡിറ്റ് ചെയ്യുക",
  "Edit Person": "വ്യക്തി എഡിറ്റ് ചെയ്യുക",
  "Ensure all deposits for the tax year are closed before generating statements.": "സ്റ്റേറ്റ്‌മെന്റ് ഉണ്ടാക്കുന്നതിന് മുൻപ് നികുതി വർഷത്തിലെ എല്ലാ ഡിപ്പോസിറ്റുകളും അടഞ്ഞതാണെന്ന് ഉറപ്പ് വരുത്തൂ.",
  "Export Options": "കയറ്റുമതി ഓപ്ഷനുകൾ",
  "F": "പെ",
  "Failed to save settings": "ക്രമീകരണം സംരക്ഷിക്കൽ പരാജയപ്പെട്ടു",
  "Family Navigation": "കുടുംബ നാവിഗേഷൻ",
  "Feb": "ഫെബ്",
  "File Integrity:": "ഫയൽ ഇൻ്റഗ്രിറ്റി:",
  "Filtering": "ഫിൽട്ടറിംഗ്",
  "Finance": "ധനകാര്യം",
  "Finance Dashboard": "ധനകാര്യ ഡാഷ്‌ബോർഡ്",
  "Force Import": "ബലം ഉപയോഗിച്ച് ഇറക്കുമതി",
  "Force Import will retry and may create duplicate data.": "ബലം ഉപയോഗിച്ചുള്ള ഇറക്കുമതി വീണ്ടും ശ്രമിക്കും, ഡ്യൂപ്ലിക്കേറ്റ് ഡേറ്റ ഉണ്ടാകാം.",
  "Fund Allocation": "ഫണ്ട് വിഹിതം",
  "Generate": "ഉണ്ടാക്കുക",
  "Generate Tax Statements": "നികുതി സ്റ്റേറ്റ്‌മെന്റ് ഉണ്ടാക്കുക",
  "Generate annual giving statements for donors and identify giving patterns.": "ദാതാക്കൾക്ക് വാർഷിക ദക്ഷിണ സ്റ്റേറ്റ്‌മെന്റ് ഉണ്ടാക്കൂ.",
  "Generate annual tax-deductible giving statements for donors. Can be printed or emailed.": "ദാതാക്കൾക്ക് ഇൻകം ടാക്‌സ് ദക്ഷിണ സ്റ്റേറ്റ്‌മെന്റ് ഉണ്ടാക്കൂ. പ്രിന്റ് ചെയ്യാം അല്ലെങ്കിൽ ഇമെയിൽ ചെയ്യാം.",
  "Generate detailed reports for individual deposits or date ranges.": "വ്യക്തിഗത ഡിപ്പോസിറ്റ് അല്ലെങ്കിൽ തീയതി ശ്രേണിക്ക് വിശദ റിപ്പോർട്ട് ഉണ്ടാക്കൂ."
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-13.json', 'w', encoding='utf-8') as f:
    json.dump(translations_13, f, ensure_ascii=False, indent=2)
print("ml-13.json written")
