import json

translations_16 = {
  "needs to be picked up from": "ഇവിടെ നിന്ന് കൂട്ടിക്കൊണ്ടുപോകണം",
  "their classroom": "അവരുടെ ക്ലാസ്‌റൂം",
  "All timezones match": "എല്ലാ ടൈംസോണുകളും ഒത്തുചേരുന്നു",
  "Baseline": "ബേസ്‌ലൈൻ",
  "Browser": "ബ്രൗസർ",
  "Browser differs from system config - dates may display incorrectly for this user.": "ബ്രൗസർ സിസ്റ്റം കോൺഫിഗറേഷനിൽ നിന്ന് വ്യത്യസ്തമാണ് - ഈ ഉപയോക്താവിന് തീയതികൾ തെറ്റായി കാണിക്കാം.",
  "Cannot write to ChurchCRM installation directory. Please check that the web server has write permissions.": "ChurchCRM ഇൻസ്റ്റാളേഷൻ ഡയറക്ടറിയിൽ എഴുതാൻ കഴിഞ്ഞില്ല. വെബ് സർവ്വർ write അനുമതികൾ ഉണ്ടെന്ന് ഉറപ്പ് വരുത്തൂ.",
  "Comparing timezones...": "ടൈംസോണുകൾ താരതമ്യം ചെയ്യുന്നു...",
  "Destination directory does not exist. Please verify ChurchCRM is installed correctly.": "ലക്ഷ്യ ഡയറക്ടറി ഇല്ല. ChurchCRM ശരിയായി ഇൻസ്റ്റാൾ ചെയ്തതാണോ എന്ന് ഉറപ്പ് വരുത്തൂ.",
  "Does not match system config": "സിസ്റ്റം കോൺഫിഗറേഷനുമായി ഒത്തുചേരുന്നില്ല",
  "Downloaded release file is empty. This may be due to network issues or GitHub rate limiting. Please try again later.": "ഡൗൺലോഡ് ചെയ്ത റിലീസ് ഫയൽ ശൂന്യമാണ്. ശൃംഖലാ പ്രശ്‌നം അല്ലെങ്കിൽ GitHub rate limiting ആകാം. പിന്നീട് ശ്രമിക്കൂ.",
  "Extraction completed but upgrade files not found. The upgrade archive may be corrupted.": "എക്‌സ്ട്രാക്ഷൻ പൂർത്തിയായി, പക്ഷേ അപ്‌ഗ്രേഡ് ഫയലുകൾ കണ്ടെത്തിയില്ല. ആർക്കൈവ് കേടായിരിക്കാം.",
  "Failed to apply upgrade. Please check the server logs for details.": "അപ്‌ഗ്രേഡ് പ്രയോഗിക്കൽ പരാജയപ്പെട്ടു. വിശദാംശങ്ങൾക്ക് സർവ്വർ ലോഗ് പരിശോധിക്കൂ.",
  "Failed to create Upgrade directory. Please check file permissions.": "അപ്‌ഗ്രേഡ് ഡയറക്ടറി ഉണ്ടാക്കൽ പരാജയപ്പെട്ടു. ഫയൽ അനുമതി പരിശോധിക്കൂ.",
  "Failed to download the release file from GitHub after multiple attempts. Please check your server's internet connection and try again.": "ഒന്നിലധികം ശ്രമങ്ങൾക്ക് ശേഷം GitHub-ൽ നിന്ന് ഡൗൺലോഡ് ചെയ്യൽ പരാജയപ്പെട്ടു.",
  "Failed to extract upgrade archive. Please check disk space and file permissions.": "അപ്‌ഗ്രേഡ് ആർക്കൈവ് എക്‌സ്ട്രാക്ട് ചെയ്യൽ പരാജയപ്പെട്ടു. ഡിസ്ക് സ്‌പേസ്, ഫയൽ അനുമതി പരിശോധിക്കൂ.",
  "Failed to open upgrade archive. The downloaded file may be corrupted.": "അപ്‌ഗ്രേഡ് ആർക്കൈവ് തുറക്കൽ പരാജയപ്പെട്ടു. ഡൗൺലോഡ് ഫയൽ കേടായിരിക്കാം.",
  "Failed to save the downloaded release file. Please check disk space and permissions.": "ഡൗൺലോഡ് ഫയൽ സംരക്ഷിക്കൽ പരാജയപ്പെട്ടു. ഡിസ്ക് സ്‌പേസ്, അനുമതി പരിശോധിക്കൂ.",
  "Invalid date format in start parameter": "ആരംഭ പാരാമീറ്ററിൽ അസാധുവായ തീയതി ഫോർമാറ്റ്",
  "Mismatch": "ഒത്തുചേർന്നില്ല",
  "Not set": "ക്രമീകരിച്ചിട്ടില്ല",
  "PHP Active": "PHP സജീവം",
  "Source directory does not exist. The upgrade archive may not have extracted correctly. Please check file permissions and disk space.": "ഉറവ ഡയറക്ടറി ഇല്ല. ആർക്കൈവ് ശരിയായി എക്‌സ്ട്രാക്ട് ആകാതിരിക്കാം.",
  "System Config": "സിസ്റ്റം കോൺഫിഗ്",
  "Timezone Information": "ടൈംസോൺ വിവരം",
  "Timezone mismatch detected": "ടൈംസോൺ ഒത്തുചേർന്നില്ല",
  "mismatch detected": "ഒത്തുചേർന്നില്ല",
  "mismatches detected": "ഒത്തുചേർന്നില്ല",
  "%d hour": "%d മണിക്കൂർ",
  "About WebDAV Backups": "WebDAV ബാക്കപ്പിനെ കുറിച്ച്",
  "Add Link": "ലിങ്ക് ചേർക്കുക",
  "Add an extra layer of security to your account": "നിങ്ങളുടെ അക്കൗണ്ടിൽ ഒരു അധിക സുരക്ഷ ലേഖ ചേർക്കൂ",
  "Add custom external links to the navigation menu.": "നാവിഗേഷൻ മെനുവിൽ ഇഷ്‌ടാനുസൃത ബാഹ്യ ലിങ്കുകൾ ചേർക്കൂ.",
  "Allow Self-Signed Certificates": "സ്വ-ഒപ്പ് സർട്ടിഫിക്കറ്റ് അനുവദിക്കൂ",
  "An error occurred processing the plugin request": "പ്ലഗ്-ഇൻ അഭ്യർത്ഥന പ്രോസസ് ചെയ്യുന്നതിൽ ഒരു പിശക് ഉണ്ടായി",
  "Are you sure you want to disable two-factor authentication? Your account will be less secure.": "ഇരട്ടഘടക ആധികാരികത പ്രവർത്തനരഹിതമാക്കണോ? നിങ്ങളുടെ അക്കൗണ്ട് കുറഞ്ഞ സുരക്ഷ ആകും.",
  "As part of the restore, external backups have been disabled. If you wish to continue automatic backups, re-enable the External Backup plugin in Admin > Plugins.": "പുനഃസ്ഥാപനത്തിന്റെ ഭാഗമായി ബാഹ്യ ബാക്കപ്പ് പ്രവർത്തനരഹിതമാക്കി. Auto ബാക്കപ്പ് തുടരാൻ External Backup plugin വീണ്ടും പ്രവർത്തനക്ഷമമാക്കൂ.",
  "Audiences": "ഓഡിയൻസ്",
  "Authentication failed. Please check username and password.": "ആധികാരികത പരാജയപ്പെട്ടു. ഉപയോക്തൃനാമവും പാസ്‌വേഡും പരിശോധിക്കൂ.",
  "Auto-Backup Interval": "ഓട്ടോ-ബാക്കപ്പ് ഇടവേള",
  "Automatically backup your ChurchCRM database to external cloud storage via WebDAV.": "WebDAV വഴി ChurchCRM ഡേറ്റാബേസ് ബാഹ്യ ക്ലൗഡ് സ്‌റ്റോറേജിൽ സ്വയം ബാക്കപ്പ് ചെയ്യൂ.",
  "Avg Click Rate": "ശരാശരി ക്ലിക്ക് നിരക്ക്",
  "Avg Open Rate": "ശരാശരി ഓപ്പൺ നിരക്ക്",
  "Back to Dashboard": "ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക",
  "Backup created but failed to copy to remote server": "ബാക്കപ്പ് ഉണ്ടാക്കി, ദൂര സർവ്വറിൽ കോപ്പി ചെയ്യൽ പരാജയപ്പെട്ടു",
  "Backup to WebDAV Now": "ഇപ്പോൾ WebDAV-ലേക്ക് ബാക്കപ്പ്",
  "Before You Start": "ആരംഭിക്കുന്നതിന് മുൻപ്",
  "Browser language preference detected": "ബ്രൗസർ ഭാഷ മുൻഗണന കണ്ടെത്തി",
  "CRM Members Not Subscribed": "CRM അംഗങ്ങൾ സബ്‌സ്‌ക്രൈബ് ചെയ്തിട്ടില്ല",
  "Campaigns Sent": "കാമ്പെയ്‌നുകൾ അയച്ചു",
  "Can't scan?": "സ്കാൻ ചെയ്യാൻ കഴിഞ്ഞില്ലേ?",
  "Change Your Locale": "ലോക്കൽ മാറ്റൂ",
  "ChurchCRM supports a plugin architecture for extending functionality.": "ChurchCRM ഫംഗ്‌ഷണാലിറ്റി വിപുലീകരിക്കാൻ ഒരു പ്ലഗ്-ഇൻ ആർക്കിടെക്ചർ പിന്തുണ ചെയ്യുന്നു.",
  "Cleaned": "ക്ലീൻ ചെയ്തു",
  "Click the button below to test your WebDAV connection settings.": "WebDAV ബന്ധ ക്രമീകരണം പരിശോധിക്കാൻ താഴെ ബട്ടൺ ക്ലിക്ക് ചെയ്യൂ.",
  "Community Plugins": "കമ്മ്യൂണിറ്റി പ്ലഗ്-ഇനുകൾ",
  "Community plugins": "കമ്മ്യൂണിറ്റി പ്ലഗ്-ഇനുകൾ",
  "Configure External Backup": "ബാഹ്യ ബാക്കപ്പ് ക്രമീകരിക്കൂ",
  "Configure MailChimp": "MailChimp ക്രമീകരിക്കൂ",
  "Configure these settings in the": "ഈ ക്രമീകരണങ്ങൾ ഇതിൽ ക്രമീകരിക്കൂ",
  "Configure this plugin to automatically backup your ChurchCRM database to WebDAV-compatible cloud storage services like Nextcloud, ownCloud, or any WebDAV server. Backups are encrypted during transfer using HTTPS.": "ChurchCRM ഡേറ്റാബേസ് Nextcloud, ownCloud തുടങ്ങിയ WebDAV ക്ലൗഡ് സ്‌റ്റോറേജിൽ ബാക്കപ്പ് ചെയ്യാൻ ഈ പ്ലഗ്-ഇൻ ക്രമീകരിക്കൂ.",
  "Configured": "ക്രമീകരിച്ചു",
  "Confirm with a code from your authenticator app": "ഓതന്റിക്കേറ്റർ ആപ്പിൽ നിന്ന് ഒരു കോഡ് ഉപയോഗിച്ച് സ്ഥിരീകരിക്കൂ",
  "Connected": "ബന്ധിച്ചു",
  "Connection failed": "ബന്ധം പരാജയപ്പെട്ടു",
  "Connection failed with HTTP code": "HTTP കോഡ് ഉപയോഗിച്ച് ബന്ധം പരാജയപ്പെട്ടു",
  "Connection successful! WebDAV endpoint is accessible.": "ബന്ധം വിജയകരം! WebDAV എൻഡ്‌പോയിന്റ് ആക്സസ് ചെയ്യാം.",
  "Connection test failed": "ബന്ധ പരിശോധന പരാജയപ്പെട്ടു",
  "Core Plugins": "കോർ പ്ലഗ്-ഇനുകൾ",
  "Core plugins": "കോർ പ്ലഗ്-ഇനുകൾ",
  "Create a backup now and upload it to your WebDAV server.": "ഇപ്പോൾ ഒരു ബാക്കപ്പ് ഉണ്ടാക്കി WebDAV സർവ്വറിൽ അപ്‌ലോഡ് ചെയ്യൂ.",
  "Create an Audience in MailChimp": "MailChimp-ൽ ഒരു ഓഡിയൻസ് ഉണ്ടാക്കൂ",
  "Custom": "ഇഷ്‌ടാനുസൃതം",
  "Custom Menu Links": "ഇഷ്‌ടാനുസൃത മെനു ലിങ്കുകൾ",
  "Default Image Style": "ഡിഫോൾട്ട് ചിത്ര ശൈലി",
  "Default List ID": "ഡിഫോൾട്ട് ലിസ്‌റ്റ് ID",
  "Disable": "പ്രവർത്തനരഹിതമാക്കൂ",
  "Disable Plugin": "പ്ലഗ്-ഇൻ പ്രവർത്തനരഹിതമാക്കൂ",
  "Disable Two-Factor Authentication": "ഇരട്ടഘടക ആധികാരികത പ്രവർത്തനരഹിതമാക്കൂ",
  "Dismiss": "ഒഴിവാക്കൂ",
  "Done": "പൂർത്തിയായി",
  "Each plugin requires a": "ഓരോ പ്ലഗ്-ഇനിനും ആവശ്യമാണ്",
  "Each time you sign in, you'll need to confirm with a code from your authenticator app": "ഓരോ ലോഗ്-ഇൻ സമയത്തും ഓതന്റിക്കേറ്റർ ആപ്പ് കോഡ് ഉപയോഗിച്ച് സ്ഥിരീകരിക്കണം",
  "Email Addresses": "ഇമെയിൽ വിലാസങ്ങൾ",
  "Enable": "പ്രവർത്തനക്ഷമമാക്കൂ",
  "Enable External Backup Plugin": "ബാഹ്യ ബാക്കപ്പ് പ്ലഗ്-ഇൻ പ്രവർത്തനക്ഷമമാക്കൂ",
  "Enable Plugin": "പ്ലഗ്-ഇൻ പ്രവർത്തനക്ഷമമാക്കൂ",
  "Enable Two-Factor Authentication": "ഇരട്ടഘടക ആധികാരികത പ്രവർത്തനക്ഷമമാക്കൂ",
  "Enable this only for local network servers with self-signed SSL certificates. Disables certificate verification.": "ഇത് സ്വ-ഒപ്പ് SSL ഉള്ള ലോക്കൽ നെറ്റ്‌വർക്ക് സർവ്വർ ഉള്ളവർ മാത്രം ഉപയോഗിക്കൂ.",
  "Endpoint URL": "എൻഡ്‌പോയിന്റ് URL",
  "Enter the 6-digit code from your authenticator app": "ഓതന്റിക്കേറ്റർ ആപ്പിൽ നിന്ന് 6-അക്ക കോഡ് നൽകൂ",
  "Enter your username and password as usual": "പതിവ് പോലെ ഉപയോക്തൃനാമവും പാസ്‌വേഡും നൽകൂ",
  "External Backup": "ബാഹ്യ ബാക്കപ്പ്",
  "External Backup (WebDAV)": "ബാഹ്യ ബാക്കപ്പ് (WebDAV)",
  "External Backup Settings": "ബാഹ്യ ബാക്കപ്പ് ക്രമീകരണങ്ങൾ",
  "External Backup plugin is not configured. Please configure WebDAV settings in the plugin.": "ബാഹ്യ ബാക്കപ്പ് പ്ലഗ്-ഇൻ ക്രമീകരിച്ചിട്ടില്ല. ദയവായി WebDAV ക്രമീകരണങ്ങൾ ക്രമീകരിക്കൂ.",
  "External Backup plugin is not enabled. Please enable and configure it in Plugin Management.": "ബാഹ്യ ബാക്കപ്പ് പ്ലഗ്-ഇൻ പ്രവർത്തനക്ഷമമല്ല. ദയവായി Plugin Management-ൽ ക്രമീകരിക്കൂ.",
  "Failed to create link": "ലിങ്ക് ഉണ്ടാക്കൽ പരാജയപ്പെട്ടു",
  "Failed to delete link": "ലിങ്ക് ഇല്ലാതാക്കൽ പരാജയപ്പെട്ടു",
  "Failed to disable plugin": "പ്ലഗ്-ഇൻ പ്രവർത്തനരഹിതമാക്കൽ പരാജയപ്പെട്ടു",
  "Failed to enable plugin": "പ്ലഗ്-ഇൻ പ്രവർത്തനക്ഷമമാക്കൽ പരാജയപ്പെട്ടു",
  "Failed to get plugin details": "പ്ലഗ്-ഇൻ വിശദാംശങ്ങൾ ലഭ്യമാക്കൽ പരാജയപ്പെട്ടു",
  "Failed to list plugins": "പ്ലഗ്-ഇനുകൾ ലിസ്‌റ്റ് ചെയ്യൽ പരാജയപ്പെട്ടു",
  "Failed to reset settings": "ക്രമീകരണങ്ങൾ റീസെറ്റ് ചെയ്യൽ പരാജയപ്പെട്ടു",
  "Family Status": "കുടുംബ സ്ഥിതി",
  "Family not found": "കുടുംബം കണ്ടെത്തിയില്ല",
  "Find in MailChimp: Audience > Settings > Audience name and defaults > Audience ID": "MailChimp-ൽ: Audience > Settings > Audience name and defaults > Audience ID",
  "From Phone Number": "ഫോൺ നമ്പറിൽ നിന്ന്",
  "From dashboard.vonage.com": "dashboard.vonage.com-ൽ നിന്ന്",
  "GA4 Measurement ID": "GA4 Measurement ID",
  "Generate new code": "പുതിയ കോഡ് ഉണ്ടാക്കൂ",
  "Get Started": "ആരംഭിക്കൂ",
  "Get your API key from MailChimp: Account Settings > Extras > API Keys": "MailChimp-ൽ നിന്ന് API key ലഭ്യമാക്കൂ: Account Settings > Extras > API Keys",
  "Have your authenticator app ready (Google Authenticator, Microsoft Authenticator, Authy, etc.)": "ഓതന്റിക്കേറ്റർ ആപ്പ് തയ്യാറാക്കൂ (Google Authenticator, Microsoft Authenticator, Authy, തുടങ്ങിയവ)",
  "Help": "സഹായം",
  "Id": "ID",
  "Image shown when no Gravatar exists for the email address": "ഇമെയിൽ വിലാസത്തിന് Gravatar ഇല്ലാതിരുന്നാൽ കാണിക്കുന്ന ചിത്രം",
  "Important": "പ്രധാനം",
  "Install plugins by placing them in": "ഇതിൽ ഇടൂ, പ്ലഗ്-ഇനുകൾ ഇൻസ്റ്റാൾ ആകും",
  "Invalid code. Please try again.": "അസാധുവായ കോഡ്. വീണ്ടും ശ്രമിക്കൂ.",
  "Invalid endpoint URL. Must be a full URL starting with https:// (e.g., https://cloud.example.com/remote.php/dav/files/user/backups/)": "അസാധുവായ endpoint URL. https:// ൽ ആരംഭിക്കേണ്ടതാണ്.",
  "Kiosk device not found": "കിയോസ്‌ക് ഉപകരണം കണ്ടെത്തിയില്ല",
  "Last Backup": "അവസാന ബാക്കപ്പ്",
  "Last Campaign": "അവസാന കാമ്പെയ്‌ൻ",
  "Last Subscriber": "അവസാന സബ്‌സ്‌ക്രൈബർ",
  "Last Successful Backup": "അവസാനമായി വിജയകരമായ ബാക്കപ്പ്",
  "Last campaign": "അവസാന കാമ്പെയ്‌ൻ",
  "Link Name": "ലിങ്ക് നാമം",
  "Link address cannot contain HTML tags": "ലിങ്ക് വിലാസം HTML ടാഗ് ഉൾക്കൊള്ളരുത്",
  "Link address is required": "ലിങ്ക് വിലാസം ആവശ്യമാണ്",
  "Link must be a valid URL": "ലിങ്ക് സാധുവായ URL ആയിരിക്കണം",
  "Link must start with http:// or https://": "ലിങ്ക് http:// അല്ലെങ്കിൽ https:// ൽ ആരംഭിക്കണം",
  "Link not found": "ലിങ്ക് കണ്ടെത്തിയില്ല",
  "Loading recovery codes": "Recovery കോഡ് ലോഡ് ചെയ്യുന്നു",
  "MailChimp": "MailChimp",
  "MailChimp API Key": "MailChimp API Key",
  "MailChimp Dashboard": "MailChimp ഡാഷ്‌ബോർഡ്",
  "Manage Links": "ലിങ്കുകൾ മാനേജ് ചെയ്യുക",
  "Manage Two-Factor Authentication": "ഇരട്ടഘടക ആധികാരികത മാനേജ് ചെയ്യൂ",
  "Manual Backup": "മാനുവൽ ബാക്കപ്പ്",
  "Menu Links": "മെനു ലിങ്കുകൾ",
  "Menu name cannot contain HTML tags": "മെനു പേര് HTML ടാഗ് ഉൾക്കൊള്ളരുത്",
  "Menu name is required": "മെനു പേര് ആവശ്യമാണ്",
  "Menu name must be 50 characters or less": "മെനു പേര് 50 അക്ഷരമോ കുറവോ ആയിരിക്കണം",
  "Menu name must be at least 2 characters": "മെനു പേര് കുറഞ്ഞത് 2 അക്ഷരം ആയിരിക്കണം",
  "Must start with http:// or https://": "http:// അല്ലെങ്കിൽ https:// ൽ ആരംഭിക്കണം",
  "Needs Configuration": "ക്രമീകരണം ആവശ്യമാണ്",
  "Never": "ഒരിക്കലും ഇല്ല",
  "No Audiences Found": "ഓഡിയൻസ് കണ്ടെത്തിയില്ല",
  "No backups recorded": "ബാക്കപ്പ് രേഖപ്പെടുത്തിയില്ല"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-16.json', 'w', encoding='utf-8') as f:
    json.dump(translations_16, f, ensure_ascii=False, indent=2)
print("ml-16.json written")
