import json

translations_14 = {
  "Generate reminder letters for families with outstanding pledges.": "കുടിശ്ശിക സംഭാവന പ്രതിജ്ഞകളുള്ള കുടുംബങ്ങൾക്ക് ഓർമ്മിപ്പിക്കൽ കത്തുകൾ ഉണ്ടാക്കൂ.",
  "Generate reports for tax statements, pledge tracking, and financial analysis.": "നികുതി സ്റ്റേറ്റ്‌മെന്റ്, പ്രതിജ്ഞ ട്രാക്കിംഗ്, സാമ്പത്തിക വിശകലനം എന്നിവയ്ക്ക് റിപ്പോർട്ട് ഉണ്ടാക്കൂ.",
  "ID": "ID",
  "Identify members who have not made any donations within a date range.": "ഒരു തീയതി ശ്രേണിക്കുള്ളിൽ ഒരു സംഭാവനയും നൽകാത്ത അംഗങ്ങളെ കണ്ടെത്തൂ.",
  "Import failed": "ഇറക്കുമതി പരാജയപ്പെട്ടു",
  "Jan": "ജനു",
  "Jr., Sr.": "ജൂ., സീ.",
  "Jul": "ജൂലൈ",
  "Jun": "ജൂൺ",
  "Let's get your system set up and ready to use": "നിങ്ങളുടെ സിസ്റ്റം ക്രമീകരിക്കാം",
  "List members eligible to vote based on giving history and membership criteria.": "ദക്ഷിണ ചരിത്രം, അംഗത്വ മാനദണ്ഡങ്ങൾ അനുസരിച്ച് വോട്ടർ അർഹതയുള്ള അംഗങ്ങൾ ലിസ്‌റ്റ് ചെയ്യൂ.",
  "Location": "സ്ഥാനം",
  "M": "ആ",
  "Manage Funds": "ഫണ്ടുകൾ മാനേജ് ചെയ്യുക",
  "Mar": "മാർ",
  "Membership Reports": "അംഗത്വ റിപ്പോർട്ടുകൾ",
  "Most reports can be exported as PDF for printing or CSV for spreadsheet analysis.": "മിക്ക റിപ്പോർട്ടുകളും PDF ആയി അല്ലെങ്കിൽ CSV ആയി കയറ്റുമതി ചെയ്യാം.",
  "Mr., Mrs., Dr.": "ശ്രീ., ശ്രീമതി., ഡോ.",
  "Name & Identity": "പേര് & ഐഡൻ്റിറ്റി",
  "New Deposit Will Be Created": "പുതിയ ഡിപ്പോസിറ്റ് ഉണ്ടാക്കും",
  "New Payment": "പുതിയ പേമെന്റ്",
  "New Pledge": "പുതിയ സംഭാവന പ്രതിജ്ഞ",
  "No Active Deposit": "സജീവ ഡിപ്പോസിറ്റ് ഇല്ല",
  "No active funds configured.": "സജീവ ഫണ്ടുകൾ ക്രമീകരിച്ചിട്ടില്ല.",
  "No deposits found.": "ഡിപ്പോസിറ്റുകൾ കണ്ടെത്തിയില്ല.",
  "No format": "ഫോർമാറ്റ് ഇല്ല",
  "Nov": "നവ",
  "Oct": "ഒക്ടോ",
  "Open": "തുറക്കുക",
  "Open Deposits:": "തുറന്ന ഡിപ്പോസിറ്റുകൾ:",
  "Orphaned Files:": "അനാഥ ഫയലുകൾ:",
  "PDF/CSV": "PDF/CSV",
  "Payment": "പേമെന്റ്",
  "Pledge Reports": "സംഭാവന പ്രതിജ്ഞ റിപ്പോർട്ടുകൾ",
  "Print or email annual giving statements to all donors.": "എല്ലാ ദാതാക്കൾക്കും വാർഷിക ദക്ഷിണ സ്റ്റേറ്റ്‌മെന്റ് പ്രിന്റ് ചെയ്യൂ അല്ലെങ്കിൽ ഇമെയിൽ ചെയ്യൂ.",
  "Quick Actions": "ദ്രുത പ്രവർത്തനങ്ങൾ",
  "Quick Start": "ദ്രുത ആരംഭം",
  "Recent Deposits": "സമീപ ഡിപ്പോസിറ്റുകൾ",
  "Recording a Payment": "ഒരു പേമെന്റ് രേഖപ്പെടുത്തൽ",
  "Recording a Pledge": "ഒരു സംഭാവന പ്രതിജ്ഞ രേഖപ്പെടുത്തൽ",
  "Report Tips": "റിപ്പോർട്ട് നുറുങ്ങുകൾ",
  "Reports related to member voting eligibility and organization governance.": "അംഗ വോട്ടിംഗ് അർഹതയും ഓർഗനൈസേഷൻ ഭരണവും സംബന്ധിച്ച റിപ്പോർട്ടുകൾ.",
  "Reset": "റീസെറ്റ്",
  "Restore": "പുനഃസ്ഥാപിക്കുക",
  "Restore from a backup file. Erases existing data.": "ഒരു ബാക്കപ്പ് ഫയലിൽ നിന്ന് പുനഃസ്ഥാപിക്കൂ. നിലവിലുള്ള ഡേറ്റ മായ്ക്കും.",
  "Review Donation Funds": "സംഭാവന ഫണ്ടുകൾ അവലോകനം ചെയ്യുക",
  "Save and Add New Family": "സംരക്ഷിച്ച് പുതിയ കുടുംബം ചേർക്കുക",
  "Sep": "സെപ്",
  "Server error": "സർവ്വർ പിശക്",
  "Settings": "ക്രമീകരണങ്ങൾ",
  "Settings saved successfully": "ക്രമീകരണങ്ങൾ വിജയകരമായി സംരക്ഷിച്ചു",
  "Social Media": "സോഷ്യൽ മീഡിയ",
  "Some application prerequisites are not met": "ചില ആപ്ലിക്കേഷൻ ആവശ്യകതകൾ നിറവേറ്റിയിട്ടില്ല",
  "State (Other)": "സംസ്ഥാനം (മറ്റ്)",
  "Status:": "സ്ഥിതി:",
  "Summary of pledges vs payments by fund for the fiscal year.": "ധനകാര്യ വർഷത്തിലെ ഫണ്ട് അനുസരിച്ചുള്ള സംഭാവന പ്രതിജ്ഞ vs പേമെന്റ് സംഗ്രഹം.",
  "System Configuration:": "സിസ്റ്റം കോൺഫിഗറേഷൻ:",
  "System Health": "സിസ്റ്റം ആരോഗ്യം",
  "System Info": "സിസ്റ്റം വിവരം",
  "Tax & Giving Reports": "നികുതി & ദക്ഷിണ റിപ്പോർട്ടുകൾ",
  "Tax Report Verbiage": "നികുതി റിപ്പോർട്ട് ഉള്ളടക്കം",
  "Tax Statements (Giving Report)": "നികുതി സ്റ്റേറ്റ്‌മെന്റ് (ദക്ഷിണ റിപ്പോർട്ട്)",
  "Tax Year Reporting Checklist": "നികുതി വർഷ റിപ്പോർട്ടിംഗ് ചെക്‌ലിസ്‌റ്റ്",
  "Today": "ഇന്ന്",
  "Total": "ആകെ",
  "Total Amount": "ആകെ തുക",
  "Total Deposits:": "ആകെ ഡിപ്പോസിറ്റുകൾ:",
  "Track pledges and payment progress for campaigns and fiscal year budgeting.": "പ്രചാരണങ്ങൾക്കും ധനകാര്യ വർഷ ബജറ്റിനും സംഭാവന പ്രതിജ്ഞ, പേമെന്റ് പുരോഗതി ട്രാക്ക് ചെയ്യൂ.",
  "Type:": "തരം:",
  "Unmet Prerequisites": "നിറവേറ്റാത്ത ആവശ്യകതകൾ",
  "Upgrade": "അപ്‌ഗ്രേഡ്",
  "Use classification and family filters to generate reports for specific groups of donors.": "ദാതാക്കളുടെ പ്രത്യേക ഗ്രൂപ്പുകൾക്ക് റിപ്പോർട്ട് ഉണ്ടാക്കാൻ വർഗ്ഗീകരണ, കുടുംബ ഫിൽട്ടറുകൾ ഉപയോഗിക്കൂ.",
  "User must be an Admin or have Finance permission": "ഉപയോക്താവ് അഡ്‌മിൻ ആകണം അല്ലെങ്കിൽ ധനകാര്യ അനുമതി ഉണ്ടായിരിക്കണം",
  "Verify church name, address, and contact info appears on tax statements.": "നികുതി സ്റ്റേറ്റ്‌മെന്റിൽ പള്ളി പേര്, വിലാസം, ബന്ധ വിവരം ശരിയാണെന്ന് ഉറപ്പ് വരുത്തൂ.",
  "Verify fund names and descriptions are accurate for statements.": "സ്റ്റേറ്റ്‌മെന്റിൽ ഫണ്ട് പേരുകളും വിവരണങ്ങളും കൃത്യമാണെന്ന് ഉറപ്പ് വരുത്തൂ.",
  "Version:": "പതിപ്പ്:",
  "YTD Payments": "ഇക്കൊല്ലം (YTD) പേമെന്റ്",
  "YTD Pledges": "ഇക്കൊല്ലം (YTD) സംഭാവന പ്രതിജ്ഞ",
  "You may create family members now or add them later. All entries will become new person records.": "ഇപ്പോൾ കുടുംബ അംഗങ്ങളെ ഉണ്ടാക്കൂ അല്ലെങ്കിൽ പിന്നീട് ചേർക്കൂ.",
  "Your fiscal year starts in month": "നിങ്ങളുടെ ധനകാര്യ വർഷം ആരംഭിക്കുന്ന മാസം",
  "ZipArchive extension required for upgrades": "അപ്‌ഗ്രേഡിന് ZipArchive എക്സ്‌റ്റൻഷൻ ആവശ്യമാണ്",
  "active": "സജീവം",
  "ago": "മുൻപ്",
  "day": "ദിവസം",
  "days": "ദിവസങ്ങൾ",
  "found": "കണ്ടെത്തി",
  "in": "ൽ",
  "issues": "പ്രശ്‌നങ്ങൾ",
  "open": "തുറക്കുക",
  "years": "വർഷങ്ങൾ",
  "(Enter state/province for countries without predefined states)": "(മുൻ-നിശ്ചിത സംസ്ഥാനങ്ങൾ ഇല്ലാത്ത രാജ്യങ്ങൾക്ക് സംസ്ഥാനം/പ്രവിശ്യ നൽകൂ)",
  "Base URL configuration is invalid. Please check your Config.php file.": "അടിസ്ഥാന URL കോൺഫിഗറേഷൻ അസാധുവാണ്. Config.php ഫയൽ പരിശോധിക്കൂ.",
  "Base URL is not configured in Config.php": "Config.php ൽ അടിസ്ഥാന URL ക്രമീകരിച്ചിട്ടില്ല",
  "ChurchCRM Supported Locales": "ChurchCRM പിന്തുണ ലോക്കലുകൾ",
  "Connect to your server via SSH, FTP, or your hosting control panel": "SSH, FTP, അല്ലെങ്കിൽ ഹോസ്‌റ്റിംഗ് കൺട്രോൾ പാനൽ വഴി സർവ്വറിലേക്ക് ബന്ധിക്കൂ",
  "Contact": "ബന്ധം",
  "Critical Configuration Error": "ഗുരുതര കോൺഫിഗറേഷൻ പിശക്",
  "Current $URL[0] value:": "നിലവിലെ $URL[0] മൂല്യം:",
  "Custom port:": "ഇഷ്‌ടാനുസൃത പോർട്ട്:",
  "Ends with a <strong>trailing slash</strong> (/)": "<strong>ട്രെയിലിംഗ് സ്ലാഷ്</strong> (/) ൽ അവസാനിക്കുന്നു",
  "Error:": "പിശക്:",
  "Find the line:": "ഈ വരി കണ്ടെത്തൂ:",
  "Group Memberships": "ഗ്രൂപ്പ് അംഗത്വങ്ങൾ",
  "How to Fix:": "ഇത് എങ്ങനെ ശരിയാക്കാം:",
  "Join the ChurchCRM community and help us improve by sharing your information. It takes less than a minute!": "ChurchCRM കമ്മ്യൂണിറ്റിയിൽ ചേരൂ, വിവരം പങ്കുവെക്കൂ. ഒരു മിനിറ്റ് ആകില്ല!",
  "Language": "ഭാഷ",
  "Local development:": "ലോക്കൽ ഡെവലപ്‌മെന്റ്:",
  "Locale Support": "ലോക്കൽ പിന്തുണ",
  "Location & Contact Information": "സ്ഥാനവും ബന്ധ വിവരവും",
  "New to": "പുതിയ",
  "No locales configured": "ലോക്കലുകൾ ക്രമീകരിച്ചിട്ടില്ല",
  "Register Now": "ഇപ്പോൾ രജിസ്‌ട്രേഷൻ",
  "Register Your Church": "നിങ്ങളുടെ പള്ളി രജിസ്‌ട്രേഷൻ ചെയ്യൂ",
  "Save the file and refresh this page": "ഫയൽ സംരക്ഷിച്ച് ഈ പേജ് പുതുക്കൂ",
  "Starts with <strong>http://</strong> or <strong>https://</strong>": "<strong>http://</strong> അല്ലെങ്കിൽ <strong>https://</strong> ൽ ആരംഭിക്കുന്നു",
  "System Locale Support": "സിസ്റ്റം ലോക്കൽ പിന്തുണ",
  "URL does not contain a valid hostname": "URL-ൽ സാധുവായ ഹോസ്‌ട്ട്‌നെയ്‌മ് ഇല്ല",
  "URL hostname is not valid": "URL ഹോസ്‌ട്ട്‌നെയ്‌മ് സാധുവല്ല",
  "URL is not in valid format": "URL സാധുവായ ഫോർമാറ്റിൽ അല്ല",
  "URL must end with a trailing slash (/)": "URL ഒരു ട്രെയിലിംഗ് സ്ലാഷ് (/) ൽ അവസാനിക്കണം",
  "URL must start with http:// or https://": "URL http:// അല്ലെങ്കിൽ https:// ൽ ആരംഭിക്കണം",
  "Unable to load state list. Please check your network connection or try again later.": "സംസ്ഥാന ലിസ്‌റ്റ് ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല. നെറ്റ്‌വർക്ക് ബന്ധം പരിശോധിക്കൂ.",
  "Update it to a valid URL that:": "ഒരു സാധുവായ URL-ലേക്ക് അപ്‌ഡേറ്റ് ചെയ്യൂ:",
  "Valid Examples:": "സാധുവായ ഉദാഹരണങ്ങൾ:",
  "View Logs": "ലോഗ് കാണുക",
  "View and manage system log files for debugging.": "ഡീബഗ്ഗിംഗിന് സിസ്റ്റം ലോഗ് ഫയലുകൾ കാണൂ, മാനേജ് ചെയ്യൂ.",
  "You must enter a Last Name.": "ഒരു കുടുംബപ്പേര് നൽകണം.",
  "Your privacy is important. We never share your information with third parties.": "നിങ്ങളുടെ സ്വകാര്യത പ്രധാനമാണ്. ഞങ്ങൾ ഒരിക്കലും മൂന്നാം കക്ഷികളുമായി വിവരം പങ്കുവെക്കില്ല.",
  "Additional Information": "അധിക വിവരം",
  "All information is correct": "എല്ലാ വിവരവും ശരിയാണ്",
  "Assign Opportunities": "അവസരങ്ങൾ നൽകുക",
  "Choose a property...": "ഒരു സ്വഭാവം തിരഞ്ഞെടുക്കൂ...",
  "Choose opportunities...": "അവസരങ്ങൾ തിരഞ്ഞെടുക്കൂ...",
  "Confirm Family Information": "കുടുംബ വിവരം സ്ഥിരീകരിക്കുക",
  "Confirm family information": "കുടുംബ വിവരം സ്ഥിരീകരിക്കുക",
  "Contact & Personal Info": "ബന്ധ & വ്യക്തിഗത വിവരം",
  "Copied!": "കോപ്പി ചെയ്തു!",
  "Edited": "എഡിറ്റ് ചെയ്തു",
  "Email PDF": "PDF ഇമെയിൽ ചെയ്യുക",
  "Failed to copy URL": "URL കോപ്പി ചെയ്യൽ പരാജയപ്പെട്ടു",
  "Newsletter": "ന്യൂസ്‌ലെറ്റർ",
  "Open in New Tab": "പുതിയ ടാബിൽ തുറക്കുക",
  "Personal": "വ്യക്തിഗതം",
  "Please confirm your family information:": "ദയവായി നിങ്ങളുടെ കുടുംബ വിവരം സ്ഥിരീകരിക്കൂ:",
  "Please update our records with corrections": "ദയവായി ഞങ്ങളുടെ രേഖകൾ ശരിയാക്കൂ",
  "Provide any corrections or additional information here...": "ഇവിടെ ഏതെങ്കിലും തിരുത്തൽ അല്ലെങ്കിൽ അധിക വിവരം നൽകൂ...",
  "Remove Property": "സ്വഭാവം നീക്കം ചെയ്യുക",
  "Select Opportunities": "അവസരങ്ങൾ തിരഞ്ഞെടുക്കൂ",
  "Share this URL with family members to verify their information": "ഈ URL കുടുംബ അംഗങ്ങൾക്ക് അവരുടെ വിവരം സ്ഥിരീകരിക്കാൻ പങ്കിടൂ",
  "Submit Verification": "സ്ഥിരീകരണം സമർപ്പിക്കുക"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-14.json', 'w', encoding='utf-8') as f:
    json.dump(translations_14, f, ensure_ascii=False, indent=2)
print("ml-14.json written")
