import json

translations_3 = {
  "Export Selected Rows (OFX)": "തിരഞ്ഞെടുത്ത വരികൾ കയറ്റുമതി ചെയ്യുക (OFX)",
  "Export Selected Rows (CSV)": "തിരഞ്ഞെടുത്ത വരികൾ കയറ്റുമതി ചെയ്യുക (CSV)",
  "Fundraiser Listing": "ഫണ്ട്‌റൈസർ ലിസ്‌റ്റ്",
  "Date Start": "ആരംഭ തീയതി",
  "Apply Filters": "ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക",
  "Date End": "അവസാന തീയതി",
  "Clear Filter": "ഫിൽട്ടർ ക്ലിയർ ചെയ്യുക",
  "Number": "നമ്പർ",
  "Create New Fund Raiser": "പുതിയ ഫണ്ട്‌റൈസർ ഉണ്ടാക്കുക",
  "Add Donated Item": "സംഭാവന വസ്തു ചേർക്കുക",
  "Generate Catalog": "കാറ്റലോഗ് ഉണ്ടാക്കുക",
  "Generate Bid Sheets": "ബിഡ് ഷീറ്റുകൾ ഉണ്ടാക്കുക",
  "Generate Certificates": "സർട്ടിഫിക്കറ്റുകൾ ഉണ്ടാക്കുക",
  "Donated items for this fundraiser": "ഈ ഫണ്ട്‌റൈസറിനായി സംഭാവന ചെയ്ത വസ്തുക്കൾ",
  "Donor": "ദാതാവ്",
  "Buyer": "വാങ്ങുന്നയാൾ",
  "Sale Price": "വിൽപ്പന വില",
  "Material Value": "ഭൗതിക മൂല്യം",
  "Minimum Price": "ഏറ്റവും കുറഞ്ഞ വില",
  "Family Geographic Utilities": "കുടുംബ ഭൂമിശാസ്ത്ര ഉപകരണങ്ങൾ",
  "Select Family": "കുടുംബം തിരഞ്ഞെടുക്കുക",
  "Maximum number of neighbors": "ഏറ്റവും കൂടിയ അയൽക്കാരുടെ എണ്ണം",
  "Maximum distance": "ഏറ്റവും കൂടിയ ദൂരം",
  "Data file format": "ഡേറ്റ ഫയൽ ഫോർമാറ്റ്",
  "GPS Visualizer": "GPS വിഷ്വലൈസർ",
  "Street Atlas USA": "Street Atlas USA",
  "Include families in the coordinate file": "കോർഡിനേറ്റ് ഫയലിൽ കുടുംബങ്ങൾ ഉൾപ്പെടുത്തുക",
  "Neighbor Families": "അയൽ കുടുംബങ്ങൾ",
  "Make Data File": "ഡേറ്റ ഫയൽ ഉണ്ടാക്കുക",
  "Show Neighbors": "അയൽക്കാരെ കാണിക്കുക",
  "Distance": "ദൂരം",
  "Direction": "ദിശ",
  "Latitude": "അക്ഷാംശം",
  "Longitude": "രേഖാംശം",
  "Add to Cart": "കാർട്ടിൽ ചേർക്കുക",
  "Intersect with Cart": "കാർട്ടുമായി വിഭജിക്കുക",
  "Remove from Cart": "കാർട്ടിൽ നിന്ന് നീക്കം ചെയ്യുക",
  "Group Editor": "ഗ്രൂപ്പ് എഡിറ്റർ",
  "Group Settings": "ഗ്രൂപ്പ് ക്രമീകരണങ്ങൾ",
  "Type of Group": "ഗ്രൂപ്പ് തരം",
  "Group Member Roles": "ഗ്രൂപ്പ് അംഗ പങ്കുകൾ",
  "Clone roles": "പങ്കുകൾ ക്ലോൺ ചെയ്യുക",
  "from group": "ഗ്രൂപ്പിൽ നിന്ന്",
  "Select a group": "ഒരു ഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക",
  "Group Specific Properties": "ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവങ്ങൾ",
  "Enabled": "പ്രവർത്തനക്ഷമം",
  "Edit Group-Specific Properties Form": "ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവ ഫോം എഡിറ്റ് ചെയ്യുക",
  "Disabled": "പ്രവർത്തനരഹിതം",
  "Enable Group Specific Properties": "ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവങ്ങൾ പ്രവർത്തനക്ഷമമാക്കുക",
  "Group Roles": "ഗ്രൂപ്പ് പങ്കുകൾ",
  "Group role name changes are saved as soon as the box loses focus": "ബോക്സ് ഫോക്കസ് നഷ്ടപ്പെടുമ്പോൾ ഗ്രൂപ്പ് പങ്ക് നാമ മാറ്റങ്ങൾ സംരക്ഷിക്കപ്പെടും",
  "New Role": "പുതിയ പങ്ക്",
  "Group Listing": "ഗ്രൂപ്പ് ലിസ്‌റ്റ്",
  "Group Member Properties Editor": "ഗ്രൂപ്പ് അംഗ സ്വഭാവ എഡിറ്റർ",
  "This group currently has no properties!  You can add them in the Group Editor.": "ഈ ഗ്രൂപ്പിൽ ഇപ്പോൾ സ്വഭാവങ്ങൾ ഒന്നുമില്ല! ഗ്രൂപ്പ് എഡിറ്ററിൽ ചേർക്കാം.",
  "Return to Person Record": "വ്യക്തി റെക്കോർഡിലേക്ക് മടങ്ങുക",
  "Editing": "എഡിറ്റ് ചെയ്യുന്നു",
  "data for member": "അംഗത്തിനുള്ള ഡേറ്റ",
  "Group-Specific Properties Form Editor": "ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവ ഫോം എഡിറ്റർ",
  "No properties have been added yet": "ഇതുവരെ സ്വഭാവങ്ങൾ ഒന്നും ചേർത്തിട്ടില്ല",
  "Show in": "ഇതിൽ കാണിക്കുക",
  "Person View": "വ്യക്തി കാഴ്ച",
  "Other Email": "മറ്റ് ഇമെയിൽ",
  "Group View": "ഗ്രൂപ്പ് കാഴ്ച",
  "Confirm Delete Group": "ഗ്രൂപ്പ് ഇല്ലാതാക്കൽ സ്ഥിരീകരിക്കുക",
  "Please confirm deletion of this group record": "ഈ ഗ്രൂപ്പ് റെക്കോർഡ് ഇല്ലാതാക്കൽ സ്ഥിരീകരിക്കുക",
  "This will also delete all Roles and Group-Specific Property data associated with this Group record.": "ഈ ഗ്രൂപ്പ് റെക്കോർഡുമായി ബന്ധപ്പെട്ട എല്ലാ പങ്കുകളും ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവ ഡേറ്റയും ഇല്ലാതാകും.",
  "All group membership and properties will be destroyed.  The group members themselves will not be altered.": "എല്ലാ ഗ്രൂപ്പ് അംഗത്വങ്ങളും സ്വഭാവങ്ങളും നഷ്ടമാകും. ഗ്രൂപ്പ് അംഗങ്ങൾക്ക് തന്നെ മാറ്റം വരില്ല.",
  "Please select target group for members": "അംഗങ്ങൾക്കായി ലക്ഷ്യ ഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക",
  "Default Role": "ഡിഫോൾട്ട് പങ്ക്",
  "Group-Specific Properties": "ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവങ്ങൾ",
  "Letters and Mailing Labels": "കത്തുകളും മെയിലിംഗ് ലേബലുകളും",
  "Newsletter labels": "ന്യൂസ്‌ലെറ്റർ ലേബലുകൾ",
  "Confirm data labels": "ഡേറ്റ ലേബലുകൾ സ്ഥിരീകരിക്കുക",
  "Invalid login or password": "അസാധുവായ ലോഗിൻ അല്ലെങ്കിൽ പാസ്‌വേഡ്",
  "Too many failed logins: your account has been locked.  Please contact an administrator.": "ലോഗിൻ പലതവണ പരാജയപ്പെട്ടു: നിങ്ങളുടെ അക്കൗണ്ട് ലോക്ക് ചെയ്തിരിക്കുന്നു. ദയവായി അഡ്‌മിനിസ്‌ട്രേറ്ററെ ബന്ധപ്പെടുക.",
  "Email/Username": "ഇമെയിൽ/ഉപയോക്തൃനാമം",
  "Password": "പാസ്‌വേഡ്",
  "Login": "ലോഗിൻ",
  "Envelope Manager": "കവർ മാനേജർ",
  "Update Family Records": "കുടുംബ റെക്കോർഡുകൾ അപ്‌ഡേറ്റ് ചെയ്യുക",
  "Update Envelopes": "കവറുകൾ അപ്‌ഡേറ്റ് ചെയ്യുക",
  "Confirm": "സ്ഥിരീകരിക്കുക",
  "Sort by": "ഇതനുസരിച്ച് അടുക്കുക",
  "Zero": "പൂജ്യം",
  "Assign starting at #": "# ൽ ആരംഭിച്ച് നൽകുക",
  "Member Role Change": "അംഗ പങ്ക് മാറ്റം",
  "Member's Name": "അംഗത്തിന്റെ പേര്",
  "Current Role": "നിലവിലെ പങ്ക്",
  "All People": "എല്ലാ ആളുകളും",
  "Email All": "എല്ലാവർക്കും ഇമെയിൽ",
  "Family Roles": "കുടുംബ പങ്കുകൾ",
  "Family Geographic": "കുടുംബ ഭൂമിശാസ്ത്രം",
  "Volunteer Opportunities": "സ്വമേധയാ അവസരങ്ങൾ",
  "Families": "കുടുംബങ്ങൾ",
  "People": "ആളുകൾ",
  "Sunday School Kids": "സൺഡേ സ്‌കൂൾ കുട്ടികൾ",
  "Role / Gender": "പങ്ക് / ലിംഗം",
  "Count": "എണ്ണം",
  "Gender Demographics": "ലിംഗ ജനസ്ഥിതി",
  "Boys": "ആൺകുട്ടികൾ",
  "Girls": "പെൺകുട്ടികൾ",
  "Sunday School Classes": "സൺഡേ സ്‌കൂൾ ക്ലാസ്സുകൾ",
  "Deposit Tracking": "ഡിപ്പോസിറ്റ് ട്രാക്കിംഗ്",
  "Latest Families": "ഏറ്റവും പുതിയ കുടുംബങ്ങൾ",
  "Family Name": "കുടുംബ പേര്",
  "Updated Families": "അപ്‌ഡേറ്റ് ചെയ്ത കുടുംബങ്ങൾ",
  "Updated": "അപ്‌ഡേറ്റ് ചെയ്തു",
  "Please confirm deletion of this note": "ഈ കുറിപ്പ് ഇല്ലാതാക്കൽ സ്ഥിരീകരിക്കുക",
  "Yes, delete this record": "അതെ, ഈ റെക്കോർഡ് ഇല്ലാതാക്കുക",
  "(this action cannot be undone)": "(ഈ പ്രവർത്തനം പഴയ നിലയിലേക്ക് മടക്കാനാവില്ല)",
  "Note Editor": "കുറിപ്പ് എഡിറ്റർ",
  "Private": "സ്വകാര്യം",
  "Person": "വ്യക്തി",
  "Group": "ഗ്രൂപ്പ്",
  "Option": "ഓപ്ഷൻ",
  "Error: Duplicate": "പിശക്: ഡ്യൂപ്ലിക്കേറ്റ്",
  "Default": "ഡിഫോൾട്ട്",
  "Duplicate name found.": "ഡ്യൂപ്ലിക്കേറ്റ് പേര് കണ്ടെത്തി.",
  "Make Default": "ഡിഫോൾട്ട് ആക്കുക",
  "Exit": "പുറത്തിറങ്ങുക",
  "Add New": "പുതിയത് ചേർക്കുക",
  " by that name already exists.": " ആ പേരിൽ ഇതിനകം നിലവിലുണ്ട്.",
  "Buyer Number Editor": "വാങ്ങുന്നയാളുടെ നമ്പർ എഡിറ്റർ",
  "Generate Statement": "സ്റ്റേറ്റ്‌മെന്റ് ഉണ്ടാക്കുക",
  "Buyers for this fundraiser:": "ഈ ഫണ്ട്‌റൈസറിനുള്ള വാങ്ങുന്നവർ:",
  "Select all": "എല്ലാം തിരഞ്ഞെടുക്കുക",
  "Select none": "ഒന്നും തിരഞ്ഞെടുക്കരുത്",
  "Add Buyer": "വാങ്ങുന്നയാളെ ചേർക്കുക",
  "Generate Statements for Selected": "തിരഞ്ഞെടുത്തവർക്ക് സ്റ്റേറ്റ്‌മെന്റ് ഉണ്ടാക്കുക",
  "Select": "തിരഞ്ഞെടുക്കുക",
  "Custom Person Fields Editor": "ഇഷ്‌ടാനുസൃത വ്യക്തി ഫീൽഡ് എഡിറ്റർ",
  "No custom person fields have been added yet": "ഇഷ്‌ടാനുസൃത വ്യക്തി ഫീൽഡുകൾ ഇതുവരെ ചേർത്തിട്ടില്ല",
  "Person Editor": "വ്യക്തി എഡിറ്റർ",
  "Not a valid Friend Date": "സാധുവായ സൗഹൃദ തീയതിയല്ല",
  "Not a valid Membership Date": "സാധുവായ അംഗത്വ തീയതിയല്ല",
  "Work Email is Not Valid": "ജോലി ഇമെയിൽ സാധുവല്ല",
  "Birth Month": "ജനന മാസം",
  "Birth Day": "ജനനദിനം",
  "Birth Year": "ജനന വർഷം",
  "Hide Age": "പ്രായം മറയ്ക്കുക",
  "Create a new family (using last name)": "കുടുംബപ്പേര് ഉപയോഗിച്ച് പുതിയ കുടുംബം ഉണ്ടാക്കുക",
  "Friend Date": "സൗഹൃദ തീയതി",
  "Person Profile": "വ്യക്തി പ്രൊഫൈൽ",
  "Not assigned": "നൽകിയിട്ടില്ല",
  "Make User": "ഉപയോക്താവ് ആക്കുക",
  "Edit User": "ഉപയോക്താവ് എഡിറ്റ് ചെയ്യുക",
  "Change Role": "പങ്ക് മാറ്റുക",
  "Update Properties": "സ്വഭാവങ്ങൾ അപ്‌ഡേറ്റ് ചെയ്യുക",
  "Assign New Group": "പുതിയ ഗ്രൂപ്പ് നൽകുക"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-3.json', 'w', encoding='utf-8') as f:
    json.dump(translations_3, f, ensure_ascii=False, indent=2)
print("ml-3.json written")
