import json

translations_8 = {
  "Trinidad and Tobago": "ത്രിനിദാദ് ആൻഡ് ടൊബാഗോ",
  "Tristan da Cunha": "ട്രിസ്‌റ്റൻ ഡ കൂൻഹ",
  "Tunisia (‫تونس‬‎)": "ടുണീഷ്യ",
  "Turkey (Türkiye)": "തുർക്കി",
  "Turkmenistan": "തുർക്ക്‌മെനിസ്ഥാൻ",
  "Turks and Caicos Islands": "ടർക്ക്‌സ് ആൻഡ് കൈക്കോസ് ദ്വീപുകൾ",
  "Tuvalu": "തുവാലൂ",
  "U.S. Outlying Islands": "യുഎസ് ഔട്ട്‌ലൈയിംഗ് ദ്വീപുകൾ",
  "U.S. Virgin Islands": "യുഎസ് വർജിൻ ദ്വീപുകൾ",
  "Uganda": "ഉഗാൻഡ",
  "Ukraine (Україна)": "ഉക്രൈൻ",
  "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)": "ഐക്യ അറബ് എമിറേറ്റ്‌സ്",
  "United Kingdom": "ഐക്യ രാജ്യം",
  "United States": "ഐക്യ നാടുകൾ",
  "Uruguay": "ഉറുഗ്വേ",
  "Uzbekistan (Oʻzbekiston)": "ഉസ്‌ബെക്കിസ്ഥാൻ",
  "Vanuatu": "വനുവാത്തു",
  "Vatican City (Città del Vaticano)": "വത്തിക്കാൻ നഗരം",
  "Venezuela": "വെനിസ്വേല",
  "Vietnam (Việt Nam)": "വിയറ്റ്‌നാം",
  "Wallis and Futuna": "വാലിസ് ആൻഡ് ഫ്യൂച്ചുന",
  "Western Sahara (‫الصحراء الغربية‬‎)": "പടിഞ്ഞാറൻ സഹാറ",
  "Yemen (‫اليمن‬‎)": "യെമൻ",
  "Zambia": "സാംബിയ",
  "Zimbabwe": "സിംബാബ്‌വെ",
  "Please verify your family's information": "നിങ്ങളുടെ കുടുംബ വിവരം സ്ഥിരീകരിക്കുക",
  "Unable to load verification info": "സ്ഥിരീകരണ വിവരം ലഭ്യമാക്കാൻ കഴിഞ്ഞില്ല",
  "No Changes": "മാറ്റങ്ങൾ ഇല്ല",
  "Page not fond": "പേജ് കണ്ടെത്തിയില്ല",
  "Oops! Page not found.": "ക്ഷമിക്കണം! പേജ് കണ്ടെത്തിയില്ല.",
  "Family Registration": "കുടുംബ രജിസ്‌ട്രേഷൻ",
  "Please enter the following to start your family's verification": "നിങ്ങളുടെ കുടുംബ സ്ഥിരീകരണം ആരംഭിക്കാൻ ഇനിപ്പറയുന്നത് നൽകുക",
  "Family Verification": "കുടുംബ സ്ഥിരീകരണം",
  "Request Family Info Verification": "കുടുംബ വിവര സ്ഥിരീകരണം അഭ്യർത്ഥിക്കുക",
  "Select how do you want to request the family information to be verified": "കുടുംബ വിവരം സ്ഥിരീകരിക്കേണ്ടത് എങ്ങനെ ആണ് അഭ്യർത്ഥിക്കണ്ടതെന്ന് തിരഞ്ഞെടുക്കുക",
  "Online Verification": "ഓൺലൈൻ സ്ഥിരീകരണം",
  "Verified In Person": "നേരിട്ട് സ്ഥിരീകരിച്ചു",
  "Backup archive does not contain a database": "ബാക്കപ്പ് ആർക്കൈവ് ഡേറ്റാബേസ് ഉൾക്കൊള്ളുന്നില്ല",
  "Make user-entered zip/postcodes UPPERCASE when saving to the database.": "ഡേറ്റാബേസിൽ സംരക്ഷിക്കുമ്പോൾ ഉപയോക്താവ് നൽകിയ സിപ്/പോസ്‌റ്റ്‌കോഡ് വലിയ അക്ഷരമാക്കുക.",
  "Used to end a letter before Signer": "ഒപ്പിടുന്നയാൾക്ക് മുൻപ് ഒരു കത്ത് അവസാനിക്കാൻ ഉപയോഗിക്കുന്നത്",
  "English - United States": "English - United States",
  "English - Canada": "English - Canada",
  "English - Australia": "English - Australia",
  "English - Great Britain": "English - Great Britain",
  "German - Germany": "German - Germany",
  "Spanish - Spain": "Spanish - Spain",
  "French - France": "French - France",
  "Hungarian": "Hungarian",
  "Italian - Italy": "Italian - Italy",
  "Norwegian": "Norwegian",
  "Dutch - Netherlands": "Dutch - Netherlands",
  "Polish": "Polish",
  "Portuguese - Brazil": "Portuguese - Brazil",
  "Romanian - Romania": "Romanian - Romania",
  "Russian": "Russian",
  "Sami (Northern) (Sweden)": "Sami (Northern) (Sweden)",
  "Albanian": "Albanian",
  "Vietnamese": "Vietnamese",
  "Chinese - China": "Chinese - China",
  "Chinese - Taiwan": "Chinese - Taiwan",
  "Maximum upload size": "പരമാവധി അപ്‌ലോഡ് വലുപ്പം",
  "The selected file exceeds this servers maximum upload size of": "തിരഞ്ഞെടുത്ത ഫയൽ ഈ സർവ്വറിന്റെ പരമാവധി അപ്‌ലോഡ് വലുപ്പം കവിഞ്ഞു",
  "Failed": "പരാജയപ്പെട്ടു",
  "Church Checking Account Number": "പള്ളി ചെക്കിംഗ് അക്കൗണ്ട് നമ്പർ",
  "Marked the Family as Inactive": "കുടുംബം നിഷ്‌ക്രിയമായി അടയാളപ്പെടുത്തി",
  "Marked the Family as Active": "കുടുംബം സജീവമായി അടയാളപ്പെടുത്തി",
  "families": "കുടുംബങ്ങൾ",
  "Financial Settings": "സാമ്പത്തിക ക്രമീകരണങ്ങൾ",
  "An invalid configuration name has been requested": "അസാധുവായ കോൺഫിഗറേഷൻ പേര് അഭ്യർത്ഥിച്ചു",
  "An invalid configuration id has been requested": "അസാധുവായ കോൺഫിഗറേഷൻ ID അഭ്യർത്ഥിച്ചു",
  "Profile Image uploaded": "പ്രൊഫൈൽ ചിത്രം അപ്‌ലോഡ് ചെയ്തു",
  "payment(s)?": "പേമെന്റ്(കൾ)?",
  "Confirm Deactivation": "നിഷ്‌ക്രിയം സ്ഥിരീകരിക്കുക",
  "Confirm Activation": "സജീവം സ്ഥിരീകരിക്കുക",
  "Please confirm deactivation of family": "കുടുംബം നിഷ്‌ക്രിയമാക്കൽ സ്ഥിരീകരിക്കുക",
  "Please confirm activation of family": "കുടുംബം സജീവമാക്കൽ സ്ഥിരീകരിക്കുക",
  "Show neighbors with these classifications": "ഈ വർഗ്ഗീകരണങ്ങളുള്ള അയൽക്കാരെ കാണിക്കുക",
  "Please select a Family.": "ഒരു കുടുംബം തിരഞ്ഞെടുക്കുക.",
  "Coordinate database file name": "കോർഡിനേറ്റ് ഡേറ്റാബേസ് ഫയൽ നാമം",
  "select an option": "ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക",
  "Direct me": "എന്നെ നയിക്കൂ",
  "Your cart is empty": "നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്",
  "The record could not be found.": "റെക്കോർഡ് കണ്ടെത്തിയില്ല.",
  "The property is already assigned.": "സ്വഭാവം ഇതിനകം നൽകിയിട്ടുണ്ട്.",
  "The property is successfully assigned.": "സ്വഭാവം വിജയകരമായി നൽകി.",
  "The property could not be assigned.": "സ്വഭാവം നൽകാൻ കഴിഞ്ഞില്ല.",
  "The property is successfully unassigned.": "സ്വഭാവം വിജയകരമായി നീക്കി.",
  "The property could not be unassigned.": "സ്വഭാവം നീക്കാൻ കഴിഞ്ഞില്ല.",
  "Select event": "ഇവന്റ് തിരഞ്ഞെടുക്കുക",
  "Person has been already checked in for this event": "ഈ ഇവന്റിന് വ്യക്തി ഇതിനകം ചെക്ക്-ഇൻ ചെയ്തിട്ടുണ്ട്",
  "Adult Checking Out Person": "മുതിർന്നയാൾ ചെക്ക്-ഔട്ട് ചെയ്യുന്ന വ്യക്തി",
  "Text before name in emails/reports": "ഇമെയിലുകളിൽ/റിപ്പോർട്ടുകളിൽ പേരിന് മുൻപ് ടെക്സ്റ്റ്",
  "Display bill counts on deposit slip": "ഡിപ്പോസിറ്റ് സ്ലിപ്പിൽ ബിൽ എണ്ണം കാണിക്കുക",
  "Your Account was Deleted": "നിങ്ങളുടെ അക്കൗണ്ട് ഇല്ലാതാക്കി",
  "Your ChurchCRM Account was Deleted.": "നിങ്ങളുടെ ChurchCRM അക്കൗണ്ട് ഇല്ലാതാക്കി.",
  "Account Locked": "അക്കൗണ്ട് ലോക്ക് ചെയ്തു",
  "Your New Account": "നിങ്ങളുടെ പുതിയ അക്കൗണ്ട്",
  "Password Reset": "പാസ്‌വേഡ് റീസെറ്റ്",
  "Account Unlocked": "അക്കൗണ്ട് അൺലോക്ക് ചെയ്തു",
  "Part": "ഭാഗം",
  "View Photo": "ഫോട്ടോ കാണുക",
  "Status": "സ്ഥിതി",
  "Include": "ഉൾപ്പെടുത്തുക",
  "View Cart": "കാർട്ട് കാണുക",
  "Your Cart is Empty": "നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്",
  "Legend": "ഐതിഹ്യം",
  "assigned": "നൽകിയ",
  "Showing students with birthdays in": "ജന്മദിനമുള്ള വിദ്യാർത്ഥികൾ കാണിക്കുന്നു",
  "Actions": "പ്രവർത്തനങ്ങൾ",
  "Action Confirmation": "പ്രവർത്തന സ്ഥിരീകരണം",
  "Please confirm reset failed login count": "പരാജയപ്പെട്ട ലോഗിൻ എണ്ണം റീസെറ്റ് ചെയ്യൽ സ്ഥിരീകരിക്കുക",
  "SMTP Server timeout in sec": "SMTP സർവ്വർ ടൈംഔട്ട് സെക്കൻഡിൽ",
  "Exclude Inactive Families": "നിഷ്‌ക്രിയ കുടുംബങ്ങൾ ഒഴിവാക്കുക",
  "The role is already assigned.": "പങ്ക് ഇതിനകം നൽകിയിട്ടുണ്ട്.",
  "The role is successfully assigned.": "പങ്ക് വിജയകരമായി നൽകി.",
  "The role could not be assigned.": "പങ്ക് നൽകാൻ കഴിഞ്ഞില്ല.",
  "Your ChurchCRM account was locked.": "നിങ്ങളുടെ ChurchCRM അക്കൗണ്ട് ലോക്ക് ചെയ്തിരിക്കുന്നു.",
  "A ChurchCRM account was created for you": "നിങ്ങൾക്കായി ഒരു ChurchCRM അക്കൗണ്ട് ഉണ്ടാക്കി",
  "You can reset your ChurchCRM password by clicking this link": "ഈ ലിങ്ക് ക്ലിക്ക് ചെയ്ത് ChurchCRM പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യാം",
  "Your ChurchCRM account was unlocked.": "നിങ്ങളുടെ ChurchCRM അക്കൗണ്ട് അൺലോക്ക് ചെയ്തു.",
  "system user created": "സിസ്റ്റം ഉപയോക്താവ് ഉണ്ടാക്കി",
  "system user updated": "സിസ്റ്റം ഉപയോക്താവ് അപ്‌ഡേറ്റ് ചെയ്തു",
  "system user deleted": "സിസ്റ്റം ഉപയോക്താവ് ഇല്ലാതാക്കി",
  "system user password reset": "സിസ്റ്റം ഉപയോക്തൃ പാസ്‌വേഡ് റീസെറ്റ്",
  "system user changed password": "സിസ്റ്റം ഉപയോക്താവ് പാസ്‌വേഡ് മാറ്റി",
  "system user password changed by admin": "അഡ്‌മിൻ സിസ്റ്റം ഉപയോക്തൃ പാസ്‌വേഡ് മാറ്റി",
  "system user login reset": "സിസ്റ്റം ഉപയോക്തൃ ലോഗിൻ റീസെറ്റ്",
  "Notification for": "ഇവർക്ക് അറിയിപ്പ്",
  "ERROR": "പിശക്",
  "Title FirstName MiddleName LastName": "പദവി പേര് മദ്ധ്യനാമം കുടുംബപ്പേര്",
  "Title FirstName MiddleInitial. LastName": "പദവി പേര് മദ്ധ്യ ഇനിഷ്യൽ. കുടുംബപ്പേര്",
  "LastName, Title FirstName MiddleName": "കുടുംബപ്പേര്, പദവി പേര് മദ്ധ്യനാമം",
  "LastName, Title FirstName MiddleInitial": "കുടുംബപ്പേര്, പദവി പേര് മദ്ധ്യ ഇനിഷ്യൽ",
  "FirstName MiddleName LastName": "പേര് മദ്ധ്യനാമം കുടുംബപ്പേര്",
  "Title FirstName LastName": "പദവി പേര് കുടുംബപ്പേര്",
  "LastName, Title FirstName": "കുടുംബപ്പേര്, പദവി പേര്",
  "Event Log severity to write, used by ORM and App Logs": "എഴുതേണ്ട ഇവന്റ് ലോഗ് തീവ്രത, ORM ഉം App ലോഗുകളും ഉപയോഗിക്കുന്നത്",
  "Time zone": "സമയ മേഖല",
  "KioskVisibilityTimestamp": "KioskVisibilityTimestamp",
  "Show/Hide Lost Password Link on the login screen": "ലോഗിൻ സ്ക്രീനിൽ പാസ്‌വേഡ് നഷ്ടമായ ലിങ്ക് കാണിക്കുക/മറയ്ക്കുക",
  "Backup": "ബാക്കപ്പ്",
  "Guardian(s) of": "ഇവരുടെ രക്ഷകൻ/രക്ഷകർ",
  "Your ChurchCRM password has been changed": "നിങ്ങളുടെ ChurchCRM പാസ്‌വേഡ് മാറ്റി",
  "Password Reset Link": "പാസ്‌വേഡ് റീസെറ്റ് ലിങ്ക്",
  "Reset Password": "പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യുക",
  "Reset your password": "പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യൂ",
  "Sorry, we are unable to process your request at this point in time.": "ക്ഷമിക്കണം, ഇപ്പോൾ നിങ്ങളുടെ അഭ്യർത്ഥന പ്രോസസ് ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  "Kiosk Manager": "കിയോസ്‌ക് മാനേജർ",
  "Report an issue": "ഒരു പ്രശ്‌നം റിപ്പോർട്ട് ചെയ്യുക",
  "Active Kiosks": "സജീവ കിയോസ്‌കുകൾ"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-8.json', 'w', encoding='utf-8') as f:
    json.dump(translations_8, f, ensure_ascii=False, indent=2)
print("ml-8.json written")
