import json

translations_7 = {
  "Finland (Suomi)": "ഫിൻലൻഡ്",
  "France": "ഫ്രാൻസ്",
  "French Guiana (Guyane française)": "ഫ്രഞ്ച് ഗയാന",
  "French Polynesia (Polynésie française)": "ഫ്രഞ്ച് പോളിനേഷ്യ",
  "French Southern Territories (Terres australes françaises)": "ഫ്രഞ്ച് ദക്ഷിണ ഭൂ.",
  "Gabon": "ഗബോൺ",
  "Gambia": "ഗാംബിയ",
  "Georgia (საქართველო)": "ജോർജിയ",
  "Germany (Deutschland)": "ജർമ്മനി",
  "Ghana (Gaana)": "ഘാന",
  "Gibraltar": "ജിബ്രാൾട്ടർ",
  "Greece (Ελλάδα)": "ഗ്രീസ്",
  "Greenland (Kalaallit Nunaat)": "ഗ്രീൻലൻഡ്",
  "Grenada": "ഗ്രനേഡ",
  "Guadeloupe": "ഗ്വഡലൂപ്",
  "Guam": "ഗ്വം",
  "Guatemala": "ഗ്വാട്ടിമാല",
  "Guernsey": "ഗേൺസി",
  "Guinea (Guinée)": "ഗ്വിനിയ",
  "Guinea-Bissau (Guiné Bissau)": "ഗ്വിനി-ബിസ്സൗ",
  "Guyana": "ഗയാന",
  "Haiti": "ഹെയ്തി",
  "Heard & McDonald Islands": "ഹേർഡ് & മക്‌ഡൊണൾഡ് ദ്വീപുകൾ",
  "Honduras": "ഹോണ്ടുറാസ്",
  "Hong Kong (香港)": "ഹോങ് കോങ്",
  "Hungary (Magyarország)": "ഹംഗറി",
  "Iceland (Ísland)": "ഐസ്‌ലൻഡ്",
  "India (भारत)": "ഇന്ത്യ",
  "Indonesia": "ഇൻഡോനേഷ്യ",
  "Iran (‫ایران‬‎)": "ഇറാൻ",
  "Iraq (‫العراق‬‎)": "ഇറാഖ്",
  "Ireland": "അയർലൻഡ്",
  "Isle of Man": "ഐൽ ഓഫ് മാൻ",
  "Israel (‫ישראל‬‎)": "ഇസ്രായേൽ",
  "Italy (Italia)": "ഇറ്റലി",
  "Jamaica": "ജമൈക്ക",
  "Japan (日本)": "ജപ്പാൻ",
  "Jersey": "ജഴ്‌സി",
  "Jordan (‫الأردن‬‎)": "ജോർദ്ദാൻ",
  "Kazakhstan (Казахстан)": "കസാഖ്‌സ്‌താൻ",
  "Kenya": "കെനിയ",
  "Kiribati": "കിരിബാട്ടി",
  "Kosovo (Kosovë)": "കൊസോവോ",
  "Kuwait (‫الكويت‬‎)": "കുവൈത്ത്",
  "Kyrgyzstan (Кыргызстан)": "കിർഗിസ്ഥാൻ",
  "Laos (ລາວ)": "ലാവോസ്",
  "Lebanon (‫لبنان‬‎)": "ലെബനൻ",
  "Lesotho": "ലെസോതോ",
  "Liberia": "ലൈബീരിയ",
  "Libya (‫ليبيا‬‎)": "ലിബിയ",
  "Liechtenstein": "ലൈഖ്‌ടൻഷ്‌റ്റൈൻ",
  "Lithuania (Lietuva)": "ലിത്വാനിയ",
  "Luxembourg": "ലക്‌സംബർഗ്",
  "Macau (澳門)": "മക്കാവോ",
  "Macedonia (FYROM) (Македонија)": "മാസിഡോണിയ",
  "Madagascar (Madagasikara)": "മഡഗാസ്‌കർ",
  "Malawi": "മലാവി",
  "Malaysia": "മലേഷ്യ",
  "Maldives": "മാലദ്വീപ്",
  "Mali": "മാലി",
  "Malta": "മാൾട്ട",
  "Marshall Islands": "മാർഷൽ ദ്വീപുകൾ",
  "Martinique": "മാർട്ടിനിക്",
  "Mauritania (‫موريتانيا‬‎)": "മൗറിത്താനിയ",
  "Mauritius (Moris)": "മൗറീഷ്യസ്",
  "Mayotte": "മയോട്ടെ",
  "Mexico (México)": "മെക്‌സിക്കോ",
  "Micronesia": "മൈക്രോനേഷ്യ",
  "Moldova (Republica Moldova)": "മോൾഡോവ",
  "Monaco": "മൊണാക്കോ",
  "Mongolia (Монгол)": "മംഗോളിയ",
  "Montenegro (Crna Gora)": "മോണ്ടിനിഗ്രോ",
  "Montserrat": "മോൺസേറ്റ്",
  "Morocco (‫المغرب‬‎)": "മൊറോക്കോ",
  "Mozambique (Moçambique)": "മൊസാംബിക്ക്",
  "Myanmar (Burma) (မြန်မာ)": "മ്യാൻമാർ",
  "Namibia (Namibië)": "നമീബിയ",
  "Nauru": "നൗറു",
  "Nepal (नेपाल)": "നേപ്പാൾ",
  "Netherlands (Nederland)": "നെതർലൻഡ്‌സ്",
  "New Caledonia (Nouvelle-Calédonie)": "ന്യൂ കാലിഡോണിയ",
  "New Zealand": "ന്യൂസിലൻഡ്",
  "Nicaragua": "നിക്കരാഗ്വ",
  "Niger (Nijar)": "നൈജർ",
  "Nigeria": "നൈജീരിയ",
  "Niue": "നിയൂ",
  "Norfolk Island": "നോർഫോക്ക് ദ്വീപ്",
  "Northern Mariana Islands": "നോർതേൺ മരിയാന ദ്വീപുകൾ",
  "North Korea (조선 민주주의 인민 공화국)": "ഉത്തര കൊറിയ",
  "Norway (Norge)": "നോർവേ",
  "Oman (‫عُمان‬‎)": "ഒമാൻ",
  "Pakistan (‫پاکستان‬‎)": "പാകിസ്ഥാൻ",
  "Palau": "പലാവ്",
  "Palestine (‫فلسطين‬‎)": "പലസ്തീൻ",
  "Panama (Panamá)": "പനാമ",
  "Papua New Guinea": "പാപ്വ ന്യൂ ഗിനി",
  "Paraguay": "പരാഗ്വേ",
  "Peru (Perú)": "പെറു",
  "Philippines": "ഫിലിപ്പൈൻസ്",
  "Pitcairn Islands": "പിറ്റ്‌കെയ്‌ൻ ദ്വീപുകൾ",
  "Poland (Polska)": "പോളണ്ട്",
  "Portugal": "പോർച്ചുഗൽ",
  "Puerto Rico": "പ്വേർട്ടോ റിക്കോ",
  "Qatar (‫قطر‬‎)": "ഖത്തർ",
  "Réunion (La Réunion)": "റിയൂണിയൻ",
  "Romania (România)": "റൊമാനിയ",
  "Russia (Россия)": "റഷ്യ",
  "Rwanda": "റുവാൻഡ",
  "Saint Barthélemy (Saint-Barthélemy)": "സെന്റ് ബർത്തലോമ്യൂ",
  "Saint Helena": "സെന്റ് ഹെലേന",
  "Saint Kitts and Nevis": "സെന്റ് കിറ്റ്‌സ് ആൻഡ് നെവിസ്",
  "Saint Lucia": "സെന്റ് ലൂഷ്യ",
  "Saint Martin (Saint-Martin (partie française))": "സെന്റ് മാർട്ടിൻ",
  "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)": "സെന്റ് പിറ്ററും മിക്ക്ലോണും",
  "Samoa": "സമോവ",
  "San Marino": "സാൻ മരിനോ",
  "São Tomé and Príncipe (São Tomé e Príncipe)": "സൗ ടോമെ ആൻഡ് പ്രിൻസിപ്",
  "Saudi Arabia (‫المملكة العربية السعودية‬‎)": "സൗദി അറേബ്യ",
  "Senegal (Sénégal)": "സെനഗൽ",
  "Serbia (Србија)": "സെർബിയ",
  "Seychelles": "സെഷൽസ്",
  "Sierra Leone": "സിയെറ ലിയോൺ",
  "Singapore": "സിംഗപ്പൂർ",
  "Sint Maarten": "സിന്റ് മാർട്ടൻ",
  "Slovakia (Slovensko)": "സ്ലൊവാക്യ",
  "Slovenia (Slovenija)": "സ്ലൊവേനിയ",
  "Solomon Islands": "സോളമൻ ദ്വീപുകൾ",
  "Somalia (Soomaaliya)": "സോമാലിയ",
  "South Africa": "ദക്ഷിണ ആഫ്രിക്ക",
  "South Georgia & South Sandwich Islands": "ദക്ഷിണ ജോർജ്ജിയ & ദക്ഷിണ സാൻഡ്‌വിച്ച് ദ്വീപുകൾ",
  "South Korea (대한민국)": "ദക്ഷിണ കൊറിയ",
  "South Sudan (‫جنوب السودان‬‎)": "ദക്ഷിണ സൂദാൻ",
  "Spain (España)": "സ്പെയിൻ",
  "Sri Lanka (ශ්‍රී ලංකාව)": "ശ്രീലങ്ക",
  "St. Vincent & Grenadines": "സെന്റ് വിൻസെൻറ് & ഗ്രനഡൈൻസ്",
  "Sudan (‫السودان‬‎)": "സൂദാൻ",
  "Suriname": "സൂരിനാം",
  "Svalbard and Jan Mayen (Svalbard og Jan Mayen)": "സ്വാൽബാർഡ് ആൻഡ് ജാൻ മായൻ",
  "Swaziland": "സ്വാസിലൻഡ്",
  "Sweden (Sverige)": "സ്വീഡൻ",
  "Switzerland (Schweiz)": "സ്വിറ്റ്‌സർലൻഡ്",
  "Syria (‫سوريا‬‎)": "സിറിയ",
  "Taiwan (台灣)": "തൈവാൻ",
  "Tajikistan": "താജിക്കിസ്ഥാൻ",
  "Tanzania": "ടാൻസാനിയ",
  "Thailand (ไทย)": "തായ്‌ലൻഡ്",
  "Timor-Leste": "ടിമോർ-ലെസ്‌തെ",
  "Togo": "ടോഗോ",
  "Tokelau": "ടൊക്കെലൗ",
  "Tonga": "ടോംഗ"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-7.json', 'w', encoding='utf-8') as f:
    json.dump(translations_7, f, ensure_ascii=False, indent=2)
print("ml-7.json written")
