import json, sys

translations_1 = {
  "Cannot execute query.": "ക്വറി എക്സിക്യൂട്ട് ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  "Delete": "ഇല്ലാതാക്കുക",
  "Cancel": "റദ്ദാക്കുക",
  "Save": "സംരക്ഷിക്കുക",
  "Unassigned": "നിയോഗിക്കാത്തത്",
  "None": "ഒന്നുമില്ല",
  "City": "നഗരം",
  "State": "സംസ്ഥാനം",
  "Country": "രാജ്യം",
  "Phone": "ഫോൺ",
  "Email": "ഇമെയിൽ",
  "Credit Card": "ക്രെഡിറ്റ് കാർഡ്",
  "Backup Database": "ഡേറ്റാബേസ് ബാക്കപ്പ്",
  "Batch Winner Entry": "ബാച്ച് വിജയി എൻട്രി",
  "Winner": "വിജയി",
  "Price": "വില",
  "Enter Winners": "വിജയികളെ നൽകുക",
  "CSV Export": "CSV കയറ്റുമതി",
  "Field Selection": "ഫീൽഡ് തിരഞ്ഞെടുപ്പ്",
  "Last Name": "കുടുംബപ്പേര്",
  "Required": "ആവശ്യമാണ്",
  "First Name": "പേര്",
  "Middle Name": "മദ്ധ്യനാമം",
  "Zip": "പിൻകോഡ്",
  "Envelope": "കവർ",
  "Work/Other Email": "ജോലി/മറ്റ് ഇമെയിൽ",
  "Membership Date": "അംഗത്വ തീയതി",
  "Age / Years Married": "പ്രായം / വൈവാഹിക വർഷങ്ങൾ",
  "Family Role": "കുടുംബ പങ്ക്",
  "Depends whether using person or family output method": "വ്യക്തി അല്ലെങ്കിൽ കുടുംബ ഔട്ട്‌പുട്ട് രീതി ഉപയോഗിക്കുന്നതിനെ ആശ്രയിക്കുന്നു",
  "Custom Field Selection": "ഇഷ്‌ടാനുസൃത ഫീൽഡ് തിരഞ്ഞെടുപ്പ്",
  "Custom Person Fields": "ഇഷ്‌ടാനുസൃത വ്യക്തി ഫീൽഡുകൾ",
  "Custom Family Fields": "ഇഷ്‌ടാനുസൃത കുടുംബ ഫീൽഡുകൾ",
  "Filters": "ഫിൽട്ടറുകൾ",
  "Records to export": "കയറ്റുമതി ചെയ്യേണ്ട രേഖകൾ",
  "Based on filters below..": "താഴെ നൽകിയ ഫിൽട്ടറുകൾ അനുസരിച്ച്..",
  "People in Cart (filters ignored)": "കാർട്ടിലുള്ള ആളുകൾ (ഫിൽട്ടറുകൾ അവഗണിക്കപ്പെടും)",
  "Use Ctrl Key to select multiple": "ഒന്നിലധികം തിരഞ്ഞെടുക്കാൻ Ctrl കീ ഉപയോഗിക്കുക",
  "Don't Filter": "ഫിൽട്ടർ ചെയ്യരുത്",
  "Male": "പുരുഷൻ",
  "Female": "സ്ത്രീ",
  "Group Membership": "ഗ്രൂപ്പ് അംഗത്വം",
  "From": "തൊട്ട്",
  "To": "വരെ",
  "Anniversary Date": "വാർഷിക തീയതി",
  "Output Method:": "ഔട്ട്‌പുട്ട് രീതി:",
  "CSV Individual Records": "CSV വ്യക്തിഗത രേഖകൾ",
  "CSV Combine Families": "CSV കുടുംബങ്ങൾ ഒന്നിപ്പിക്കുക",
  "Add Individuals to Cart": "വ്യക്തികളെ കാർട്ടിൽ ചേർക്കുക",
  "Skip records with incomplete mail address": "അപൂർണ്ണ മെയിൽ വിലാസമുള്ള രേഖകൾ ഒഴിവാക്കുക",
  "Create File": "ഫയൽ ഉണ്ടാക്കുക",
  "Title": "പദവി",
  "Suffix": "സഫിക്സ്",
  "Gender": "ലിംഗം",
  "Home Phone": "വീട്ടിലെ ഫോൺ",
  "Work Phone": "ജോലി ഫോൺ",
  "Mobile Phone": "മൊബൈൽ ഫോൺ",
  "Work / Other Email": "ജോലി / മറ്റ് ഇമെയിൽ",
  "Birth Date": "ജനന തീയതി",
  "Wedding Date": "വിവാഹ തീയതി",
  "Classification": "വർഗ്ഗീകരണം",
  "Add Cart to Event": "ഇവന്റിൽ കാർട്ട് ചേർക്കുക",
  "OR": "അല്ലെങ്കിൽ",
  "Your cart is empty!": "നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്!",
  "No family name entered!": "കുടുംബപ്പേര് നൽകിയിട്ടില്ല!",
  "Add Cart to Family": "കാർട്ട് കുടുംബത്തിൽ ചേർക്കുക",
  "Name": "പേര്",
  "Assign Role": "പങ്ക് നൽകുക",
  "Already in a family": "ഒരു കുടുംബത്തിൽ ഇതിനകം ഉണ്ട്",
  "Create new family": "പുതിയ കുടുംബം ഉണ്ടാക്കുക",
  "If adding a new family, enter data below.": "പുതിയ കുടുംബം ചേർക്കുകയാണെങ്കിൽ, താഴെ വിവരങ്ങൾ നൽകുക.",
  "Use address/contact data from": "ഇതിൽ നിന്ന് വിലാസം/ബന്ധപ്പെടൽ ഡേറ്റ ഉപയോഗിക്കുക",
  "Only the new data below": "താഴെ നൽകിയ പുതിയ ഡേറ്റ മാത്രം",
  "Do not auto-format": "സ്വയം ഫോർമാറ്റ് ചെയ്യരുത്",
  "Add to Family": "കുടുംബത്തിൽ ചേർക്കുക",
  "Add Cart to Group": "ഗ്രൂപ്പിൽ കാർട്ട് ചേർക്കുക",
  "Select the group to which you would like to add your cart": "കാർട്ട് ചേർക്കേണ്ട ഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക",
  "Select Group": "ഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക",
  "No Group Selected": "ഗ്രൂപ്പ് തിരഞ്ഞെടുത്തിട്ടില്ല",
  "Add to Group": "ഗ്രൂപ്പിൽ ചേർക്കുക",
  "You have no items in your cart.": "നിങ്ങളുടെ കാർട്ടിൽ ഒന്നുമില്ല.",
  "Back to Menu": "മെനുവിലേക്ക് മടങ്ങുക",
  "Empty Cart": "കാർട്ട് ശൂന്യമാക്കുക",
  "Empty Cart to Group": "കാർട്ട് ഗ്രൂപ്പിലേക്ക് ഒഴിക്കുക",
  "Empty Cart to Family": "കാർട്ട് കുടുംബത്തിലേക്ക് ഒഴിക്കുക",
  "Map Cart": "കാർട്ട് മാപ്പ് ചെയ്യുക",
  "Bulk Mail Presort": "ബൾക്ക് മെയിൽ പ്രീസോർട്ട്",
  "Quiet Presort": "ശാന്തമായ പ്രീസോർട്ട്",
  "Your cart contains": "നിങ്ങളുടെ കാർട്ടിൽ ഉള്ളത്",
  "people from": "ആളുകൾ",
  "Remove": "നീക്കം ചെയ്യുക",
  "Yes": "അതെ",
  "No": "ഇല്ല",
  "Event Checkin": "ഇവന്റ് ചെക്ക്-ഇൻ",
  "Select Event": "ഇവന്റ് തിരഞ്ഞെടുക്കുക",
  "Checked In Time": "ചെക്ക്-ഇൻ സമയം",
  "Checked In By": "ചെക്ക്-ഇൻ ചെയ്തത്",
  "Checked Out Time": "ചെക്ക്-ഔട്ട് സമയം",
  "Checked Out By": "ചെക്ക്-ഔട്ട് ചെയ്തത്",
  "Action": "പ്രവർത്തനം",
  "Member": "അംഗം",
  " of the": " യുടെ",
  "(No assigned family)": "(കുടുംബം നൽകിയിട്ടില്ല)",
  "Convert Individuals to Families": "വ്യക്തികളെ കുടുംബങ്ങളാക്കി മാറ്റുക",
  "Convert Next": "അടുത്തത് മാറ്റുക",
  "Convert All": "എല്ലാം മാറ്റുക",
  "Deposit Slip Number": "ഡിപ്പോസിറ്റ് സ്ലിപ്പ് നമ്പർ",
  "Deposit Details": "ഡിപ്പോസിറ്റ് വിശദാംശങ്ങൾ",
  "Important: Failed transactions will be deleted permanently when the deposit slip is closed.": "പ്രധാനം: ഡിപ്പോസിറ്റ് സ്ലിപ്പ് അടച്ചാൽ പരാജയപ്പെട്ട ഇടപാടുകൾ സ്ഥിരമായി ഇല്ലാതാകും.",
  "Add Payment": "പേമെന്റ് ചേർക്കുക",
  "Load Authorized": "അധികൃതം ലോഡ് ചെയ്യുക",
  "Run Transactions": "ഇടപാടുകൾ നടത്തുക",
  "Directory reports": "ഡയറക്ടറി റിപ്പോർട്ടുകൾ",
  "Select classifications to include": "ഉൾപ്പെടുത്തേണ്ട വർഗ്ഗീകരണങ്ങൾ തിരഞ്ഞെടുക്കുക",
  "Which role is the head of household?": "ഏത് പങ്കാണ് കുടുംബനാഥൻ?",
  "Which role is the spouse?": "ഏത് പങ്കാണ് ഇണ?",
  "Which role is a child?": "ഏത് പങ്കാണ് കുട്ടി?",
  "Information to Include": "ഉൾപ്പെടുത്തേണ്ട വിവരങ്ങൾ",
  "Address": "വിലാസം",
  "Birthday": "ജന്മദിനം",
  "Family Home Phone": "കുടുംബ വീട്ടു ഫോൺ",
  "Family Work Phone": "കുടുംബ ജോലി ഫോൺ",
  "Family Cell Phone": "കുടുംബ സെൽ ഫോൺ",
  "Family Email": "കുടുംബ ഇമെയിൽ",
  "Personal Home Phone": "വ്യക്തിഗത വീട്ടു ഫോൺ",
  "Personal Work Phone": "വ്യക്തിഗത ജോലി ഫോൺ",
  "Personal Cell Phone": "വ്യക്തിഗത സെൽ ഫോൺ",
  "Personal Email": "വ്യക്തിഗത ഇമെയിൽ",
  "Personal Work/Other Email": "വ്യക്തിഗത ജോലി/മറ്റ് ഇമെയിൽ",
  "Photos": "ഫോട്ടോകൾ",
  "Number of Columns": "നിരകളുടെ എണ്ണം",
  "Paper Size": "കടലാസ് വലുപ്പം",
  "Font Size": "ഫോണ്ട് വലുപ്പം",
  "Title page": "ശീർഷക പേജ്",
  "Use Title Page": "ശീർഷക പേജ് ഉപയോഗിക്കുക",
  "Church Name": "പള്ളിയുടെ പേര്",
  "Disclaimer": "നിരാകരണം",
  "Create Directory": "ഡയറക്ടറി ഉണ്ടാക്കുക",
  "Donated Item Editor": "സംഭാവന വസ്തു എഡിറ്റർ",
  "Save and Add": "സംരക്ഷിച്ച് ചേർക്കുക",
  "Item": "വസ്തു",
  "Multiple items": "ഒന്നിലധികം വസ്തുക്കൾ",
  "Sell to everyone": "എല്ലാവർക്കും വിൽക്കുക",
  "Estimated Price": "ഏകദേശ വില",
  "Multiple": "ഒന്നിലധികം",
  "Final Price": "അന്തിമ വില",
  "Replicate item": "വസ്തു പകർത്തുക",
  "Go": "പോകുക",
  "Description": "വിവരണം",
  "Picture URL": "ചിത്ര URL"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-1.json', 'w', encoding='utf-8') as f:
    json.dump(translations_1, f, ensure_ascii=False, indent=2)

print("ml-1.json written")
