import json

translations_9 = {
  "Self Verification": "സ്വ-സ്ഥിരീകരണം",
  "Check Number": "ചെക്ക് നമ്പർ",
  "Details": "വിശദാംശങ്ങൾ",
  "Verification email sent": "സ്ഥിരീകരണ ഇമെയിൽ അയച്ചു",
  "Confirm Enable Group Specific Properties": "ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവങ്ങൾ പ്രവർത്തനക്ഷമമാക്കൽ സ്ഥിരീകരിക്കുക",
  "This will create a group-specific properties table for this group.  You should then add needed properties with the Group-Specific Properties Form Editor.": "ഈ ഗ്രൂപ്പിനായി ഒരു ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവ പട്ടിക ഉണ്ടാക്കും. ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവ ഫോം എഡിറ്ററിൽ ആവശ്യമായ സ്വഭാവങ്ങൾ ചേർക്കുക.",
  "Confirm Disable Group Specific Properties": "ഗ്രൂപ്പ് പ്രത്യേക സ്വഭാവങ്ങൾ പ്രവർത്തനരഹിതമാക്കൽ സ്ഥിരീകരിക്കുക",
  "Are you sure you want to remove the group-specific person properties?  All group member properties data will be lost!": "ഗ്രൂപ്പ് പ്രത്യേക വ്യക്തി സ്വഭാവങ്ങൾ നീക്കം ചെയ്യണമോ? എല്ലാ ഗ്രൂപ്പ് അംഗ സ്വഭാവ ഡേറ്റയും നഷ്ടമാകും!",
  "Role Name": "പങ്കിന്റെ പേര്",
  "Sequence": "ക്രമം",
  "Do you want to delete this person?  This cannot be undone.": "ഈ വ്യക്തിയെ ഇല്ലാതാക്കണോ? ഇത് പഴയ നിലയിലേക്ക് മടക്കാനാകില്ല.",
  "Are you sure you want to unassign this property?": "ഈ സ്വഭാവം നീക്കം ചെയ്യണോ?",
  "Select a family": "ഒരു കുടുംബം തിരഞ്ഞെടുക്കുക",
  "Release Notes": "റിലീസ് കുറിപ്പുകൾ",
  "Move": "മാറ്റുക",
  "Arabic - Egypt": "Arabic - Egypt",
  "Thai": "Thai",
  "Pending Self Verify": "സ്വ-സ്ഥിരീകരണം കാത്തിരിക്കുന്നു",
  "Self Verify": "സ്വ-സ്ഥിരീകരണം",
  "Indonesian - Indonesia": "Indonesian - Indonesia",
  "records(s) successfully added to selected Group.": "റെക്കോർഡ്(കൾ) തിരഞ്ഞെടുത്ത ഗ്രൂപ്പിൽ വിജയകരമായി ചേർത്തു.",
  "For defining the date in Date-Picker, per default : yyyy-mm-dd, In French : dd/mm/yyyy for example.": "ഡേറ്റ്-പിക്കറിൽ തീയതി നിർവ്വചിക്കാൻ, ഡിഫോൾട്ടായി: yyyy-mm-dd, ഉദാഹരണം ഫ്രഞ്ചിൽ: dd/mm/yyyy.",
  "For defining the date in Date-Picker, per default : Y-m-d, In French : d/m/Y for example.": "ഡേറ്റ്-പിക്കറിൽ തീയതി നിർവ്വചിക്കാൻ, ഡിഫോൾട്ടായി: Y-m-d, ഉദാഹരണം ഫ്രഞ്ചിൽ: d/m/Y.",
  "Comma Separated list of PersonIDs of people to notify when a new family or person is added": "പുതിയ കുടുംബം അല്ലെങ്കിൽ വ്യക്തി ചേർക്കുമ്പോൾ അറിയിക്കേണ്ടവരുടെ PersonID-കളുടെ കോമ-വേർതിരിച്ച ലിസ്‌റ്റ്",
  "Allow unauthenticated reads of events from the external calendar API": "ബാഹ്യ കലണ്ടർ API-ൽ നിന്ന് ഇവന്റുകൾ ആധികാരികതയില്ലാതെ വായിക്കാൻ അനുവദിക്കുക",
  "New Person Added": "പുതിയ വ്യക്തി ചേർത്തു",
  "New Family Added": "പുതിയ കുടുംബം ചേർത്തു",
  "Church Greeter": "പള്ളി സ്വീകർത്താവ്",
  "External Calendar API is disabled": "ബാഹ്യ കലണ്ടർ API പ്രവർത്തനരഹിതമാണ്",
  "Special Group Settings : Sunday School Type": "പ്രത്യേക ഗ്രൂപ്പ് ക്രമീകരണങ്ങൾ: സൺഡേ സ്‌കൂൾ തരം",
  "Sunday School group can't be modified, only in this two cases :": "സൺഡേ സ്‌കൂൾ ഗ്രൂപ്പ് ഈ രണ്ട് കേസുകളിൽ മാത്രം മാറ്റാൻ കഴിയൂ:",
  "Add new roles, but not modify or rename the Student and the Teacher roles.": "പുതിയ പങ്കുകൾ ചേർക്കാം, എന്നാൽ വിദ്യാർത്ഥി, അദ്ധ്യാപക പങ്കുകൾ മാറ്റാനോ പേരുമാറ്റാനോ ആകില്ല.",
  "E": "കി.",
  "ENE": "കിവ.കി.",
  "ESE": "കിത.കി.",
  "N": "വ.",
  "NE": "വ.കി.",
  "NNE": "വ.വ.കി.",
  "NNW": "വ.വ.പ.",
  "NW": "വ.പ.",
  "S": "ത.",
  "SE": "ത.കി.",
  "SSW": "ത.ത.പ.",
  "SW": "ത.പ.",
  "W": "പ.",
  "WNW": "പ.വ.പ.",
  "WSW": "പ.ത.പ.",
  "Search Family": "കുടുംബം തിരയുക",
  "Show Family Head of House Names": "കുടുംബ നാഥൻ്റെ പേരുകൾ കാണിക്കുക",
  "Search Groups": "ഗ്രൂപ്പുകൾ തിരയുക",
  "Search Deposits": "ഡിപ്പോസിറ്റുകൾ തിരയുക",
  "Search Payments": "പേമെന്റുകൾ തിരയുക",
  "Quick Search": "ദ്രുത തിരയൽ",
  "Search Addresses": "വിലാസങ്ങൾ തിരയുക",
  "Maximum number of Families": "പരമാവധി കുടുംബങ്ങളുടെ എണ്ണം",
  "Maximum number of Family H.O.H Names": "പരമാവധി കുടുംബ നാഥൻ്റെ പേരുകളുടെ എണ്ണം",
  "Maximum number of Groups": "പരമാവധി ഗ്രൂപ്പുകളുടെ എണ്ണം",
  "Maximum number of Deposits": "പരമാവധി ഡിപ്പോസിറ്റുകളുടെ എണ്ണം",
  "Maximum number of Payments": "പരമാവധി പേമെന്റുകളുടെ എണ്ണം",
  "Maximum number of Addresses": "പരമാവധി വിലാസങ്ങളുടെ എണ്ണം",
  "Add Students": "വിദ്യാർത്ഥികളെ ചേർക്കുക",
  "OK": "ശരി",
  "Please select target Role for members": "അംഗങ്ങൾക്കായി ലക്ഷ്യ പങ്ക് തിരഞ്ഞെടുക്കുക",
  "GroupID required for role selection prompt": "പങ്ക് തിരഞ്ഞെടുക്കൽ പ്രോംപ്റ്റിന് GroupID ആവശ്യമാണ്",
  "Select Group and Role": "ഗ്രൂപ്പും പങ്കും തിരഞ്ഞെടുക്കുക",
  "All Members": "എല്ലാ അംഗങ്ങളും",
  "PhotoBook": "ഫോട്ടോ ബുക്ക്",
  "With Photos": "ഫോട്ടോകളോടൊപ്പം",
  "Create PhotoBook": "ഫോട്ടോ ബുക്ക് ഉണ്ടാക്കുക",
  "SSE": "ത.ത.കി.",
  "Recipient Naming Method": "സ്വീകർത്താവ് നാമ രീതി",
  "Salutation Utility": "അഭിവാദ്യ ഉപകരണം",
  "Add A Group Name": "ഒരു ഗ്രൂപ്പ് പേര് ചേർക്കുക",
  "Default Name Group": "ഡിഫോൾട്ട് പേര് ഗ്രൂപ്പ്",
  "Group Role": "ഗ്രൂപ്പ് പങ്ക്",
  "OR Create a Group and add the CART in ONE ACTION": "അല്ലെങ്കിൽ ഒരു ഗ്രൂപ്പ് ഉണ്ടാക്കി ഒരേ പ്രവർത്തനത്തിൽ കാർട്ട് ചേർക്കുക",
  "Create Group + ADD Cart": "ഗ്രൂപ്പ് ഉണ്ടാക്കുക + കാർട്ട് ചേർക്കുക",
  "Profile": "പ്രൊഫൈൽ",
  "Sign out": "പുറത്തിറങ്ങുക",
  "Sermon Text": "പ്രഭാഷണ ടെക്സ്റ്റ്",
  "Change Settings": "ക്രമീകരണങ്ങൾ മാറ്റുക",
  "Unknown Type": "അജ്ഞാത തരം",
  "PersonID for Cart must be numeric": "കാർട്ടിനുള്ള PersonID അക്കത്തിൽ ആയിരിക്കണം",
  "GroupID for Cart must be numeric": "കാർട്ടിനുള്ള GroupID അക്കത്തിൽ ആയിരിക്കണം",
  "FamilyID for Cart must be numeric": "കാർട്ടിനുള്ള FamilyID അക്കത്തിൽ ആയിരിക്കണം",
  "Search People": "ആളുകൾ തിരയുക",
  "Maximum number of People": "പരമാവധി ആളുകളുടെ എണ്ണം",
  "Field where Father Of Confession is listed, must be a people of group type": "കുമ്പസ്സാർ അച്ഛൻ ലിസ്‌റ്റ് ചെയ്യപ്പെടുന്ന ഫീൽഡ്, ഗ്രൂപ്പ് തരത്തിലെ ആൾ ആയിരിക്കണം",
  "Field where last Confession is stored, must be a date type": "അവസാന കുമ്പസ്സാർ സൂക്ഷിക്കുന്ന ഫീൽഡ്, തീയതി തരം ആയിരിക്കണം",
  "People Reports": "ആളുകൾ റിപ്പോർട്ടുകൾ",
  "People Dashboard": "ആളുകൾ ഡാഷ്‌ബോർഡ്",
  "People Directory": "ആളുകൾ ഡയറക്ടറി",
  "System Upgrade": "സിസ്റ്റം അപ്‌ഗ്രേഡ്",
  "Contributing": "സംഭാവന ചെയ്യുന്നു",
  "Automatically enable SMTP encryption if offered by the relaying server.": "റിലേ ചെയ്യുന്ന സർവ്വർ വാഗ്ദാനം ചെയ്താൽ SMTP എൻക്രിപ്ഷൻ സ്വയം പ്രവർത്തനക്ഷമമാക്കുക.",
  "Set the encryption system to use - ssl (deprecated) or tls": "ഉപയോഗിക്കേണ്ട എൻക്രിപ്ഷൻ സിസ്റ്റം ക്രമീകരിക്കുക - ssl (പഴഞ്ചൻ) അല്ലെങ്കിൽ tls",
  "Generate Deposit Slip for Selected Rows (PDF)": "തിരഞ്ഞെടുത്ത വരികൾക്ക് ഡിപ്പോസിറ്റ് സ്ലിപ്പ് ഉണ്ടാക്കുക (PDF)",
  "Add All to Cart": "എല്ലാം കാർട്ടിൽ ചേർക്കുക",
  "Remove All from Cart": "കാർട്ടിൽ നിന്ന് എല്ലാം നീക്കം ചെയ്യുക",
  "records(s) successfully deleted from the selected Group.": "റെക്കോർഡ്(കൾ) തിരഞ്ഞെടുത്ത ഗ്രൂപ്പിൽ നിന്ന് വിജയകരമായി ഇല്ലാതാക്കി.",
  "Not Found": "കണ്ടെത്തിയില്ല",
  "User must be an Admin": "ഉപയോക്താവ് അഡ്‌മിൻ ആയിരിക്കണം",
  "No logged in user": "ലോഗ്-ഇൻ ചെയ്ത ഉപയോക്താവ് ഇല്ല",
  "not found": "കണ്ടെത്തിയില്ല",
  "Deleted from group": "ഗ്രൂപ്പിൽ നിന്ന് ഇല്ലാതാക്കി",
  "Added to group": "ഗ്രൂപ്പിൽ ചേർത്തു",
  "SMTP Host is not setup, please visit the settings page": "SMTP ഹോസ്റ്റ് ക്രമീകരിച്ചിട്ടില്ല, ദയവായി ക്രമീകരണ പേജ് സന്ദർശിക്കുക",
  "Debug Email Connection": "ഇമെയിൽ ബന്ധം ഡീബഗ് ചെയ്യുക",
  "This Family is Inactive": "ഈ കുടുംബം നിഷ്‌ക്രിയമാണ്",
  "The database has been cleared.": "ഡേറ്റാബേസ് ക്ലിയർ ചെയ്തു.",
  "Anniversaries": "വാർഷികങ്ങൾ",
  "New Family Notification Email Error": "പുതിയ കുടുംബ അറിയിപ്പ് ഇമെയിൽ പിശക്",
  "New Person Notification Email Error": "പുതിയ വ്യക്തി അറിയിപ്പ് ഇമെയിൽ പിശക്",
  "View User": "ഉപയോക്താവ് കാണുക",
  "not found or user without an email": "കണ്ടെത്തിയില്ല അല്ലെങ്കിൽ ഇമെയിൽ ഇല്ലാത്ത ഉപയോക്താവ്",
  "UserName not set": "ഉപയോക്തൃനാമം ക്രമീകരിച്ചിട്ടില്ല",
  "Self Registrations": "സ്വ-രജിസ്ട്രേഷനുകൾ",
  "Public Calendar": "പൊതു കലണ്ടർ",
  "Private Calendar": "സ്വകാര്യ കലണ്ടർ",
  "Username": "ഉപയോക്തൃനാമം",
  "Are you sure you want to move": "മാറ്റണോ",
  "Access Token": "ആക്സസ് ടോക്കൺ",
  "New Access Token": "പുതിയ ആക്സസ് ടോക്കൺ",
  "ICS URL": "ICS URL",
  "Foreground Color": "ഫോർഗ്രൗണ്ട് നിറം",
  "Background Color": "ബാക്ക്ഗ്രൗണ്ട് നിറം",
  "Delete Calendar": "കലണ്ടർ ഇല്ലാതാക്കുക",
  "Invalid Entry": "അസാധുവായ എൻട്രി",
  "Calendar Name": "കലണ്ടർ നാമം",
  "New Calendar": "പുതിയ കലണ്ടർ",
  "Links": "ലിങ്കുകൾ",
  "Enable Finance menu": "ധനകാര്യ മെനു പ്രവർത്തനക്ഷമമാക്കുക",
  "Enable Fundraiser menu.": "ഫണ്ട്‌റൈസർ മെനു പ്രവർത്തനക്ഷമമാക്കുക.",
  "Validation Error": "സ്ഥിരീകരണ പിശക്",
  "Debug": "ഡീബഗ്",
  "Family Custom Fields": "കുടുംബ ഇഷ്‌ടാനുസൃത ഫീൽഡുകൾ",
  "Person Custom Fields": "വ്യക്തി ഇഷ്‌ടാനുസൃത ഫീൽഡുകൾ",
  "Donation Funds": "സംഭാവന ഫണ്ടുകൾ",
  "Unable to open file": "ഫയൽ തുറക്കാൻ കഴിഞ്ഞില്ല",
  "Missing calendar access token": "കലണ്ടർ ആക്സസ് ടോക്കൺ ഇല്ല",
  "Calendar access token not found": "കലണ്ടർ ആക്സസ് ടോക്കൺ കണ്ടെത്തിയില്ല",
  "User must have Delete Records permission": "ഉപയോക്താവിന് റെക്കോർഡ് ഇല്ലാതാക്കൽ അനുമതി ഉണ്ടായിരിക്കണം",
  "ChurchCRM Central Notifications URL": "ChurchCRM കേന്ദ്ര അറിയിപ്പ് URL",
  "invalid event type id": "അസാധുവായ ഇവന്റ് തരം ID",
  "invalid calendar pinning": "അസാധുവായ കലണ്ടർ പിന്നിംഗ്",
  "invalid status value": "അസാധുവായ സ്ഥിതി മൂല്യം",
  "invalid export value": "അസാധുവായ കയറ്റുമതി മൂല്യം",
  "Invalid User/Password": "അസാധുവായ ഉപയോക്താവ്/പാസ്‌വേഡ്",
  "Duplicate Emails": "ഡ്യൂപ്ലിക്കേറ്റ് ഇമെയിലുകൾ",
  "HTML URL": "HTML URL"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-9.json', 'w', encoding='utf-8') as f:
    json.dump(translations_9, f, ensure_ascii=False, indent=2)
print("ml-9.json written")
