import json

translations_2 = {
  "Donation Fund Editor": "സംഭാവന ഫണ്ട് എഡിറ്റർ",
  "Invalid fields or selections. Changes not saved! Please correct and try again!": "അസാധുവായ ഫീൽഡുകൾ അല്ലെങ്കിൽ തിരഞ്ഞെടുപ്പുകൾ. മാറ്റങ്ങൾ സംരക്ഷിച്ചില്ല! ദയവായി ശരിയാക്കി വീണ്ടും ശ്രമിക്കുക!",
  "No funds have been added yet": "ഇതുവരെ ഫണ്ടുകൾ ഒന്നും ചേർത്തിട്ടില്ല",
  "Active": "സജീവം",
  "Save Changes": "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
  "Church Event Editor": "പള്ളി ഇവന്റ് എഡിറ്റർ",
  "Edit Event Types": "ഇവന്റ് തരങ്ങൾ എഡിറ്റ് ചെയ്യുക",
  "Edit Event Type": "ഇവന്റ് തരം എഡിറ്റ് ചെയ്യുക",
  "Event Type": "ഇവന്റ് തരം",
  "Save Name": "പേര് സംരക്ഷിക്കുക",
  "Recurrence Pattern": "ആവർത്തന രീതി",
  "Attendance Counts": "ഹാജർ എണ്ണം",
  "Return to Event Types": "ഇവന്റ് തരങ്ങളിലേക്ക് മടങ്ങുക",
  "Family": "കുടുംബം",
  "Type": "തരം",
  "Fiscal Year": "ധനകാര്യ വർഷം",
  "Amount": "തുക",
  "Fund": "ഫണ്ട്",
  "Bank": "ബാങ്ക്",
  "Year": "വർഷം",
  "Edit": "എഡിറ്റ് ചെയ്യുക",
  "Event Title": "ഇവന്റ് തലക്കെട്ട്",
  "Create Event": "ഇവന്റ് ഉണ്ടാക്കുക",
  "Create a new Event": "പുതിയ ഇവന്റ് ഉണ്ടാക്കുക",
  " errors. Please see below": " പിശകുകൾ. ദയവായി താഴെ കാണുക",
  "Select your event type": "നിങ്ങളുടെ ഇവന്റ് തരം തിരഞ്ഞെടുക്കുക",
  "You must pick an event type.": "ഒരു ഇവന്റ് തരം തിരഞ്ഞെടുക്കണം.",
  "No Attendance counts recorded": "ഹാജർ എണ്ണം രേഖപ്പെടുത്തിയിട്ടില്ല",
  "Event Status": "ഇവന്റ് സ്ഥിതി",
  "Return to Events": "ഇവന്റുകളിലേക്ക് മടങ്ങുക",
  "Sundays": "ഞായറാഴ്ചകൾ",
  "Mondays": "തിങ്കളാഴ്ചകൾ",
  "Tuesdays": "ചൊവ്വാഴ്ചകൾ",
  "Wednesdays": "ബുധനാഴ്ചകൾ",
  "Thursdays": "വ്യാഴാഴ്ചകൾ",
  "Fridays": "വെള്ളിയാഴ്ചകൾ",
  "Saturdays": "ശനിയാഴ്ചകൾ",
  "Add Event Type": "ഇവന്റ് തരം ചേർക്കുക",
  "Custom Family Fields Editor": "ഇഷ്‌ടാനുസൃത കുടുംബ ഫീൽഡ് എഡിറ്റർ",
  "Default Option": "ഡിഫോൾട്ട് ഓപ്ഷൻ",
  "No custom Family fields have been added yet": "ഇഷ്‌ടാനുസൃത കുടുംബ ഫീൽഡുകൾ ഇതുവരെ ചേർത്തിട്ടില്ല",
  "Special option": "പ്രത്യേക ഓപ്ഷൻ",
  "Security Option": "സുരക്ഷ ഓപ്ഷൻ",
  "You must select a group.": "ഒരു ഗ്രൂപ്പ് തിരഞ്ഞെടുക്കണം.",
  "Edit List Options": "ലിസ്റ്റ് ഓപ്ഷനുകൾ എഡിറ്റ് ചെയ്യുക",
  "Help on types..": "തരങ്ങളിൽ സഹായം..",
  "You must enter a name": "ഒരു പേര് നൽകണം",
  "That field name already exists.": "ആ ഫീൽഡ് പേര് ഇതിനകം നിലവിലുണ്ട്.",
  "Family Editor": "കുടുംബ എഡിറ്റർ",
  "First name must be entered": "പേര് നൽകണം",
  "Invalid Birth Date.": "ജനന തീയതി അസാധുവാണ്.",
  "Not a valid Wedding Date": "സാധുവായ വിവാഹ തീയതിയല്ല",
  "Email is Not Valid": "ഇമെയിൽ സാധുവല്ല",
  "Family Info": "കുടുംബ വിവരം",
  "Contact Info": "ബന്ധ വിവരം",
  "Envelope Info": "കവർ വിവരം",
  "Custom Fields": "ഇഷ്‌ടാനുസൃത ഫീൽഡുകൾ",
  "Family Members": "കുടുംബാംഗങ്ങൾ",
  "First": "ആദ്യം",
  "Middle": "മദ്ധ്യം",
  "Last": "അവസാനം",
  "Role": "പങ്ക്",
  "Select Gender": "ലിംഗം തിരഞ്ഞെടുക്കുക",
  "Select Role": "പങ്ക് തിരഞ്ഞെടുക്കുക",
  "Unknown": "അജ്ഞാതം",
  "January": "ജനുവരി",
  "February": "ഫെബ്രുവരി",
  "March": "മാർച്ച്",
  "April": "ഏപ്രിൽ",
  "May": "മേയ്",
  "June": "ജൂൺ",
  "July": "ജൂലൈ",
  "August": "ഓഗസ്റ്റ്",
  "September": "സെപ്‌റ്റംബർ",
  "October": "ഒക്ടോബർ",
  "November": "നവംബർ",
  "December": "ഡിസംബർ",
  "Unk": "അജ്ഞ",
  "Created": "ഉണ്ടാക്കി",
  "Envelope Number": "കവർ നമ്പർ",
  "Upload Photo": "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
  "Delete Photo": "ഫോട്ടോ ഇല്ലാതാക്കുക",
  "Timeline": "ടൈംലൈൻ",
  "Pledges and Payments": "സംഭാവന പ്രതിജ്ഞകളും പേമെന്റുകളും",
  "Value": "മൂല്യം",
  "Edit Value": "മൂല്യം എഡിറ്റ് ചെയ്യുക",
  "Assign a New Property": "പുതിയ സ്വഭാവം നൽകുക",
  "Assign": "നൽകുക",
  "Date Updated": "അപ്‌ഡേറ്റ് ചെയ്ത തീയതി",
  "Updated By": "അപ്‌ഡേറ്റ് ചെയ്തത്",
  "Since": "മുതൽ",
  "Update": "അപ്‌ഡേറ്റ്",
  "Date": "തീയതി",
  "Schedule": "ഷെഡ്യൂൾ",
  "Method": "രീതി",
  "Comment": "അഭിപ്രായം",
  "Close": "അടയ്ക്കുക",
  "Confirm Delete": "ഇല്ലാതാക്കൽ സ്ഥിരീകരിക്കുക",
  "You are about to delete the profile photo, this procedure is irreversible.": "നിങ്ങൾ പ്രൊഫൈൽ ഫോട്ടോ ഇല്ലാതാക്കാൻ പോകുകയാണ്, ഈ നടപടി മാറ്റാനാവില്ല.",
  "Do you want to proceed?": "തുടരാൻ ആഗ്രഹിക്കുന്നോ?",
  "You are about to email copy of the family information to the following emails": "നിങ്ങൾ ഇനിപ്പറയുന്ന ഇമെയിലുകളിലേക്ക് കുടുംബ വിവരം ഇമെയിൽ ചെയ്യാൻ പോകുകയാണ്",
  "Financial Reports": "സാമ്പത്തിക റിപ്പോർട്ടുകൾ",
  "Report Type": "റിപ്പോർട്ട് തരം",
  "Select Report Type": "റിപ്പോർട്ട് തരം തിരഞ്ഞെടുക്കുക",
  "Pledge Summary": "സംഭാവന പ്രതിജ്ഞ സംഗ്രഹം",
  "Pledge Family Summary": "കുടുംബ സംഭാവന പ്രതിജ്ഞ സംഗ്രഹം",
  "Pledge Reminders": "സംഭാവന പ്രതിജ്ഞ ഓർമ്മിപ്പിക്കൽ",
  "Voting Members": "വോട്ടർ അംഗങ്ങൾ",
  "Giving Report (Tax Statements)": "ദക്ഷിണ റിപ്പോർട്ട് (നികുതി സ്റ്റേറ്റ്‌മെന്റുകൾ)",
  "Zero Givers": "ദക്ഷിണ നൽകാത്തവർ",
  "Individual Deposit Report": "വ്യക്തിഗത ഡിപ്പോസിറ്റ് റിപ്പോർട്ട്",
  "Advanced Deposit Report": "വിപുലമായ ഡിപ്പോസിറ്റ് റിപ്പോർട്ട്",
  "Next": "അടുത്തത്",
  "Filter by Family": "കുടുംബം അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
  "Report Start Date": "റിപ്പോർട്ട് ആരംഭ തീയതി",
  "Report End Date": "റിപ്പോർട്ട് അവസാന തീയതി",
  "Apply Report Dates To": "റിപ്പോർട്ട് തീയതികൾ ബാധകമാക്കുക",
  "Deposit Date (Default)": "ഡിപ്പോസിറ്റ് തീയതി (ഡിഫോൾട്ട്)",
  "Payment Date": "പേമെന്റ് തീയതി",
  "Filter by Deposit": "ഡിപ്പോസിറ്റ് അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
  "If deposit is selected, date criteria will be ignored.": "ഡിപ്പോസിറ്റ് തിരഞ്ഞെടുത്താൽ, തീയതി മാനദണ്ഡം അവഗണിക്കപ്പെടും.",
  "All deposits within date range": "തീയതി ശ്രേണിക്കുള്ളിലെ എല്ലാ ഡിപ്പോസിറ്റുകളും",
  "Filter by Payment Type": "പേമെന്റ് തരം അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക",
  "All Methods": "എല്ലാ രീതികളും",
  "Check": "ചെക്ക്",
  "Cash": "പണം",
  "Bank Draft": "ബാങ്ക് ഡ്രാഫ്റ്റ്",
  "Minimum Total Amount:": "ഏറ്റവും കുറഞ്ഞ ആകെ തുക:",
  "0 - No Minimum": "0 - ഏറ്റവും കുറഞ്ഞ തുകയില്ല",
  "Other Settings": "മറ്റ് ക്രമീകരണങ്ങൾ",
  "Only Payments with Pledges": "സംഭാവന പ്രതിജ്ഞ ഉള്ള പേമെന്റുകൾ മാത്രം",
  "All Payments": "എല്ലാ പേമെന്റുകളും",
  "Only Families with unpaid pledges": "അടയ്ക്കാത്ത സംഭാവന പ്രതിജ്ഞ ഉള്ള കുടുംബങ്ങൾ മാത്രം",
  "All Families": "എല്ലാ കുടുംബങ്ങളും",
  "Report Heading:": "റിപ്പോർട്ട് ശീർഷകം:",
  "Graphic": "ഗ്രാഫിക്",
  "Church Address": "പള്ളി വിലാസം",
  "Blank": "ശൂന്യം",
  "Remittance Slip:": "അയക്കൽ സ്ലിപ്പ്:",
  "Sort Data by:": "ഡേറ്റ അടുക്കേണ്ടത്:",
  "Deposit": "ഡിപ്പോസിറ്റ്",
  "All Data": "എല്ലാ ഡേറ്റയും",
  "Moderate Detail": "മിതമായ വിശദാംശം",
  "Summary Data": "സംഗ്രഹ ഡേറ്റ",
  "CSV": "CSV",
  "Back": "പിന്നോട്ട്",
  "Create Report": "റിപ്പോർട്ട് ഉണ്ടാക്കുക",
  "Deposit Listing": "ഡിപ്പോസിറ്റ് ലിസ്‌റ്റ്",
  "Deposits": "ഡിപ്പോസിറ്റുകൾ",
  "Delete Selected Rows": "തിരഞ്ഞെടുത്ത വരികൾ ഇല്ലാതാക്കുക"
}

with open('/home/runner/work/CRM/CRM/locale/terms/missing/ml/ml-2.json', 'w', encoding='utf-8') as f:
    json.dump(translations_2, f, ensure_ascii=False, indent=2)
print("ml-2.json written")
