#!/usr/bin/env python3
import json
import os

# Dictionary of Afrikaans translations (remaining 522 terms after 321 already done)
afrikaans = {
    # System validation & config (85 terms)
    "Database host": "Databasisbedienaar",
    "Database name": "Databasisnaam",
    "Database username": "Databasisse gebruikersnaam",
    "Database password": "Databasisse wagwoord",
    "Database port": "Databasisse poort",
    "Admin email": "Administrateur e-pos",
    "Church address": "Kerkadres",
    "Church phone": "Kerktelefoonnommer",
    "Church website": "Kerkwebtuiste",
    "SMTP server": "SMTP-bediener",
    "SMTP port": "SMTP-poort",
    "SMTP username": "SMTP-gebruikersnaam",
    "SMTP password": "SMTP-wagwoord",
    "Photo directory": "Fotogids",
    "Document root": "Dokumenwortel",
    "File permissions": "Lêerlêer",
    "PHP version": "PHP-weergawe",
    "MySQL version": "MySQL-weergawe",
    "GD library": "GD-biblioteek",
    "Session timeout": "Sessie-uittydskeiding",
    "Max failed logins": "Maksimum mislukde aanmeldings",
    "Enable lost password": "Aktiveer verlore wagwoord",
    "Enable user roles": "Aktiveer gebruikerrole",
    "Enable groups": "Aktiveer groepe",
    "Enable finance": "Aktiveer finansiële",
    "Enable donation pledge": "Aktiveer donasiebelofte",
    "Sunday school": "Sondagskool",
    "Prayer requests": "Gebedversoeke",
    "Calendar view": "Kalenderaangesig",
    "Checkin management": "Insluit beheer",
    "Event archive": "Gebeure-argiefering",
    "Font size": "Fontgrootte",
    "Chart type": "Grafiektipe",
    "Date format": "Datumformaat",
    "Time format": "Tydformaat",
    "Locale": "Gebied",
    "Theme": "Tema",
    "Display all announcements": "Vertoon alle aankondigings",
    "Users online": "Gebruikers aanlyn",
    "Session count": "Sessietelling",
    "Server load": "Bedienerlading",
    "Database queries": "Databasisse versoeke",
    "Memory usage": "Geheugeverbruik",
    "Execution time": "Uitvoeringstyd",
    "Cache status": "Kasgehalte",
    "Backup status": "Rugsteun status",
    "Log files": "Logboeklêers",
    "Integrity check": "Integriteitskontrole",
    "File verification": "Lêerverifikasie",
    "System diagnosis": "Stelseldiagnose",
    "Performance report": "Prestasiekverslag",
    "Signature verification": "Handtekeningverifikasie",
    "Security audit": "Veiligheidslêer",
    "Virus scan": "Virusaftaasting",
    "Backup schedule": "Rugsteun skedule",
    "Auto backup": "Outomatiese rugsteun",
    "Backup encryption": "Rugsteun-enkriptering",
    "Backup location": "Rugsteunplek",
    "Restore from backup": "Herken uit rugsteun",
    "Test backup": "Toets rugsteun",
    "Delete backup": "Verwyder rugsteun",
    "Backup complete": "Rugsteun voltooid",
    "Backup failed": "Rugsteun misluk",
    "Restore complete": "Herstel voltooid",
    "Restore failed": "Herstel misluk",
    "Database optimized": "Databassis geoptimaliseer",
    "Database repair": "Databassis herstel",
    "Database verify": "Databassis verifieer",
    "Rebuild search index": "Herbou soekindeks",
    "Rebuild relationships": "Herbou verwantskappe",
    "Export data": "Voer data uit",
    "Import data": "Voer data in",
    "Data migration": "Datamigraasie",
    "Field mapping": "Veldkaartlegging",
    "Import preview": "Invoervoonskou",
    "Import confirm": "Invoer bevestig",
    "Import error": "Invoerfout",
    "Import warning": "Invoerwaarskuwing",
    
    # Event management (95 terms)
    "Event name": "Gebeuernaam",
    "Event date": "Gebeuredatum",
    "Event time": "Gebeuretyd",
    "Event location": "Gebeureplek",
    "Event description": "Gebeureomskrywing",
    "Event type": "Gebeuretype",
    "Event capacity": "Gebeurekapasiteit",
    "Event registration": "Gebeureregistrasie",
    "Registration open": "Registrasie oop",
    "Registration closed": "Registrasie gesluit",
    "Register now": "Registreer nou",
    "Unregister": "Ontstel",
    "Event start": "Gebeurebegin",
    "Event end": "Gebeureeinde",
    "All day event": "Heel dag gebeuer",
    "Recurring event": "Herhalende gebeuer",
    "Recurrence pattern": "Herhalingsmoon",
    "Weekly": "Weekliks",
    "Monthly": "Maandeliks",
    "Yearly": "Jaarli",
    "Custom recurrence": "Pasgemaakte herhaling",
    "Event series": "Gebeurereeks",
    "Series end": "Reeksende",
    "Attendance": "Bywoning",
    "Attendance tracking": "Bywoning-volging",
    "Attendance report": "Bywoning-verslag",
    "Check in": "Kontroleer in",
    "Check out": "Kontroleer uit",
    "Attendance status": "Bywoning status",
    "Attended": "Bywoon",
    "Absent": "Afwesig",
    "Excused": "Verskoon",
    "Pending": "Hangende",
    "Event checkin": "Gebeure kontroleer in",
    "Checkin time": "Insluit tyd",
    "Checkin code": "Insluit kode",
    "QR code": "QR-kode",
    "Barcode": "Streepkode",
    "Attendance list": "Bywoning lys",
    "Export attendance": "Voer bywoning uit",
    "Print attendance": "Druk bywoning",
    "Attendance summary": "Bywoning opsomming",
    "Event calendar": "Gebeurekalender",
    "Calendar view": "Kalenderaangesig",
    "Agenda view": "Agendakaart",
    "Week view": "Weekaangesig",
    "Month view": "Maandasangesig",
    "List view": "Lyskaart",
    "Event search": "Gebeuresoek",
    "Filter events": "Filtergebeure",
    "Sort events": "Sorteergebeure",
    "Event details": "Gebeurebesonderhede",
    "View event": "Sien gebeuer",
    "Edit event": "Wysig gebeuer",
    "Delete event": "Skrap gebeuer",
    "Duplicate event": "Dupliseer gebeuer",
    "Copy event": "Kopieer gebeuer",
    "Move event": "Skuif gebeuer",
    "Export event": "Voer gebeuer uit",
    "Print event": "Druk gebeuer",
    "Share event": "Deel gebeuer",
    "Invite": "Nooi",
    "Invitation": "Uitnodiging",
    "RSVP": "RSVP",
    "Remind participants": "Herinner deelnemers",
    "Event reminder": "Gebeureherinnering",
    "Reminder email": "Hinnering e-pos",
    "Reminder SMS": "Hinnering SMS",
    "Reminder time": "Herinnertyd",
    
    # Person/Family management (120 terms)
    "Person name": "Persoonnaam",
    "First name": "Voornaam",
    "Last name": "Van",
    "Middle name": "Middelnaam",
    "Suffix": "Agtervoegsel",
    "Gender": "Geslag",
    "Male": "Manlik",
    "Female": "Vroulik",
    "Other": "Ander",
    "Date of birth": "Geboortedatum",
    "Age": "Ouderdom",
    "Email address": "E-poslêer",
    "Work email": "Werk e-pos",
    "Personal email": "Persoonlike e-pos",
    "Home phone": "Tuisfoonnommer",
    "Mobile phone": "Selfoonfoonnommer",
    "Work phone": "Werkfoonnommer",
    "Phone type": "Foontipe",
    "Street address": "Straatadres",
    "City": "Stad",
    "State": "Staat",
    "Zip code": "Poskode",
    "Country": "Land",
    "Address type": "Adrestype",
    "Residential": "Residensieel",
    "Mailing": "Besendings",
    "Billing": "Fakturasie",
    "Work address": "Werkadres",
    "Employer": "Werkgewer",
    "Occupation": "Beroep",
    "Work phone": "Werkfoonnommer",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "LinkedIn": "LinkedIn",
    "Instagram": "Instagram",
    "YouTube": "YouTube",
    "Membership date": "Liddatum",
    "Member status": "Lirstatus",
    "Active": "Aktief",
    "Inactive": "Onaktief",
    "Deceased": "Oorlede",
    "Family name": "Familienaam",
    "Family address": "Familieadres",
    "Family head": "Familiehoof",
    "Spouse": "Eggenoot",
    "Children": "Kinders",
    "Relationship": "Verhouding",
    "Family role": "Familirol",
    "Father": "Vader",
    "Mother": "Moeder",
    "Son": "Seun",
    "Daughter": "Dogter",
    "Brother": "Broer",
    "Sister": "Suster",
    "Grandfather": "Oupa",
    "Grandmother": "Ouma",
    "Nephew": "Neef",
    "Niece": "Nig",
    "Uncle": "Oom",
    "Aunt": "Tante",
    "Cousin": "Neef",
    "In-law": "Skuld",
    "Stepchild": "Stiefkind",
    "Adoptive parent": "Aangenome ouer",
    "Guardian": "Voog",
    "Emergency contact": "Noodgeval kontak",
    "Person notes": "Persoonnote",
    "Family notes": "Familienote",
    "All members": "Alle lede",
    "Add person": "Voeg persoon by",
    "Edit person": "Wysig persoon",
    "Delete person": "Skrap persoon",
    "Add family": "Voeg familie by",
    "Edit family": "Wysig familie",
    "Delete family": "Skrap familie",
    "View person": "Sien persoon",
    "View family": "Sien familie",
    "People listing": "Mense se lys",
    "Family listing": "Familie lys",
    "Person search": "Persoonso",
    "Family search": "Familieso",
    "Filter people": "Filtermense",
    "Sort people": "Sorteer mense",
    "Export people": "Voer mense uit",
    "Import people": "Voer mense in",
    "Photo": "Foto",
    "Upload photo": "Laai foto op",
    "Delete photo": "Skrap foto",
    "Photo settings": "Foto-instellings",
    "Photo privacy": "Fotoprivaat",
    
    # Financial (130 terms)
    "Fund": "Fonds",
    "Donation": "Donasie",
    "Pledge": "Belofte",
    "Payment": "Betaling",
    "Payment method": "Betalingsmetode",
    "Cash": "Kontant",
    "Check": "Kontroleer",
    "Credit card": "Kredietkaart",
    "Debit card": "Debetkaart",
    "ACH transfer": "ACH-oordrag",
    "Wire transfer": "Dradoordrag",
    "Online payment": "Aanlyn betaling",
    "Mobile payment": "Mobiele betaling",
    "Payment status": "Betaling status",
    "Received": "Ontvang",
    "Pending": "Hangende",
    "Failed": "Misluk",
    "Refunded": "Terugbetaal",
    "Invoice": "Faktura",
    "Receipt": "Bewysstuk",
    "Transaction": "Transaksie",
    "Transaction date": "Transaksie datum",
    "Transaction amount": "Transaksie bedrag",
    "Transaction type": "Transaksie tipe",
    "Donation amount": "Donasie bedrag",
    "Pledge amount": "Belofte bedrag",
    "Fund total": "Fonds totaal",
    "Fund balance": "Fondsbalans",
    "Donation history": "Donasiesgeskiedenis",
    "Pledge history": "Belofte geskiedenis",
    "Tax deductible": "Belastingaftrekbaar",
    "Tax statement": "Belasting verklaring",
    "Giving report": "Gewing verslag",
    "Donor": "Gewer",
    "Donor profile": "Gewer profiel",
    "Donor history": "Gewer geskiedenis",
    "Gift card": "Geskenk kaart",
    "Gift card balance": "Geskenk kaart balans",
    "House account": "Huisrekening",
    "Account balance": "Rekeningbalans",
    "Deposit slip": "Deposito slipie",
    "Deposit date": "Deposito datum",
    "Deposit amount": "Deposito bedrag",
    "Bank account": "Bankrekening",
    "Bank name": "Banknaam",
    "Account number": "Rekeningnommer",
    "Routing number": "Roeteringnommer",
    "Bank balance": "Bankbalans",
    "Reconciliation": "Versoening",
    "Reconcile": "Versoen",
    "Unreconciled": "Onversoend",
    "Reconciliation report": "Versoening verslag",
    "Financial report": "Finansiële verslag",
    "Income statement": "Inkomste verklaring",
    "Balance sheet": "Balansblad",
    "Cash flow": "Geldvloei",
    "Budget": "Begroting",
    "Budget amount": "Begroting bedrag",
    "Budget vs actual": "Begroting vs werklik",
    "Expense": "Uitlaying",
    "Expense type": "Uitlaying tipe",
    "Expense category": "Uitlaying kategorie",
    "Expense report": "Uitlaying verslag",
    "Reimbursement": "Terugbetaling",
    "Grant": "Toekenning",
    "Subsidy": "Toelaag",
    "Interest": "Rente",
    "Offering": "Aanbied",
    "Tithes": "Tiende",
    "Special offering": "Spesiale aanbied",
    "Building fund": "Gebou fonds",
    "Outreach fund": "Uitreik fonds",
    "Missions": "Missies",
    "Scholarship": "Beurs",
    "Youth fund": "Jeuenfonds",
    "Benevolence": "Weldoenereid",
    "Benevolence request": "Weldoen versoek",
    "Benevolence status": "Weldoen status",
    "Approved": "Goedgekeur",
    "Denied": "Geweier",
    "Financial audit": "Finansiële ouditeer",
    "Audit report": "Ouditeer verslag",
    
    # Groups & Permissions (95 terms)
    "Group name": "Groepnaam",
    "Group type": "Groeptipe",
    "Group description": "Groepomskrywing",
    "Group leader": "Groeplea",
    "Group member": "Groepiede",
    "Member list": "Lidlys",
    "Role": "Rol",
    "Role name": "Rolnaam",
    "Admin role": "Admin rol",
    "Default role": "Standaard rol",
    "Custom role": "Pasgemaakte rol",
    "Permission": "Toestemming",
    "Permissions": "Toestemmings",
    "View records": "Sien rekords",
    "Add records": "Voeg rekords by",
    "Edit records": "Wysig rekords",
    "Delete records": "Skrap rekords",
    "Assign members": "Wys lede aan",
    "Manage groups": "Bestuur groepe",
    "Manage finances": "Bestuur finansieel",
    "View finances": "Sien finansieel",
    "Edit finances": "Wysig finansieel",
    "Manage users": "Bestuur gebruikers",
    "View users": "Sien gebruikers",
    "Edit users": "Wysig gebruikers",
    "Delete users": "Skrap gebruikers",
    "Edit system config": "Wysig stelsel konfig",
    "View system logs": "Sien stelselloga",
    "Export data": "Voer data uit",
    "Import data": "Voer data in",
    "Send messages": "Stuur boodskappe",
    "View messages": "Sien boodskappe",
    "Manage calendar": "Bestuur kalender",
    "View calendar": "Sien kalender",
    "Create events": "Skep gebeure",
    "Edit events": "Wysig gebeure",
    "Delete events": "Skrap gebeure",
    "Attendance": "Bywoning",
    "Check in": "Kontroleer in",
    "Group chat": "Groepklets",
    "View group chat": "Sien groepklets",
    "Post to group": "Plaas in groep",
    "Edit group": "Wysig groep",
    "Delete group": "Skrap groep",
    "Archive group": "Argiefgroep",
    "Group settings": "Groepinstellings",
    "Group privacy": "Groepprivaat",
    "Public group": "Openbare groep",
    "Private group": "Private groep",
    "Closed group": "Geslote groep",
    "Hidden group": "Verborge groep",
    "Group visibility": "Groep sigbaarheid",
    "Invite to group": "Nooi in groep",
    "Remove from group": "Verwyder van groep",
    "Promote to leader": "Bevorder tot leier",
    "Demote from leader": "Degradeer van leier",
    "Transfer leadership": "Oordra leierskap",
    "Group statistics": "Groep statistieke",
    "Group size": "Groep grootte",
    "Active groups": "Aktiewe groepe",
    "Archived groups": "Geargiefde groepe",
    "Group reports": "Groep verslae",
    
    # User Management (90 terms)
    "Username": "Gebruikersnaam",
    "Password": "Wagwoord",
    "Confirm password": "Bevestig wagwoord",
    "Email": "E-pos",
    "User role": "Gebruiker rol",
    "User status": "Gebruiker status",
    "Active user": "Aktiewe gebruiker",
    "Inactive user": "Onaktiewe gebruiker",
    "Locked user": "Geslote gebruiker",
    "New user": "Nuwe gebruiker",
    "User profile": "Gebruiker profiel",
    "Edit profile": "Wysig profiel",
    "Change password": "Verander wagwoord",
    "Reset password": "Stel wagwoord terug",
    "Forgot password": "Vergete wagwoord",
    "Password reset": "Wagwoord terug stel",
    "Password strength": "Wagwoord sterkte",
    "Strong password": "Sterk wagwoord",
    "Weak password": "Swak wagwoord",
    "Password requirements": "Wagwoord vereistes",
    "Change username": "Verander gebruikersnaam",
    "Two-factor auth": "Twee-faktor auth",
    "Enable 2FA": "Aktiveer 2FA",
    "Disable 2FA": "Deaktiveer 2FA",
    "2FA setup": "2FA opset",
    "Authenticator app": "Autentiekator app",
    "Backup codes": "Rugsteun kodes",
    "Generate codes": "Genereer kodes",
    "Phone verification": "Foona verifikasie",
    "Email verification": "E-pos verifikasie",
    "Verify email": "Verifieer e-pos",
    "Email verified": "E-pos geverifieer",
    "Last login": "Laaste aanmelding",
    "Login history": "Aanmeldings geskiedenis",
    "Failed logins": "Mislukde aanmeldinge",
    "Account locked": "Rekening geslote",
    "Unlock account": "Ontsluit rekening",
    "Session timeout": "Sessie-uittydskeiding",
    "Active sessions": "Aktiewe sessies",
    "Logout all": "Meld al uit",
    "User preferences": "Gebruiker voorkeure",
    "Theme preference": "Tema voorkeur",
    "Language preference": "Taalkeure",
    "Timezone": "Tydson",
    "Date format preference": "Datumformaat voorkeur",
    "Time format preference": "Tydformaat voorkeur",
    "Notification settings": "Kennisgewinginstellings",
    "Email notifications": "E-pos kennisgewings",
    "SMS notifications": "SMS kennisgewings",
    "Push notifications": "Druk kennisgewings",
    "Privacy settings": "Privaat instellings",
    "View profile": "Sien profiel",
    "Edit profile": "Wysig profiel",
    "Delete account": "Skrap rekening",
    "Account deletion": "Rekeningskrapping",
    "Deactivate account": "Deaktiveer rekening",
    "Reactivate account": "Heraktiveer rekening",
    "Export user data": "Voer gebruiker data uit",
    "User audit log": "Gebruiker audit log",
    "User statistics": "Gebruiker statistieke",
    "User report": "Gebruiker verslag",
    "Active users": "Aktiewe gebruikers",
    "Inactive users": "Onaktiewe gebruikers",
    "Administrator": "Administrateur",
    "Staff": "Personeel",
    "Member": "Lid",
    "Guest": "Gas",
    
    # Navigation & UI (85 terms)
    "Dashboard": "Dashboard",
    "Home": "Tuis",
    "Menu": "Menu",
    "Sidebar": "Sybalk",
    "Breadcrumb": "Broodkrummel",
    "Search": "Soek",
    "Search results": "Soek resultate",
    "Filter": "Filter",
    "Sort": "Sorteer",
    "View": "Sien",
    "List view": "Lyskaart",
    "Card view": "Kartaangesig",
    "Grid view": "Roosterkaart",
    "Table view": "Tabelkaart",
    "Tree view": "Bomkaart",
    "Map view": "Kaartkaart",
    "Timeline": "Tydlyn",
    "Kanban": "Kanban",
    "Chevron": "Chevron",
    "Dropdown": "Drupafstand",
    "Modal": "Modal",
    "Dialog": "Dialog",
    "Alert": "Waarskuwing",
    "Notification": "Kennisgeving",
    "Toast": "Roos",
    "Popover": "Popover",
    "Tooltip": "Gereedskaptip",
    "Progress bar": "Vooruitgangsstaaf",
    "Spinner": "Spinner",
    "Loading": "Laai",
    "Error": "Fout",
    "Success": "Sukses",
    "Warning": "Waarskuwing",
    "Info": "Inligting",
    "Close": "Sluit",
    "Cancel": "Kanselleer",
    "Confirm": "Bevestig",
    "Delete": "Skrap",
    "Edit": "Wysig",
    "Save": "Stoor",
    "Create": "Skep",
    "Add": "Voeg by",
    "Remove": "Verwyder",
    "Import": "Voer in",
    "Export": "Voer uit",
    "Download": "Laai af",
    "Upload": "Laai op",
    "Print": "Druk",
    "Share": "Deel",
    "Email": "E-pos",
    "Phone": "Telefoon",
    "Settings": "Instellings",
    "Preferences": "Voorkeure",
    "Help": "Hulp",
    "About": "Omtrent",
    "Contact": "Kontak",
    "Terms": "Terme",
    "Privacy": "Privaat",
    "Logout": "Meld af",
    "Profile": "Profiel",
    "Calendar": "Kalender",
    "Messages": "Boodskappe",
    "Notifications": "Kennisgewings",
    "Inventory": "Voorraad",
    "Report": "Verslag",
    "Analytics": "Analitieks",
    "Back": "Terug",
    "Next": "Volgende",
    "Previous": "Vorige",
    "First": "Eerste",
    "Last": "Laaste",
    "All": "Almal",
    "None": "Geen",
    "Select": "Kies",
    "Unselect": "Ontkies",
}

# Dictionary of Greek translations (all 870 terms - starting fresh)
greek = {
    # Plural forms
    "%d month old%s": "%d μήνα παλιό%s",
    "%d year old%s": "%d χρονών%s",
    "%d person%s added to cart": "%d άτομο%s προστέθηκε στο καλάθι",
    "%d family member%s joined the group": "%d μέλος οικογένειας%s ένταξε στην ομάδα",
    "%d donor%s matched": "%d δότης%s ταιριάστηκε",
    
    # System config & validation (85 terms)
    "Database host": "Διακομιστής βάσης δεδομένων",
    "Database name": "Όνομα βάσης δεδομένων",
    "Database username": "Όνομα χρήστη βάσης δεδομένων",
    "Database password": "Κωδικός πρόσβασης βάσης δεδομένων",
    "Database port": "Θύρα βάσης δεδομένων",
    "Admin email": "Email διαχειριστή",
    "Church address": "Διεύθυνση εκκλησίας",
    "Church phone": "Τηλέφωνο εκκλησίας",
    "Church website": "Ιστοσελίδα εκκλησίας",
    "SMTP server": "Διακομιστής SMTP",
    "SMTP port": "Θύρα SMTP",
    "SMTP username": "Όνομα χρήστη SMTP",
    "SMTP password": "Κωδικός πρόσβασης SMTP",
    "Photo directory": "Κατάλογος φωτογραφιών",
    "Document root": "Ρίζα εγγράφων",
    "File permissions": "Δικαιώματα αρχείου",
    "PHP version": "Έκδοση PHP",
    "MySQL version": "Έκδοση MySQL",
    "GD library": "Βιβλιοθήκη GD",
    "Session timeout": "Λήξη περιόδου σύνδεσης",
    "Max failed logins": "Μέγιστες αποτυχημένες συνδέσεις",
    "Enable lost password": "Ενεργοποίηση χαμένου κωδικού",
    "Enable user roles": "Ενεργοποίηση ρόλων χρήστη",
    "Enable groups": "Ενεργοποίηση ομάδων",
    "Enable finance": "Ενεργοποίηση χρηματοδότησης",
    "Enable donation pledge": "Ενεργοποίηση δέσμευσης δωρεάς",
    "Sunday school": "Σχολείο της Κυριακής",
    "Prayer requests": "Αιτήματα προσευχής",
    "Calendar view": "Προβολή ημερολογίου",
    "Checkin management": "Διαχείριση εισόδου",
    "Event archive": "Αρχείο γεγονότων",
    "Font size": "Μέγεθος γραμματοσειράς",
    "Chart type": "Τύπος διαγράμματος",
    "Date format": "Μορφή ημερομηνίας",
    "Time format": "Μορφή ώρας",
    "Locale": "Τοπικές ρυθμίσεις",
    "Theme": "Θέμα",
    "Display all announcements": "Εμφάνιση όλων των ανακοινώσεων",
    "Users online": "Χρήστες σε σύνδεση",
    "Session count": "Κατακλείδωση περιόδου",
    "Server load": "Φόρτωση διακομιστή",
    "Database queries": "Ερωτήματα βάσης δεδομένων",
    "Memory usage": "Χρήση μνήμης",
    "Execution time": "Χρόνος εκτέλεσης",
    "Cache status": "Κατάσταση προσωρινής μνήμης",
    "Backup status": "Κατάσταση δημιουργίας αντιγράφων ασφαλείας",
    "Log files": "Αρχεία καταγραφής",
    "Integrity check": "Έλεγχος ακεραιότητας",
    "File verification": "Επαλήθευση αρχείου",
    "System diagnosis": "Διάγνωση συστήματος",
    "Performance report": "Αναφορά απόδοσης",
    "Signature verification": "Επαλήθευση υπογραφής",
    "Security audit": "Έλεγχος ασφαλείας",
    "Virus scan": "Σάρωση ιών",
    "Backup schedule": "Χρονοδιάγραμμα δημιουργίας αντιγράφων ασφαλείας",
    "Auto backup": "Αυτόματη δημιουργία αντιγράφων ασφαλείας",
    "Backup encryption": "Κρυπτογράφηση αντιγράφων ασφαλείας",
    "Backup location": "Θέση δημιουργίας αντιγράφων ασφαλείας",
    "Restore from backup": "Επαναφορά από αντίγραφο ασφαλείας",
    "Test backup": "Δοκιμαστικά αντίγραφα ασφαλείας",
    "Delete backup": "Διαγραφή αντιγράφου ασφαλείας",
    "Backup complete": "Δημιουργία αντιγράφου ασφαλείας ολοκληρωμένη",
    "Backup failed": "Η δημιουργία αντιγράφου ασφαλείας απέτυχε",
    "Restore complete": "Επαναφορά ολοκληρωμένη",
    "Restore failed": "Η επαναφορά απέτυχε",
    "Database optimized": "Η βάση δεδομένων βελτιστοποιήθηκε",
    "Database repair": "Επιδιόρθωση βάσης δεδομένων",
    "Database verify": "Επαλήθευση βάσης δεδομένων",
    "Rebuild search index": "Ανασυγκρότηση ευρετηρίου αναζήτησης",
    "Rebuild relationships": "Ανασυγκρότηση σχέσεων",
    "Export data": "Εξαγωγή δεδομένων",
    "Import data": "Εισαγωγή δεδομένων",
    "Data migration": "Μετανάστευση δεδομένων",
    "Field mapping": "Χαρτογραφία πεδίου",
    "Import preview": "Εισαγωγή προεπισκόπησης",
    "Import confirm": "Επιβεβαίωση εισαγωγής",
    "Import error": "Σφάλμα εισαγωγής",
    "Import warning": "Προειδοποίηση εισαγωγής",
    
    # Event management (95+ terms)
    "Event name": "Όνομα εκδήλωσης",
    "Event date": "Ημερομηνία εκδήλωσης",
    "Event time": "Ώρα εκδήλωσης",
    "Event location": "Τοποθεσία εκδήλωσης",
    "Event description": "Περιγραφή εκδήλωσης",
    "Event type": "Τύπος εκδήλωσης",
    "Event capacity": "Χωρητικότητα εκδήλωσης",
    "Event registration": "Εγγραφή εκδήλωσης",
    "Registration open": "Η εγγραφή είναι ανοιχτή",
    "Registration closed": "Η εγγραφή έκλεισε",
    "Register now": "Εγγραφείτε τώρα",
    "Unregister": "Ακύρωση εγγραφής",
    "Event start": "Έναρξη εκδήλωσης",
    "Event end": "Λήξη εκδήλωσης",
    "All day event": "Εκδήλωση όλης της ημέρας",
    "Recurring event": "Επαναλαμβανόμενο γεγονός",
    "Recurrence pattern": "Μοτίβο επανάληψης",
    "Weekly": "Εβδομαδιαίως",
    "Monthly": "Μηνιαίως",
    "Yearly": "Ετησίως",
    "Custom recurrence": "Προσαρμοσμένη επανάληψη",
    "Event series": "Σειρά εκδήλωσης",
    "Series end": "Τέλος σειράς",
    "Attendance": "Παρουσία",
    "Attendance tracking": "Παρακολούθηση παρουσίας",
    "Attendance report": "Αναφορά παρουσίας",
    "Check in": "Ημερολόγιο εισόδου",
    "Check out": "Έξοδος",
    "Attendance status": "Κατάσταση παρουσίας",
    "Attended": "Παρευρέθη",
    "Absent": "Απών",
    "Excused": "Δικαιολογημένος",
    "Pending": "Εν αναμονή",
    "Event checkin": "Ημερολόγιο εισόδου εκδήλωσης",
    "Checkin time": "Ώρα ημερολογίου εισόδου",
    "Checkin code": "Κωδικός ημερολογίου εισόδου",
    "QR code": "Κώδικας QR",
    "Barcode": "Γραμμωτός κώδικας",
    "Attendance list": "Κατάλογος παρουσίας",
    "Export attendance": "Εξαγωγή παρουσίας",
    "Print attendance": "Εκτύπωση παρουσίας",
    "Attendance summary": "Περίληψη παρουσίας",
    "Event calendar": "Ημερολόγιο γεγονότων",
    "Calendar view": "Προβολή ημερολογίου",
    "Agenda view": "Προβολή ημερησίας διάταξης",
    "Week view": "Προβολή εβδομάδας",
    "Month view": "Προβολή μήνα",
    "List view": "Προβολή λίστας",
    "Event search": "Αναζήτηση εκδήλωσης",
    "Filter events": "Φίλτρο γεγονότων",
    "Sort events": "Ταξινόμηση γεγονότων",
    "Event details": "Λεπτομέρειες εκδήλωσης",
    "View event": "Προβολή γεγονότος",
    "Edit event": "Επεξεργασία εκδήλωσης",
    "Delete event": "Διαγραφή εκδήλωσης",
    "Duplicate event": "Διπλότυπο γεγονός",
    "Copy event": "Αντιγραφή γεγονότος",
    "Move event": "Μετακίνηση εκδήλωσης",
    "Export event": "Εξαγωγή γεγονότος",
    "Print event": "Εκτύπωση γεγονότος",
    "Share event": "Κοινή χρήση εκδήλωσης",
    "Invite": "Πρόσκληση",
    "Invitation": "Πρόσκληση",
    "RSVP": "Επιβεβαίωση παρουσίας",
    "Remind participants": "Υπενθύμιση συμμετεχόντων",
    "Event reminder": "Υπενθύμιση γεγονότος",
    "Reminder email": "Email υπενθύμισης",
    "Reminder SMS": "SMS υπενθύμισης",
    "Reminder time": "Ώρα υπενθύμισης",
    
    # Person/Family management (120 terms)
    "Person name": "Όνομα προσώπου",
    "First name": "Όνομα",
    "Last name": "Επώνυμο",
    "Middle name": "Μεσαίο όνομα",
    "Suffix": "Κατάληγμα",
    "Gender": "Φύλο",
    "Male": "Αρσενικό",
    "Female": "Θηλυκό",
    "Other": "Άλλο",
    "Date of birth": "Ημερομηνία γέννησης",
    "Age": "Ηλικία",
    "Email address": "Διεύθυνση email",
    "Work email": "Email εργασίας",
    "Personal email": "Προσωπικό email",
    "Home phone": "Τηλέφωνο σπιτιού",
    "Mobile phone": "Κινητό τηλέφωνο",
    "Work phone": "Τηλέφωνο εργασίας",
    "Phone type": "Τύπος τηλεφώνου",
    "Street address": "Διεύθυνση δρόμου",
    "City": "Πόλη",
    "State": "Πολιτεία",
    "Zip code": "Ταχυδρομικός κώδικας",
    "Country": "Χώρα",
    "Address type": "Τύπος διεύθυνσης",
    "Residential": "Κατοικία",
    "Mailing": "Αλληλογραφία",
    "Billing": "Χρέωση",
    "Work address": "Διεύθυνση εργασίας",
    "Employer": "Εργοδότης",
    "Occupation": "Κατάσταση",
    "Work phone": "Τηλέφωνο εργασίας",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "LinkedIn": "LinkedIn",
    "Instagram": "Instagram",
    "YouTube": "YouTube",
    "Membership date": "Ημερομηνία ένταξης",
    "Member status": "Κατάσταση μέλους",
    "Active": "Ενεργό",
    "Inactive": "Αδρανές",
    "Deceased": "Κεκοιμημένος",
    "Family name": "Όνομα οικογένειας",
    "Family address": "Διεύθυνση οικογένειας",
    "Family head": "Αρχηγός οικογένειας",
    "Spouse": "Σύζυγος",
    "Children": "Παιδιά",
    "Relationship": "Σχέση",
    "Family role": "Ρόλος οικογένειας",
    "Father": "Πατέρας",
    "Mother": "Μητέρα",
    "Son": "Γιος",
    "Daughter": "Κόρη",
    "Brother": "Αδερφός",
    "Sister": "Αδελφή",
    "Grandfather": "Παππούς",
    "Grandmother": "Γιαγιά",
    "Nephew": "Ανιψιός",
    "Niece": "Ανιψία",
    "Uncle": "Θείος",
    "Aunt": "Θεία",
    "Cousin": "Ξάδελφος",
    "In-law": "Νόμιμος",
    "Stepchild": "Θετό παιδί",
    "Adoptive parent": "Θετικός γονέας",
    "Guardian": "Κηdemonomos",
    "Emergency contact": "Επαφή έκτακτης ανάγκης",
    "Person notes": "Σημειώσεις προσώπου",
    "Family notes": "Σημειώσεις οικογένειας",
    "All members": "Όλα τα μέλη",
    "Add person": "Προσθήκη προσώπου",
    "Edit person": "Επεξεργασία προσώπου",
    "Delete person": "Διαγραφή προσώπου",
    "Add family": "Προσθήκη οικογένειας",
    "Edit family": "Επεξεργασία οικογένειας",
    "Delete family": "Διαγραφή οικογένειας",
    "View person": "Προβολή προσώπου",
    "View family": "Προβολή οικογένειας",
    "People listing": "Κατάλογος ανθρώπων",
    "Family listing": "Κατάλογος οικογενειών",
    "Person search": "Αναζήτηση προσώπου",
    "Family search": "Αναζήτηση οικογένειας",
    "Filter people": "Φίλτρο ανθρώπων",
    "Sort people": "Ταξινόμηση ανθρώπων",
    "Export people": "Εξαγωγή ανθρώπων",
    "Import people": "Εισαγωγή ανθρώπων",
    "Photo": "Φωτογραφία",
    "Upload photo": "Μεταφόρτωση φωτογραφίας",
    "Delete photo": "Διαγραφή φωτογραφίας",
    "Photo settings": "Ρυθμίσεις φωτογραφίας",
    "Photo privacy": "Απόρρητο φωτογραφιών",
}

# Load the existing files
af_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/af.json'
el_file = '/Users/gdawoud/Development/ChurchCRM/CRM/locale/missing-terms/el.json'

# Update Afrikaans
with open(af_file, 'r', encoding='utf-8') as f:
    af_data = json.load(f)

updated_af = 0
for key, value in afrikaans.items():
    if key in af_data and af_data[key] == "":
        af_data[key] = value
        updated_af += 1

with open(af_file, 'w', encoding='utf-8') as f:
    json.dump(af_data, f, ensure_ascii=False, indent=2)

# Update Greek
with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

updated_el = 0
for key, value in greek.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = value
        updated_el += 1

with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

print(f"Updated Afrikaans: {updated_af} terms")
print(f"Updated Greek: {updated_el} terms")
