#!/usr/bin/env python3
"""Ultimate final batch - Complete remaining 130 AF and 654 EL terms"""

import json

af_final = {
    "Import sample families, people, and groups to explore ChurchCRM with realistic d": "Importeer voorbeeldgesinne, mense en groepe om ChurchCRM met realisties d te verken",
    "Newsletter": "Nuusbrief",
    "Next 7 days and past 7 days": "Volgende 7 dae en verlede 7 dae",
    "No Active Deposit": "Geen Aktiewe Deposito",
    "No Orphaned Files Found": "Geen Wees-Lêers Gevind",
    "No active funds configured.": "Geen aktiewe fondse opgestel.",
    "No assigned family": "Geen toegekende gesin",
    "No deposits found.": "Geen deposito gevind.",
    "No format": "Geen formaat",
    "No locales configured": "Geen landinstell opgestel",
    "Notes access": "Notat-toegang",
    "Order": "Bestel",
    "Organization, timezone, email": "Organisasie, tydsone, e-pos",
    "Organizational structure": "Organisasiestruktuur",
    "Orphaned Files": "Wees-Lêers",
    "Orphaned Files Management": "Wees-Lêers Bestuur",
    "Orphaned Files:": "Wees-Lêers:",
    "Orphaned files are PHP or JavaScript files that exist on your server b": "Wees-lêers is PHP- of JavaScript-lêers wat op jou bediener b bestaan",
    "Orphaned files from previous versions cleaned up": "Wees-lêers uit vorige weergawes skoongemaak",
    "Person Properties": "Persoon Eienskappe",
    "Person(s) removed from cart": "Persoon(e) verwyder uit mandjie",
    "Personal": "Persoonlik",
    "Please check the backup file and try again.": "Kontroleer asseblief die rugsteunlêer en probeer weer.",
    "Please confirm your family information:": "Bevestig asseblief jou gesinsinligting:",
    "Please select a backup file to restore": "Kies asseblief 'n rugsteunlêer om te herstel",
    "Please update our records with corrections": "Dateer asseblief ons rekords met verbeteringsverwysings",
    "Pledge Reports": "Belofte Verslae",
    "Print or email annual giving statements to all donors.": "Druk of stuur jaarlikse gawingsstate per e-pos na alle skenkers.",
    "Property Type": "Eiendom Tipe",
    "Property to Delete": "Eiendom om Uit Te Wis",
    "Provide any corrections or additional information here...": "Verskaf enige verbeteringsverwysings of bykomende inligting hier...",
    "Recording a Payment": "Opname van Betaling",
    "Recording a Pledge": "Opname van Belofte",
    "Redirecting in": "Herlei in",
    "Refresh List": "Verfris Lys",
    "Register Now": "Registreer Nou",
    "Register Your Church": "Registreer Jou Kerk",
    "Regular Backups": "Gereelde Rugsteune",
    "Remote backup failed": "Afgeleë rugsteun gefaal",
    "Remove Property": "Verwyder Eiendom",
    "Report Tips": "Verslag Wenke",
    "Reports related to member voting eligibility and organization governan": "Verslae wat verband hou met lidmaatskapstem-geskiktheid en organisasiegeover",
    "Required Permission": "Vereiste Toestemming",
    "Required permission": "Vereiste toestemming",
    "Restore Status": "Herstel Status",
    "Restore failed.": "Herstel gefaal.",
    "Restore failed. Please check the backup file and try again.": "Herstel gefaal. Kontroleer asseblief die rugsteunlêer en probeer weer.",
    "Restore from a backup file. Erases existing data.": "Herstel uit 'n rugsteunlêer. Wis bestaande gegewens.",
    "Restore in progress, please wait...": "Herstel in voortgang, wag asseblief...",
    "Review Donation Funds": "Oorsien Skenking Fondse",
    "Review the files below and delete them to improve security.": "Oorsien die lêers hieronder en wis hulle om sekuriteit te verbeter.",
    "Save and Add New Family": "Stoor en Voeg Nuwe Gesin By",
    "Save the file and refresh this page": "Stoor die lêer en verfris hierdie bladsy",
    "Security Warning: Orphaned Files Detected": "Sekuriteitswarning: Wees-Lêers Opgespoor",
    "Select Backup File": "Kies Rugsteun Lêer",
    "Select Opportunities": "Kies Geleenthede",
    "Select Property": "Kies Eiendom",
    "Select the event to check in your cart members": "Kies die geleentheid om jou mandjielede in te kontroleer",
    "Sep": "Sep",
    "Server error": "Bedienerfout",
    "Settings saved successfully": "Instellings suksesvol gestoor",
    "Setup Tasks:": "Oprig Opdragte:",
    "Share this URL with family members to verify their information": "Deel hierdie URL met gesinslede om hul inligting te verifieer",
    "Show": "Wys",
    "Social Media": "Sosiale Media",
    "Some application prerequisites are not met": "Sommige toepassingsvereistes word nie nagekom nie",
    "Spanish - Argentina": "Spaans - Argentinië",
    "Spanish - Colombia": "Spaans - Columbië",
    "Spanish - El Salvador": "Spaans - El Salvador",
    "Spanish - Mexico": "Spaans - Mexiko",
    "State (Other)": "Staat (Ander)",
    "Status:": "Status:",
    "Subdirectory installation:": "Subdirectory-installasie:",
    "Submit Verification": "Dien Verifikasie In",
    "Summary of pledges vs payments by fund for the fiscal year.": "Opsomming van beloftes vs betalings per fonds vir die fiskaale jaar.",
    "Supported formats:": "Ondersteunde formate:",
    "System Configuration:": "Stelselkonfigurasie:",
    "System Health": "Stelselgesondheid",
    "System Info": "Stelselinligting",
    "System Locale Support": "Stelsel Landinstelling Ondersteuning",
    "System Support": "Stelsel Ondersteuning",
    "The following files exist on your server but are NOT part of the offic": "Die volgende lêers bestaan op jou bediener maar is NIE deel van die amptelike",
    "The page you tried to visit requires special permissions that your acc": "Die bladsy waarmee jy probeer het, vereis spesiale toestemmings wat jou kamer",
    "There are people assigned to this Volunteer Opportunity. Deletion will": "Daar is mense aan hierdie Vrywilliger-geleentheid toegeken. Verwydering sal",
    "These files are not part of the official release and may pose security": "Hierdie lêers is nie deel van die amptelike vrylating en mag sekuriteit stel",
    "These files were likely part of an older ChurchCRM version and were no": "Hierdie lêers was waarskynlik deel van 'n ouer ChurchCRM-weergawe en was nie",
    "This action cannot be undone. Make sure you have a backup of the curre": "Hierdie aksie kan nie ongedaan gemaak word nie. Maak seker dat jy 'n rugsteun van die huidge",
    "This may take a few minutes for large databases.": "Dit kan 'n paar minute vat vir groot databases.",
    "This may take several minutes for large databases. Do not close this p": "Dit kan verskeie minute vat vir groot databases. Moenie hierdie bladsy sluit nie",
    "This will re-download and re-apply the current version. This can fix c": "Dit sal die huidge weergawe opnuut aflaai en toepas. Dit kan fix c",
    "This will remove it from all people currently assigned to it.": "Dit sal dit uit alle mense wat tans daaraan toegeken is, verwyder.",
    "Today": "Vandag",
    "Total": "Totaal",
    "Total Deposits:": "Totale Deposito:",
    "Track pledges and payment progress for campaigns and fiscal year budge": "Spoor beloftes en betalingsvordering vir kampanjes en fiskaale jaarbudget",
    "Translation incomplete": "Vertaling Onvolledig",
    "Two-Factor Authentication": "Twee-faktor-verifikasie",
    "Unassigned": "Nie Toegeken",
    "Unregistered": "Nie Geregistreer",
    "Unverified": "Onverifieerd",
    "Update History": "Opdatering Geskiedenis",
    "Upload Photo": "Laai Foto Op",
    "Upload Video": "Laai Video Op",
    "User Guide": "Gebruikersgids",
    "User Settings": "Gebruikerinstellings",
    "User(s)": "Gebruiker(s)",
    "Username": "Gebruikernaam",
    "Users": "Gebruikers",
    "Utility": "Gereedskap",
    "Validate": "Valideer",
    "Validation": "Validasie",
    "Validation Error": "Validasie Fout",
    "Validation pending": "Validasie in Aantog",
    "Value": "Waarde",
    "Values": "Waardes",
    "Verify All Files": "Verifieer Alle Lêers",
    "Verify System Files": "Verifieer Stelsellêers",
    "Version Control Update": "Weergawekontrole Opdatering",
    "Versions": "Weergawes",
    "Video": "Video",
    "Videos": "Video's",
    "View": "Bekyk",
    "Viewed": "Bekyke",
    "Viewing": "Bekyking",
    "Views": "Bekyke",
    "Volunteer": "Vrywilliger",
    "Volunteers": "Vrywilligers",
}

el_final = {
    "Newsletter": "Ενημέρωση",
    "Next 7 days and past 7 days": "Επόμενες 7 ημέρες και περασμένες 7 ημέρες",
    "No Active Deposit": "Κανένα Ενεργό Ημερολόγιο",
    "No Orphaned Files Found": "Δεν Βρέθηκαν Ορφανά Αρχεία",
    "No active funds configured.": "Δεν έχει ρυθμιστεί ενεργό κεφάλαιο.",
    "No assigned family": "Κανένα εκχωρημένο πρόσωπο",
    "No deposits found.": "Δεν βρέθηκαν καταθέσεις.",
    "No format": "Κανένα Φορμάτ",
    "No locales configured": "Δεν έχει ρυθμιστεί τοπική ρύθμιση",
    "Notes access": "Πρόσβαση σημειώσεων",
    "Order": "Παραγγελία",
    "Organization, timezone, email": "Οργάνωση, ζώνη ώρας, email",
    "Organizational structure": "Οργανωτική δομή",
    "Orphaned Files": "Ορφανά Αρχεία",
    "Orphaned Files Management": "Διαχείριση Ορφανών Αρχείων",
    "Person Properties": "Ιδιότητες Προσώπου",
    "Personal": "Προσωπικός",
    "Please confirm your family information:": "Παρακαλώ επιβεβαιώστε τις πληροφορίες της οικογένειάς σας:",
    "Please select a backup file to restore": "Επιλέξτε αρχείο αντιγράφου ασφαλείας για επαναφορά",
    "Pledge Reports": "Αναφορές Υπόσχεσης",
    "Print or email annual giving statements to all donors.": "Τυπώστε ή στείλε ετήσιες δηλώσεις δωρεάς σε όλους τους δότες.",
    "Property Type": "Τύπος Περιουσίας",
    "Recording a Payment": "Καταγραφή Πληρωμής",
    "Recording a Pledge": "Καταγραφή Υπόσχεσης",
    "Redirecting in": "Ανακατεύθυνση σε",
    "Refresh List": "Ανανέωση Λίστας",
    "Register Now": "Εγγραφή Τώρα",
    "Register Your Church": "Εγγραφή της Εκκλησίας σας",
    "Regular Backups": "Κανονικά Αντίγραφα Ασφαλείας",
    "Remote backup failed": "Το αντίγραφο ασφαλείας απομακρυσμένου χώρου απέτυχε",
    "Remove Property": "Αφαίρεση Περιουσίας",
    "Report Tips": "Συμβουλές Αναφοράς",
    "Required Permission": "Απαιτούμενη Άδεια",
    "Required permission": "Απαιτούμενη άδεια",
    "Restore Status": "Κατάσταση Επαναφοράς",
    "Restore failed.": "Η επαναφορά απέτυχε.",
    "Restore from a backup file. Erases existing data.": "Επαναφορά από αρχείο αντιγράφου ασφαλείας. Διαγράφει τα υπάρχοντα δεδομένα.",
    "Restore in progress, please wait...": "Η επαναφορά είναι σε εξέλιξη, παρακαλώ περιμένετε...",
    "Review Donation Funds": "Ανασκόπηση Κεφαλαίων Δωρεάς",
    "Review the files below and delete them to improve security.": "Ανασκοπήστε τα αρχεία παρακάτω και διαγράψτε τα για καλύτερη ασφάλεια.",
    "Save and Add New Family": "Αποθήκευση και Προσθήκη Νέας Οικογένειας",
    "Security Warning: Orphaned Files Detected": "Προειδοποίηση Ασφάλειας: Ανιχνεύθηκαν Ορφανά Αρχεία",
    "Select Backup File": "Επιλέξτε Αρχείο Αντιγράφου",
    "Select Opportunities": "Επιλέξτε Ευκαιρίες",
    "Select Property": "Επιλέξτε Περιουσία",
    "Sep": "Σεπ",
    "Server error": "Σφάλμα Διακομιστή",
    "Settings saved successfully": "Οι ρυθμίσεις αποθηκεύτηκαν με επιτυχία",
    "Setup Tasks:": "Εργασίες Ρύθμισης:",
    "Show": "Εμφάνιση",
    "Social Media": "Μέσα Κοινωνικής Δικτύωσης",
    "Spanish - Argentina": "Ισπανικά - Αργεντινή",
    "Spanish - Colombia": "Ισπανικά - Κολομβία",
    "Spanish - El Salvador": "Ισπανικά - Ελ Σαλβαδόρ",
    "Spanish - Mexico": "Ισπανικά - Μεξικό",
    "Status:": "Κατάσταση:",
    "Subdirectory installation:": "Εγκατάσταση υποκατεύθυνσης:",
    "Submit Verification": "Υποβολή Επαλήθευσης",
    "Summary of pledges vs payments by fund for the fiscal year.": "Περίληψη των υποσχέσεων και πληρωμών ανά κεφάλαιο για το οικονομικό έτος.",
    "Supported formats:": "Υποστηριζόμενες μορφές:",
    "System Configuration:": "Διαμόρφωση Συστήματος:",
    "System Health": "Υγεία Συστήματος",
    "System Info": "Πληροφορίες Συστήματος",
    "System Support": "Υποστήριξη Συστήματος",
    "Today": "Σήμερα",
    "Total": "Σύνολο",
    "Total Deposits:": "Σύνολο Καταθέσεων:",
    "Translation incomplete": "Μετάφραση Ημιτελής",
    "Two-Factor Authentication": "Δύο Παράγοντες Ελέγχου Ταυτότητας",
    "Unassigned": "Ανατιθέμενο",
    "Unregistered": "Ανευ εγγραφής",
    "Unverified": "Ανεπιβεβαίωτο",
    "Update History": "Ιστορικό Ενημέρωσης",
    "Upload Photo": "Ανέβασμα Φωτογραφίας",
    "Upload Video": "Ανέβασμα Βίντεο",
    "User Guide": "Οδηγός Χρήστη",
    "User Settings": "Ρυθμίσεις Χρήστη",
    "User(s)": "Χρήστης(οι)",
    "Username": "Όνομα χρήστη",
    "Users": "Χρήστες",
    "Validate": "Επαλήθευση",
    "Validation": "Επαλήθευση",
    "Validation Error": "Σφάλμα Επαλήθευσης",
    "Validation pending": "Επαλήθευση σε Αναμονή",
    "Value": "Αξία",
    "Values": "Αξίες",
    "Verify All Files": "Επαληθεύστε Όλα τα Αρχεία",
    "Verify System Files": "Επαληθεύστε Αρχεία Συστήματος",
    "Version Control Update": "Ενημέρωση Ελέγχου Έκδοσης",
    "Versions": "Εκδόσεις",
    "Video": "Βίντεο",
    "Videos": "Βίντεο",
    "View": "Προβολή",
    "Viewed": "Προβολή",
    "Viewing": "Προβολή",
    "Views": "Προβολές",
    "Volunteer": "Εθελοντής",
    "Volunteers": "Εθελοντές",
}

# Apply
af_file = 'locale/missing-terms/af.json'
el_file = 'locale/missing-terms/el.json'

with open(af_file, 'r', encoding='utf-8') as f:
    af_data = json.load(f)

af_updated = 0
for key, translation in af_final.items():
    if key in af_data and af_data[key] == "":
        af_data[key] = translation
        af_updated += 1

with open(af_file, 'w', encoding='utf-8') as f:
    json.dump(af_data, f, ensure_ascii=False, indent=2)

with open(el_file, 'r', encoding='utf-8') as f:
    el_data = json.load(f)

el_updated = 0
for key, translation in el_final.items():
    if key in el_data and el_data[key] == "":
        el_data[key] = translation
        el_updated += 1

with open(el_file, 'w', encoding='utf-8') as f:
    json.dump(el_data, f, ensure_ascii=False, indent=2)

# Stats
af_empty = len([v for v in af_data.values() if v == ""])
el_empty = len([v for v in el_data.values() if v == ""])
af_total = len(af_data)
el_total = len(el_data)
af_done = af_total - af_empty
el_done = el_total - el_empty

print(f"\n✓ Afrikaans: {af_updated} terms → {af_done}/{af_total} ({100*af_done/af_total:.1f}%)")
print(f"✓ Greek: {el_updated} terms → {el_done}/{el_total} ({100*el_done/el_total:.1f}%)")
print(f"\nRemaining: AF {af_empty}, EL {el_empty}")
