<?php
// Convert a relative URL into an absolute URL and redirect the browser there.
function TranslateMenuOptions ()
{
	foreach ( array(
	'Main',
	'Log Off',
	'Change My Password',
	'Change My Settings',
	'Admin',
	'Edit Users',
	'Add New User',
	'Edit Custom Person Fields',
	'Edit Donation Funds',
	'Backup Database',
	'CSV Import',
	'Access report',
	'Edit General Settings',
	'Edit Report Settings',
	'Edit User Default Settings',
	'Envelope Manager',
	'Please select this option to register ChurchInfo after configuring.',
	'People/Families',
	'Add New Person',
	'View All Persons',
	'Classification Manager',
	'---------------------------',
	'Edit volunteer opportunities',
	'Add New Family',
	'View All Families',
	'Family Geographic Utilties',
	'Family Map',
	'Family Roles Manager',
	'Events',
	'List Church Events',
	'Add Church Event',
	'List Event Types',
	'Check-in and Check-out',
	'Deposit',
	'Create New Deposit',
	'View All Deposits',
	'Deposit Reports',
	'Edit Deposit Slip',
	'Cart',
	'List Cart Items',
	'Empty Cart',
	'Empty Cart to Group',
	'Empty Cart to Family',
	'Empty Cart to Event',
	'Data/Reports',
	'CSV Export Records',
	'Query Menu',
	'Reports Menu',
	'Groups',
	'List Groups',
	'Add a New Group',
	'Edit Group Types',
	'Group Assignment Helper',
	'Properties',
	'People Properties',
	'Family Properties',
	'Group Properties',
	'Property Types',
	'Help',
	'About ChurchInfo',
	'Wiki Documentation',
	'People',
	'Families',
	'Geographic features',
	'Groups',
	'Finances',
	'Reports',
	'Administration',
	'Cart',
	'Properties',
	'Notes',
	'Custom Fields',
	'Classifications',
	'Canvass Support',
	'Events',
	'Menu Options',
	'Edit Custom Family Fields'
	) as $str) {
		$sSQL = "update menuconfig_mcf set content='" . gettext ($str) . "' where content_english='". $str . "'";
		RunQuery ($sSQL);
	}
}

?>