<?php

$serviceContainer = \Propel\Runtime\Propel::getServiceContainer();
$serviceContainer->initDatabaseMaps(array(
  'default' =>
  array(
    0 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\CalendarEventTableMap',
    1 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\CalendarTableMap',
    2 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\ConfigTableMap',
    3 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DepositTableMap',
    4 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DonatedItemTableMap',
    5 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DonationFundTableMap',
    6 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EgiveTableMap',
    7 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EmailMessagePendingTableMap',
    8 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EmailRecipientPendingTableMap',
    9 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventAttendTableMap',
    10 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventAudienceTableMap',
    11 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventCountNameTableMap',
    12 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventCountsTableMap',
    13 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventTableMap',
    14 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventTypeTableMap',
    15 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyCustomMasterTableMap',
    16 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyCustomTableMap',
    17 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyTableMap',
    18 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FundRaiserTableMap',
    19 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\GroupPropMasterTableMap',
    20 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\GroupTableMap',
    21 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\KioskAssignmentTableMap',
    22 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\KioskDeviceTableMap',
    23 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\ListOptionTableMap',
    24 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\LocationTableMap',
    25 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\MenuLinkTableMap',
    26 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\NoteTableMap',
    27 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\Person2group2roleP2g2rTableMap',
    28 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonCustomMasterTableMap',
    29 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonCustomTableMap',
    30 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonTableMap',
    31 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonVolunteerOpportunityTableMap',
    32 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PledgeTableMap',
    33 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PredefinedReportsTableMap',
    34 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PropertyTableMap',
    35 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PropertyTypeTableMap',
    36 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\QueryParameterOptionsTableMap',
    37 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\QueryParametersTableMap',
    38 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\RecordPropertyTableMap',
    39 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\TokenTableMap',
    40 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserConfigTableMap',
    41 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserSettingTableMap',
    42 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserTableMap',
    43 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\VersionTableMap',
    44 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\VolunteerOpportunityTableMap',
    45 => '\\ChurchCRM\\model\\ChurchCRM\\Map\\WhyCameTableMap',
  ),
));
