# syntax = devthefuture/dockerfile-x
FROM  php:8-apache

INCLUDE Dockerfile.churchcrm-apache-php8-test-debian

RUN apt-get update && \
    apt-get install -y \
        make \
        git \
        python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    rm composer-setup.php

RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh -o /opt/node-install.sh && \
    chmod a+x /opt/node-install.sh && \
    /opt/node-install.sh && \
    rm /opt/node-install.sh

RUN /bin/bash -c "source /root/.nvm/nvm.sh && nvm install --lts && npm install -g node-gyp"
