services:
  database:
    profiles: [test, ci]
    image: mariadb:10.11
    ports:
      - ${DOCKER_BIND_ADDRESS:-127.0.0.1}:${DATABASE_PORT:-3306}:3306
    env_file:
      - .env
    volumes:
      - ../cypress/data:/docker-entrypoint-initdb.d:ro
    hostname: crm-database
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10

  mailserver:
    profiles: [test]
    image: axllent/mailpit:latest
    ports:
      - ${DOCKER_BIND_ADDRESS:-127.0.0.1}:${MAILSERVER_PORT:-1025}:1025
      - ${DOCKER_BIND_ADDRESS:-127.0.0.1}:${MAILSERVER_GUI_PORT:-8025}:8025
    hostname: crm-mailserver

  webserver:
    profiles: [test, ci]
    build:
      context: .
      dockerfile: Dockerfile.churchcrm-apache-php8
      target: test
    image: churchcrm/crm:php8-debian
    ports:
      - ${DOCKER_BIND_ADDRESS:-127.0.0.1}:${WEBSERVER_PORT:-80}:80
    volumes:
      - ../src:/var/www/html
      - ..:/home/ChurchCRM
      - ../cypress/data/images/people:/var/www/html/Images/Person
      - ../cypress/data/images/family:/var/www/html/Images/Family
    hostname: crm-webserver
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
