FROM  php:8-apache

EXPOSE 80

RUN apt-get update && \
    apt-get install -y \
        libxml2-dev \
        gettext \
        locales \
        locales-all \
        libpng-dev \
        libzip-dev \
        libfreetype6-dev \
        libmcrypt-dev \
        libjpeg-dev \
        git

RUN docker-php-ext-install -j$(nproc) xml exif pdo_mysql gettext iconv mysqli zip
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

RUN docker-php-ext-install -j$(nproc) gd && pecl install xdebug && docker-php-ext-enable xdebug

COPY ./apache/default.conf /etc/apache2/apache2.conf
RUN a2enmod rewrite

# Configure PHP
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" && \
    sed -i 's/^upload_max_filesize.*$/upload_max_filesize = 2G/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/^post_max_size.*$/post_max_size = 2G/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/^memory_limit.*$/memory_limit = 2G/g' $PHP_INI_DIR/php.ini && \
    sed -i 's/^max_execution_time.*$/max_execution_time = 120/g' $PHP_INI_DIR/php.ini

RUN apt-get update && \
    apt-get install -y \
        make \
        python3

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    rm composer-setup.php

RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh -o /opt/node-install.sh && \
    chmod a+x /opt/node-install.sh && \
    /opt/node-install.sh && \
    rm /opt/node-install.sh

RUN /bin/bash -c "source /root/.nvm/nvm.sh && nvm install --lts && npm install -g node-gyp"
