<?php

require '../Include/Config.php';
require '../Include/Functions.php';

//Security
if (!isset($_SESSION['iUserID'])) {
  Redirect("Login.php");
  exit;
}


// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';

// Instantiate the app
$settings = require __DIR__ . '/settings.php';
$app = new \Slim\App();

// Set up dependencies
require __DIR__ . '/dependencies.php';

// system routes
require __DIR__ . '/routes/data.php';
require __DIR__ . '/routes/database.php';

// people routes
require __DIR__ . '/routes/search.php';
require __DIR__ . '/routes/persons.php';
require __DIR__ . '/routes/families.php';

// finance routes
require __DIR__ . '/routes/deposits.php';
require __DIR__ . '/routes/payments.php';

// Run app
$app->run();

