<?php
require '../Include/Config.php';

// This file is generated by Composer
require_once dirname(__FILE__).'/../vendor/autoload.php';

use Slim\Container;
use Slim\App;
use Slim\Http\Request;
use Slim\Http\Response;
use Slim\Views\PhpRenderer;
use ChurchCRM\SessionUser;
use ChurchCRM\dto\SystemURLs;
use ChurchCRM\Slim\Middleware\VersionMiddleware;

// Instantiate the app
$settings = require __DIR__.'/../Include/slim/settings.php';

$container = new Container;

// Add middleware to the application
$app = new App($container);

$app->add(new VersionMiddleware());

// Set up
require __DIR__.'/../Include/slim/error-handler.php';



$app->get('/begin', 'beginSession');


function beginSession(Request $request, Response $response, array $args)
{

    $renderer = new PhpRenderer('templates/');
    $curUser = SessionUser::getUser();

    $pageArgs = [
        'sRootPath' => SystemURLs::getRootPath(),
        'user' => $curUser
    ];
    

    # Defermine if approprirate to pre-fill the username field
    if (isset($_GET['username'])) {
        $pageArgs['prefilledUserName'] = $_GET['username'];
    }
    elseif (isset($_SESSION['user'])) {
        $user = $_SESSION['user'];
        $pageArgs['prefilledUserName'] = $user->getUserName();
    } elseif (isset($_SESSION['username'])) {
        $pageArgs['prefilledUserName'] == $_SESSION['username'];
    }

    return $renderer->render($response, 'begin-session.php', $pageArgs);
}

// Run app
$app->run();
