<?php



require '../Include/Config.php';

// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';
require './CRMFamilyFilesFolder.php';

use ChurchCRM\FamilyQuery;
use Sabre\DAV;

class CRMFamiliesListFolder extends DAV\Collection
{
    private $myPath;

    public function __construct($myPath)
    {
        $this->myPath = $myPath;
    }

    public function getChildren()
    {
        $children = array();
        $families = FamilyQuery::create() ->find();
        foreach ($families as $family) {
            $children[] = new CRMFamilyFilesFolder($family->getFamilyString());
        }
        return $children;
    }

    public function getChild($name)
    {
        $path = $this->myPath . '/' . $name;

        // We have to throw a NotFound exception if the file didn't exist
        if (!file_exists($path)) {
            throw new DAV\Exception\NotFound('The file with name: ' . $name . ' could not be found');
        }

        // Some added security
        if ($name[0]=='.') {
            throw new DAV\Exception\NotFound('Access denied');
        }

        if (is_dir($path)) {
            return new MyDirectory($path);
        } else {
            return new MyFile($path);
        }
    }

    public function childExists($name)
    {
        return file_exists($this->myPath . '/' . $name);
    }

    public function getName()
    {
        return basename($this->myPath);
    }
}
