<?php

require '../Include/Config.php';

// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';

use ChurchCRM\File;
use ChurchCRM\FileQuery;
use ChurchCRM\dto\SystemConfig;

$files = new FileQuery();
$file = $files->find();

if ($files != null) {
    echo "found file.  Contents:<br>";
    foreach($files as $file){
        echo "File: " . $file->getFileName()."  Created: ". $file->getCreated()->format(SystemConfig::getValue("sDateTimeFormat")) ." Modified: " .$file->getModified()->format(SystemConfig::getValue("sDateTimeFormat")) ."<br>Content:<br>";
        try {
            echo $file->getContent();
        }
        catch(\Exception $e) {
            echo $e;
        }
        echo "<br><br>";
    }
}
else {
    echo "couldn't find file";
}