-- ChurchCRM 7.7.1 — Classification filter on every people query in Data & Reports (#9914)
--
-- Every predefined query that returns people gets a multi-select Classification
-- parameter (alias ~percls~). The option list is read live from list_lst
-- (lst_ID = 1) plus an "Unassigned" row for per_cls_ID = 0, so a church that
-- renames or adds classifications in Admin -> Classification Manager sees them
-- here. Leaving the control empty means "all classifications" (QueryView.php
-- substitutes every option value for an optional multi-select left blank).
--
-- The Birthdays parameter (qrp_ID 33) used to be a static qrp_Type 1 list of
-- five hardcoded names in queryparameteroptions_qpo; it is converted to the
-- same live multi-select and its static option rows are removed.
--
-- Idempotent: UPDATEs are repeatable, INSERTs use INSERT IGNORE on the primary
-- key and only insert when the parent query row exists (no orphans).

UPDATE `query_qry` SET `qry_SQL` = 'SELECT \r\nper_ID as AddToCart, \r\nCONCAT(per_FirstName,\' \',per_LastName) AS Name, \r\nCONCAT(r2p_Value,\' \') AS Value\r\nFROM person_per,record2property_r2p\r\nWHERE per_ID = r2p_record_ID\r\nAND r2p_pro_ID = ~PropertyID~\r\nAND per_cls_ID IN (~percls~)\r\nORDER BY per_LastName', `qry_Description` = 'Returns person records which are assigned the given property.' WHERE `qry_ID` = 9;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT per_ID as AddToCart, per_BirthDay as Day, CONCAT(per_FirstName,\' \',per_LastName) AS Name FROM person_per WHERE per_cls_ID IN (~percls~) AND per_BirthMonth=~birthmonth~ ORDER BY per_BirthDay', `qry_Description` = 'People with birthdays in a particular month' WHERE `qry_ID` = 18;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT per_ID as AddToCart, DAYOFMONTH(per_MembershipDate) as Day, per_MembershipDate AS DATE, CONCAT(per_FirstName,\' \',per_LastName) AS Name FROM person_per WHERE per_cls_ID IN (~percls~) AND MONTH(per_MembershipDate)=~membermonth~ ORDER BY per_MembershipDate', `qry_Description` = 'People who joined in a particular month' WHERE `qry_ID` = 22;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT per_ID as AddToCart, CONCAT(\'<a href=/people/view/\',per_ID,\'>\',per_FirstName,\' \',per_LastName,\'</a>\') AS Name FROM person_per LEFT JOIN person2volunteeropp_p2vo ON per_id = p2vo_per_ID WHERE p2vo_vol_ID = ~volopp~ AND per_cls_ID IN (~percls~) ORDER BY per_LastName', `qry_Description` = 'Find volunteers for a particular opportunity' WHERE `qry_ID` = 25;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT per_ID as AddToCart, CONCAT(per_FirstName,\' \',per_LastName) AS Name FROM person_per WHERE DATE_SUB(NOW(),INTERVAL ~friendmonths~ MONTH)<per_FriendDate AND per_cls_ID IN (~percls~) ORDER BY per_MembershipDate', `qry_Description` = 'Friends who signed up in previous months' WHERE `qry_ID` = 26;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT a.per_ID as AddToCart, CONCAT(\'<a href=/people/view/\',a.per_ID,\'>\',a.per_FirstName,\' \',a.per_LastName,\'</a>\') AS Name FROM person_per AS a LEFT JOIN person2volunteeropp_p2vo p2v1 ON (a.per_id = p2v1.p2vo_per_ID AND p2v1.p2vo_vol_ID = ~volopp1~) LEFT JOIN person2volunteeropp_p2vo p2v2 ON (a.per_id = p2v2.p2vo_per_ID AND p2v2.p2vo_vol_ID = ~volopp2~) WHERE p2v1.p2vo_per_ID=p2v2.p2vo_per_ID AND a.per_cls_ID IN (~percls~) ORDER BY per_LastName', `qry_Description` = 'Find volunteers for who match two specific opportunity codes' WHERE `qry_ID` = 100;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT per_ID as AddToCart, CONCAT(\'<a href=/people/view/\',per_ID,\'>\',per_FirstName,\',\',per_LastName,\'</a>\') AS Name, per_LastName AS Lastname FROM person_per LEFT OUTER JOIN (SELECT event_attend.attend_id, event_attend.person_id FROM event_attend WHERE event_attend.event_id IN (~event~)) a ON person_per.per_ID = a.person_id WHERE a.attend_id is NULL AND person_per.per_cls_ID IN (~percls~) ORDER BY person_per.per_LastName, person_per.per_FirstName', `qry_Description` = 'Find people who didn\'t attend an event' WHERE `qry_ID` = 201;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT per_ID as AddToCart, DAYOFMONTH(fam_WeddingDate) as Day, DATE_FORMAT(fam_WeddingDate, \'%Y-%m-%d\') as Date, CONCAT(per_FirstName,\' \',per_LastName) AS Name FROM person_per JOIN family_fam ON per_fam_ID=fam_ID WHERE per_fmr_ID IN (1,2) AND fam_WeddingDate IS NOT NULL AND MONTH(fam_WeddingDate)=~weddingmonth~ AND per_cls_ID IN (~percls~) ORDER BY DAYOFMONTH(fam_WeddingDate), per_LastName', `qry_Description` = 'People with wedding anniversaries in a particular month' WHERE `qry_ID` = 300;
UPDATE `query_qry` SET `qry_SQL` = 'SELECT per_ID as AddToCart, \'Birthday\' as Type, per_BirthDay as Day, CONCAT(per_FirstName,\' \',per_LastName) AS Name FROM person_per WHERE per_BirthMonth=~month~ AND per_BirthDay>0 AND per_cls_ID IN (~percls~) UNION ALL SELECT per_ID as AddToCart, \'Anniversary\' as Type, DAYOFMONTH(fam_WeddingDate) as Day, CONCAT(per_FirstName,\' \',per_LastName) AS Name FROM person_per JOIN family_fam ON per_fam_ID=fam_ID WHERE per_fmr_ID IN (1,2) AND fam_WeddingDate IS NOT NULL AND MONTH(fam_WeddingDate)=~month~ AND per_cls_ID IN (~percls~) ORDER BY Day', `qry_Description` = 'People with birthdays or wedding anniversaries in a particular month' WHERE `qry_ID` = 301;

-- Birthdays (qry 18): convert the static Classification list to the live multi-select.
UPDATE `queryparameters_qrp` SET
  `qrp_Type` = 3,
  `qrp_OptionSQL` = 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value',
  `qrp_Description` = 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.',
  `qrp_Default` = '',
  `qrp_Required` = 0,
  `qrp_Validation` = '',
  `qrp_NumericMax` = 0, `qrp_NumericMin` = 0, `qrp_AlphaMinLength` = 0, `qrp_AlphaMaxLength` = 0
WHERE `qrp_ID` = 33 AND `qrp_qry_ID` = 18 AND `qrp_Alias` = 'percls';

DELETE FROM `queryparameteroptions_qpo` WHERE `qpo_qrp_ID` = 33;

-- Classification parameter for every other people query.
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 302, 9, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 9;
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 303, 22, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 22;
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 304, 25, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 25;
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 305, 26, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 26;
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 306, 100, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 100;
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 307, 201, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 201;
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 308, 300, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 300;
INSERT IGNORE INTO `queryparameters_qrp` (`qrp_ID`, `qrp_qry_ID`, `qrp_Type`, `qrp_OptionSQL`, `qrp_Name`, `qrp_Description`, `qrp_Alias`, `qrp_Default`, `qrp_Required`, `qrp_InputBoxSize`, `qrp_Validation`, `qrp_NumericMax`, `qrp_NumericMin`, `qrp_AlphaMinLength`, `qrp_AlphaMaxLength`)
  SELECT 309, 301, 3, 'SELECT Value, Display FROM (SELECT lst_OptionID AS Value, lst_OptionName AS Display, lst_OptionSequence AS Seq FROM list_lst WHERE lst_ID = 1 UNION ALL SELECT 0, \'Unassigned\', 9999) AS cls ORDER BY Seq, Value', 'Classification', 'Hold Ctrl (Cmd on Mac) to choose more than one. Leave empty for all classifications.', 'percls', '', 0, 0, '', 0, 0, 0, 0 FROM `query_qry` WHERE `qry_ID` = 301;
