<?php
/**
 * Perpl ORM Database Map Initialization
 * 
 * This file initializes the Propel/Perpl ORM database map with table-to-class mappings.
 * Required for Perpl ORM to resolve table names to TableMap classes.
 * 
 * Generated from orm/schema.xml via: composer run orm-gen
 * 
 * DO NOT EDIT MANUALLY - Regenerate after schema changes with:
 *   cd src && composer run orm-gen
 */

$serviceContainer = \Propel\Runtime\Propel::getServiceContainer();
$serviceContainer->initDatabaseMapFromDumps([
    'default' => [
        'tablesByName' => [
            'calendar_events' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\CalendarEventTableMap',
            'calendars' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\CalendarTableMap',
            'config_cfg' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\ConfigTableMap',
            'deposit_dep' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DepositTableMap',
            'donateditem_di' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DonatedItemTableMap',
            'donationfund_fun' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DonationFundTableMap',
            'event_attend' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventAttendTableMap',
            'event_audience' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventAudienceTableMap',
            'event_types' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventTypeTableMap',
            'eventcountnames_evctnm' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventCountNameTableMap',
            'eventcounts_evtcnt' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventCountsTableMap',
            'events_event' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventTableMap',
            'family_custom' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyCustomTableMap',
            'family_custom_master' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyCustomMasterTableMap',
            'family_fam' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyTableMap',
            'fundraiser_fr' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FundRaiserTableMap',
            'group_grp' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\GroupTableMap',
            'groupprop_master' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\GroupPropMasterTableMap',
            'kioskassginment_kasm' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\KioskAssignmentTableMap',
            'kioskdevice_kdev' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\KioskDeviceTableMap',
            'list_lst' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\ListOptionTableMap',
            'locations' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\LocationTableMap',
            'menu_links' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\MenuLinkTableMap',
            'note_nte' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\NoteTableMap',
            'paddlenum_pn' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PaddleNumTableMap',
            'person2group2role_p2g2r' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\Person2group2roleP2g2rTableMap',
            'person2volunteeropp_p2vo' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonVolunteerOpportunityTableMap',
            'person_custom' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonCustomTableMap',
            'person_custom_master' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonCustomMasterTableMap',
            'person_per' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonTableMap',
            'pledge_plg' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PledgeTableMap',
            'property_pro' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PropertyTableMap',
            'propertytype_prt' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PropertyTypeTableMap',
            'query_qry' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PredefinedReportsTableMap',
            'queryparameteroptions_qpo' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\QueryParameterOptionsTableMap',
            'queryparameters_qrp' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\QueryParametersTableMap',
            'record2property_r2p' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\RecordPropertyTableMap',
            'tokens' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\TokenTableMap',
            'user_settings' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserSettingTableMap',
            'user_usr' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserTableMap',
            'userconfig_ucfg' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserConfigTableMap',
            'version_ver' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\VersionTableMap',
            'volunteeropportunity_vol' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\VolunteerOpportunityTableMap',
            'whycame_why' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\WhyCameTableMap',
        ],
        'tablesByPhpName' => [
            '\\CalendarEvent' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\CalendarEventTableMap',
            '\\Calendar' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\CalendarTableMap',
            '\\Config' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\ConfigTableMap',
            '\\Deposit' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DepositTableMap',
            '\\DonatedItem' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DonatedItemTableMap',
            '\\DonationFund' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\DonationFundTableMap',
            '\\EventAttend' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventAttendTableMap',
            '\\EventAudience' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventAudienceTableMap',
            '\\EventType' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventTypeTableMap',
            '\\EventCountName' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventCountNameTableMap',
            '\\EventCounts' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventCountsTableMap',
            '\\Event' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\EventTableMap',
            '\\FamilyCustom' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyCustomTableMap',
            '\\FamilyCustomMaster' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyCustomMasterTableMap',
            '\\Family' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FamilyTableMap',
            '\\FundRaiser' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\FundRaiserTableMap',
            '\\Group' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\GroupTableMap',
            '\\GroupPropMaster' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\GroupPropMasterTableMap',
            '\\KioskAssignment' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\KioskAssignmentTableMap',
            '\\KioskDevice' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\KioskDeviceTableMap',
            '\\ListOption' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\ListOptionTableMap',
            '\\Location' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\LocationTableMap',
            '\\MenuLink' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\MenuLinkTableMap',
            '\\Note' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\NoteTableMap',
            '\\PaddleNum' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PaddleNumTableMap',
            '\\Person2group2roleP2g2r' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\Person2group2roleP2g2rTableMap',
            '\\PersonVolunteerOpportunity' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonVolunteerOpportunityTableMap',
            '\\PersonCustom' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonCustomTableMap',
            '\\PersonCustomMaster' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonCustomMasterTableMap',
            '\\Person' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PersonTableMap',
            '\\Pledge' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PledgeTableMap',
            '\\Property' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PropertyTableMap',
            '\\PropertyType' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PropertyTypeTableMap',
            '\\PredefinedReports' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\PredefinedReportsTableMap',
            '\\QueryParameterOptions' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\QueryParameterOptionsTableMap',
            '\\QueryParameters' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\QueryParametersTableMap',
            '\\RecordProperty' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\RecordPropertyTableMap',
            '\\Token' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\TokenTableMap',
            '\\UserSetting' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserSettingTableMap',
            '\\User' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserTableMap',
            '\\UserConfig' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\UserConfigTableMap',
            '\\Version' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\VersionTableMap',
            '\\VolunteerOpportunity' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\VolunteerOpportunityTableMap',
            '\\WhyCame' => '\\ChurchCRM\\model\\ChurchCRM\\Map\\WhyCameTableMap',
        ],
    ],
]);
