name: Security

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0

      - name: PHP Security
        uses: symfonycorp/security-checker-action@v2
        with:
          lock: src/composer.lock

      - name: Node Security
        id: njsscan
        uses: ajinabraham/njsscan-action@v5
        with:
          args: '.'
